### ISSUE TITLE
make the error report more appealing

### ISSUE THREAD

**Issue by gurrrung** [pallets/jinja#1005]
![Screenshot from 2019-05-18 19-48-46](https://user-images.githubusercontent.com/30543444/58116241-74f8cd80-7c19-11e9-8468-bf3e5c8482a1.png)
Would be great to have errors highlighted in red.

Useful links:
https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
https://gist.github.com/herrkaefer/3582e2ab5a344647e325782e1a1f3c84

**Comment by davidism** [comment]
How tracebacks are formatted is not something that Jinja controls. You're looking for something like https://github.com/skorokithakis/tbvaccine/.

**Comment by gurrrung** [comment]
Thanks for pointing to it.
