### ISSUE TITLE
indent filter escapes html syntax

### ISSUE THREAD

**Issue by maxbachmann** [pallets/jinja#1017]
I use two jinja2 templates (the second one extends the first one)

```html
{%- filter indent(width=6) %}
{%- block body %}
{%- endblock %}
{%- endfilter %}
```
and
```html
{%- block body %}
<!-- Banner -->
<section id="banner">
  <div class="content">
    <header>
      <h2>{{ this.title }}</h2>
      <p>{{ this.slogan }}</p>
      <p>{{ this.hinweis }} {% if this.hinweis_txt %}<a href="{% if this.hinweis_url %}{{this.hinweis_url }}{% else %}#four{% endif %}">{{ this.hinweis_txt }}</a>{% endif %}</p>
    </header>
    <span class="image"> 
      <img src="{{ '/images/logo.svg'|asseturl }}" alt="" />
    </span>
  </div>
  <a href="#scroll-1" class="goto-next scrolly">Next</a>
</section>
{% endblock %}
```

I expected this to just add 6 whitespaces in front of each line. Actually it even does this, however it does escape the html syntax aswell, so the output is the following:
```html
      &lt;!-- Banner --&gt;
      &lt;section id=&#34;banner&#34;&gt;
        &lt;div class=&#34;content&#34;&gt;
          &lt;header&gt;
            &lt;h2&gt;Toolbox Bodensee e.V.&lt;/h2&gt;
            &lt;p&gt;Gemeinnütziger Maker- und Hackspace am Bodensee.&lt;/p&gt;
            &lt;p&gt;Wir treffen uns jeden Donnerstagabend. Komm doch mal &lt;a href=&#34;/kontakt/&#34;&gt;bei uns vorbei!&lt;/a&gt;&lt;/p&gt;
          &lt;/header&gt;
          &lt;span class=&#34;image&#34;&gt; 
            &lt;img src=&#34;./images/logo.svg?h=2ef1b96c&#34; alt=&#34;&#34; /&gt;
          &lt;/span&gt;
        &lt;/div&gt;
        &lt;a href=&#34;#scroll-1&#34; class=&#34;goto-next scrolly&#34;&gt;Next&lt;/a&gt;
      &lt;/section&gt;
```

Is there a option that I missed to tell it not to escape the html syntax, or is there a way to unescape it again?

**Comment by jab** [comment]
Did you try the`safe` filter documented at http://jinja.pocoo.org/docs/2.10/templates/#safe?

**Comment by maxbachmann** [comment]
Yes I did however the ident filter appears to overwrite it again.
(It works with other filters like join)

**Comment by maxbachmann** [comment]
Ah found the issue. This is actually a known bug, thats already fixed on the master branch, but not added to the version 2.10 :/
Well I added the fix as a custom filter that works now and will replace it with the original again when the fix gets added (hopefully soon)

**Comment by jab** [comment]
Glad you got it working! In that case I’ll close this. Please link to the duplicate, fixed issue from here in case others find this one first and want to find the resolution.

**Comment by derdritte** [comment]
@maxbachmann  Could you share a link to the bug (and the fix) so other people can fix their code until a new version is released?

**Comment by maxbachmann** [comment]
Sorry forgot about it. Here is the commit in which it was fixed:
https://github.com/pallets/jinja/commit/a2f5e2c7972c4d5148c1c75c724e24950d8605bc

**Comment by derdritte** [comment]
Cheers, dude!

Since you mentioned that version 2.10 is bugged, I have simply downgraded to jinja2 version 2.9 and ran it "normally" (?), that is:

```jinja2
<h1>Some template</h1>
<div>
    {{ some_html_macro('Weeeeee')|indent(4)|safe }}
</div>
```
That is a bit more markup than I would want, but it works for me, for now (without patching anything).
