### ISSUE TITLE
Boolean output string filter

### ISSUE THREAD

**Issue by darkdragon-001** [pallets/jinja#1024]
I need to output boolean variables as string to build a command. My commands want to have `yes` and `no`. So the `string` filter (`mybool|string`) does not work since it outputs `True` and `False`.
Currently, I use `('yes' if mybool else 'no')`, but it would be nice to have something prettier built-in.

**Comment by flexferrum** [comment]
I suppose you can use `applymacro` filter ( #910 ) for this purpose:
```
{% macro mybool(val, t, f) %}{{ t if val else f }}{% endmacro %}
...
{{ some_list | map('applymacro', macro='mybool', t="yes", f="no") }}
```

**Comment by davidism** [comment]
``{{ "yes" if mybool else "no" }}``

**Comment by davidism** [comment]
`{{ 'yes' if mybool else 'no' }}` is built-in and seems fine to me. "Pretty" is pretty subjective, so I don't think we'll add another thing based on that alone. You can always add a custom filter that does what you need.
