### ISSUE TITLE
missing details in 'sort' filter docs

### ISSUE THREAD

**Issue by utoddl** [pallets/jinja#1033]
This is an issue with the "sort" filter's docs. (The code itself seems to work fine.) A couple of extra lines could save people a _lot_ of time. Please consider adding (1) that the sort performed by the sort filter is stable, and (2) that sorting by multiple attributes therefore can be accomplished by
```jinja
    sort(attribute='b') | sort(attribute='a')
```
---

## Expected Behavior
Users read the sort docs, then write the above code.

## Actual Behavior
Users read the sort docs, then write code like the following over the course of more hours than I'd like to admit to accomplish the same thing:
```jinja
  sort(attribute='a') | groupby(attribute='a') | map('last') 
              | map('sort', attribute='b') | list | flatten
```
## Your Environment
Not really relevant, but since you asked:
* Python version: multiple (We're using Ansible in a 800+host environment.)
* Jinja version: surprisingly recent, given the hodge-podge of hosts we're running from.

**Comment by davidism** [comment]
PRs welcome
