### ISSUE TITLE
meta.find_undeclared_variables does not take into account default filter

### ISSUE THREAD

**Issue by chandanc-ns** [pallets/jinja#1034]
meta.find_undeclared_variables does not take into account default filter
---

## Expected Behavior
Please see the code in Template Code section, while the template renders correctly find_undeclared_variables reports bar as undeclared variable

meta.find_undeclared_variables(ast) == set([])

## Actual Behavior
meta.find_undeclared_variables(ast) == set(['bar'])

## Template Code
```jfrom jinja2 import Environment, meta
from jinja2 import Template

_template_body = '{% set foo = 42 %}{{ bar|default(10) + foo }}'
_temp = Template(_template_body)
assert _temp.render()
env = Environment()
ast = env.parse(_template_body)
assert meta.find_undeclared_variables(ast) == set([''])
```

## Full Traceback
None

## Your Environment
* Python version: Python 3.5.2
* Jinja version: 2.10.1

**Comment by davidism** [comment]
`bar` *is* undeclared, it just happens to pass through a filter later that does something with the `Undefined` value. The intention of `find_undeclared_variables` is to determine what variables can be passed in to the template. If you want to know if the default filter is used, you can traverse the AST and look for a `Filter(name='default')` node, but knowing in general whether a variable is required before rendering is undecidable.
