### ISSUE TITLE
Template.generate does not use generators all the way down

### ISSUE THREAD

**Issue by maartenbreddels** [pallets/jinja#1044]
## Expected Behavior
When using `Template.generate()` I expect to it to yield snippets for each statements, independent of it calling a super block.

## Actual Behavior

Calls to `{{ super() }}` will eagerly 'evaluate' the block (in the implementation I see it is implemented with e.g.:
```
yield to_string(context.call(l_0_super))
``` 

What I expect, is that I get all the template snippets from the super block, e.g. implemented somwhat like
```
yield from to_string(context.call(l_0_super))
```

## Example Code

```python
from jinja2 import Template, Environment, DictLoader

def users():
    l =  'foo bar'.split()
    for k in l:
        yield k
sources = {
    "base":"""
    <html>
    
    {% block users %}
    {% for user in users() %}
        {{ user }}
    {% endfor %}
    {% endblock users %}
    
    {{ bla }}
    
    </html>""",
    "derived": """
    {% extends 'base' %}
    {% block users %}
    {{ super() }}
    {% endblock users %}

    """
}
env = Environment(loader=DictLoader(sources))

template = env.get_template('derived')

for part in template.generate(bla=1, users=users):
    print("--- begin ---")
    print(part)
    print("---  end ---")
```

Gives as output:
```
$ python jinjatest.py                                                                            dev
--- begin ---


---  end ---
--- begin ---

    <html>


---  end ---
--- begin ---



        foo

        bar



---  end ---
--- begin ---


    1

    </html>
---  end ---
```

(foo and bar are returned together).

While using the base template (`template = env.get_template('base')`) I get the expected result:
```
$ python jinjatest.py                                                                            dev
--- begin ---

    <html>


---  end ---
--- begin ---


---  end ---
--- begin ---

        foo

---  end ---
--- begin ---

        bar

---  end ---
--- begin ---


---  end ---
--- begin ---


    1

    </html>
---  end ---
```

(foo and bar are not returned in 1 snippet).

## Your Environment
* Python version: 3.6
* Jinja version: 2.10.1

**Comment by davidism** [comment]
Note that `generate` isn't guaranteed to yield per statement. For example, multiple lines of statements and template data can be compiled to a single string formatting call internally.

**Comment by davidism** [comment]
I'm not sure if this is possible to change. `{{ super() }}` looks like any other expression from the compiler's perspective. I can't think of a straightforward way to replace expressions with versions that will yield if they return generators and have this work with the various ways expressions could show up in the compiled module.

**Comment by davidism** [comment]
I don't think this is possible to change at this point. If someone wants to dig into the internals and figure something out, I'm willing to review it, but I don't think it's worth leaving open right now.
