### ISSUE TITLE
Remove self-assignment

### ISSUE THREAD

**Issue by r41d** [pallets/jinja#1049]
Is there a reason for this assignment or can it be removed?

https://github.com/pallets/jinja/blob/274eff178d1dedcedf488a586f414a03952ac733/jinja2/_compat.py#L67

**Comment by ThiefMaster** [comment]
Looks like a leftover from this:

https://github.com/pallets/jinja/commit/28c7488224102aea5cc5045a837c88e3820d86ba#diff-65d3fed441e0bee9895176265b373c3bL50

I doubt it's needed.. maybe just to be explicit?

**Comment by davidism** [comment]
It's assigning a built-in to a local variable, so that `from ._compat import intern` works. Removing it would mean it would only be locally defined for Python 3, and would fail to import on Python 2.
