### ISSUE TITLE
Async generators for python 3.5

### ISSUE THREAD

**Issue by maartenbreddels** [pallets/jinja#1058]
This packages provides async generators for Python3.5:
https://pypi.org/project/async_generator/

Is there interest in using this? Let's say if I open a PR, would that make a change of being merged?

**Comment by ecederstrand** [comment]
Either that, or `python_requires` in setup.py should be changed to not advertise Python 3.5 support. The `jinja2.asyncfilters` and `jinja2.asyncsupport` contain syntax errors when imported in Python 3.5.

**Comment by davidism** [comment]
Jinja does support Python 3.5. *Async* support is Python 3.6+. While the library is interesting, I don't want to add a required external dependency.
