### ISSUE TITLE
tojson filter doesn't take safe into account when esacping

### ISSUE THREAD

**Issue by laurent-chriqui** [pallets/jinja#1062]
## Expected Behavior

`{{ variable|safe|tojson }}` shouldn't escape characters

## Actual Behavior

    -   ``<``
    -   ``>``
    -   ``&``
    -   ``'``

are always escaped.

## Your Environment

* Python version: 3.6
* Jinja version: 2.10

**Comment by davidism** [comment]
This is documented behavior. https://jinja.palletsprojects.com/en/2.10.x/templates/#tojson

> The following characters are escaped in strings:
> 
> *   `<`
> *   `>`
> *   `&`
> *   `'`
> 
> This makes it safe to embed such strings in any place in HTML...

The `tojson` filter is specifically documented as being intended for HTML and `<script>` tags. If you have another use case, you can always register your own `tojson` filter:

```python
env.filters["tojson"] = my_tojson
```

**Comment by laurent-chriqui** [comment]
It is the documented behavior but it would be nice if it made the replacements only if the date has not been marked safe...

**Comment by ThiefMaster** [comment]
I don't think it makes sense to `|safe` something before converting it to JSON...

**Comment by laurent-chriqui** [comment]
It does if you're simply displaying json content in the browser. I used pprint instead.

**Comment by davidism** [comment]
`|safe` is essentially a special `str()`, so you may be seeing unexpected results if you call `dict|safe|tojson`, since that's converting a dict to a string then to JSON, which is not the same as converting a dict to JSON.

I don't plan on changing the behavior at this point.

**Comment by ThiefMaster** [comment]
@laurent-chriqui: You can use `{{ foo|tojson|forceescape }}` in that case.
