### ISSUE TITLE
Python 3 support wording

### ISSUE THREAD

**Issue by itdependsnetworks** [pallets/jinja#1066]
## Expected Behavior
Python 3 openly supported. The wording on palletsprojects.com seems to indicate it is not fully supported. 

## Actual Behavior

In https://jinja.palletsprojects.com/en/2.10.x/intro/#experimental-python-3-support it states: Experimental Python 3 Support

## Template Code
```jinja

```

## Full Traceback
```pytb

```

## Your Environment
* Python version: 3.x
* Jinja version: 2.10.x

**Comment by ThiefMaster** [comment]
This was already removed in master: https://jinja.palletsprojects.com/en/master/intro/

**Comment by itdependsnetworks** [comment]
Thanks! I was wondering why it was not showing in the code, I presumed the content was not coming from here then.
