### ISSUE TITLE
Show some equivalent list comprehensions in filter examples

### ISSUE THREAD

**Issue by mlda065** [pallets/jinja#1068]
I'm willing to write a pull-request for this, but I just want to see what people think before I write it.

So the issue is this.
I'm very familiar with python.
I'm new to Jinja2.

Often I find myself with complex data structures in my Ansible playbook (e.g. list of dicts with a list inside that), and I want to do some basic filtering, mapping etc.

I think

> I could do this in one line in python. I'm sure it's possible in Jinja, but I just can't figure out how. 

Looking up how `map`, `selectattr` etc work, then playing around with trial and errors takes a long time, especially when you're combining them.

So what if we had a "quick start" page, or another FAQ answer, which just listed a few list comprehension statements in python, and their equivalent in Jinja?

How do people feel about that?
(Feel free to correct my draft, or propose new examples.)

# Draft

## List Comprehension with a filter or getting the attribute

In python

```
data = [
    {
        'c': 'A',
        'x': 1
    },
    {
        'c': 'B',
        'x': 2
    },
    {
        'c': 'C',
        'x': 1
    },
    {
        'c': 'D',
        'x': 1
    }
]

# filter out all elements not with x > 5
a = [el for el in data if el['x'] > 5]

# get all the 'c' attributes as a list
b = [el['c'] for el in data]

# get all the 'c' attributes for the elements with x > 5
c = [el['c'] for el in data if el['x'] > 5]
```

In Jinja2:

```
a: {{ data | selectattr('x', 'gt', 5) | list }}
b: {{ data | map(attribute='c') | list }} 
c: {{ data | selectattr('x', 'gt', 5) | map(attribute='c') | list }} 
```

## Reversing

In python 

```
x = [1, 2, 3]
y = x[::-1]
```

In Ansible

```
y: {{ x | reverse }}
```

## Json and Yaml

In python:

```
import json
d = {'a':'b'}
s = json.dumps(d)
x = json.loads(s)
```

In Jinja2, to convert to json, just print as string.

```
{{ d }}
```

To convert to yaml use

```
{{ d | to_yaml }}
```

In Jinja2, to load from json, just use 

```
{{ d | from_json }}
```

In Jinja2, to load from yaml, use

```
{{ d | from_yaml }}
```

## Load from file

In python

```
with open('file.txt', 'r') as f:
  s = f.read()
```

In Jinja2:

```
{{ lookup('file', 'file.txt') }}
```

To read a yaml file into a variable, use

```
x: {{ lookup('file', 'file.yaml') | from_yaml }}
```

**Comment by davidism** [comment]
Most of the filters you mention are provided by Ansible, not Jinja. I'd be willing to see some "equivalent to this comprehension" examples in the docs for some of the common filters.

**Comment by mlda065** [comment]
Which filters are the standard ones?

Are the list/dict manipulation ones standard, the file file operation ones Ansible?

**Comment by carc1n0gen** [comment]
https://jinja.palletsprojects.com/en/2.10.x/templates/#builtin-filters
