### ISSUE TITLE
Creating a NativeTemplate directly doesn't create a NativeEnvironment

### ISSUE THREAD

**Issue by cindyzwang** [pallets/jinja#1091]
## Expected Behavior
Create a dictionary with keys and values that are strings. I was able to do this correctly when I was doing `NativeTemplate(...).render(...)` so I would expect that the behavior would be the same if I used a `NativeEnvironment(...).from_string(...).render(...)`.

## Actual Behavior
I have some templates that create dictionaries. However, those tests error out because I expect to create a payload like `{'apples': 'bananas'}` but am instead creating `{'apples: bananas'}`.

I dug around and saw that `preserve_quotes=False` [here](https://github.com/pallets/jinja/blob/master/jinja2/nativetypes.py#L226), which was odd because I thought the behavior should be the same if I was creating an environment or using the spontaneous environment. But it turns out the spontaneous environment is the base `Environment`.

## Template Code
```jinja
>>> env = NativeEnvironment()
>>> env.from_string('{ "{{a}}": "{{b}}" }').render(a='apple', b='banana')
{'apple: banana'}
>>> NativeTemplate('{ "{{a}}": "{{b}}" }').render(a='apple', b='banana')
{'apple': 'banana'}
>>> NativeTemplate('').environment
<jinja2.environment.Environment object at 0x10a688cc0>
```

## Full Traceback
No traceback because it doesn't throw an error, this is just not the expected behavior

## Your Environment
* Python version: 3.6.6
* Jinja version: 2.10

## How I'm currently working around it
```
env = Environment()
... # set up globals & filters
env.template_class = NativeTemplate
```

**Comment by davidism** [comment]
The issue you're describing is real (`get_spontaneous_environment` doesn't take into account what type of environment to create, only the args to it), but the example you've shown works correctly on my machine, both lines produce dicts.

**Comment by cindyzwang** [comment]
I just updated my version of Jinja2 to 2.10.3 and still have the same output:
<img width="551" alt="Screen Shot 2019-10-25 at 12 56 28 PM" src="https://user-images.githubusercontent.com/11622825/67600393-ed167280-f726-11e9-88f3-3909d468b1b4.png">

If you're using the NativeEnvironment, shouldn't you expect this same output? It's documented [here](https://github.com/pallets/jinja/blob/master/jinja2/nativetypes.py#L41-L44), and `preserve_quotes` is hard-coded to False

**Comment by davidism** [comment]
The behavior and fix you're referring to is part of 2.11, which is not released yet. You're looking at the master branch, but you're running 2.10.3, those aren't the same.

**Comment by cindyzwang** [comment]
so this will be fixed in 2.11?

**Comment by davidism** [comment]
Yes, that's why it's marked as part of the 2.11 milestone and merged in.

**Comment by davidism** [comment]
Sorry, I don't think I was clear. You've reported a real issue, in that `NativeEnvironment.from_string()` and `NativeTemplate()` produce different results. It's just that the specific issue you showed is already fixed as part of another fix.
