### ISSUE TITLE
PackageLoader fails on namespace packages

### ISSUE THREAD

**Issue by iomintz** [pallets/jinja#1097]
## Expected Behavior

In the attached [jinja_namespace_bug.zip](https://github.com/pallets/jinja/files/3799437/jinja_namespace_bug.zip), app.py prints "Hi"

## Actual Behavior

A traceback occurs. This is due to [python3.7 namespace packages having their `__file__` attribute set to None](https://github.com/nedbat/coveragepy/commit/c9f4f661ccb7decb55055d80a1e9a1cbb825b27f).

## Reproduction steps

Instead of running the commands below, you can also extract the [attached zip file](https://github.com/pallets/jinja/files/3799437/jinja_namespace_bug.zip) and run app.py.
```
mkdir -p foo/bar
mkdir foo/bar/templates
echo 'x = 1' > foo/bar/baz.py
echo 'Hi' > foo/bar/templates/test.html
cat << 'EOF' > app.py
#!/usr/bin/env python3

import jinja2
jinja_env = jinja2.Environment(loader=jinja2.PackageLoader('foo.bar', 'templates'))
print(jinja_env.get_template('test.html').render())
EOF
chmod +x app.py
./app.py
```

## Full Traceback

```pytb
Traceback (most recent call last):
  File "./app.py", line 5, in <module>
    jinja_env = jinja2.Environment(loader=jinja2.PackageLoader('foo.bar', 'templates'))
  File "/home/io/code/language/python/3/snippets/.venv/lib/python3.7/site-packages/jinja2/loaders.py", line 224, in __init__
    provider = get_provider(package_name)
  File "/home/io/code/language/python/3/snippets/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 364, in get_provider
    return _find_adapter(_provider_factories, loader)(module)
  File "/home/io/code/language/python/3/snippets/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1392, in __init__
    self.module_path = os.path.dirname(getattr(module, '__file__', ''))
  File "/usr/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Your Environment

* Python version: 3.7.4
* Jinja version: 2.10.3

**Comment by davidism** [comment]
The loader has been reworked, and will be updated in 2.11. Does this fail on master?

**Comment by iomintz** [comment]
Yes
```pytb
➤ ./app.py
Traceback (most recent call last):
  File "./app.py", line 4, in <module>
    jinja_env = jinja2.Environment(loader=jinja2.PackageLoader('foo.bar', 'templates'))
  File "/home/io/code/language/python/3/snippets/.venv/lib/python3.7/site-packages/jinja2/loaders.py", line 254, in __init__
    os.path.dirname(self._loader.get_filename(package_name)), package_path
AttributeError: 'NoneType' object has no attribute 'get_filename'
```

**Comment by iomintz** [comment]
As a workaround, `__path__` can be used instead for namespace packages. However, `__path__` is an iterable of strings, and I'm not sure if always using the first element is the right approach.

**Comment by iomintz** [comment]
For now I'm doing ```py
import foo.bar.templates
jinja_env = jinja2.Environment(loader=jinja2.FileSystemLoader(next(iter(foo.bar.templates.__path__))))
```

**Comment by kevin-brown** [comment]
https://docs.python.org/3/library/pkgutil.html#pkgutil.get_loader

This would seem to suggest that `foo.bar` can't be properly imported. This appears to be correct, [per the spec](https://www.python.org/dev/peps/pep-0451/#namespace-packages), for namespace packages.

Unlike in coveragepy, where `__file___` is being used on the module to get the path. `PackageLoader` is getting the internal loader and using that to get the file path to the module itself. Since we can't depend on `package.templates` being a proper Python module, we're then joining the package module with `templates` instead of checking for the path to the `package.templates` module.

**Comment by davidism** [comment]
Ignore the current release, as pkg_resources doesn't support loading resources from namespace packages.

`pkgutil.get_loader()` returns `None` if a namespace package hasn't been imported yet. Trying to import the given package is a good fix regardless, as it gives users a clearer error for typos or missing packages.

Python's `_NamespaceLoader` doesn't support `get_filename`. We could look through `loader._path` to find the first one with the templates folder, but that assumes the package isn't treating the templates folder itself as a namespace package, which would mean we need to adapt `PackageLoader` to scan multiple paths.

Namespace package contributors don't have to be directories, they can also be zip files, just like regular packages. Unlike normal zip packages though, there's no loader API for namespace zips, so we now have to manage opening, scanning, and loading files from the zip file ourselves.

I'm not enthusiastic about developing and maintaining all this, it seems out of scope for Jinja at this point. We could support a limited version of this by assuming a single location and skipping zip files, but ultimately Python needs to improve their loader or `importlib.resources` APIs to make loading package resources more consistent.

**Comment by davidism** [comment]
OK, since your example isn't really using namespace packages for their intended use (multiple sources contributing to one package) and is instead just taking advantage of omitting `__init__.py`, I'm sort of on the fence. Really, you should just add `__init__.py` and be done with it. But adding limited support for one non-zip directory wasn't really an issue, so I'll support that.

**Comment by davidism** [comment]
Reverting this in 2.11.2, it broke compatibility with Pytest. However, support will be present when 3.0 is released. See #1168, #1169
