### ISSUE TITLE
FileSystemLoader Loader Constructs Incorrect Path

### ISSUE THREAD

**Issue by tbpassin** [pallets/jinja#1106]
In loaders.py, there is code at line 68 that does not produce the desired path in Windows in some cases:
```
def get_source(self, environment, template):
    pieces = split_template_path(template)
    for searchpath in self.searchpath:
        filename = path.join(searchpath, *pieces)
        # ...
```

The function `split_template_path()` splits a full path into fragments like this: `['c:', 'xxx', 'yyy', 'zzz'txt']`.

The bug is that for this kind of split path, os.path.join() does not produce a proper path in Windows.  E.g.:
```
sep = '\\'
pieces = ['c:', 'xxx', 'yyy', 'zzz.txt']
filename = os.path.join(sep, *pieces) 
# gives 'c:xxx\yyy\zzz.txt', not the intended c:\xxx\yyy\zzz.txt
```

I have observed cases where the full path to a template file is split by `split_template_path()`, then passed to `get_source` with `searchpath` = `\`.  The intended output is obviously a fully qualified path since it gets passed to open_if_exists().  The result is that the template is never found.

This code may appear in other loaders too, but I have not checked this.

This joining behavior is actually the documented behavior for os.path.join().  So Jinja needs to work around it.  One way would be to check to see if the `template` string is an existing path.  This could look like the following:

```
    def get_source(self, environment, template):
        pieces = split_template_path(template)
        for searchpath in self.searchpath:
            if os.path.exists(template):
                filename = template
            else:           
                filename = path.join(searchpath, *pieces)
            f = open_if_exists(filename)
```

---

## Desired Behavior
To demonstrate, run the following code:
```
import os
from jinja2 import loaders
PTH =  '\\'
fqp = r'c:\spam\green\eggs.txt'  # or 'spam\green\eggs.txt'
splitpath = loaders.split_template_path(fqp)
if os.path.exists(fqp):
    filename = fqp
else:
   filename = os.path.join(PTH, *splitpath)
print filename 
# When fqp points to an actual file, observe filename = fqp
# When fqp is not an absolute path to an actual file,  observe 
# that a proper path is constructed: \spam\green\eggs.txt
```

## Actual Behavior
```
import os
from jinja2 import loaders
PTH = '\\'
fqp = r'c:\spam\green\eggs.txt' 
splitpath = loaders.split_template_path(fqp)
print splitpath # observe lack of "\" after the "c:".
filename = os.path.join(PTH, *splitpath)
print filename 
# observe incorrect path c:spam\green\eggs.txt'
```

## Your Environment
* Python version: 2.7
* Jinja version: 2.10.3

**Comment by davidism** [comment]
Template paths are not supposed to be filesystem paths. It doesn't make sense to be passing `c:\anything` in this context.
