### ISSUE TITLE
block 'content' defined twice

### ISSUE THREAD

**Issue by AkgunFatih** [pallets/jinja#1107]
why cant i use this

```
{% if session().has('oauth_token') %}
<div>aqsqsd</div>
{% block content %}{% endblock %}

{% else %}

{% block content %}{% endblock %}

{% endif %}
```

**Comment by davidism** [comment]
http://jinja.palletsprojects.com/en/2.10.x/templates/#template-inheritance

> You can’t define multiple `{% block %}` tags with the same name in the same template. This limitation exists because a block tag works in “both” directions. That is, a block tag doesn’t just provide a placeholder to fill - it also defines the content that fills the placeholder in the parent. If there were two similarly-named `{% block %}` tags in a template, that template’s parent wouldn’t know which one of the blocks’ content to use.

Place the if block inside the content block.
