### ISSUE TITLE
Extra evaluation by NativeTemplate

### ISSUE THREAD

**Issue by prescod** [pallets/jinja#1118]
## Expected Behavior

I would expect these four lines to be rendered the same way:

```python
>>> Template("{{date}}").render(date="2012-01-02")
'2012-01-02'
>>> NativeTemplate("{{date}}").render(date="2012-01-02")
'2012-01-02'
>>> Template("{{date}}").render(date="2012-11-12")
'2012-11-12'
>>> NativeTemplate("{{date}}").render(date="2012-11-12")
'2012-11-12'
```

## Actual Behavior
```python
>>> Template("{{date}}").render(date="2012-01-02")
'2012-01-02'
>>> NativeTemplate("{{date}}").render(date="2012-01-02")
'2012-01-02'
>>> Template("{{date}}").render(date="2012-11-12")
'2012-11-12'
>>> NativeTemplate("{{date}}").render(date="2012-11-12")
1989
```

The last one goes through two stages of evaluation and generates an integer instead of a string or date object.

## Template Code
```python
from jinja2.nativetypes import NativeTemplate
NativeTemplate("{{date}}").render(date="2012-11-12")
```

## Your Environment
* Python version: Python 3.6.9
* Jinja version: 2.10.3

**Comment by davidism** [comment]
I can't reproduce this on 2.10.3 or master.

**Comment by prescod** [comment]
What versions of Python do you support and which did you test?

https://gist.github.com/prescod/b6c7c55b4c90ca8c44a06b24f4447143

**Comment by prescod** [comment]
And here's why it changed:

https://gist.github.com/prescod/049cd4d033f165cf12f019f7724ae107

**Comment by davidism** [comment]
That's not something that can be fixed then, it's an issue with Python 3.6.

**Comment by prescod** [comment]
If you don't want to fix it, I don't care: I've already removed NativeEnvironment from my project.

But there is a way to fix it if you want.

The code for literal_eval is very self-contained and not super-complicated, so you could just copy it and inline the modern, correct version of it behind a version test:

https://github.com/python/cpython/blob/master/Lib/ast.py#L52

https://github.com/python/cpython/pull/4035

**Comment by davidism** [comment]
You can monkey patch that in in your own project, but I don't plan on adding that maintenance overhead for an old version of Python.
