### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by amotl** [pallets/jinja#1119]
Dear @mitsuhiko, @davidism, @ThiefMaster, @untitaker and the whole Jinja community,

first things first: Thanks a bunch for conceiving and maintaining the excellent Jinja2 module.

We are currently working on https://github.com/jpmens/mqttwarn/issues/127, https://github.com/jpmens/mqttwarn/issues/332 and https://github.com/jpmens/mqttwarn/issues/336 and found that Jinja2 would still croak about things related to #867, #927 and #969 with the most current release version 2.10.3 available from PyPI.

When reading the message `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`, one can assume that Jinja2 will not work on Python 3.8 yet?

Is there anything we can do about it? Just recently, I've been seeing Python 3.8 landing on some machines I was working on or on machines of other people I was working together with.

Please let me know if you need any support for releasing this change within a (probably upcoming?) version 2.11.0. I can see @davidism is busy merging community contributions as well as pushing things from his own pen. Good luck, David!

Thanks already and with kind regards,
Andreas.

**Comment by davidism** [comment]
It works on 3.8 fine, they bumped back the deprecation for that from what I can tell. Features are frozen on 2.11, but I'm always happy to have people contribute PRs. 🙂

**Comment by amotl** [comment]
Thanks!
