### ISSUE TITLE
Incomplete traceback with descriptors and StrictUndefined

### ISSUE THREAD

**Issue by Pitmairen** [pallets/jinja#113]
``` python
from jinja2 import Environment, StrictUndefined

class Test(object):

    @property
    def test(self):
        return self._non_existing_property

env = Environment(undefined=StrictUndefined)

tpl = '''
{{ test.test }}
'''
test = Test()
```

When accessing the test.test property from normal python code you get the following traceback:

``` python
print test.test

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    print test.test
  File "test.py", line 8, in test
    return self._non_existing_property
AttributeError: 'Test' object has no attribute '_non_existing_property'
```

From a template you get the following traceback, which doesn't show the real error:

``` python
print env.from_string(tpl).render(test=test)

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    print env.from_string(tpl).render(test=Test())
  File "jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "<template>", line 2, in top-level template code
jinja2.exceptions.UndefinedError: '__main__.Test object' has no attribute 'test'

```

**Comment by kevin-brown** [comment]
Unfortunately there's no good way to determine that a property is defined on an object if the property returns an `AttributeError`. You can read more about why this is at

[Why does hasattr execute the @property decorator code block](https://stackoverflow.com/q/30143957/359284)

It basically comes down to the fact that there's no way to tell the difference between an `AttributerError` raised by the property not existing and an `AttributeError` raised within the property. I believe the way it is handled in DRF is to catch the `AttributeError`, check if the property is in `dir(obj)`, before re-raising the error (for the right traceback) or treating it as undefined (for when it's really not there). I believe this would need to be done in [`Environment.getattr`](https://github.com/pallets/jinja/blob/9aa8296781e885e06417c401cb5a8f1b9fee7f9c/jinja2/environment.py#L427-L438).

---

I can verify this still remains an issue in the latest version of Jinja2:

```python
>>> import jinja2
>>> class Test:
...   @property
...   def test(self):
...     return self._no_property
... 
>>> env = jinja2.Environment(undefined=jinja2.StrictUndefined)
>>> tpl = '{{ test.test}}'
>>> test = Test()
>>> print test.test
  File "<stdin>", line 1
    print test.test
             ^
SyntaxError: Missing parentheses in call to 'print'
>>> print(test.test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in test
AttributeError: 'Test' object has no attribute '_no_property'
>>> print(env.from_string(tpl).render(test=test))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/sf_GitHub/jinja/jinja2/environment.py", line 1010, in render
    return self.environment.handle_exception(exc_info, True)
  File "/media/sf_GitHub/jinja/jinja2/environment.py", line 782, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/media/sf_GitHub/jinja/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: '__main__.Test object' has no attribute 'test'
>>>
```

**Comment by davidism** [comment]
This is a weird Python quirk, where it's hard to distinguish whether a property exists if it could potentially raise an `AttributeError` internally. Not worth the overhead of checking during runtime.

As to the lack of source on the last line of the traceback, that's because there is no source file for Python to draw from since you initialized the template from a string.
