### ISSUE TITLE
Template coverage discussion

### ISSUE THREAD

**Issue by Thomasb81** [pallets/jinja#1130]
Hello
I probably may not use the issue tracking as expected. Sorry about this.

In reference to:
https://github.com/pallets/jinja/pull/674#issuecomment-549373909
https://github.com/pallets/jinja/issues/408#issuecomment-556501327

Given following template, helloWorld.text:
```
1
2
3  {% block block1 %}
4     {% if poli %}
5  Hello World
6      {% else %}
7
8
9
10     {% endif %}
11  {% endblock %}
12
```

Producing such runtime-code where I report the requirement pointed by @davidism  :
- record the start and end line into node structure
- make it appear in the AST 

```from __future__ import division, generator_stop
from jinja.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound, Namespace, Undefined
name = 'helloWorld.text'

def root(context, missing=missing):
    start_line = 1
    end_line = 12
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    cond_expr_undefined = Undefined
    if 0: yield None
    pass
    yield '1\n2\n3  '
    yield from context.blocks['block1'][0](context)
    yield '\n12'

def block_block1(context, missing=missing):
    start_line = 3
    end_line = 11
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    cond_expr_undefined = Undefined
    if 0: yield None
    l_0_poli = resolve('poli')
    pass
    yield '\n4     '
    if (undefined(name='poli') if l_0_poli is missing else l_0_poli):
        start_line = 4
        end_line = 6
        pass
        yield '\n5  Hello World\n6      '
    else:
        start_line = 6
        end_line = 10
        pass
        yield '\n7\n8\n9\n10     '
    yield '\n11  '

blocks = {'block1': block_block1}
debug_info = '3=14&4=27'
```
Does that match implementation criteria in order to progress on _template coverage support_ in jinja ?
Thanks
Thomas

**Comment by davidism** [comment]
I'm sorry, I'm having trouble understanding what you're asking. It looks like you've just produced the raw compiled module for a template. Maybe you're trying to say that we could look at the coverage of the module? That's already how coverage works, then a coverage plugin would try to map covered Python lines to Jinja lines using `debug_info`. As #408 states, this is not enough, as not every Jinja line maps to a Python line. My last comment on #408 outlines the major shortcomings with the current `debug_info` map.

**Comment by Thomasb81** [comment]
I quote you from #408 :
`If someone figures out how to record the start and end line for each node, that will go a long way towards getting the information we need for full coverage.`

That's basically what I though I have done... so I print the raw code as illustration of the achievement...

Then the idea would not to re-use `get_corresponding_lineno` nor `debug_info` but directly get the value of `start_line` and `end_line` from the frame when [coverage.FileTracer.line_number_range](https://coverage.readthedocs.io/en/coverage-4.3.2/api_plugin.html#coverage.FileTracer.line_number_range) is call...

But I am not a jinja nor coverage expert, so I am just asking if I am on track ... But according to your claim I am not anymore sure.

**Comment by davidism** [comment]
If you've actually implemented that, then you should open a PR for review. I want to output to `debug_info` though. `start_line` and `end_line` have no meaning during regular runtime, can't be used by Jinja's existing introspection, and it's not clear that coverage does anything with variables named like that anyway.

**Comment by Thomasb81** [comment]
Nothing is automatic ...

But in your plugin, you have the responsibility to implement [coverage.FileTracer.line_number_range](https://coverage.readthedocs.io/en/coverage-4.3.2/api_plugin.html#coverage.FileTracer.line_number_range). I understand this function is call on every executed line of your program under analyze. 
So instead of retrieving the jinja environment like done here :  https://github.com/MrSenko/coverage-jinja-plugin/blob/e074018d3e3854bf39a588ef62abc4936c43c2a4/jinja_coverage/plugin.py#L35 from the frame, I expect to be able to access `start_line` and `end_line` of the current context to return the covered line range. At least that's what I have in mind...

Actually I record `start_line `and `end_line` of data node only. So you may be disappointed if you expect anything else... (I didn't try to understand what is `debug_info`, and what is wrong with it's content)

I am happy, that it can have an interest for you. I plan to do the PR tomorrow. (Sorry in Europe it's already late)

**Comment by davidism** [comment]
Thanks for working on this. While I still encourage you to submit a PR demonstrating how you tracked lines, I can tell you now that I don't plan on accepting it if it injects `start_line` and `end_line` everywhere. Perhaps try and figure out how to output to `debug_info` instead.

**Comment by Thomasb81** [comment]
Well in  https://github.com/pallets/jinja/pull/674#issuecomment-549373909
I understand that it would have been an option to do not use `debug_info`:
`Perhaps we could add start and end lines to nodes, or base coverage on an analysis of the AST rather than the debug_info, but either way someone will have to investigate that more and provide a cleaner solution before I'm willing to add it.`

But maybe there is room for compromise ? 
Anyway I will also do as you suggest and look at `debug_info`
