### ISSUE TITLE
Potential indentation issue obscured by error handling?

### ISSUE THREAD

**Issue by KyKoPho** [pallets/jinja#1134]
Hi there,

It looks like there might be a problem on the line referenced below.  I think, and I could be mistaken, that the `else` on this line is indented one level too deeply. This line has been causing problems when I access properties, albeit only sometimes.  When I outdented the line in my virtual environment, it appears to fix the problem.

https://github.com/pallets/jinja/blob/bbdafe33ce9f47e3cbfb9415619e354349f11243/src/jinja2/environment.py#L459

**Comment by mitsuhiko** [comment]
The code in question is correct in that it does what it should do. Please open an issue with the actual error you're encountering.

**Comment by KyKoPho** [comment]
OK, will do.
