### ISSUE TITLE
coroutine object is not iterable error

### ISSUE THREAD

**Issue by autumnjolitz** [pallets/jinja#1135]
## Expected Behavior
I have a Jinja template that does an if-check and a for loop over a `list`-like (technically it inherits list, proxies several methods) object -- it does not define `__aiter__` at all. 

This was a simple upgrade from 2.10.3 to 2.11.0. I expected there to be no behavioral differences (async support has been opted into via the following) -
```
@background.on_start
async def setup_jinja(app, loop):
    app.jinja_env = env = Environment(enable_async=True)
    loader = PackageLoader("minions", "templates")
    env.loader = loader
    ...
```

A variety of synchronous function filters are provided.

## Actual Behavior
A cryptic `'coroutine' object not iterable` error is thrown. Only wholesale removal of the `{% for ...` and `{% if ` statements avoids any errors.

## Template Code
```jinja
{%- if training.annotations | map(attribute='type') | to_set | intersects(annotation_types) %}
Last two annotations:
{%- for annotation in training.annotations[-2:] %}
- [{{annotation.type.name}}] {{annotation.message | truncate(200)}}
{%- endfor %}
{%- endif %}
```

If I reduce it to just 
```jinja
Last two annotations:
{%- for annotation in training.annotations[-2:] %}
- [{{annotation.type.name}}] {{annotation.message | truncate(200)}}
{%- endfor %}
```

I still get the same error, except the line that is errored is "Last two annotations" (which is even more confusing) instead of `{%- if training.annotations | map(attribute='type') | to_set | intersects(annotation_types) %}` as the errored line.

to_set, intersects are defined and injected with the functions:

```
def intersects(item, other):
    if not isinstance(item, (frozenset, set)):
        item = frozenset(item)
    if not isinstance(other, (frozenset, set)):
        other = frozenset(other)
    return item & other

def to_set(iterable):
    return frozenset(iterable)
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/minions/worker.py", line 1116, in _run_task
    task_result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/minions/worker.py", line 281, in __call__
    result = await result
  File "/usr/local/lib/python3.7/site-packages/minions/training.py", line 1773, in handle_training_failure
    raise exception
  File "/usr/local/lib/python3.7/site-packages/minions/worker.py", line 274, in __call__
    result = await self.func(context, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/minions/training.py", line 2810, in monitor_validate_stack
    context.jinja_env,
  File "/usr/local/lib/python3.7/site-packages/minions/training.py", line 1237, in abort_read_headers
    annotation_types=(AnnotationType.WARNING, AnnotationType.ERROR),
  File "/usr/local/lib/python3.7/site-packages/minions/utils.py", line 199, in render_template_raw
    return await template.render_async(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 65, in render_async
    return self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 25, in concat_async
    await collect()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 22, in collect
    async for event in async_gen:
  File "/usr/local/lib/python3.7/site-packages/minions/templates/training/training_validate_end.jinja", line 10, in top-level template code
    {%- if training.annotations | map(attribute='type') | to_set | intersects(annotation_types) %}
TypeError: 'coroutine' object is not subscriptable
```

If I dump the `f_locals` for the erroring frame via `print(e.__traceback__.tb_next.tb_frame.f_locals)`, I see:

```
{
    'jinja_environment': <jinja2.environment.Environment object at 0x7f3a5acffb10>,
    'template_name': 'training/training_validate_end.jinja',
    'context': {
        'training': Training(
            annotations=ListInterceptor([
                Annotation(type=<AnnotationType.WARNING: 'warning'>, message='Watch your language! Column at index 0 is rude!', scope='labels', created_date=datetime.datetime(2020, 1, 28, 2, 53, 38))
            ]), ),
        'annotation_types': (<AnnotationType.WARNING: 'warning'>, <AnnotationType.ERROR: 'error'>)
    }, 'template': <Template 'training/training_validate_end.jinja'>
}
```

## Your Environment
* Python version: Python 3.7.5 (provided via `python:3.7-alpine` docker image)
* Jinja version: 2.11.0

**Comment by mitsuhiko** [comment]
Cannot reproduce. Can you make a minimal testcase?

**Comment by autumnjolitz** [comment]
Oh yeah, I can 😀 

I've created a minimal test at https://gist.github.com/autumnjolitz/0e202b66fef2bf27c77dfe9d0f77a8d1

To prove it has nothing to do with my infrastructure, I will use an isolated python:3.7-alpine docker image (same procedure works on my OSX laptop, but I wanted to remove out the possibility of my employer's private PyPI index)

This comment compares between Jinja 2.10.3 (working) and Jinja 2.11.0 (not working) - https://gist.github.com/autumnjolitz/0e202b66fef2bf27c77dfe9d0f77a8d1#gistcomment-3159063

**Comment by autumnjolitz** [comment]
2.10.x and before appear to give an `Awaitable` for `map(...)` filter and we handle that by returning an `Awaitable` (which returns `FrozenSet[T]`). 2.11.x appears to choke on that. Because `map(...)` returns an Awaitable, I am uncertain how one can unpack the async_generator in 2.11.x. 🙁

**Comment by davidism** [comment]
If it's happening with `map` in async mode, it may have something to do with #913. However, the example you've given is still pretty complex. Is the external `instruct` dependency, all those types, and the `to_set` filter really necessary? A minimal example should be only the code needed to demonstrate the issue.

**Comment by autumnjolitz** [comment]
This was a mirror opensource only implementation of how it’s actually used. 

Sorry to offend with things being too complex because I only noticed by accident of a typo while implementing this at the end of a few hours of preparing this report followup that there’s a causal link between map, async and returning an awaitable because map gives an async_generator.
