### ISSUE TITLE
why jinja2 can not retrieve missing variables when my template start and end strings are different from {{ and }} ?

### ISSUE THREAD

**Issue by eurydice76** [pallets/jinja#1140]
Hi,

I have the following template:

```python
s = """
- "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }} "
- "no_proxy==[[ no_proxy ]] "
disk_size: "[[ disk_size ]]"
```

I use `[[` and `]]` instead of `{{` and `}}` because I do not want `.HTTPIP` and `.HTTPORT` to be rendered.
Based on this, I would like to use `jinja2` to render that string and check that every variable has been actually rendered.

Here is my code:

```python
import jinja2
from jinja2.meta import find_undeclared_variables

s = """
- "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }} "
- "no_proxy==[[ no_proxy ]] "
disk_size: "[[ disk_size ]]"
"""

env = jinja2.Environment(undefined=jinja2.DebugUndefined, variable_start_string="[[", variable_end_string="]]")
template = env.from_string(s)

environment = {"disk_size":1000}

# Render template without passing all variables
rendered = template.render(**environment)

print(rendered)

# Check if rendering was done correctly
ast = env.parse(rendered)
undefined = find_undeclared_variables(ast)  # {'bar', 'baz'}
if undefined:
    print(f'The following variables are undefined: {undefined!r}')
```

Surprinsingly, I do not get any print message about missing variable while it should be the case for variable `no_proxy`. 

Looking deeper, I realized that after rendering the rendered string is:

```jinja
- "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }} "
- "no_proxy=={{ no_proxy }}"
disk_size: 1000
```

So we can see that the missing variable (`no_proxy`) is not anymore surrounded by `[[` and `]]` but by `{{` and `}}` which might explained why there is no complaint about missing variable.

Is that a bug or am I doing something wrongly ?

thanks for your help

**Comment by davidism** [comment]
You asked for the undeclared variables in the second template, not the original.

**Comment by eurydice76** [comment]
Yeap but what  I want is to check my variable **after** rendering in order to have a warning whether the user forgot to provide one variable

**Comment by davidism** [comment]
You need to do that before rendering then. Find undefined variables in the first template, compare that to the set of variables the user wants to render with, then stop if they don't match.

Or, much more straightforward, use `StrictUndefined`.

**Comment by eurydice76** [comment]
Indeed, using StrictUndefined is much eaiser. Thanks a lot for your help.
