### ISSUE TITLE
Check that contextfunction, etc. is True

### ISSUE THREAD

**Issue by davidism** [pallets/jinja#1145]
In order to determine if the context should be passed to a function or filter, Jinja has the `contextfunction` and `contextfilter` decorators which set corresponding attributes on the functions. However, they're checked with `if getattr(f, "contextfunction", 0)`, which causes issues for objects that are callable and have permissive `__getattr__` functions, such as `Mock`.

Changing everything to default to `False` and check `is True`, would be good for consistency. 

The full list is `contextfunction`, `evalcontextfunction`, `environmentfunction`, `contextfilter`, `evalcontextfilter`, and `environmentcontextfilter`.

_Extracted from https://github.com/pallets/jinja/issues/1139_

**Comment by mitsuhiko** [comment]
I'm honestly not sure if it's a good idea to pass mock objects to a template in the first place. FWIW the reason `0` is used is because this code was faster on 2.x where the constant optimization was not applied yet.

**Comment by davidism** [comment]
I agree it's not, but there was another example of it coming up outside testing and it's a straightforward fix. 0 was only used in one place, False was used everywhere else already.
