### ISSUE TITLE
Regression: package was not installed in a way that PackageLoader understands.

### ISSUE THREAD

**Issue by jaraco** [pallets/jinja#1148]
## Expected Behavior
PackageLoader should continue to load from a namespace package even under pytest.

## Actual Behavior
Starting with jinja2 2.11, the tests for pmxbot have [started failing](https://travis-ci.org/yougov/pmxbot/jobs/647234617?utm_medium=notification&utm_source=github_status). They fail when pytest attempts to rewrite the modules for running under test and in doing so, cause the `jinja2.loaders.PackageLoader` not to recognize the 'pmxbot.web' package. Note that `pmxbot` is a setuptools namespace package.

## Full Traceback
```pytb
pmxbot/web/__main__.py:1: in <module>
    import pmxbot.web.viewer
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
.tox/python/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:143: in exec_module
    exec(co, module.__dict__)
pmxbot/web/viewer.py:24: in <module>
    jenv = jinja2.Environment(loader=jinja2.loaders.PackageLoader('pmxbot.web'))
.tox/python/lib/python3.8/site-packages/jinja2/loaders.py:288: in __init__
    raise ValueError(
E   ValueError: The 'pmxbot.web' package was not installed in a way that PackageLoader understands.
```

The error is not triggered when simply importing the package naturally; it only seems to happen during the pytest rewrite.

## Your Environment
* Python version: 3.8.1
* Jinja version: 2.11.x

Downgrading to Jinja 2.10.3 works around the failure. I suspect #970 is implicated.

**Comment by davidism** [comment]
We've switched to using `packaging.resources`. I think you're a maintainer for that, any insight into how to support this style of namespace?

**Comment by jaraco** [comment]
I don't see that you're using `importlib.resources`, at least not in the #1082. Indeed, even in master, `importlib.resources` (or its backport) [isn't imported](https://github.com/pallets/jinja/blob/e08dadd220563609a67bc32d4d1c0abe91699231/src/jinja2/loaders.py#L4-L15).

I do agree that using importlib.resources should make the implementation cleaner and it's a laudable goal to drop pkg_resources (it's also one of my goals). However, I believe [lack of support for subdirectory traversal](https://gitlab.com/python-devs/importlib_resources/issues/58) is a blocker to adopt `importlib.resources`.

I'm not sure what it is about the "pytest assert rewrite" functionality that's triggering the error, and I don't know how difficult it will be to debug either (given that it happens during test runner setup and not during test execution).

I don't know when I'll get the time to troubleshoot, but I'll try to help when I have the time.

**Comment by davidism** [comment]
You're right, I was remembering what we started with, but we ended up only using pkgutils and doing a few things manually since importlib didn't handle it.

I recall a pytest issue we opened that had to do with monkeypatching modules, I'll see if I can find it.

**Comment by davidism** [comment]
See pytest-dev/pytest#5098. Their `monkeypatch.syspath_prepend()` has to call `pkg_resources.fixup_namespace_packages()` and `importlib.invalidate_caches()` in order to get dynamic changes to be recognized during tests. Perhaps there's something similar going on in your test setup?

**Comment by davidism** [comment]
I think this is a specific case of #1168, do you think we can close this in favor of the discussion there?

**Comment by jaraco** [comment]
Agreed, that ticket gets closer to the root of the issue, so I'll close this as a manifestation of that issue.
