### ISSUE TITLE
3.0.0a1 fails to install on python 3.4, 3.5, and 2.7

### ISSUE THREAD

**Issue by wumpus** [pallets/jinja#1154]
## Expected Behavior
installing jinja2 with python 2.7, 3.4, and 3.5 should get a valid package

## Actual Behavior
I got Jinja2 3.0.0a1, which has f-strings on Python 3.4 and Python 3.5, and setuptools failed on 2.7 with an encoding= keyword problem.

Full details in https://travis-ci.org/wumpus/warcio/builds/651237313

**Comment by ThiefMaster** [comment]
I think something is wrong with you pip/setuptools... 1) you got a prerelease, 2) that version [clearly specifies in its metadata](https://pypi.org/project/Jinja2/3.0.0a1/) that it's only compatible with 3.6+, so pip should never install it on anything older

**Comment by ThiefMaster** [comment]
Could it be that `python setup.py install` use something outdated? Try `pip install .` instead.

**Comment by wumpus** [comment]
I am not an expert on this kind of thing. setup.py for my package doesn't install Jinja2, it comes in via httpbin==0.5.0.

Indeed, "pip install -U Jinja2" in my environment gets Jinja2-2.10.3.

**Comment by ThiefMaster** [comment]
I think the solution is to ditch the `python setup.py install` in your travis config and replace it with `pip install .` - that way it should work fine.

**Comment by wumpus** [comment]
That probably papers over the problem for just me, sure, but doesn't help the other users of `warcio`. As I said, I'm not an expert on these issues.

**Comment by ThiefMaster** [comment]
What I meant is that people should not use `python setup.py install` to install your (or any other) package, but rather use pip to install.

FWIW, I'm not familiar enough with python packaging internals to know if this is a general shortcoming of `setup.py install` or only happens e.g. if setuptools isn't properly installed. I'd ask on IRC (freenode) in #pypa.

**Comment by davidism** [comment]
Setuptools issues the following warning when using `python setup.py test`. 

> WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.

My understanding of the setuptools support roadmap is that they have not supported (or will not support) the `test` command or other "environment management" commands. Their advice is to use `pip` to install packages, while `setuptools` is only for building package. The `setup.py` versions of commands are very old and use `easy_install`, which is not generally supported and does not behave the way pip does.

Another solution to this issue if you can't use `pip` and `tox` is for a project to pin dependency versions so they can control when they upgrade.
