### ISSUE TITLE
{% extends template_obj %} not supported as documentation claims

### ISSUE THREAD

**Issue by UmbrellaDish** [pallets/jinja#1155]
## Expected Behavior

[Documentation](https://github.com/pallets/jinja/blob/master/docs/templates.rst#template-objects) reads it is possible to pass a template object to extends-clause that is used as parent template.

## Actual Behavior

Jinja still evaluates that reference as a string and tries to split it into separate path segments. Apparently extends clause does not call `get_template()` from environment instance but `_load_template()`. Only the former has pass-through functionality for cases where a template object is passed.

## Template Code
```jinja
{% extends layout %}
{% block content %}
...
{% endblock %}

```

## Full Traceback
```pytb
  File ".../django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File ".../django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".../django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../myapp/myapp/views.py", line 16, in htmlpage
    return HttpResponse(template.render(context, request))
  File ".../django/template/backends/jinja2.py", line 71, in render
    return self.template.render(context)
  File ".../jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File ".../jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File ".../jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File ".../jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "templates/test.html", line 1, in top-level template code
    {% extends layout %}
  File ".../jinja2/loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File ".../jinja2/loaders.py", line 27, in split_template_path
    for piece in template.split('/'):
```

## Your Environment
* Python version: 3.6.9
* Jinja version: 2.10.3

**Comment by davidism** [comment]
I can't reproduce this issue. I tried the following in both Jinja 2.10.3 and 2.11.1.

```python
from jinja2 import DictLoader
from jinja2 import Environment

e = Environment(loader=DictLoader({
    "base": "{% block content %}base{% endblock %}",
    "item": "{% extends layout %}{% block content %}item{% endblock %}",
}))
t = e.get_template("item.txt")
print(t.render(layout=e.get_template("base.txt")))
```

I also tried with `FileSystemLoader` to ensure it wasn't a difference in loaders.

**Comment by UmbrellaDish** [comment]
Your code works for me, too, I just needed to remove `.txt` extension from template names. Why has it worked as posted for you?

Still, it is weird. Could not figure out where extends clause is actually *processed* in first place. In the stacktrace there is an ominous jump from some `top-level template code` to `get_source`, which does expect a path. Well, you closed the issue, seems I'm up to find the solution on my own.

**Comment by UmbrellaDish** [comment]
Following code works indeed and leaves me wondering why then my above code does not in its execution context.
 
```python3
import os
from jinja2 import FileSystemLoader, Environment

TMPDIR = '/tmp/test-objbase-templates'
try:
    os.mkdir(TMPDIR)
except FileExistsError:
    pass

with open(os.path.join(TMPDIR, 'base.tmpl'), 'w') as tmpl:
    print("{% block content %}base{% endblock %}", file=tmpl)
with open(os.path.join(TMPDIR, 'item.tmpl'), 'w') as tmpl:
    print("{% extends layout %}{% block content %}item{% endblock %}", file=tmpl)

e = Environment(
    loader=FileSystemLoader([TMPDIR]),
)

t = e.get_template("item.tmpl")
print(t.render(layout=e.get_template("base.tmpl")))
```
So apparently it is not Jinjas fault. I will investigate further, maybe jinja could anticipate with a better exception at least.
