### ISSUE TITLE
filter: titlecase() - alternative to title()

### ISSUE THREAD

**Issue by joedf** [pallets/jinja#1157]
# Suggestion for<sup>1</sup> the<sup>1</sup> Current Implementation
This isn't really a bug, more of an observation with a proposed alternative. 
The current title() filter is not very useful. Since all words are capitalized (including short words like of, the, to, etc.) and its effects can be achieved with a simple css rule:
```css
text-transform: capitalize;
```
**1**: see what I did there? ;)

## Current Behaviour
`the foo of the bar` -> `The Foo Of The Bar`

## Expected Behaviour
`the foo of the bar` -> `The Foo of the Bar`

## Alternative Implementation
Currently, a "truer" titlecase, in webdev, is usually achieved with javascript or something else (as far as I know), which kind of defeats the purpose of using jinja for this particular case. That said, custom filters allow for flexibility around this. 👍 

A common alternative in python is: https://pypi.org/project/titlecase/
However, I've written a shorter alternative: https://gist.github.com/joedf/e94fe2a9ef949a289737dd5a4bca4e3a

## Environment
* Python version: 3.7.3 x64
* Jinja version: 2.11.1

**Comment by davidism** [comment]
This would be a good use of a custom filter in a project, or an extension that provides such a filter, that uses that library. But we can't pull in external dependencies just for a filter, and I don't think we need to maintain our own implementation.

**Comment by joedf** [comment]
No worries!
I was gonna say that it was very similar to `str.title()`, but actually the current jinja implementation is actually better! Since it doesn't "double capitalize" hyphenated words or contractions.
https://github.com/pallets/jinja/blob/master/src/jinja2/filters.py#L244-L254
```py
def do_title(s):
    """Return a titlecased version of the value. I.e. words will start with
    uppercase letters, all remaining characters are lowercase.
    """
    return "".join(
        [
            item[0].upper() + item[1:].lower()
            for item in _word_beginning_split_re.split(soft_str(s))
            if item
        ]
    )
```
