### ISSUE TITLE
Weird behavior of NativeEnvironment which causes duplicated elements in Jinja 2.10.x

### ISSUE THREAD

**Issue by tonyseek** [pallets/jinja#1159]
## Expected Behavior
```
>>> print(NativeEnvironment().from_string('{{ "tr" }} ue').render())
tr ue
```

## Actual Behavior

In Jinja2 `2.10.1` (the version used by [kubespray](https://github.com/kubernetes-sigs/kubespray)) and `2.10.3` (the latest version of 2.10.x)

```
>>> print(NativeEnvironment().from_string('{{ "tr" }} ue').render())
tr uetr ue
```

Nevertheless, everything works as expected in Jinja2 `2.11.1` (the latest major version).

## Template Code
``` python
Python 3.7.3 (default, Dec 13 2019, 19:58:14)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> from jinja2.nativetypes import NativeEnvironment
>>>
>>> print(jinja2.__version__)
2.10.3

env = NativeEnvironment()
print(env.from_string('{{ "tr" }} ue').render()) >>>
>>> env = NativeEnvironment()
>>> print(env.from_string('{{ "tr" }} ue').render())
tr uetr ue
>>>
```

## Full Traceback

None

## Your Environment
* Python version: 3.7.3
* Jinja version: 2.10.3

**Comment by davidism** [comment]
If you use `git bisect` you can find the first commit that fixed this issue. If you want to backport the relevant PR to the 2.10.x branch, I'm happy to review and release a fix.
