### ISSUE TITLE
Traceback formatting in Python 3.6 32-bit Windows causes hang

### ISSUE THREAD

**Issue by samuelchen** [pallets/jinja#1162]
Hi,

I was facing an issue when using incorrect variable name in `Flask` template. An dash "-" linked variable name in template cause Flask to hang without throwing any exception.

At first I doubt it's `Jinja` issue but I found Jinja raised the exception and `Werkzeug` handled it.

Eventually, I found an endless loop in `Python\Lib\traceback.py` to walk trackback stacks. The 
trackbacks are stored in a link which nodes point to next. In `flask\templating.py`, 
`flask\app.py` and `werkzeug\debug\tbtools.py`, the exception was catched. In 
`handle_exception()` of `flask\app.py`, `Werkzeug` wants to log it and print it out. 

The trackback link has looped reference as below picture.

![](http://blog.samuelchen.net/Flask-Werkzeug-templating-caused-trackback-loop-issue/flask_tb_next_loop_ref.png)

Hope its helpful. Thanks you.

### Expected Behavior
Render variable out or throw exception out.

```python
import sys
from flask import Flask, request, render_template_string, make_response, url_for, redirect

### {{ font-size }} causes app hang ###

app = Flask(__name__)

template_page = '''
<html>
<head>
<meta charset="{{ encoding }}" />
<meta http-equiv="content-type" content="text/html; charset={{ encoding }}" />
<style type="text/css">
  body, pre, p, div, input, h1,h2,h3,h4,h5 {
    font-family : Consolas, Courier New;
  }
</style>
</head>
<body>
    <div id="wrapper" style="font-size:{{ font-size }}em">
        {{ content | safe }}
    </div>
</body>'''


@app.route('/', methods=['GET'])
def index():
    context = {
        "encoding": 'utf-8',
        "font-size": 0.9,
        "content": 'hello flask'
    }
    resp = make_response(render_template_string(template_page, **context))
    resp.headers['Content-Type'] = 'text/html; charset=utf-8'
    return resp


if __name__ == "__main__":
    # app.run(debug=True, host='0.0.0.0', port=8080)

    app.run()
```

### Actual Behavior
App hangs.

```pytb
N/A
```

### Environment

* Python version: 3.6.8
* Flask version: 1.1.1
* Werkzeug version: 0.16.1

**Comment by mitsuhiko** [comment]
> @mitsuhiko Jinja2 2.11.1

Can you check if this also happens on 2.10?

**Comment by davidism** [comment]
I can reproduce this with 2.11 on Python 3.6.8 32-bit on Windows. Python 3.6.8 64-bit does not have the issue. 2.10.3 does not have the issue.

**Comment by davidism** [comment]
Looks like a bad assumption about the size of `PyObject_HEAD`, a holdover from the previous version that I thought might still be better than the [suggested alternative](https://github.com/python-trio/trio/issues/405#issuecomment-582773655). Changing from

```python
ctypes.c_byte * (32 if hasattr(sys, "getobjects") else 16)
```

to

```python
ctypes.c_byte * object().__sizeof__()
```

fixes the issue.
