### ISSUE TITLE
How can I break a long Jinja if expression???

### ISSUE THREAD

**Issue by larryw3i** [pallets/jinja#1165]
How can I break a long Jinja if expression???

```jinja
{% if request.GET.filter == 'aaaaaaaa' or bbbbb.paginator.num_pages > ccccc.paginator.num_pages %}
```
which more than 80 words.

**Comment by ThiefMaster** [comment]
just like in python, there are many ways of doing it... not sure what kind of answer you expect from us there.

**Comment by larryw3i** [comment]
I have tried
```jinja
{% if request.GET.filter == 'aaaaaaaa' or \
bbbbb.paginator.num_pages > ccccc.paginator.num_pages %}
```
and
```jinja
{% if request.GET.filter == 'aaaaaaaa' or 
bbbbb.paginator.num_pages > ccccc.paginator.num_pages %}
```
It doesn't work

**Comment by larryw3i** [comment]
😭

**Comment by davidism** [comment]
I'd usually say I'm happy to accept a PR, but there are so many behaviors with whitespace right now that I'm not confident about accepting changes to this part of the lexer. I don't really see this as a pressing issue.

**Comment by larryw3i** [comment]
I try to control the count of characters on each line for good readability. then I use the "as" expression and it has been resolved now.

**Comment by ptroon** [comment]
Tbh, if you have a lot of logic, the Jinja isn't usually the best place for it.  I would work on the logic up a level (view level) and pass it a flag of some type to the template to check
