### ISSUE TITLE
Render datetime.datetime as string when in object.

### ISSUE THREAD

**Issue by comtihon** [pallets/jinja#1173]
Hi, I faced an issue with datetime.datetime being rendered as string when in object.
This works fine:
```
template = Template(source)
template.render('{{ date }}', dict(date=datetime.datetime.now()))
```
returns `'2020-03-20 17:25:12.964967'`

This renders date as string:
```
template = Template(source)
template.render('{{ object_with_date }}', dict(object_with_date={'date': datetime.datetime.now()}))
```
expected:
`'{\'object\':\'2020-03-20 17:25:12.964967\'}`

got:
`'{\'object\': datetime.datetime(2020, 3, 20, 17, 25, 12, 964967)}'`

python version: 3.7
jinja version: 2.11.1

**Comment by ThiefMaster** [comment]
That's just normal python behavior and has nothing to do with Jinja. Converting an arbitrary object (or dict/list) to a string uses the repr() of it.

**Comment by comtihon** [comment]
don't you find it's an inconsistency, when it renders normally while being key-value and renders as object when in object?
It would be better for me as a user to expect single behavior - either object both ways or formatted string both ways, so that I can handle it before it is passed to jinja.

**Comment by ThiefMaster** [comment]
Like I said, it's is standard python behavior.

```
>>> from datetime import datetime
>>> now = datetime.now()
>>> print(now)
2020-03-20 17:56:34.074807
>>> print({'now': now})
{'now': datetime.datetime(2020, 3, 20, 17, 56, 34, 74807)}
```

Why are you printing the repr of some object in your template at all - this is most likely the wrong way of doing whatever you are really trying to do. What is your actual goal?

**Comment by comtihon** [comment]
yes, it is.
I am the author of end-to-end test [tool](https://github.com/comtihon/catcher) which heavily relies on jinja2.
The main idea is - user can run step and register output. F.e.:
```
postgres:
              actions:
                - request:
                    conf: '{{ postgres_conf }}'
                    query: "select * from table "
                  register: { data: '{{ OUTPUT }}'}
```
In case there is date time column in postgres `data` variable will contain object with datetime object rendered as string.
I'll handle it on my side then.
