### ISSUE TITLE
Cannot set dictionary keys

### ISSUE THREAD

**Issue by TheLastProject** [pallets/jinja#1176]
I used [j2cli](https://pypi.org/project/j2cli/) to run my example, hope that's okay.

I've looked through the documentation but I couldn't find something explaining this would not be possible. I also found no other issues reporting this. As this is a valid Python operation, I would expect this to work.

## Expected Behavior
Setting a dictionary key with `set` should update that dictionary key

## Actual Behavior
Jinja2 returns a `TemplateSyntaxError`

## Template Code
```jinja
{% set data = {"foo": "bar"} %}
data should be {"foo": "bar"}: "{{ data }}" {# succesful #}
{% set data2 = data["foo"] %}
assigning a key's value to a variable goes fine: "{{ data2 }}"
{% set data["foo"] = "barbar" %} {# assigning a variable to a key causes a crash #}
"{{ data }}"
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/usr/local/bin/j2", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/j2cli/cli.py", line 206, in main
    sys.argv[1:]
  File "/usr/local/lib/python3.7/site-packages/j2cli/cli.py", line 186, in render_command
    result = renderer.render(args.template, context)
  File "/usr/local/lib/python3.7/site-packages/j2cli/cli.py", line 86, in render
    .get_template(template_path) \
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/sylviavanos/minimal_example.j2", line 3, in template
    {% set data["foo"] = "barbar" %} {# crash! #}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '['
```

## Your Environment
* Python version: 3.7
* Jinja version: 2.11.1

**Comment by ThiefMaster** [comment]
This will not be supported. Modifying dicts in templates is rarely a good idea anyway.

**Comment by TheLastProject** [comment]
But... using append and all is supported, thus modifying a dict in a template is already supported? What is the rationale behind this decision?

**Comment by ThiefMaster** [comment]
If you do need a mutable object on which you can set stuff, have a look at https://jinja.palletsprojects.com/en/2.11.x/templates/#namespace

**Comment by ThiefMaster** [comment]
It's not supported. We just can't stop you from doing it because `{{ foo.append('bar') }}` and `{{ foo.get_html_for_something('bar') }}` isn't really different unless you are a human

**Comment by TheLastProject** [comment]
I will say I disagree completely with the given reasoning, as it boils down to: "editing dictionaries is not a good idea, so this way will not be supported, but existing ways to edit dictionaries will not be removed".

Specifically, the issues I have with this is:
- It would be trivial to block other calls, so users will not have the expectation it will work
- The documentation nowhere states this is not supported or intended
- The documentation [explicitly mentions](https://jinja.palletsprojects.com/en/2.11.x/templates/#expression-statement) how to do something that "is not supported but we cannot stop you from doing"

So, to me, it feels extremely arbitrary to not support this method, but not prevent other methods. Even worse, this unsupported method is documented as something you can do just fine!

For others running into this issue: I worked around this by assigning the dictionary key to another temporary variable and editing all references in my code to that dictionary key to instead refer to that variable.

Before:
```
{% set the_vars = foo["bar"] %}
{% set foo["bar"] = "barbar" %}
{% include "some_other_template.j2" with context %}
{% set foo["bar"] = the_vars %}
```

After:
```
{% set the_vars = foo["bar"] %}
{% set the_vars_clean = foo["bar"] %}
{% set the_vars = "barbar" %}
{% include "some_other_template.j2" with context %}
{% set the_vars = the_vars_clean %}
```

This sadly means I'm introducing 2 temporary variables instead of just one and need to replace variables in all other templates, but it's the best workaround given this limitation.

**Comment by ThiefMaster** [comment]
> It would be trivial to block other calls, so users will not have the expectation it will work

Using the [sandbox](https://jinja.palletsprojects.com/en/2.11.x/sandbox/) this could be done. But we have *no* way to know what type some variable is, without checking if it's a dict and then prohibiting certain calls. But outside the sandbox we assume developers don't do "weird" things, or that they know what they are doing otherwise. So yes, in principle you can modify a dict - doesn't mean you should.

> The documentation explicitly mentions how to do something that "is not supported but we cannot stop you from doing"

OK that's a good point. The do extension isn't enabled by default though...


---

That aside, have you checked my previous link if the `namespace()` object helps you?

**Comment by TheLastProject** [comment]
The namespace() object doesn't solve my issue as I am not creating a new object, I am modifying a dictionary passed to Jinja2. I also explicitly want to prevent the effect of the edit persisting outside of the loop. So, as far as I can tell, my workaround seems to be the only way.

**Comment by ThiefMaster** [comment]
IIRC you can pass a dict or `**kwargs` to `namespace()` to prefill it
