### ISSUE TITLE
Update documentation to state that python dicts preserve insertion order

### ISSUE THREAD

**Issue by septatrix** [pallets/jinja#1184]
Since Python 3.7 `dicts` must preserve insertion order in all implementations (in Python 3.6 it was only an implementation detail in CPython). Thus I think it would make sense to state this in the [loop section](https://jinja.palletsprojects.com/en/master/templates/#for) of the docs which currently states the following:
> Note, however, that *Python dicts are not ordered*; so you might want to either pass a sorted `list` of `tuple`s [...]

I think it would be helpful to state that since 3.7 these measures are not necessarily needed anymore.

This also works towards https://github.com/pallets/meta/issues/26

**Comment by davidism** [comment]
This statement basically still applies though, since it's about sorted order, not insertion order. Maybe the following: "Python dicts preserve insertion order, which may not be the order you expect. If order matters, you can sort ``data.items()`` or use the ``dictsort`` filter."

**Comment by sixtyfathoms** [comment]
I would be happy to take on this issue... if I do multiple docs issues, would you want a combined PR or separate PRs?

**Comment by davidism** [comment]
Separate prs for separate fixes please.
