### ISSUE TITLE
Unpythonic operator precedence

### ISSUE THREAD

**Issue by luc-j-bourhis** [pallets/jinja#119]
Jinja2 version 2.6 parses {{ a \* b % c }} as a \* (b %c) whereas Python would parse it as (a \* b) % c.
Here is a regression test:
###### 

from jinja2 import Environment

env = Environment()
t = env.from_string('''
{{2 \* 4 % 8}}
{{2 \* 12 % 8}}
''')
rendered = t.render()
correct = '''
0
0
'''
assert rendered == correct, "%s\ninstead of%s" % (rendered, correct)
###### 

fails with

AssertionError: 
8
8
instead of
0
0

**Comment by ngaya-ll** [comment]
Maybe this could be configurable?  That way it wouldn't break backward compatibility, but the old precedence could be deprecated and eventually removed completely.

**Comment by jeffwidman** [comment]
That sounds reasonable to me.

**Comment by ricky-undeadcoders** [comment]
I can't recreate this in Jinja 2.10, I'm pretty sure this was fixed in the following commit:

https://github.com/pallets/jinja/commit/4fa37123b93c25de6f6596825df8b297a0433eee

**Comment by Jamim** [comment]
Hi there,
Shouldn't this issue be closed?
