### ISSUE TITLE
Support python f-strings

### ISSUE THREAD

**Issue by septatrix** [pallets/jinja#1193]
https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals

## Expected Behavior
Jinja should parse f-strings in templates

## Actual Behavior
Jinja raises a syntax error

## Template Code
```jinja
{{ f"" }}
```

## Full Traceback
```pytb
Syntax error in jinja2 template: expected token 'end of print statement', got 'string'
```

**Comment by ThiefMaster** [comment]
I'm not sure if supporting f-strings in templates makes any sense... I'm tending towards no ;x

**Comment by septatrix** [comment]
I disagree. It is shorter and cleaner to write as one can put the variables directly where they belong.
In addition it would also confuse people coming from python trying to use the syntax if we do not support it
