### ISSUE TITLE
Update docs on adding extensions

### ISSUE THREAD

**Issue by davidism** [pallets/jinja#1201]
https://jinja.palletsprojects.com/en/2.11.x/extensions/#adding-extensions currently says "Once the environment is created additional extensions cannot be added." However, that's not the case, there's a `add_extensions` method.

https://github.com/pallets/jinja/blob/6478c22f29bb85b2bae635602148d95df5e5c7ce/src/jinja2/environment.py#L359-L364

Pointed out in lektor/lektor#770. Update the docs to reflect the ability to add extensions after initializing the environment.

**Comment by sixtyfathoms** [comment]
I'm interested in working on this, but I might need some help figuring out the right changes to make... My understanding is that the discussion in #770 basically lays out the things that should be included. Is this correct?

**Comment by davidism** [comment]
lektor/lektor#770, not 770 from this repo. But everything is summarized in my initial comment.

**Comment by devanshushah1** [comment]
can you tell me what to do brother ma man
