### ISSUE TITLE
tests.test_number validates to True for NaN

### ISSUE THREAD

**Issue by phryk** [pallets/jinja#1206]
`float('nan')` explicitly represents "**Not** a Number" and is used as such by numpy and pandas, but is a number according to jinja2's `number` test.

## Expected Behavior
`jinja2.tests.test_number(float('nan')) -> False`

## Actual Behavior
`jinja2.tests.test_number(float('nan')) -> True`

## Environment
* Python version: any
* Jinja version: at least 2.11.1 and up, most likely any

## Fix
This will need its own explicit check – append `and not math.isnan(value)` to the boolean expression in `test_number`. *Please note that `==` and `!=` **don't** work as expected with `float('nan')`.*

**Comment by davidism** [comment]
Despite its name `is number` is checking the type of the object, not the value. Despite its name, `nan` is a number type. I don't think it's good to add value checking to this test. If you're using Jinja in a context where you need this check, it can be added to that project, it doesn't need to be in Jinja.
