### ISSUE TITLE
why index page has 神社？what this mean?

### ISSUE THREAD

**Issue by yxxhero** [pallets/jinja#1218]
why index page has 神社？what this mean?

**Comment by ThiefMaster** [comment]
Are you talking about our logo?

![](https://jinja.palletsprojects.com/en/2.11.x/_images/jinja-logo.png)

If not, I have no idea what you are talking about, but it's most likely not related to Jinja...

**Comment by yxxhero** [comment]
yes  the log

**Comment by yxxhero** [comment]
I like jinja，but I want kown the logo mean.

**Comment by greyli** [comment]
> Why is it called Jinja?
> The name Jinja was chosen because it’s the name of a Japanese temple (i.e. 神社) and temple and template share a similar pronunciation. It is not named after the city in Uganda.

https://jinja.palletsprojects.com/en/2.11.x/faq/#why-is-it-called-jinja
