### ISSUE TITLE
QUESTION: how do relative paths work on Windows?

### ISSUE THREAD

**Issue by AdamJel** [pallets/jinja#1219]
Hi, I have a problem with templates folder loading on Windows 10. Basically, all works if I use absolute path for `jinja2.FileSystemLoader`. But nothing works, if I use just relative path. More details below.

Also, this behaviour is only if I run the program from IDE (I tried vscode - my native and Spyder). But if I run it from cmd, then it works.

My question 1 is, what am I doing wrong, or what should I tweak in order to make it work.

Question 2 is, why is `jinja2.exceptions.TemplateNotFound:` raised instead of some actually useful exception? I mean, there is problem with path, clearly, but error is about template file.. Even if I try with nonsense path (like `'foo\\\\bar'`), it raises the same error, which is simply not helpful. 

---

## Expected Behavior
Template `test.html` should be loaded using relative path just as in [docs](url)

## Actual Behavior
Exception `jinja2.exceptions.TemplateNotFound:` is raised.

## Template Code
folder structure is this:
geomacc
 |-templates
 |  |-test.html
 |
 |-run.py

```python
import jinja2 as jnj

def foo():
    env = jnj.Environment(
        # WORKS
        loader = jnj.FileSystemLoader(searchpath='C:/Users/jelinek/xxx/app/geomacc/templates'),
        
        # DOES NOT WORK
        loader = jnj.FileSystemLoader('/templates/'),
        loader = jnj.FileSystemLoader('./templates'),
        loader = jnj.FileSystemLoader('/templates'),
        loader = jnj.FileSystemLoader('templates/'),
        loader = jnj.FileSystemLoader('templates'),
        
        autoescape=jnj.select_autoescape(['html']),
    )
    template = env.get_template('test.html')

    output = template.render(
        table_number='does not work from IDE',
    )
    print(output)

```

## Full Traceback
```pytb
  File "c:\Users\jelinek\xxx\app\geomacc\templating.py", line 19, in <module>
    foo()
  File "c:\Users\jelinek\xxx\app\geomacc\templating.py", line 12, in foo
    template = env.get_template('compensations.mpf.jinja')
  File "C:\tools\miniconda3\envs\playground\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\tools\miniconda3\envs\playground\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\tools\miniconda3\envs\playground\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\tools\miniconda3\envs\playground\lib\site-packages\jinja2\loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: compensations.mpf.jinja

```

## Your Environment
* Python version: 3.7.6
* Jinja version: 2.11.2
* Windows: 1909.18363.836
* vscode: 1.45.1

**Comment by obfusk** [comment]
Sounds like it might be a problem with the current working directory vscode uses. I suggest checking whether

```py
import os
print(os.getcwd())
```

gives the same output in vscode as on the command line. If that's the problem, this looks like a solution: https://stackoverflow.com/questions/38623138/vscode-how-to-set-working-directory-for-debug

**Comment by davidism** [comment]
Seems like a CWD issue, closing since there hasn't been a response.

Regarding the error message, the interface for the environment and loaders says that a `TemplateNotFoundError` is raised when the template name is not found. The loader could be trying multiple sub-loaders. The filesystem loader can try multiple paths, and it makes sense to me that some of these paths may not exist, or may not exist when the loader is created. So overall I don't see a clean way to report more detailed information.
