### ISSUE TITLE
Switching From Django Example on Website Out of Date

### ISSUE THREAD

**Issue by hzy** [pallets/jinja#122]
Hi,

on the website one of the examples for how jinja2 differs from Django is the ability to use `{% elif ... %}`. Django now supports that as of 1.4 and should be removed from the docs.

page in question: http://jinja.pocoo.org/docs/switching/#django

**Comment by jeffwidman** [comment]
I can't find an `elif` on that page. I assume it's been updated but nobody closed this issue.
