### ISSUE TITLE
Macro documentation unclear about macros/call

### ISSUE THREAD

**Issue by Chealer** [pallets/jinja#1220]
I am having a hard time understanding the _call_ control structure. The first example in [its documentation](https://jinja.palletsprojects.com/en/2.11.x/templates/#call) uses the _caller_ variable. The only documentation about caller is:

> If the macro was called from a call tag, the caller is stored in this variable as a callable macro.

...which makes me wonder if I even understand macros properly. Please clarify which macros are not callable (or callable).

**Comment by davidism** [comment]
All macros are callable. If you want to call them with a `call` block, you can use `caller()` to treat the block itself as a callable. It's very circular, so it's a bit hard to describe, and I'm not really sure how I would change that section to be clearer.
