### ISSUE TITLE
Using Python function as macro.

### ISSUE THREAD

**Issue by Dreamsorcerer** [pallets/jinja#1249]
I can't seem to figure out how to use a Python function as a macro. I've tried using a function like:

`def if_cond(arg, caller=None):`

called as:

```
{% call if_cond("bar") %}
    APPLE
{% endcall %}
```

But, it seems that caller is `<Macro anonymous>`, which doesn't seem to have any way to retrieve the body. Looking at the source, it appears that the Macro object should have a `body` attribute, however it does not.

**Comment by davidism** [comment]
Macros are a special construct produces by a Jinja `macro` block. `call` is not intended to be used on Python functions passed in to the template.

**Comment by mvolfik** [comment]
@Dreamsorcerer What you want to do (at least in the example, can't see what is the full use case) can be achieved with a filter block:

```python3
import jinja2

def if_cond(body, arg):
    # do something
    return arg + body.strip() + arg

e = jinja2.Environment()
e.filters["if_cond"] = if_cond

template = e.from_string(
"""{% filter if_cond('bar') %}
    APPLE
{% endfilter %}""")

print(template.render())
# --> barAPPLEbar
```
