### ISSUE TITLE
What's wrong with this Jinja template when using {% elif %}

### ISSUE THREAD

**Issue by haimat** [pallets/jinja#1253]
I have the following **Jinja** template:

```jinja
{% if new_data_set_created is defined %}
    {% if new_data_set_created == True %}
        The new image data set <strong>{{ form_data["data_set_name"] }}</strong> has been created.
        {% set form_data = {"data_set_name": "", "client": "", "project": ""} %}
    {% else %}
        The new image data set <strong>{{ form_data["data_set_name"] }}</strong> could not be created.<br />
    {% endif %}
{% elif deleted_data_set is defined %}
    The image data set <strong>{{ deleted_data_set }}</strong> has been deleted from DB and from disk.
    {% set form_data = {"data_set_name": "", "client": "", "project": ""} %}
{% else %}
    {% set form_data = {"data_set_name": "", "client": "", "project": ""} %}
{% endif %}
```

However, when rendering this template via **Flask** I get the error message that `form_data` in line 3 of this code section is undefined (which is not the case, I double-checked that):

    jinja2.exceptions.UndefinedError: 'form_data' is undefined

Now when I remove the `elif` block from that code section above (i.e. lines 8-10) then the very same template does work again and line 3 does not lead to an error any more.

I am calling this template like so:

```python
return render_template(
    "image-data-sets.html",
    new_data_set_created=True,
    form_data=request.form,
    data_sets=ImageDataSet.query.all(),
    clients=clients,
)
```

I double-checked that `request.form` (and thus `form_data` within the template) is not `None`. And as said, I don't make any changes to this call, I just remove those lines from the template and then it's working.

So my question: Why does removing the `elif` block fix this issue, and why is this error raised in the first place? What's wrong with my `if-elif-else-endif` block? Is this a bug or am I missing something?

**Comment by ovezovs** [comment]
I was able to reproduce the issue as it is described. I did some research on this, however, wasn't able to find the cause.

**Comment by davidism** [comment]
The use of `set` here is unnecessary if not incorrect, but I'm not sure if that's causing the issue.

**Comment by ovezovs** [comment]
> The use of `set` here is unnecessary if not incorrect, but I'm not sure if that's causing the issue. Would need to dump the compiled code to see what's being generated and see if that reveals anything. Otherwise step through the frames to see what's defined at that point in the execution.

`set` is, indeed, causing the issue. When I commented out the first `set` on line 4, everything works fine. However, when I executed the `elif` block and printed out `data_form["data_set_name"]`, the `set` within `elif` didn't cause any issues.

**Comment by davidism** [comment]
An initial guess it that setting a name that's passed in to the render context is not intended to be supported, and there's something going on with that in the runtime. So we need to identify the code that's handling that and then decide whether to change it or raise a better error.
