### ISSUE TITLE
[Question] Can someone point me in the direction regex for checking jinja syntax?

### ISSUE THREAD

**Issue by mmoore-3lc** [pallets/jinja#1257]
I have an application that has a requirement to parse jinja syntax to determine correct structure before the template is sent up to the server for processing. If the expression is ill-formed, the user is to be notified so they can correct it.

Can someone point me toward a class in the Jinja source that implements something similar, or a couple of regular expressions I can implement in code? Anything along these lines would be helpful, thanks in advance.

**Comment by davidism** [comment]
Perform the validation server side by trying to parse and returning an error if it doesn't. `env.parse(source)` The alternative is to recreate the parser in whatever language your client is written in.

Please use [our Discord](https://discord.gg/pallets) for discussion about your own code. This tracker is for issues related to the project itself.
