### ISSUE TITLE
Access to the variable name from a filter

### ISSUE THREAD

**Issue by mohovkm** [pallets/jinja#1261]
Hi!
Is it possible, to access the variable name from a filter?

structure: `{"foo":{"bar":123, :"baz":""}}`

filter: `env.filters['my_filter'] = my_filter`

template: `{{ foo.baz|my_filter }}`

```
def my_filter(number: str):
    if number == '':
        #  and here I want to print the name, 
        # in this case its "foo.baz"
        raise Exception(f'You pass an empty string to the [VARIABLE_NAME]') # <--- how to access VARIABLE_NAME ?
```

**Comment by davidism** [comment]
No, this is not possible from a filter. If the name is defined, it's already resolved.
