### ISSUE TITLE
`string()` in List of Builtin Tests table of contents links to wrong section of document

### ISSUE THREAD

**Issue by jerrykan** [pallets/jinja#1262]
## Expected Behavior
Clicking on the `string()` item in the [List of Builtin Tests](https://jinja.palletsprojects.com/en/master/templates/#list-of-builtin-tests) table of contents items takes the user to the documentation for `string()` under [List of Builtin Filters](https://jinja.palletsprojects.com/en/master/templates/#list-of-builtin-filters) instead.

## Actual Behavior
Clicking on the `string()` item in the [List of Builtin Tests](https://jinja.palletsprojects.com/en/master/templates/#list-of-builtin-tests) table of contents items should take the user to the documentation for `string()` under List of Builtin Tests.

This seems to be due to a name collision where the documentation for `string()` under both sections would generate the same document identifier (`id` attribute). I was rather confused when trying to read the documentation until I realised what was going on and had to manually scroll to the correct section.

## Template Code
N/A

## Full Traceback
N/A

## Your Environment
N/A

**Comment by davidism** [comment]
Duplicate of https://github.com/pallets/pallets-sphinx-themes/issues/29, but I'll leave this open since it's more likely to be seen.

**Comment by Enigma04** [comment]
Is this still an issue? I just checked the link given above and as far as I've seen it looks fine, unless I am missing something.

**Comment by davidism** [comment]
yes, it's still an issue

**Comment by Enigma04** [comment]
can you elaborate more?

**Comment by jerrykan** [comment]
@Enigma04 The issue still exists as outlined in my initial submission. I'm not sure what else there is to elaborate on.

**Comment by Pirate2606** [comment]
I want to work on this issue, where can I find the code of the webpages?

**Comment by davidism** [comment]
pallets/pallets-sphinx-themes#29
