### ISSUE TITLE
Jinja renderization doesn't ignore files that are in %include% tag inside HTML comments

### ISSUE THREAD

**Issue by nachokhan** [pallets/jinja#1265]
## Expected Behavior
_**{% include '/yyyyy.html' %}**_ should be ignored because it is inside a comment.

## Actual Behavior
The file '_yyyyy.html_' is being included although it is inside a comment (independently of multi- or single line comment)

## Template Code
```
<div class="row">
      <div class="col">
            {% include '/xxxxx.html' %}
      </div>
      <!-- <div class="col">
            {% include '/yyyyy.html' %}
      </div> -->
</div>
```

## Full Traceback
```
```

## Your Environment
* Python version: 3.7
* Jinja version: 2.11.2

**Comment by ThiefMaster** [comment]
Why would HTML comments affect Jinja? Use `{# ... #}` Jinja comments if you do not want template code to run.

**Comment by nachokhan** [comment]
Because I have a whole structured HTML and while developing I dont want to render some include. The reason: They are not finished, they may still contain bugs. 

If I have a big section in my HTML file containing HTML, Jinja tags.. and I comment all that section, I expect that everything inside this comment is treated as a "final commented HTML section".

In my particular case, the yyyyyyyy.html file contains a jinja variable (a python object) which is not still being passed to the main Jinja template because I'm still debuging. 

Trying to understand your point: which is the reason tough, to include files that are inside an HTML comment?

**Comment by nachokhan** [comment]
I already understood what you meant. 

It is because I have a whole structured HTML and while developing I don't want to render some include. The reason: They are not finished, they may still contain bugs, or whatever development-reason

In my particular case, the yyyyyyyy.html file contains a jinja variable (a python object) which is not still being passed to the main Jinja template because I'm still debuging. When it includes this file, jinja is trying to get the variables that are inside the final commeted section and I get an error.

I already understood what you meant. The thing is

**main.html**
```
... some HTML code

<!-- not still full implemented in my view -->
<!-- <div class="col">
            {% include '/yyyyyy.html' %}
</div> -->
```


**yyyyyy.html**
```
<!-- NAME -->
<label>{{ user.name }}</label>
<!-- AGE -->
<label>{{ user.age }}</label>
```

**"final".html**
```
... some HTML code

<!-- not still full implemented in my view -->
<!-- <div class="col">
	<!-- NAME -->
	<label>{{ user.name }}</label>
	<!-- AGE -->
	<label>{{ user.age }}</label>
</div> -->
```

The comment would be:
```
<!-- <div class="col">
	<!-- NAME -->
```
leaving this as a normal not-commented jinja expression:
`<label>{{ user.name }}</label>`

As you can see, I got an error cause _user_ still does not exist. Of course this example is very simple. I have a bigger HTML structure with this "comments" and I the only way to make work is commenting every single jinja line besides the entire HTML section.

That's why I expect that everything inside this comment is treated as a "final commented HTML section". If not, I have to comment not only my HTML code but also every single jinja line.

Cheers!
