### ISSUE TITLE
docs: clarification for map

### ISSUE THREAD

**Issue by Dreamsorcerer** [pallets/jinja#1269]
Documentation says here: https://jinja.palletsprojects.com/en/2.11.x/templates/#map

`You can specify a default value to use if an object in the list does not have the given attribute.`

Similar to: `(u.username or "Anonymous" for u in users)`

But, the latter will error if the attribute doesn't exist, and uses the default when the attribute is set to `None` (or 0, "" etc.).

If default actually works if the attribute is `None`, this should be mentioned in the documentation. Otherwise, maybe update the expression example to `getattr(u, "username", "Anonymous")`.

I'm a little confused as to what the actual behaviour is (as I am looking for a default when the value is None, rather than missing).

**Comment by tchernomax** [comment]
related to #1331

**Comment by davidism** [comment]
closed by #1356

**Comment by Dreamsorcerer** [comment]
That PR doesn't actually change the documentation. My point is that by reading the documentation, I'm unsure what the actual behaviour is.

The documentation says: if it doesn't have a given attribute
The code example used to clarify the documentation shows: if the attribute is falsy

These are different things, please update one or the other to match the actual behaviour.

**Comment by davidism** [comment]
It's fixed in the next version.

**Comment by Dreamsorcerer** [comment]
master looks identical to me:
https://github.com/pallets/jinja/blob/master/src/jinja2/filters.py#L1111
https://github.com/pallets/jinja/blob/master/src/jinja2/filters.py#L1131

**Comment by davidism** [comment]
yes, but try using it

**Comment by Dreamsorcerer** [comment]
My point is that I shouldn't need to try using it, to figure out what it does.

The 2 lines I just linked are contradictory statements about what the filter does.

This issue is only about the documentation for the filter.

**Comment by Dreamsorcerer** [comment]
So, taking your example (I get a syntax error for some reason when I try it), what happens if you change the class like this?
```
class User:
    name = None
```
or
```
class User:
    name = ""
```

**Comment by Dreamsorcerer** [comment]
OK, there was an extra `}` in your example. I've tested it, and the latter code example is wrong.

Documentation should be like this: https://github.com/pallets/jinja/pull/1364
Which is what I suggested at the very beginning.
