### ISSUE TITLE
Attempt to run `monkeytype` on the codebase.

### ISSUE THREAD

**Issue by teymour-aldridge** [pallets/jinja#1272]
This isn't a "bug" as such.

I thought it would be interesting to see what MonkeyType can come up with for the codebase (it's a tool built by Instagram for generating type hints based on the tests for a codebase).

I'm going to take a shot at this and see how it goes.

**Comment by davidism** [comment]
Closing this as monkeytype turned out to produce poor results for Werkzeug.
