### ISSUE TITLE
Handling list of dictionaries differs between python versions

### ISSUE THREAD

**Issue by Istota42** [pallets/jinja#1283]
Python 2.7 supports dictionaries comparison, so sorting of dict list is supported by default. 
On python 3 `__lt__` is not defined for dictionaries, so it makes harder to migrate projects that uses jinja2 to python 3.

For example for template
```
"{{ items|sort }}"

tmpl.render(items=[{'b': 4}, {'a': 3}, {a': 2}, {'b': 1}])
```
leads to `TypeError: '<' not supported between instances of 'dict' and 'dict'"`

Providing even basic support for dictionaries would make migration process a lot easier.

**Comment by Istota42** [comment]
duplicate #355

**Comment by davidism** [comment]
Same as #1287, I don't want to change how sorting works in Python. If you need to sort this type of data, either sort it ahead of time in Python, where you can make the key function as complex as necessary, or override the sort filter to work differently.

**Comment by davidism** [comment]
Sorry for closing these after you put in the work of PRs. I really do appreciate that you put the time in to implement them even though they were closed, it can be useful for anyone looking for this type of sorting.
