### ISSUE TITLE
Add the @ operator

### ISSUE THREAD

**Issue by remidebette** [pallets/jinja#1286]
This is related to the usage of Numpy and Pandas from Jinja, as stated in https://github.com/pallets/jinja/issues/1285.

Since Python 3.5 and the PEP 465, the `@` operator has been introduced for [matrix multiplication](https://docs.python.org/3/whatsnew/3.5.html?highlight=matrix%20multiplication#whatsnew-pep-465).

The documentation shows a use example:
```python
>>> import numpy

>>> x = numpy.ones(3)
>>> x
array([ 1., 1., 1.])

>>> m = numpy.eye(3)
>>> m
array([[ 1., 0., 0.],
       [ 0., 1., 0.],
       [ 0., 0., 1.]])

>>> x @ m
array([ 1., 1., 1.])
```

Could it be added to the Jinja standard?

**Comment by davidism** [comment]
As in #788, you can inject `operator.matmul` into the globals to allow using this operator in Jinja without any syntax changes. I'm not comfortable changing the syntax of Jinja to support more operators at this time. See https://github.com/pallets/jinja/issues/1285#issuecomment-684900406 for a longer explanation.
