### ISSUE TITLE
Grouping iterable with 'None' in keys differs between python versions

### ISSUE THREAD

**Issue by Istota42** [pallets/jinja#1287]
Python 2.7 allows to compare a value with None. It's not possible in python 3 and it makes harder to migrate projects (that uses jinja2) to python3.

Example:
```
{{ [{'foo': 1, 'bar': 2},
            {'foo': 2, 'bar': 3},
            {'foo': 1, 'bar': 1},
            {'foo': None, 'bar': 5},
            {'foo': 3, 'bar': 4}]|groupby('foo') }}
```
executing
```python
tmpl.render()
```
leads to ```TypeError: '<' not supported between instances of 'NoneType' and 'int'```

**Comment by ThiefMaster** [comment]
My first thought was that if you use Python 3 you should not use such data. But grouping by a field that can have a value or None seems pretty reasonable...

**Comment by Istota42** [comment]
> My first thought was that if you use Python 3 you should not use such data.
For huge projects it's much easier this way
