### ISSUE TITLE
Get render data with a hyphen

### ISSUE THREAD

**Issue by geemang2000** [pallets/jinja#1295]
Access a dictionary value that has a dash/hyphen in it. E.g. foo-bar

env = Environment()
tpl = env.from_string('''{{foo-bar}}''')
data = {'foo-bar': 'Foo Bar'}
assert tpl.render(data) == data['foo-bar']

Results in: jinja2.exceptions.UndefinedError: 'foo' is undefined

'''
/usr/local/lib/python3.8/site-packages/jinja2/environment.py:1090: in render
    self.environment.handle_exception()
/usr/local/lib/python3.8/site-packages/jinja2/environment.py:832: in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
/usr/local/lib/python3.8/site-packages/jinja2/_compat.py:28: in reraise
    raise value.with_traceback(tb)
'''

Environment:
- Python version: Python 3.8.3
- Jinja version: 2.11.2

**Comment by ThiefMaster** [comment]
don't pass such data as top level variables. if you really need them nest them in a dict.

**Comment by geemang2000** [comment]
Here is my workaround. 

    @contextfilter
    def do_dashes(self, context, value):
        return context.resolve(value)

    def test_match_dict(self):

        env = Environment()
        env.filters['dashes'] = self.do_dashes
        tpl = env.from_string('''{{"foo-bar"|dashes}}''')
        tpl = env.from_string('''{{foo-bar}}''')
        data = {'foo-bar': 'Foo Bar'}

        assert tpl.render(data) == data['foo-bar']

**Comment by davidism** [comment]
Since everything is a dict in Python, the name `foo-bar` can be added to a scope, but it's also not valid as an identifier, so it's not possible to look it up by name in the syntax. You can produce this exact same issue in Python itself in certain cases. The workaround demonstrates the "everything is a dict" principle, but I'd really discourage using that.
