### ISSUE TITLE
Bug: Cache pollution in Environment._load_template

### ISSUE THREAD

**Issue by sophiebits-humu** [pallets/jinja#1297]
`Environment._load_template` (called by `get_template`) uses a cache to speed up template loading.

However, note that it takes an argument `globals` but this variable is not used in the cache key:

https://github.com/pallets/jinja/blob/64ade528f3104b505f66bc8d98fd6d0ebb601077/src/jinja2/environment.py#L805-L811

This means that calling `_load_template` can return a template using different globals than the one specified which can be a serious bug.

Jinja version: latest trunk (64ade528f3104b505f66bc8d98fd6d0ebb601077, also present in latest release 2.11.2 and 3.0.0a1)

**Comment by davidism** [comment]
See #1241 and #1244

**Comment by sophiebits-humu** [comment]
Thanks for taking a look. I don't see another issue tracking this nor a new merged commit to address this. This is a bug that can really be a critical security issue in some cases (eg: if `globals` contains sensitive user-specific data).

Is #1244 the PR to track? I notice it has been pending for a few months.

**Comment by sophiebits-humu** [comment]
Oh, I just saw #295.
