### ISSUE TITLE
Filter keys of a dict based on their value

### ISSUE THREAD

**Issue by baby-gnu** [pallets/jinja#1298]
Hello.

I would like to have a new filter which take a single dict and output a list of its key/value depending of the value, which could be complex:

``` jinja
{%- set bigdict = {'top1': {'enabled': true, 'descr': 'this is a top level1 item},
                   'top2': {'enabled': false, 'descr': 'this is a top level2 item}} %}
{{ bigdict | NewFilter('enabled') | join(', ') }}
```

Or maybe it could be an extention of `selectattr`.

I need actually to calculate things with quite a huge amount of jinja:

``` jinja
{%- set bigdict = {'top1': {'enabled': false, 'descr': 'this is a top level1 item'},
                   'top2': {'enabled': true, 'descr': 'this is a top level2 item'}} %}
{%- set filtered = [] %}
{%- for k, v in bigdict.items() %}
{%-   if v.get('enabled', False) %}
{%-     do filtered.append(k) %}
{%-  endif %}
{%- endfor %}
{{ filtered | join(',') }}
```

Regards.

**Comment by davidism** [comment]
Thanks for the suggestion. If this is something you need, you can already register custom filters in your project. I don't plan to add more filters to core at this time.
