### ISSUE TITLE
Environment.getitem is broken in Python 3.9 

### ISSUE THREAD

**Issue by Tarliton** [pallets/jinja#1299]
Hello,

In Python <= 3.8 this code:
```python
dict['__name__']
```

Raises `TypeError` Exception.

In Python 3.9 it does not.
That is because it is valid syntax for type annotation.

Its type is `types.GenericAlias`

Example of valid type annotation:
```python
tags: Set[str] = set()
``` 

In Environment.getitem there is [this part](https://github.com/pallets/jinja/blob/2.11.x/src/jinja2/environment.py#L451-L453).
It expects a TypeError, but, as explained, in Python 3.9 this do not occurs anymore.

Ugly test that gives an error, I couldn't find a specific test for getitem:
```python
def test_groupby_class_name(self, env):
    tmpl = env.from_string(
        """
    {%- for grouper, list in [{'foo': dict(), 'bar': []},
                              {'foo': [], 'bar': []},
                              {'foo': dict(), 'bar': dict()},
                              {'foo': [], 'bar': ""}]|groupby('__class__.__name__') -%}
        {{ grouper }}{% for x in list %}: {{ x.foo }}, {{ x.bar }}{% endfor %}|
    {%- endfor %}"""
    )
    assert tmpl.render().split("|") == ['dict: {}, []: [], []: {}, {}: [], ', '']
```

Python 3.9:
```python
TypeError: '<' not supported between instances of 'types.GenericAlias' and 'types.GenericAlias'
```

Python <= 3.8, it works.

Expected behavior is: to work in Python 3.9.

Thanks.

Environment:

- Python version: 3.9.0
- Jinja version: 2.11.2/master

**Comment by davidism** [comment]
Perhaps there's a real issue here, but the example you've shown doesn't seem like something you should be doing in a template anyway. Why would you need to group by `__class__.__name__`? Basically, this use case seems to contrived to care about fixing.

**Comment by Tarliton** [comment]
Yes, the example is horrible. Sorry about that.
I was able to create a new one, check out if it is better:
```python
def test_groupby_class_name(self, env):
    MyClass = namedtuple("MyClass", "")
    AnotherClass = namedtuple("AnotherClass", "")
    my_list = [MyClass(), AnotherClass(),
               MyClass(), AnotherClass(),
               MyClass(), AnotherClass(),
               MyClass()]
    tmpl = env.from_string(
        """
    {%- for grouper, list in my_list|groupby('__class__.__name__') -%}
        {{ grouper }} {{ list|length }}|
    {%- endfor %}""", globals={"my_list": my_list}
    )
    assert tmpl.render().split("|") == ['AnotherClass 3', 'MyClass 4', '']
```

My real data was not that nonsense of dicts and lists. It was a list of named tuples.
I would like to group them by its class name, to display the amount of them.

In Python <= 3.8, that code above runs with no issues, as for Python 3.9 we get this error:
```python
TypeError: '<' not supported between instances of 'types.GenericAlias' and 'types.GenericAlias'
```
Because of type annotation and that code in Environment.getitem that I explained earlier.

Yes, maybe we have a real issue here, maybe not.

Let's see what do you think about this new test.

If there is no issue in getitem, we can close this.
And I will process this data a little more before rendering as you said.

**Comment by davidism** [comment]
I'd suggest that sorting a list of classes by their names is better done in Python, or by using an attribute to distinguish the types. Additionally, you should probably prefer dataclasses over namedtuples in new code. This is now a built-in behavior of Python, I don't think it's worth it to try to add a workaround in Jinja.
