### ISSUE TITLE
PackageLoader using importlib_resources

### ISSUE THREAD

**Issue by bond** [pallets/jinja#1300]
Hi,

from my understanding the PackageLoader uses pkg_resources which adds a runtime dependency on setuptools, which builds up a list of all installed packages (not just the one which is required to find templates).

It might be interesting to offer a version with importlib.resources for Python3.7+, or even using the backported importlib_resources version to avoid the overhead of pkg_resources?

Simple example of package_loader using importlib_resources:

```python
from jinja2 import Environment, BaseLoader, TemplateNotFound
import importlib_resources

class ImportLibLoader(BaseLoader):
  def __init__(self, path):
    self.path = path

  def get_source(self, environment, template):
    path = ( self.path / template )
    if not path.exists():
      raise TemplateNotFound
    return path.read_bytes().decode('utf-8'), str(path), True

def template_dir():
  resources = importlib_resources.files(__package__)
  return (resources / "templates" )

def render():
  env = Environment(loader=ImportLibLoader(template_dir()))
  template = env.get_template("template.j2")
  return template.render(who="world")
```

If its interesting, I could propose a pull-request with importlib.resources, https://docs.python.org/3.9/library/importlib.html#module-importlib.resources.

**Comment by davidism** [comment]
This is already in the next version.
