### ISSUE TITLE
Tags following urls are being improperly escaped

### ISSUE THREAD

**Issue by kdumovic** [pallets/jinja#1312]
See how in the code snippet below the closing anchor tag following a url is being escaped (`&lt;/a&gt;` instead of `</a>`) when it should not be (Example 1). If a space is added before the closing tag (Example 2), or the `https://` is dropped from the url (Example 3) the closing tag behaves as expected.

It is possible this behavior is intentional but I do not understand why.

```
from jinja2 import Template

# Example 1:
t = Template('<a href="https://www.google.com">https://www.google.com</a>')
print(t.render())
# Output: <a href="https://www.google.com">https://www.google.com&lt;/a&gt;
# Expected: <a href="https://www.google.com">https://www.google.com</a>;

# Example 2: Adding a space after the url. This works as expected.
t = Template('<a href="https://www.google.com">https://www.google.com </a>')
print(t.render())
# <a href="https://www.google.com">https://www.google.com </a>

# Example 3: Dropping the https://. This works as expected as well.
t = Template('<a href="www.google.com">www.google.com</a>')
print(t.render())
# <a href="www.google.com">www.google.com</a>
```

Environment:

- Python version: 3.8.6
- Jinja version: 2.11.2

**Comment by davidism** [comment]
I can't reproduce this issue, all the examples given work as expected. Autoescaping is not enabled by default, and even if it was it is not applied to static template data. There is something else going on with your code, not with Jinja.

**Comment by kdumovic** [comment]
Looks like this is only happening in my Jupyter notebook. If I run the same code in a python shell with the same virtual environment as my notebook, it runs as expected. Very odd.
