### ISSUE TITLE
Additional option to `meta.find_undeclared_variables` 

### ISSUE THREAD

**Issue by jrwaine** [pallets/jinja#1314]
When checking what variables need to be "send" to the template, I use the function `meta.find_undeclared_variables`, which yields all runtime variables, and consider its return the needed variables.

This works well for most cases, but when a variable is created inside a conditional statement with `{% set ... %}`, it is also returned by the function, since it is a runtime variable.

An example of this is

```python
from jinja2 import Environment, meta

src = """
{% if b == 3 %}
    {% set c  =  "test_c" %}
{% endif %}
"""

env = Environment()
ast = env.parse(src)
print(meta.find_undeclared_variables(ast) == set(["b"])) # False
print(meta.find_undeclared_variables(ast) == set(["b", "c"])) # True
```

Currently the workaroud is to declare the variable in global scope and alter it inside the if.

I think that adding an optional parameter to `meta.find_undeclared_variables` to not return variables created by `{% set ... %}` would solve this problem.

**Comment by davidism** [comment]
But `c` *is* undefined in some contexts, since you only define it conditionally. `find_undeclared_variables` is a fairly straighforward walk over the AST, if you need some other introspection you can refer to its code to write your own.
