### ISSUE TITLE
Template "filename" using Template constructor / from_string

### ISSUE THREAD

**Issue by stevelittlefish** [pallets/jinja#1316]
When you create a template by passing a string into the Template constructor, if there is an exception raised by that template it appears in the stack trace like this:

`File "<template>", line 2, in top-level template code`

I would like to be able to pass a string into the Template constructor to identify the template in the stack trace like this:

`my_template = Template('<html>{{ invalid_variable }}</html>', identifier='<Product: ball-bearings>')`

Which would cause the exception to be rendered like this:

`File "<Product: ball-bearings>", line 2, in top-level template code`

This would make it a lot easier to find template issues when you have a lot of small templates rendered in a loop.

**Comment by davidism** [comment]
```python
env = Environment()
code = env.compile("source", filename="<product>")
t = env.template_class.from_code(env, code, env.globals)
```

You can also do this by making your own loader, `Loader.load` returns a tuple of `code, filename, up_to_date_callback`. If you're creatinga  bunch of templates the way you're describing, that's a good idea regardless of wanting custom filenames, as it will be able to take advantage of the compilation cache.

**Comment by davidism** [comment]
While it would be *possible* to add an argument to `from_string`, I think that might give users the impression that it's appropriate to use `from_string` as you've described, for lots of small templates. If a project is rendering so many small templates with errors that it becomes hard to tell them apart, that's an indication they should write a loader. It will give full control and greatly speed up rendering.

**Comment by stevelittlefish** [comment]
Thanks @davidism - your suggestion looks like exactly what I was after.  I will update my code to use a loader.
