### ISSUE TITLE
Continuous fuzzing intergation

### ISSUE THREAD

**Issue by DavidKorczynski** [pallets/jinja#1318]
Hi Maintainers,

I would like to set up continuous fuzzing of jinja by way of OSS-Fuzz. Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. OSS-Fuzz recently added support for Python and it would be great to have Jinja integrated. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid.

In this PR https://github.com/google/oss-fuzz/pull/4761 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate Jinja. This includes developing initial fuzzers as well as integrating into OSS-Fuzz. If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. The emails should be linked to a Google account in order to view the detailed reports and notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by davidism** [comment]
Thanks, this looks interesting, however I don't have the time to manage another service like this. I know Google uses our projects extensively internally and externally, and I'd be happy to accept PRs their employees find as part of this program, all contributions are welcome. :-) Thank you.
