### ISSUE TITLE
Access templates loaded using from_string() by name

### ISSUE THREAD

**Issue by simonvanderveldt** [pallets/jinja#1324]
Thanks for the awesome project!

I've got a question/feature request: Maybe I've missed some functionality somewhere, but it seems like what I'm trying to do isn't possible.
I'd like to include and/or extend a template I've loaded using `env.from_string()` but it seems like this isn't possible because templates that are loaded like this don't have a name/there's no way to reference them from within other templates.

Simplest solution seems to be to have a `name` argument for `from_string()` I think?

**Comment by ThiefMaster** [comment]
I'm not sure if it's a good idea to use `from_string` instead of a proper loader if you have multiple templates that need to reference each other...

**Comment by davidism** [comment]
This came up recently, and I reached the same conclusion. If you need to be referencing other templates, use a loader. DictLoader for example.

**Comment by simonvanderveldt** [comment]
Well, maybe hear out the usecase first before closing it?

So we're mostly working with regular Python code/classes where for each class we want to render some template code (using `import`) as part of a larger template. This way we can keep all the logic in the Python code and unittest it and have small units that can be rendered into the final result. The templates themselves are very small and we'd like to include them within the classes. We can already make this work with the clunky workaround of having to put the templates into a separate files, but this is just annoying overhead/noise and doesn't gain us anything with regards to readability and maintainability of the code, quiet the opposite actually.
I don't really see anything wrong with this approach and all alternative approaches seem worse, but if I'm missing something please let me know.

**Comment by davidism** [comment]
You want to implement a loader. Your loader can do anything, including loading from a class attribute.

**Comment by simonvanderveldt** [comment]
OK, I'll give that a try. Thanks!
