### ISSUE TITLE
lipsum function with equal min and max params generates error

### ISSUE THREAD

**Issue by alkaest2002** [pallets/jinja#1325]
When using **_lipsum_** to generate some fake text with min and max param set to the same value , the function generates the following error: 

```python
<p>{{ lipsum(1, min=20, max=20) }}</p>
ValueError: empty range for randrange() (20, 20, 0)
```

Although, it could make no sense for others, I wanted to have a fixed length fake text.

Environment:

- Python version: 3.8.5
- Jinja version: 2.11.2

**Comment by davidism** [comment]
It uses the same rules as Python's `range`. Use max 21.
