### ISSUE TITLE
Add ifchanged loop variable

### ISSUE THREAD

**Issue by hypertexthero** [pallets/jinja#133]
Please add the ifchanged loop variable that [is available in the original Jinja](http://wsgiarea.pocoo.org/jinja/docs/loops.html#ifchanged) to the default extensions.

**Comment by jheasly** [comment]
@mitsuhiko Could you point to an efficient example of how to achieve this? A function or macro or somesuch? Thanks for any help you can provide!

**Comment by jheasly** [comment]
To answer my own question, discovered Jinja2 [Assignments](http://jinja2.readthedocs.org/en/latest/templates.html#assignments), so:

```jinja
{$ for baz in foo %}

    {% if baz.category != variable_watcher %}
       
        {# Do whatever when there's been a change here. #}
        {% baz.category %}
        {% set variable_watcher = baz.category %}
       
    {% else %}
       
        {# Do whatever when there's no change here. #}
        {% baz.category %}
       
    {% endif %}

{% endfor %}
```

**Comment by lydell** [comment]
Here is a hack I used when migrating an older site until we could refactor the template properly:

```jinja
{% from 'macros/ifchanged.html' import ifchanged %}
{% for num in [1,2,2,3,2,3,3] %}
    {% call ifchanged() %}
        {{ num }}
    {% endcall %}
{% endfor %}
```

```jinja
{#- macros/ifchanged.html -#}

{%- set last=[] -%}
{%- macro ifchanged() -%}
  {%- set next=caller() -%}
  {%- if last|length == 0 -%}
    {{- next -}}
  {%- else -%}
    {%- set prev=last.pop() -%}
    {%- if next != prev -%}
      {{- next -}}
    {%- endif -%}
  {%- endif -%}
  {%- do last.append(next) -%}
{%- endmacro -%}
```

Result:

```
1 2 3 2 3
```

(Hope this helps desperate googlers ending up here! ;) )

**Comment by karolyi** [comment]
Another easy approach:

```html+jinja
{% set last_item=None %}
{% for item in list %}
    {% if last_item is none or last_item != item %}
    I'm changed.
    {% endif %}
    {% set last_item=item %}
{% endfor %}
```
This will work when you have no 'None' in your list. Since I iterate through `QuerySet`-s most of the time, the second condition on the `if` statement can be the check you want to do to see if your item is not the same as the one before.

Thus, you'll get the same behavior as with `ifchanged`.
