### ISSUE TITLE
map filter: can't use a false, '', None, [], {} as default (or anything that is automatically cast to false)

### ISSUE THREAD

**Issue by tchernomax** [pallets/jinja#1331]
https://github.com/pallets/jinja/blob/e39c87c4d474e36dde3b3576a674980e6f4699e1/src/jinja2/filters.py#L70

So this will work:
```
{{ users|map(attribute="username", default="Anonymous")|join(", ") }}
```
but not this:
```
{{ users|map(attribute="username", default="")|join(", ") }}
```

**Comment by s3lph** [comment]
For anyone else that happens to stumble over this: You may be able to use something like this as a workaround:

```django
{{ users | map(attribute="username") | select("defined") | join(", ") }}
```

This works at least in Ansible (where the missing values resolve to `AnsibleUndefined`), I haven't tested with pure Jinja2 though.

**Comment by BALaka-18** [comment]
@davidism I am currently working on this Issue. Notified here.
