### ISSUE TITLE
The things you write in html comments in html templates can be detected and cause errors.

### ISSUE THREAD

**Issue by bugoverdose** [pallets/jinja#1332]
When you render html templates with 'render_template', flask/jinja detect the things you write as comments. For example, the {%~%} and {{ ~ }} formats can be detected even if they are inside the html comments, and they can cause errors.
![example](https://user-images.githubusercontent.com/73531614/104731224-c22a9b00-577e-11eb-8e29-db9d2e1bac93.JPG)

An Example : https://repl.it/@Bugod96/Bug-version#templates/bugTemplate.html
![image](https://user-images.githubusercontent.com/73531614/104731405-fdc56500-577e-11eb-8c70-ae3cbe329cfa.png)
![image](https://user-images.githubusercontent.com/73531614/104731441-07e76380-577f-11eb-9031-4bf9d6dd4b03.png)
![image](https://user-images.githubusercontent.com/73531614/104731617-50068600-577f-11eb-9371-4e675b52cb3c.png)

This happend to me when I used it in Repl.it. Not so sure the same thing happens in all other environments.

**Comment by davidism** [comment]
That's correct, HTML comments are not Jinja comments. Jinja is only concerned with interpretting Jinja syntax, what it's rendering has no meaning to it (it can render any text, not just HTML). Use `{# #}` for comments in Jinja.

**Comment by bugoverdose** [comment]
OK, I guess I should stop trusting 'ctrl + /' too much. Thank you for the explanation. :)
