### ISSUE TITLE
test_nativetypes failure with Python 3.10

### ISSUE THREAD

**Issue by thmo** [pallets/jinja#1335]
There is currently one remaining failure with Python 3.10.0a4 (see https://bugzilla.redhat.com/show_bug.cgi?id=1907442):
```
================================================= FAILURES =================================================
_______________________________________ test_undefined_native_return _______________________________________

env = <jinja2.nativetypes.NativeEnvironment object at 0x7ff4469a0d00>

    def test_undefined_native_return(env):
        t = env.from_string("{{ missing }}")
>       assert isinstance(t.render(), Undefined)

tests/test_nativetypes.py:23:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/jinja2/nativetypes.py:92: in render
    return self.environment.handle_exception()
src/jinja2/environment.py:790: in handle_exception
    raise rewrite_traceback_stack(source=source)
src/jinja2/nativetypes.py:33: in native_concat
    return literal_eval(raw)
/usr/lib64/python3.10/ast.py:108: in literal_eval
    return _convert(node_or_string)
/usr/lib64/python3.10/ast.py:107: in _convert
    return _convert_signed_num(node)
/usr/lib64/python3.10/ast.py:81: in _convert_signed_num
    return _convert_num(node)
/usr/lib64/python3.10/ast.py:72: in _convert_num
    _raise_malformed_node(node)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

node = Undefined

    def _raise_malformed_node(node):
        msg = "malformed node or string"
>       if lno := getattr(node, 'lineno', None):
E       jinja2.exceptions.UndefinedError: 'missing' is undefined

/usr/lib64/python3.10/ast.py:67: UndefinedError
```
Environment:

- Python version: 3.10.0a4
- Jinja version: 2.11.2

The failure is caused by a change introduced in https://github.com/python/cpython/pull/23677 (see also https://bugs.python.org/issue28964): Lib/ast.py now calls `gettattr(node, 'lineno', None)` in `_raise_malformed_node(node)`.
Now, the test case in question renders "{{ missing }}" and expects it to return a Jinja `Undefined` object.  However, the Jinja `Undefined` object raises `UndefinedError` in `__getattr__()`, so `render()` will also raise instead of returning `Undefined`.

This minimal patch fixes the issue:

```diff
diff --git a/src/jinja2/runtime.py b/src/jinja2/runtime.py
index 950f620..316c901 100644
--- a/src/jinja2/runtime.py
+++ b/src/jinja2/runtime.py
@@ -733,6 +733,8 @@ class Undefined:
     def __getattr__(self, name):
         if name[:2] == "__":
             raise AttributeError(name)
+        if name == 'lineno':  # Python 3.10
+            raise AttributeError(name)
         return self._fail_with_undefined_error()

     __add__ = __radd__ = __sub__ = __rsub__ = _fail_with_undefined_error
```

Would this be acceptable as a PR, or is there a better solution?

**Comment by thmo** [comment]
We pass `Undefined` to `ast.literal_eval()`, while that method expects either a string or an AST expression node object. I think what we see here is a side effect of `Undefined` not being an AST node.

**Comment by davidism** [comment]
OK, perhaps we should address that instead? That seems like the more important design issue, but I'm not sure why it's done.

**Comment by thmo** [comment]
What actually happens is even a bit more complex or 'hackish':

The `Undefined` is passed to `ast.literal_eval()`, which tries to convert it, thereby throwing a `ValueError`. This however is caught in jinja's `native_concat()`, and instead the original `Undefined` is returned. 

Before 3.10, it was possible to discriminate between `{{ missing }}` (returning `Undefined`) and `{{ 3 + missing }}` (throwing `UndefinedError`). And the existence of both, `test_undefined_native_return` and `test_adding_undefined_native_return` indicates to me that this is expected behavior.

In 3.10.0a4 however, `ast.literal_eval()` tries to access `lineno` of the `Undefined` passed to it, thereby raising  `UndefinedError`, breaking the first of the two tests.

While looking to this, I found another possible patch fixing the issue:
```diff
diff --git a/src/jinja2/nativetypes.py b/src/jinja2/nativetypes.py
index c71e033..f48f320 100644
--- a/src/jinja2/nativetypes.py
+++ b/src/jinja2/nativetypes.py
@@ -4,6 +4,7 @@ from itertools import islice
 from typing import Any

 from . import nodes
+from . import UndefinedError
 from .compiler import CodeGenerator
 from .compiler import has_safe_repr
 from .environment import Environment
@@ -31,7 +32,7 @@ def native_concat(nodes):

     try:
         return literal_eval(raw)
-    except (ValueError, SyntaxError, MemoryError):
+    except (ValueError, SyntaxError, MemoryError, UndefinedError):
         return raw

```
While the testsuite passes with this with Python 3.9 as well as Python 3.10.0a4, I am not sure whether this could have other side effects. (Hiding away `UndefinedError` in case `native_concat()` gets multiple nodes instead of a single node, but I am not sure whether that actually ever happens.)

**Comment by davidism** [comment]
That doesn't seem correct either. This is the native environment code, concat wants to evaluate valid Python expressions to get a Python object instead of a string when possible. The problem is that it also wants to pass on single nodes as Python objects (including `Undefined` as demonstrated by the test), but it's still trying to evaluate such objects with `literal_eval`.

It seems like what should happen is that if there is only one node it should be returned immediately if it's not a string.
