### ISSUE TITLE
template_name and time_stamp

### ISSUE THREAD

**Issue by hginzel** [pallets/jinja#1338]
Can you please document, how to access template_name and current time_stamp from template, [How to get file name of current template inside Jinja2 template?](https://stackoverflow.com/questions/11157631/how-to-get-file-name-of-current-template-inside-jinja2-template)

**Comment by ThiefMaster** [comment]
I don't think this is something commonly needed... And if you want to provide access to the current timestamp, you could simply add it to your template context like any other data.

**Comment by hginzel** [comment]
I am sorry, I disagree. I consider as a good practice to include a comment like:
```
   This file was generated
        by      generate.py
        from    data.yaml
        using   a.sql.jinja
        on      2021-01-26 11:02:42.
```

You should teach this in (every) example in the documentation. :-) So access to the “standard generated” variables should be made as easy as possible. Lot of tools has autovariables, even Python, [Get name of current script in Python?](https://stackoverflow.com/questions/4152963/get-name-of-current-script-in-python)
