### ISSUE TITLE
Context passed to render disappears when inheritance is used

### ISSUE THREAD

**Issue by ghost** [pallets/jinja#134]
I'm 99% positive that _I'm_ doing something wrong here, but the documentation really doesn't seem to explain what I'm seeing, and tracing through the rendering pipeline is pretty arduous, so I'm hoping for a simple explanation.

Using `FileSystemLoader`, I create a context and pass it to each `Template`s `render` method like so:

``` python

env = Environment(  loader=FileSystemLoader(["./layouts"]),
                        trim_blocks=True ,
                        autoescape=False )

context     =   { "negasonic": "deny" }

for path in env.loader.list_templates():
    template    = env.get_template(path, context)
    output        = template.render(context).encode("utf-8") 
    print output
```

If a file in `./layouts` contains this:

```
{{ negasonic }}
```

Then the output is predictably

```
deny
```

If a file in `./layouts` uses inheritance to extend another file in `./layouts`:

```
{% extends "base.j2" %}
{% block content %}
    {{ super() }}
{% endblock content %}
{{ negasonic }}
```

The ouput then contains everything from `base.j2` and the output of its `content` block, but the variable `negasonic` disappears and is not expanded.

I have tried adding the contents of my `context` dict to the `Environment`'s globals as well as to the `Template`'s globals, and this makes no difference. So my questions are:
1. Why is my context emptied when I use the `extends` keyword?
2. How can a template file dump out a textual representation of everything that it _is_ being passed so I can debug via introspection in cases where the documentation simply isn't very clear?

Thanks!

**Comment by davidism** [comment]
This is intended behavior. After the `{% extends %}` tag, only stuff within blocks produces output.
