### ISSUE TITLE
Option to treat leading dash as minus-sign

### ISSUE THREAD

**Issue by prescod** [pallets/jinja#1342]
In my application I have no need of whitespace stripping features of Jinja. But I would like negative numbers to be easy to type. So I would like an option for this to produce -1. If there is such an option, I missed it:

```
>>> env.from_string("{{-1}}").render()
'1'
```

Perhaps it is possible for me to do this with an extension? Or configuration option that I missed?

**Comment by davidism** [comment]
Template braces should be padded with spaces: `{{ -1 }}` Fairly sure you can run into other issues besides this if you don't do so.
