### ISSUE TITLE
Discrepancy on order of operations with the power operator

### ISSUE THREAD

**Issue by Skeen** [pallets/jinja#1355]
I believe I have found a discrepancy between how Python and Jinja handles the power operator (`**`):
```
$ python3 -c "print(3**3**3)"
7625597484987
$ python3 -c "from jinja2 import Template; print(Template('{{ 3**3**3 }}').render())"
19683
```
The issue seems to be related to the order of operations;
Python3 evaluates the above as: `3**(3**3)`
Jinja evaluates the above as `(3**3)**3`

Environment:

- Python version: Python 3.9.1+
- Jinja version: 2.11.2

**Comment by davidism** [comment]
Probably can't change this now, but either way I would not recommend doing that sort of math in a template, use Python for that.

**Comment by Skeen** [comment]
Would it be worth documenting the discrepancy or generating a warning to introduce parenthesis to be explicit about the order you want?
