### ISSUE TITLE
Request for re 'matching' test

### ISSUE THREAD

**Issue by trane** [pallets/jinja#136]
In jinja 1.x, there was a great 'matching' re matcher in tests. It would be _extremely_ helpful to have something similar in jinja2.
https://portal.sbgrid.org/docs/usr_doc/python-jinja-1.2/html/builtins.html#tests

**Comment by davidism** [comment]
Probably better to write a specific test and add it per project. I have no insight into the Jinja 1 source, so I don't know how the original worked.
