### ISSUE TITLE
Reduce template loading complexity

### ISSUE THREAD

**Issue by WolfgangFahl** [pallets/jinja#1365]
I get the weird behavior that my testcase below works in my mac os environment with a macports python 3.8.6 as well as on my Ubuntu 20.04 LTS server with a python 3.8 in a jenkins environment. In the CI environments at github and travis the code chokes with the error 

"no module named ..."

No matter what i try - see a list of builds at https://github.com/BITPlan/pyWikiCMS/actions

I checked.

-  https://stackoverflow.com/questions/51234494/import-module-from-above-folder-does-not-work-with-ci-server
-  https://stackoverflow.com/questions/10095037/why-use-sys-path-appendpath-instead-of-sys-path-insert1-path
-  https://stackoverflow.com/questions/38617900/need-to-package-jinja2-template-for-python

which are discussing relevant questions  at length. Today I created a python test case 
```
def createPackage(self,packageFolder,templateFolder,moduleName,moduleCode,templateCode):
        moduleFolder="%s/%s" % (packageFolder,moduleName)
        os.makedirs(moduleFolder,exist_ok=True)
        absTemplateFolder="%s/%s" % (moduleFolder,templateFolder)
        os.makedirs(absTemplateFolder,exist_ok=True)
        modulePath="%s/__init__.py" % moduleFolder 
        with open(modulePath,"w") as moduleFile:
            moduleFile.write(moduleCode)
        templatePath="%s/test.html" % (absTemplateFolder)
        with open(templatePath,"w") as templateFile:
            templateFile.write(templateCode)
        
    def testIssue14Templates(self):
        '''
        test template handling
        '''
        packageFolder='%s/www.wikicms' % tempfile.gettempdir()
        templateFolder='templates'
        moduleName='bitplan_webfrontend'
        moduleCode="""
def test():
    pass
        """
        templateCode="""
{{ msg }}        
"""
        self.createPackage(packageFolder, templateFolder, moduleName, moduleCode, templateCode)
        frontend=self.server.enableFrontend('www',debug=True)
        #self.assertEqual(templateFolder,frontend.site.templateFolder)
        self.assertEqual(moduleName,frontend.site.packageName)       
        html,error=frontend.renderTemplate("test.html",{"msg":"Hello world!"})
        self.assertIsNone(error)
        self.assertTrue("Hello world!" in html)
        
```

with the weird behavior that it works in my mac os environment with a macports python 3.8.6 as well as on my Ubuntu 20.04 LTS server with a python 3.8 in a jenkins environment. In the CI environments at github and travis the code chokes with the error 

"no module named ..."

No matter what i try - see a list of builds at https://github.com/BITPlan/pyWikiCMS/actions

The question https://stackoverflow.com/questions/38642557/how-to-load-jinja-template-directly-from-filesystem  has some 79 k hits and the comment:

_Sort of ridiculous you can't load a template from a file in one line e.g. jinja2.load_template('template.html')_ 

has 104 upvotes.
For me this sounds like a big need to have better template loading handling that is less complicated. My assumption would be if a i load a template from a directory that it would be possible to hint that everything else in that directory should be considered a valid "context" for the template so that it's not necessary to fiddle with sys.path or any other python internals in a way that is incompatible with the design of Jinja2. 

I think the complexity should be completly hidden as proper information hiding would suggest.

**Comment by davidism** [comment]
Sorry, I don't understand what's being asked here. Closing due to lack of clarity or actionable request, but I'll respond to some points.

It sounds like you have an issue keeping paths consistent between your local machine and CI, but that's a general Python issue, it's not something I'm able to help debug here.

> My assumption would be if a i load a template from a directory that it would be possible to hint that everything else in that directory should be considered a valid "context" for the template so that it's not necessary to fiddle with sys.path or any other python internals in a way that is incompatible with the design of Jinja2.

As much as I can follow what you're saying here, that's already the case. You do not need to "fiddle with `sys.path` or any other Python internals" to load templates in Jinja.

> For me this sounds like a big need to have better template loading handling that is less complicated. ... I think the complexity should be completly hidden as proper information hiding would suggest.

You haven't suggested what "less complicated" should be, or how things should be "completely hidden" and yet still continue to provide the same features. I'm not clear what "proper information hiding" is or what it suggests, so there's nothing I can work with.

**Comment by WolfgangFahl** [comment]
@davidism 
thank you for looking into this.

The complexity might be lowered if the code:
```
jinja2.load_template('/somepath/mypackage/templates/template.html',asPackage=True)
```
would work. asPackage=True should be the default meaning that mypackage would be automatically be loaded as a package so that e.g. code from a module in /somepath/mypackage/mymodule.py could be automatically imported as 
```
import mymodule 
```

without extra effort.
So the first template being used from a package would automatically make sure anything else in the package is also available.

As for information hiding ... https://en.wikipedia.org/wiki/Information_hiding shows that this is a principle postulated by David Parnas in 1972 to promote better software engineering. The principle of information hiding is IMHO underrated in quite a few modern software projects and this leads to quite a few followup issues like the one i am experiencing today with this issue.

**Comment by WolfgangFahl** [comment]
Which of the answers of https://stackoverflow.com/questions/38642557/how-to-load-jinja-template-directly-from-filesystem would you personal prefer? Especially in the light of the need for inheritance?
