### ISSUE TITLE
Template cache can ignore changed globals

### ISSUE THREAD

**Issue by data-harmonization** [pallets/jinja#1370]
I'd like to report a bug where a change in the global variables is ignored by the template caching mechanism.

**Background**
The jinja2 environment loads templates using the function __load_template_ in _environment.py_. This function takes also the _globals_ parameter, where additional variables can be provided. When the template is initiated, the entries in _globals_ are given to the template as available variables to be used in the rendering process.

**Problem**
The __load_template_ function uses caching by default. So, when a template is loaded for the second time, the caching is used. Since the entries of _globals_ are given to the template, the cache should be invalidated when _globals_ changes. This doesn't happen. 

In my case, I used the file-loader to load a template and assign variables to the environment.
```
template = self.env.get_template(
    name=self.get_template_path(yml_payload).name,
    globals={"test": "test1"},
)

print(template.render({}))

template = self.env.get_template(
    name=self.get_template_path(yml_payload).name,
    globals={"test": "test2"},
)

print(template.render({}))
```
When I instantiate my template as 
```
{{ test }}
```
The resulting output of my print statements are:
> test1
> test1

When I would disable the cache by setting the "cache" parameter of my jinja2 environment to None, I get:
> test1
> test2

- Python version: 3.8.7
- Jinja version: 2.11.3

**Comment by davidism** [comment]
This is a duplicate, but I'm in my phone and can't find it now.

**Comment by data-harmonization** [comment]
Got it David! https://github.com/pallets/jinja/issues/295

It might be good to mention that in my case, there is a workaround by disabling the cache. However, big chance that this workaround is not applicable to the case of issue 295, since the use case is based on extending a template.
