### ISSUE TITLE
Whitespace control operator for lstrip_blocks and trim_blocks

### ISSUE THREAD

**Issue by ggiesen** [pallets/jinja#1372]
It would be very useful if there was a whitespace control operator similar to `-` that had the same effect as `lstrip_blocks` (leading spaces and tabs are stripped from the start of a line to a block) and `trim_blocks` (the first newline after a block is removed)

This would make whitespace control in cases where lstrip_blocks and trim_blocks can't be used globally or even per-template.

Perhaps an underscore as the operator:

`{%_` would strip all spaces and tabs from the start of a line to a block

`_%}` would remove the first newline after a block

Currently there's no way to achieve reliable newline control without `lstrip_blocks`/`trim_blocks` without using something like a comment `{# 1  #}` which clutters templates and greatly impacts readability

**Comment by davidism** [comment]
I don't plan to add more syntax such as this at this time. There is already too much complexity around how spacing is handled. Perhaps this might change in the future, but there is too much else to think about right now regarding the parser and other spacing issues to also think about how this might interact.

It would help if you showed an example of "where lstrip_blocks and trim_blocks can't be used globally". I would recommend users always start with both enabled and use `+` to turn it off selectively.

**Comment by ggiesen** [comment]
> 
> 
> I don't plan to add more syntax such as this at this time. There is already too much complexity around how spacing is handled. Perhaps this might change in the future, but there is too much else to think about right now regarding the parser and other spacing issues to also think about how this might interact.
> 
> It would help if you showed an example of "where lstrip_blocks and trim_blocks can't be used globally". I would recommend users always start with both enabled and use `+` to turn it off selectively.

I'm currently using jinja templates in Salt for both systems and network devices. Unfortunately, if you enable lstrip_blocks or trim_blocks, it break's all of Salt's formula ecosystem (https://github.com/saltstack-formulas). Salt also doesn't current have a per-file override similar to Ansible (though there is a feature request pending saltstack/salt#35398)
