### ISSUE TITLE
TemplateNotFound error when path contains Windows path separators

### ISSUE THREAD

**Issue by balsa-sarenac** [pallets/jinja#1378]
### Bug report
On Windows OS we can't render template with Windows path separator. We are using [textX-jinja](https://github.com/textX/textX-jinja) to render our templates. 

#### How to replicate
We encountered the bug when sending template path for rendering like: some_folder\file.txt.jinja
Here is the image of traceback.
![jinja-bug](https://user-images.githubusercontent.com/34557616/113394414-7ad4a380-9398-11eb-863d-d81a9552f3ec.png)

#### Solution
We also found solution to this bug. When we changed hardcoded path separator in [loader.py line 24](https://github.com/pallets/jinja/blob/1c863d0447efb7e68e2593e7de3fec87670521cb/src/jinja2/loaders.py#L24) everything was working again both on Windows OS and Linux distros.

We created this issue as a discussion before submitting pull request.

#### Expected behavior
Given template should have been rendered, instead TemplateNotFound was raised.

#### Environment:

- Python version: 3.9.2
- Jinja version: 2.11.3

**Comment by ThiefMaster** [comment]
Jinja template names/paths are not always filesystem paths. So regardless of the OS Jinja always uses forward slashes.

PS: Even for actual filesystem access forward slashes work just fine on Windows.
