### ISSUE TITLE
Support for inline for loops

### ISSUE THREAD

**Issue by buremba** [pallets/jinja#1379]
It would be great if we can use for loops similar to the way [inline if expressions](https://jinja.palletsprojects.com/en/2.11.x/templates/#if-expression) works. I'm looking for a way to pass a parameter to a function and use a for loop in order to build the parameter as follows but the snippet doesn't compile.

```
{{ myfunc(i for i in range(4)) }}
```

Is there any alternative at the moment?

**Comment by davidism** [comment]
While Jinja does support more template-based data manipulation than some other engines, in the end it's still expected that most complex data manipulation will be done in Python first. This discussion in the [docs](https://jinja.palletsprojects.com/en/2.11.x/faq/#isn-t-it-a-terrible-idea-to-put-logic-into-templates) explains a bit:

> Jinja neither allows you to put arbitrary Python code into templates nor does it allow all Python expressions. The operators are limited to the most common ones and more advanced expressions such as list comprehensions and generator expressions are not supported. This keeps the template engine easier to maintain and templates more readable.

For your simple example `myfunc(range(4))` is equivalent, for more complex examples you would probably use a filter like `myfunc(range(4) | filter(...))`, or move the filtering part of the comprehension into `myfunc` and pass the range only.

**Comment by buremba** [comment]
Thanks for the explanation @davidism.
