### ISSUE TITLE
Map gettext to list of strings.

### ISSUE THREAD

**Issue by peteris-zealid** [pallets/jinja#1396]
```
{% trans my_list=my_list|map('gettext')|join(', ') %}
Here is my list translated and joined by commas {{ my_list }}.
{% endtrans %}
```

The simplest way I could think of to do this without using `gettext` in my .py files is this:
```
{% macro translatejoin(strings) %}
{% if strings|length == 0 %}
{% else %}
    {% for s in strings[:-1] %}
        {{ gettext(s) }},
    {% endfor %}
    {{ gettext(strings[-1]) }}
{% endif %}
{% endmacro %}

{% trans my_list=translatejoin(my_list) %}
...
```
I am not an experienced jinja user so I had to dig though a lot of documentation to learn that I can write macros. I believe such list translation functionality would be useful for others. It would also allow for more flexible usage of filters.

**Comment by ThiefMaster** [comment]
Calling `gettext()` on dynamic strings is almost always wrong, since you cannot extract messages that way.

If you want data from such a list to be translated, you need to do that at an earlier point where you have static strings. Python example:

```py
# correct:
data = [_('foo'), _('bar')]
print(', '.join(data))

# wrong:
data = ['foo', 'bar']
print(', '.join(_(x) for x in data))
```

And if it's dynamic data from a database, then gettext won't help you at all...

**Comment by peteris-zealid** [comment]
The use case in particular is for an enumeration that is stored in database and defined in code. Many ORMs expect you to define your enumerations in code anyway and wrapping them in `_()` is not hard. See https://docs.python.org/3/library/gettext.html#deferred-translations

Using gettext in this case is appropriate because the strings in question are dynamic, but from a limited set of predefined values.

**Comment by ThiefMaster** [comment]
Fair enough, having static definitions for those strings that can be extracted are indeed the one exception from "almost always wrong". :)

However, I wonder if it wouldn't make more sense to expose a custom function to your template environment in this case... I think providing this out of the box is more likely to be used in incorrect ways that break extraction where people don't mark those strings for translation elsewhere...

You could probably even add a property like this to your model:

```py
@property
def translated_title(self):
    return _(self.title)
```

and then just use that in your templates.

**Comment by peteris-zealid** [comment]
Yes, but I do not want to introduce configuration of gettext in addition to one required by Flask-Babel. In other words I would like to keep gettext isolated.

Thank you for your time regarding my suggestion.
