### ISSUE TITLE
Invalid example for selectattr in docs

### ISSUE THREAD

**Issue by gralin** [pallets/jinja#1397]
In the documentation:

https://jinja.palletsprojects.com/en/2.11.x/templates/#selectattr

these are the examples of using `selectattr` filter

```python
{{ users|selectattr("is_active") }}
{{ users|selectattr("email", "none") }}
```

I believe the second example is not what was intended and it's missleading. I doubt the test was supposed to check boolean value of field named `none`. Instead, I think it was supposed to check if field `email` is equal to `none`, like this:

```python
{{ users|selectattr("email", "equalto", "none") }}
```

Forgive me if I'm wrong and no hard feelings for closing this issue.

**Comment by davidism** [comment]
That's applying the "is none" test to the "email" field.
