### ISSUE TITLE
`Markup.__init__` causes error

### ISSUE THREAD

**Issue by kernc** [pallets/jinja#1400]
I obviously don't expect you to debug my `--pre` CI runs, but what I read points to recent Jinja 3.0.0rc1 / markupsafe 2.0.0rc2 prereleases. Please see: https://github.com/kernc/backtesting.py/runs/2371946706?check_suite_focus=true#step:11:234

The error:
```
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```
issued here: https://github.com/pallets/jinja/blob/d77a91b1cba05d9dc78d4b03d312fcff3ca91ebb/src/jinja2/utils.py#L843
seems to indicate `markupsafe.Markup` for some reason is `object` rather than `str`. :confused: 

Environment:

- Python version: 3.8
- MarkupSafe version: 2.0.0rc2

**Comment by kernc** [comment]
Reported to Bokeh in https://github.com/bokeh/bokeh/pull/11174 and https://github.com/bokeh/bokeh/issues/11175.

Many thanks for your feedback!

**Comment by davidism** [comment]
I'm not going to make an rc2 release quite yet, I'll wait to see what other feedback comes in. I'd suggest pinning your dependencies for testing (and possibly in general depending on whether you're a library or end-user project), unless you were deliberately testing all pre-releases.

**Comment by davidism** [comment]
`pip install --pre -U jinja2` to get Jinja 3.0.0rc2.
