### ISSUE TITLE
Latest jinja2==3.0.0 not found via pip install

### ISSUE THREAD

**Issue by shihgianlee** [pallets/jinja#1421]
When installing latest jinja2 via pip install `jinja2==3.0.0`, it is not found.

`jinja2==3.0.0`

jinja2 3.0.0 should be installed but error out with not found error message.
Environment: Linux

- Python version: 3.7
- Jinja version: 3.0.0

**Comment by davidism** [comment]
I can't reproduce this issue. `pip install jinja2 in a fresh Python 3.7 virtualenv installs it correctly. Sounds like it might be an issue on your side.
