### ISSUE TITLE
SyntaxError in bccache.py on 20210512

### ISSUE THREAD

**Issue by wawjddq** [pallets/jinja#1423]
after I use "pip install jinja2", the code occurs an error like this:

Traceback (most recent call last):
  File "./myown.py", line 15, in <module>
    from jinja2 import Template,FileSystemLoader
  File "/usr/local/lib/python3.6/site-packages/jinja2/__init__.py", line 5, in <module>
    from .bccache import BytecodeCache
  File "/usr/local/lib/python3.6/site-packages/jinja2/bccache.py", line 26
    def get(self, key: str) -> bytes:
                     ^
SyntaxError: invalid syntax

Environment:

- Python version: 3.6
- Jinja version:  jinja2-3.0.0

**Comment by davidism** [comment]
I can't reproduce this issue. I created a fresh Python 3.6 virtualenv, installed jinja2, and did `from jinja2 import Template, FileSystemLoader` and did not get any errors.

**Comment by wawjddq** [comment]
thanks， the errors caused by python environment
