### ISSUE TITLE
Type annotations don't work in strict mode with mypy

### ISSUE THREAD

**Issue by gaborbernat** [pallets/jinja#1426]
Python 3.9.5 + mypy 0.812

```python
# magic.py
from jinja2 import Environment
```

```bash
mypy ./magic.py
Success: no issues found in 1 source file
```

```bash
mypy ./magic.py --strict
magic.py:1: error: Module 'jinja2' does not explicitly export attribute 'Environment'; implicit reexport disabled
Found 1 error in 1 file (checked 1 source file)
```

Thanks 👍

**Comment by davidism** [comment]
You can add the following config to your project to allow Jinja (or other packages) to export from `__init__`, since it's a very common pattern.

```
[mypy-jinja2]
no_implicit_reexport = False
```

See https://github.com/python/mypy/issues/10198 for discussion on changing this behavior.

**Comment by gaborbernat** [comment]
I'd expect that configuration to be part of the upstream project, not the downstream user. Seems it's a choice of the project if they want implicit re-export or not, not the user apps 🤔

**Comment by davidism** [comment]
There is no configuration that upstream projects can provide.

**Comment by gaborbernat** [comment]
Hence why most projects use explicit export to not run into this. If you insist on implicit re-export feels like worth creating a PEP and allowing this configurability.

**Comment by dquitmann-op** [comment]
Hi @davidism,

is there any release schedule for 3.0.1 fixing this behavior? I do not want to build any pressure, just to know if we should (temporarily) change our pipelines or just can wait for a fixed release coming in the next days.

Thanks very much for the quick fix and your answer in advance!
