### ISSUE TITLE
Jinja 3.0 is throwing DeprecationWarning: The 'with' extension is deprecated and will be removed in Jinja 3.1. This is built in now.

### ISSUE THREAD

**Issue by nickjj** [pallets/jinja#1429]
Environment:

- Python version: 3.9.5
- Jinja version: 3.0.0

Issue:

I updated a decently large project to use Flask 2.0 / Jinja 3.0 and now I'm seeing this deprecation warning when I start the app:

```
python3.9/site-packages/jinja2/environment.py:119: DeprecationWarning: The 'with' extension is
deprecated and will be removed in Jinja 3.1. This is built in now.
    result[extension.identifier] = extension(environment)
```

In my application I am referencing includes like `{% include 'example.html' with context %}`. It sounds like at the app level `with` is still supported but something internally to Jinja 3 needs to change?

**Comment by ThiefMaster** [comment]
As you can see here, it doesn't do anything:

https://github.com/pallets/jinja/blob/main/src/jinja2/ext.py#L600-L608

**Comment by nickjj** [comment]
When you say `you literally just need to remove the extension` what needs to be done on my end to do this? I never explicitly enabled this extension in my application.

The only bits of jinja I modified in my app has been to add a custom filter and global, neither of those things use `with`.

**Comment by olemoign** [comment]
Did you activate the `with_` extension?
```env = Environment(extensions=["jinja2.ext.with_"])```

**Comment by nickjj** [comment]
Nope, I have 0 lines of code in my application that enable any Jinja extensions.

**Comment by nickjj** [comment]
After grepping my `site-packages` it looks like Flask-Debugtoolbar references it with `./flask_debugtoolbar/__init__.py:            extensions=['jinja2.ext.i18n', 'jinja2.ext.with_']` which is here: https://github.com/flask-debugtoolbar/flask-debugtoolbar/blob/d474a6a689be916d65c2adf173e6517290902abe/flask_debugtoolbar/__init__.py#L62.

Perhaps this deprecation warning could be more specific to the reference on what's calling it?

**Comment by davidism** [comment]
It's as specific as it can be. Python's warnings don't provide much control over what context is shown, and we don't have the necessary information to show a different message either.

**Comment by davidism** [comment]
I think I can change the stack level for the warning so it shows the `Environment()` creation as the source.
