### ISSUE TITLE
Add block syntax for pgettext

### ISSUE THREAD

**Issue by remram44** [pallets/jinja#1430]
Follow up on #441, #1126

It was difficult to come to an agreement on the syntax for block translation with context, so it was left out of #1126. However this should still be added.

The possibilities that were discussed are:

* `context` keywords: `{% trans context "mycontext" num=3 %}One Text{% pluralize %}{{num}} Texts{% endtrans%}`
  * [This resembles what Django uses](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#translate-template-tag)
* `{% context %}` block: `{% trans %}Click me{% context %}In annoying popup{% endtrans %}` (similar to `{% pluralize %}`
  * But context is usually very short, using a block might be wasteful
* Adding on `trans` directly: `{% trans "greeting" %}Hello{% endtrans %}` or `{% trans(greeting) %}Hello{% endtrans %}`

I personally don't feel strongly at all, but I really could use such a syntax.

**Comment by davidism** [comment]
I prefer the third option. Parse an initial string literal if possible and use pgettext in that case.

**Comment by ThiefMaster** [comment]
3rd option looks good
