### ISSUE TITLE
macro.defaults is not available

### ISSUE THREAD

**Issue by jamesfreeman959** [pallets/jinja#1432]
I have a macro that accesses `macro.defaults`, which is documented to have the default values for keyword arguments. However, Jinja > 2.8.1 does not provide this.

```
import jinja2

e = jinja2.Environment()
t = e.from_string("""\
{% macro greet(name="World") %}
    {{ greet.defaults }}
    Hello, {{ name }}!
{% endmacro %}
{{ greet("Jinja") }}
""")
print(t.render())
```

It shows

```

Hello, Jinja!
```

But I expect it to show

```
{'name': 'World'}
Hello, Jinja!
```

Exception will be raised for Jinja2 > 2.8.1, but template will render for Jinja2 <= 2.8.1

This macro variable still appears in the documentation for Jinja2, so it should work even on newer versions

Environment:

- Python version: 3.8.5
- Jinja version: 2.9 and newer

**Comment by davidism** [comment]
Please provide a self-contained example with Jinja only, I cannot run Ansible to test this.

**Comment by jamesfreeman959** [comment]
Thank you @davidism - I had just sat down to work it into some Python code.

**Comment by amy-lei** [comment]
The `defaults` attribute was intentionally removed in 2.9 (see 9b2a4f49c61dc81c51db1a3f30aeb90e4c700ecd). Looks like the [docs](https://jinja.palletsprojects.com/en/3.0.x/templates/#macros) need to be updated to reflect this.
