### ISSUE TITLE
Unpacking **dict within a dict causes a TemplateSyntaxError

### ISSUE THREAD

**Issue by malan88** [pallets/jinja#1437]
The double star keyword argument unpacker fails to work within a dictionary and raises a `jinja2.exceptions.TemplateSyntaxError: unexpected '**'` error.

Simplest reproducible example, using flask:

Route:
```
@bp.route('/test')
def test():
    return render_template('test.html', a={'a': 1})
```
And the template:
```
{% with args={'b': 2, **a} %}
    {{ args }}
{% endwith %}
```

`args` should have been `{'b': 2, 'a': 1}` as is standard Python behavior:

```
[ins] In [11]: a = {'a': 1}
[ins] In [12]: {'b': 2, **a}
Out[12]: {'b': 2, 'a': 1}
```

I know that Jinja2 is not a full-featured implementation of Python, which is why I have to add certain functions to the globals in app instantiation, so if this is expected behavior please close the issue.

Environment:

- Python version: Python 3.6.9
- Jinja version: Jinja2==2.11.3

**Comment by davidism** [comment]
This isn't something I think we can support right now. Do this sort of processing in python.
