### ISSUE TITLE
DOCS - ERR_TOO_MANY_REDIRECTS when clicking on a search result on the documentation

### ISSUE THREAD

**Issue by luzfcb** [pallets/jinja#1441]
- Open the documentation website on https://jinja.palletsprojects.com/en/3.0.x/
- Search by a term like `space` (the search page will generate the URL https://jinja.palletsprojects.com/en/3.0.x/search/?q=space )
- Click in one of the search results, like https://jinja.palletsprojects.com/en/3.0.x/search/api/?highlight=space

This is the error:

![Screenshot_20210517_111114](https://user-images.githubusercontent.com/807599/118503048-a6b9a780-b700-11eb-9a9b-dac19f0d2abe.png)

Environment:

- Python version: not applicable
- Jinja version: 3.0

**Comment by davidism** [comment]
https://github.com/pallets/pallets-sphinx-themes/issues/39
