### ISSUE TITLE
3.0.1: build fails

### ISSUE THREAD

**Issue by kloczek** [pallets/jinja#1446]
Linux z86_64, gcc 11.1.0
```console
[tkloczko@barrel protobuf-c-1.3.0]$ make
/usr/bin/g++ -DHAVE_CONFIG_H -I.  -include ./config.h -I./protobuf-c -I. -I.   -pthread  -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -c -o protoc-c/protoc_gen_c-c_bytes_field.o `test -f 'protoc-c/c_bytes_field.cc' || echo './'`protoc-c/c_bytes_field.cc
In file included from ./protoc-c/c_bytes_field.h:68,
                 from protoc-c/c_bytes_field.cc:63:
./protoc-c/c_field.h:120:3: error: ‘scoped_array’ does not name a type
  120 |   scoped_array<scoped_ptr<FieldGenerator> > field_generators_;
      |   ^~~~~~~~~~~~
make: *** [Makefile:1366: protoc-c/protoc_gen_c-c_bytes_field.o] Error 1

```

**Comment by davidism** [comment]
This does not appear to be related to Jinja.

**Comment by blueboar2** [comment]
This is not error of Jinja. You're trying to compile protobuf, and it's not compiling. You need to ask in the protobuf bug tracker, not here.

BTW: This error is appearing, because protobuf till version 3.5.0 uses Boost C library to deliver this "scoped_array". So, you need to install Boost before compiling protobuf.

**Comment by kloczek** [comment]
Sorry.
My fault.
Neverteheless jinga build fails.
Will open separated ticket.

**Comment by kloczek** [comment]
Update. I was wrong second time. I found failing sphinx documentation however I had installed not final version of the markupsafe module.
After upgrade to final 2.0 documentation build correctly.
