### ISSUE TITLE
Token object has no atribute 'test'

### ISSUE THREAD

**Issue by austinsoft** [pallets/jinja#1450]
Environment:

- Python version:
- Jinja version:

**Comment by austinsoft** [comment]
Python 3.6 hosted on pythonanywhere.com
Jinja2

**Comment by austinsoft** [comment]
Upgraded to latest jinja and Flask now I get jinja2/parser.py", line 560, in parse_not if self.stream.current.test("name:not"): AttributeError: 'Token' object has no attribute 'test' OSError: write error

**Comment by ThiefMaster** [comment]
Please don't open low-quality issues like this. A full traceback and code to reproduce **in the issue itself** are the least you can provide...
