### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by sulaimanismail** [pallets/jinja#1458]
>>> import Jinja2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Jinja2

Environment:

- Python version:python2, python3
- Jinja version:2.8, 3.0.1

**Comment by ThiefMaster** [comment]
It's `jinja2` in lowercase

**Comment by sulaimanismail** [comment]
@ThiefMaster I tried with both option,

```>>> import Jinja2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Jinja2```

**Comment by ThiefMaster** [comment]
You still wrote it wrong according to the error.

Anyway, this means jinja2 is not installed in the environment you are running python in. We cannot really help you with this...
