### ISSUE TITLE
Encoding Problems in Jinja2 Templates

### ISSUE THREAD

**Issue by wulfraem** [pallets/jinja#146]
Hi,

I'm working with a combination of IronPython and jinja2 but keep getting encoding problems from time to time when outputting special characters like 'ä' or returning such from python methods into jinja context.

For example the template:
{%- set test= 'ä' %}
{{ test }}

Can produce exceptions (System.Text.DecoderFallbackException) with the message 'Unable to translate bytes [E4] at index 0 from specified code page to Unicode.'

Adding a space character to the end of the second line can bypass this in some cases but this approach can't be used in larger templaes with a structure that changes depending on inputted data.
It's also possible to output such characters by htmlescaping them via the '|e' filter but again, this cannot be applied anywhere.

I would be grateful for any hints how to solve this problem as it puts a damper on an otherwise good and useful template language...

**Comment by ael-code** [comment]
working with falsk-babel extension I encountered a similar issue:
https://github.com/mitsuhiko/flask-babel/issues/48

**Comment by mitsuhiko** [comment]
Closing this since I am not sure if people care much about IronPython ay more. The last comment here is unrelated.
