### ISSUE TITLE
Inconsistent version number in <title> of documentation for previous Jinja versions

### ISSUE THREAD

**Issue by lucaswerkmeister** [pallets/jinja#1461]
(Not a very important issue, but I figured this was the best place to report it.)

The HTML `<title>` of several older versions of the Jinja documentation declares a different version number than the one that’s actually being documented. Specifically:

* [https://jinja.palletsprojects.com/en/**2.9.x**/](https://jinja.palletsprojects.com/en/2.9.x/) reports 2.11.x
* [https://jinja.palletsprojects.com/en/**2.10.x**/](https://jinja.palletsprojects.com/en/2.10.x/) reports 2.11.x
* [https://jinja.palletsprojects.com/en/**2.11.x**/](https://jinja.palletsprojects.com/en/2.11.x/) reports 3.0.x

As far as I’ve seen, subpages are affected as well (specifically, I’ve tried API and Template Designer Documentation).

The same thing doesn’t happen with Flask: [1.0.x](https://flask.palletsprojects.com/en/1.0.x/) and [1.1.x](https://flask.palletsprojects.com/en/1.1.x/) correctly identify themselves in the title.

**Comment by lucaswerkmeister** [comment]
Hm, on second thought, the whole documentation might be for a different version than indicated in the URL? For instance, [https://jinja.palletsprojects.com/en/**2.11.x**/templates/#**filter**](https://jinja.palletsprojects.com/en/2.11.x/templates/#filter) documents `filter(env: 'Environment', value: str) → bool` (aka `is filter`), which is supposed to be new in 3.0.0 as far as I’m aware. (Also, observe the type hints in the signature, which I believe are also new in 3.0.0, and which don’t appear in the 2.10.x docs.)

**Comment by lucaswerkmeister** [comment]
Yeah, [https://jinja.palletsprojects.com/en/**2.11.x**/templates/#**groupby**](https://jinja.palletsprojects.com/en/2.11.x/templates/#groupby) has “*Changed in version 3.0:* Added the `default` parameter.” But it’s not identical to [https://jinja.palletsprojects.com/en/**3.0.x**/templates/#jinja-filters.**groupby**](https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.groupby) either – might be a 3.0 prerelease or release candidate?

**Comment by davidism** [comment]
Fixing this now. It's because Sphinx requires Jinja, and in old docs we didn't pin everything yet or use a readthedocs config to force install the local version.

**Comment by lucaswerkmeister** [comment]
Thanks!
