### ISSUE TITLE
Incorrect obj.__class__ comparison inside templates

### ISSUE THREAD

**Issue by p0m1d0rka** [pallets/jinja#1462]
Hello!
I faced the strange behavior while rendering remplate.
**On python:**
```
var = 1
var.__class__  
> int
var is int 
> True
var.__class__ == int
> True

```
**On template:**
```
{% set var =1 %}
{{ var.__class__ == int}} - **_False_ but should be _Thue_**
{{ var.__class__ is int }} - True 
```
Environment:

- Python version: 3.9

- Jinja version: 3.0.1

**Comment by jab** [comment]
This is working as intended. Please see the documentation for what is supported.

**Comment by p0m1d0rka** [comment]
> This is working as intended. Please see the documentation for what is supported.

ok ty. 
Excuse for troubling
