### ISSUE TITLE
allow numeric sorting for the sort filter

### ISSUE THREAD

**Issue by martin3000** [pallets/jinja#1466]
When using the sort filter on attributes, items are sorted as strings. 
'1','10','100' are grouped together, then '2','20'.
Using `sort(attribute="amount",numeric=true)` the sort could be done after converting the attributes to numbers.

**Comment by davidism** [comment]
I can't reproduce that issue. A list of ints is sorted as expected.

```python
import jinja2
print(jinja2.Template("{{ x|sort|list }}").render(x=[1, 200, 100, 2, 10]))
```
```
[1, 2, 10, 100, 200]
```

**Comment by ThiefMaster** [comment]
Probably he wants "natural sorting" for a list of strings

**Comment by martin3000** [comment]
In home assistant, all attributes are strings.
