### ISSUE TITLE
For loop fails SILENTLY when the collection variable is not defined

### ISSUE THREAD

**Issue by mcandre** [pallets/jinja#1468]
Jinja2 has poor validation of basic Jinja2 code structure.

main.tf.j2:

```jinja2
{% set region_collection = ["eu-east-1", "ca-central-1"] %}

{% for region in no_such_region_collection %}
provider "aws" {
    alias = "{{ region }}"
    region = "{{ region }}"
}
{% endfor %}
```

Running the jinja2 command line tool `jinja2 main.tf.j2 >main.tf` completely ignores the missing variable `no_such_region_collection`. Jinja2 emits no error or warning message. Jinja2 exits with an unhelpful zero exit code. This causes errors in the Jinja2 code to propagate far away out into the large system, making it much harder for engineers to troubleshoot problems.

Environment:

```console
$ python --version
Python 2.7.16

$ jinja2 --version
jinja2-cli v0.7.0.dev0
 - Jinja2 v3.0.1
 ```

**Comment by ThiefMaster** [comment]
Please read the documentation about the different types of `Undefined`.
