### ISSUE TITLE
Loader -> loaders with Environment.extend support

### ISSUE THREAD

**Issue by velocityzen** [pallets/jinja#147]
Can Environment.loader be Environment.loaders alway like a list of loaders? 
So `Environment.extend(loaders = SomeNewLoader)` check if loader not in the list will added it. 
This will be very helpful for writing extensions.

**Comment by davidism** [comment]
I'm not really clear on the use case here, but it sounds like you could solve this by writing a combining loader similar to `ChoiceLoader`.
