### ISSUE TITLE
Possible usage of soft_str in Jinja 2.x

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [pallets/jinja#1473]
Hi
Due to a project restrictions  i am stick (possible forever) with Jinja 2X ( "2.11.3" for now). I would like to ask  you is it any chance  you add minor fix in 2x future possible release to fix one particular issue between Jinja 2x and markupsafe 2.x?
To be exact this one:

` DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.`

It seems like Jinja  internally uses `soft_unicode` a lot whereas MarkupSafe 2.x demands us to use modern replacement which is  `soft_str`.
Would you be so kind and replace  'soft_unicode' to 'soft_str' as a fix to Jinja 2x please?

Thank you.

It is a pleasure to use Jinja.

**Comment by davidism** [comment]
Pin MarkupSafe 1.x as well.
