### ISSUE TITLE
3.0.1: pygments module test suite is failing

### ISSUE THREAD

**Issue by kloczek** [pallets/jinja#1476]
According to what I've beenn told in https://github.com/pygments/pygments/issues/1789 failing pygments pytest unit could be related to some jinja issue.

Python version 3.8.11.
jinja: 3.0.1

**Comment by davidism** [comment]
Please write the details needed to understand what the error is and how to reproduce it in the issue itself, not as a link.

That warning explains what needs to be replaced.

**Comment by kloczek** [comment]
All details are in `pygments` ticket.
