### ISSUE TITLE
Macro called too early?

### ISSUE THREAD

**Issue by wulfraem** [pallets/jinja#148]
Hi, I'm having some troubles with calling macros.
I'm calling a macro and pass a parameter to it.
Inside the macro operations are performed on the given object
and it seems that the macro is called earlier than I would assume it would.

Example macro:

```
{%- macro testMacro(list) %}
{%- do list.append('1') %}
{%- endmacro %}
```

Example template:

```
{%- import 'TestMacro.html' as test with context %}

{%- set myList = [] %}
{{ myList }} <br/>

{%- do myList.append('a') %}
{{ myList }} <br/>

{%- do myList.append('b') %}
{{ myList }} <br/>

{{ test.testMacro(myList) }}
{{ myList }} <br/>
```

Output:

```
[] 
['a'] 
['a', 'b', '1'] 
['a', 'b', '1'] 
```

As you can see, the macro is called before the second output.
Can I some enforce a "serial" behaviour? As I would like the output to be:

```
[] 
['a'] 
['a', 'b'] 
['a', 'b', '1'] 
```

**Comment by davidism** [comment]
Fixed by #1109, which removed the format string output.
