### ISSUE TITLE
`http://` in some external links can be replaced with `https://`

### ISSUE THREAD

**Issue by nabbisen** [pallets/jinja#1486]
There are external links in docs written as `http://` which seems able to be replaced with `https://`.

- docs/extensions.rst
    - http://babel.pocoo.org/
- docs/intro.rst
    - http://babel.pocoo.org/
- docs/make.bat
    - http://sphinx-doc.org/

Environment:

- Python version: -
- Jinja version: -

**Comment by davidism** [comment]
No need to open issues about minor docs fixes, thanks for the pr
