### ISSUE TITLE
Filter to return multiple attributes

### ISSUE THREAD

**Issue by markatdxb** [pallets/jinja#1493]
Hi just an idea here
would be great to have additional filter similar to map which can return multiple attributes from the list
we do a lot of automation with Ansible and this is quite common requirements

i bumped into this code which i use as a current solution 
https://stackoverflow.com/questions/31685125/is-it-possible-to-map-multiple-attributes-using-jinja-ansible/57665825#57665825

```
mapattributes.py
#!/usr/bin/env python
class FilterModule(object):
  def filters(self):
    return { 'mapattributes': self.mapattributes }

  def mapattributes(self, list_of_dicts, list_of_keys):
    l = []
    for di in list_of_dicts:
      newdi = { }
      for key in list_of_keys:
        # newdi[key] = di[key]
        if di.get(key, None) != None:
          newdi[key] = di[key]

      l.append(newdi)
    return l
```

**Comment by davidism** [comment]
I don't plan to add more complex data access/processing filters such as this to Jinja core. This seems more appropriate as a feature request to Ansible.
