### ISSUE TITLE
Generic import (importlib.import) extension

### ISSUE THREAD

**Issue by adamcunnington-gdt** [pallets/jinja#1500]
I am surprised that it is not possible to import an arbitrary python module within a template expression.

I had expected this to work; `{{ __import__("foo").bar }}`

It would be great if import() was a default function available in jinja2 expressions. It would take the same args as `importlib.import`.

Unfortunately, in the project that I am currently using jinja2, I am not in control of the render() call otherwise I would just do `.render(..., **{"import": importlib.import})`

I can however add extensions. I think it would be great for there to be a builtin extension which provided this extra function.

**Comment by davidism** [comment]
This is not something I intend to add to Jinja.

**Comment by adamcunnington-gdt** [comment]
Fab, thanks for the explanation 😆
