### ISSUE TITLE
Documentation error in first code block for `Template.stream(...)` method

### ISSUE THREAD

**Issue by sthagen** [pallets/jinja#1515]
# Reproducing the Documentation Bug

1. Go to https://jinja.palletsprojects.com/en/latest/api/#jinja2.Template
2. Type into the commands of the first code example block
3. The assert on the first `next(stream)` call should fail

## As is:

```python
>>> template = Template('Hello {{ name }}!')
>>> template.render(name='John Doe') == u'Hello John Doe!'
True
>>> stream = template.stream(name='John Doe')
next(stream) == u'Hello John Doe!'
True
>>> next(stream)
Traceback (most recent call last):
    ...
StopIteration
```

## Suggested:

```python
>>> template = Template('Hello {{ name }}!')
>>> template.render(name='John Doe') == 'Hello John Doe!'
True
>>> tream = template.stream(name='John Doe')
>>> next(stream) == 'Hello '
True
>>> next(stream) == 'John Doe'
True
>>> next(stream) == '!'
True
>>> next(stream)
Traceback (most recent call last):
    ...
StopIteration
```

### Environment was:

* Jinja2 v3.0.2 per pypi 
* python 3.9.2 (should not really matter)
* I did not use the `u` prefixes for string literals - I rarely do these days ...

**Comment by davidism** [comment]
That example isn't really relevant to creating a template objects, so I've removed the example and reworded the docs a bit.
