### ISSUE TITLE
Add support from relative imports

### ISSUE THREAD

**Issue by jpsca** [pallets/jinja#1533]
## What

`{% include "..." %}` and `{% import "..." %}` should support paths relative to the current template.

For example, with a templates folder tree like this 

```
+ myProject
|
+--+ templates
   |
   +--+ foo
   |    |--+ bar
   |    |  |-- header.jinja
   |    |  |-- footer.jinja
   |    |  +-- base.jinja
        |
        +--+ lorem
            +-- ipsum.jinja
```

From inside `templates/foo/bar/base.jinja`, *in addition* to

```jinja
{% import "foo/bar/header.jinja" %}
{% import "foo/bar/lorem/ipsum.jinja" %}
```

you should be able to write these instead:

```jinja
{% import "./header.jinja" %}
{% import "../lorem/ipsum.jinja" %}
```

## Why

The main advantage of relative paths is that you can move coupled files together without having to update all the `{% include "..." %}` and `{% import "..." %}` between them.

This feature is also something that is frequently expected to exists
(eg: https://github.com/pallets/jinja/issues/605) (perhaps because of the influence of how imports work in JavaScript) and worked-around in some projects that depends on Jinja, like https://github.com/saltstack/salt/pull/47490

**Comment by ThiefMaster** [comment]
I think this could become extremely confusing when multiple loaders are used...

**Comment by davidism** [comment]
Template names are not equivalent to paths. They happen to look like paths when using the `FileSystemLoader`, or when using `PrefixLoader` with the default `delimiter`, but ultimately they are names with no particular semantic meaning. For example, this means you could (but shouldn't) write a loader that takes a GitHub URL to a template.

The great thing about this though, is that if a project like Salt wants to support some other way to reference template names, such as interpreting `./` and `../` specially, they can already do this by writing a custom loader, which they have in the linked PR.

**Comment by jpsca** [comment]
> They happen to look like paths when using the FileSystemLoader

An issue target specifically to the `FileSystemLoader` would be appropriate then?

**Comment by davidism** [comment]
I don't plan to add further complexity to the existing loaders at this time.
