### ISSUE TITLE
Ternary() does not behave like true ternary

### ISSUE THREAD

**Issue by meersjo** [pallets/jinja#1553]
This may be an issue with the language parser itself and maybe unsolvable, but the ternary operators don't act like a true if in that they are always evaluated in their entirety instead of just the chosen branch.

The specific case where I'm running into it is when I need to use a maybe-undefined variable's value in the result:

`{{ ( foo is defined ) | ternary('VALUE=' ~ foo, 'Foo was undefined) }}

In a regular if/then/else sequence, we would land in the second branch, and the interpolation of foo would never be attempted. A typical ?: ternary behaves in the same way in most languages.

Using ternary(), however, seems to evaluate the entire call before branching, leading to undefined variable errors when it doesn't exist.

The workaround is to build a full if structure, which works but is needlessly complicating the templates.

I'm experiencing this in Ansible (2.9), so python version will differ depending on target server. Local active version is 2.7.18 .

**Comment by davidism** [comment]
That's not a ternary operator, that's a function called `ternary`, which is not provided by us. Jinja has a real ternary expression, see the template designer docs.
