### ISSUE TITLE
dict attribute `items` collision with python dict method

### ISSUE THREAD

**Issue by sergioisidoro** [pallets/jinja#1554]
Given the context:
```
{
  "order": {
     "id": 1,
     "items": ["a", "b", "c"]
  }
}
```

using the following template:
```
  Order: {{order.id}}                     <<<--- Works ok
  {% for item in order.items %}
    	{{item}}
  {% endfor %}
```

Returns an error, since `items` returns `<built-in method items of dict object at 0xffffa5b5b280>`
This can be bypassed with `{{order["items"]}}`, but it can certainly create confusion... 

Environment:
- Python version: `3.9`
- Jinja version: `==3.0.1`

**Comment by davidism** [comment]
Nothing we can do about this. Preprocess your data to account for it, or iterate over keys and get values instead.

**Comment by davidism** [comment]
Fairly sure there's also a way to override how dotted lookups work on the Environment too.

**Comment by ThiefMaster** [comment]
You can just use `order['items']` as well...
