### ISSUE TITLE
Export markupsafe.Markup

### ISSUE THREAD

**Issue by Dreamsorcerer** [pallets/jinja#1555]
The library now requires using `markupsafe.Markup` instead of `jinja2.Markup`. I'd like to suggest that jinja should still export `Markup` itself (just a `from markupsafe import Markup as Markup`).

The 2 issues I see with maintaining the current approach (as a user):
  `markupsafe` should now be added to the dependencies of each project, as it is being explicitly imported by the user (I have flake8 checks that enforce this as well).
  If jinja ever changes the object used internally in future, then the user's code will end up using the wrong class.

By continuing to export the class as `jinja2.Markup`, I do not need to worry about these issues. The class may have changed in v3, but I should not need to worry about that, unless the API itself has changed. Basic usage, type annotations and imports should continue to work without any changes.

**Comment by Dreamsorcerer** [comment]
Also doesn't help that I've been looking at the old documentation (maybe that can be redirected or something?):
https://jinja2docs.readthedocs.io/en/stable/api.html#jinja2.Markup

**Comment by davidism** [comment]
That documentation is not ours, it's some random person who created a Read the Docs project. We can reach out to RTD about it, but we cannot guarantee it is removed. Always use https://palletsprojects.com to find official resources for our projects.

**Comment by davidism** [comment]
I don't plan to have Jinja export names from other packages. MarkupSafe was extracted from Jinja, so anything that we would have changed in Jinja's implementation will happen in MarkupSafe instead.
