### ISSUE TITLE
Way of creating new dicts in ImmutableSandboxedEnvironment

### ISSUE THREAD

**Issue by fabiopedrosa** [pallets/jinja#1567]
When using `ImmutableSandboxedEnvironment` we're not allowed to update an existing dictionary, but how does one go about creating a new dictionary that is a result of two others? `update` would be unsafe to call, so there's no way? could we add it?

**Comment by davidism** [comment]
This sounds like something that should be done in Python before rendering the template. I don't plan to add support for this within a sandboxed template.
