### ISSUE TITLE
jinja2docs.readthedocs.io

### ISSUE THREAD

**Issue by adamchainz** [pallets/jinja#1575]
Somehow I ended up on https://jinja2docs.readthedocs.io/ (duckduckgo search results?). This is an old version of the docs (2.10, 2017), so it confused me a bit.

If you open Read the Docs version switcher at the bottom, the "View on GitHub" link points to a `jinja` repo owned by @stornado , but this no longer exists.

It would be nice to take this down or at least prevent it from being indexed in search results. Perhaps @stornado will respond and do so, or Read the Docs can be petitioned to do so.

**Comment by davidism** [comment]
Unfortunately, we can't prevent unaffiliated people from publishing our docs under other names on RTD. We can report it to RTD, and they will follow https://docs.readthedocs.io/en/stable/abandoned-projects.html.

**Comment by davidism** [comment]
I've submitted a request. Last time I did this, they responded that they would contact the user, then never followed up with me, but the project was eventually removed one way or another. I'm going to close this as there's nothing else I can do, @stornado can still take this down directly if they get the notification.

**Comment by adamchainz** [comment]
Okay, thank you for contacting 👍
