### ISSUE TITLE
Change find_undeclared_variables to not ignore globals without arguments 

### ISSUE THREAD

**Issue by robcxyz** [pallets/jinja#1580]
Using meta.find_undeclared_variables will miss any variables that exist as globals (ie 'range', 'dict', 'lipsum', 'cycler', 'joiner', 'namespace') based on changes from [#931](https://github.com/pallets/jinja/issues/931).  What could be better is if global variables are only ignored if they additionally have arguments (ie `{{range(5)}}` vs `{{range}}`) so as to allow use of globals as variables. 

```python 
from jinja2 import Environment, meta

env = Environment()

# jinja_globals = dict_keys(['range', 'dict', 'lipsum', 'cycler', 'joiner', 'namespace'])
jinja_globals = env.globals.keys()

ambiguous_vars = ["{{%s}}" % i for i in jinja_globals]

for i in ambiguous_vars:
    variables = meta.find_undeclared_variables(env.parse(i))
    # find_undeclared_variables misses all global vars 
    assert len(variables) == 0 
```

**Comment by davidism** [comment]
There is no requirement that globals take arguments, and globals are defined, so this change would produce invalid results. If you need a different report, you can copy/write an ast visitor that has the exact behavior you need.

**Comment by robcxyz** [comment]
@davidism - That makes sense.  Thank you for your help.
