### ISSUE TITLE
Lower priority of pipeline operator

### ISSUE THREAD

**Issue by teeaz** [pallets/jinja#1582]
In short, input:
```
{{ "prefix" + ".suffix" | upper }}

```
Render result:
```
prefix.SUFFIX
```

It's not intuitive, is it?

Expect result:
```
PREFIX.SUFFIX
```

Can lower priority of pipeline operator? 

I know avoid it by adding a pair of bracket. But I prefer to solve it fundamentally.

**Comment by davidism** [comment]
No, this cannot change without breaking every existing template.

**Comment by ThiefMaster** [comment]
I think it would also be extremely unintuitive to change it even if it was possible without being a breaking change..
