### ISSUE TITLE
Allow locale aware sort filters (or arguments)

### ISSUE THREAD

**Issue by paternal** [pallets/jinja#1583]
Jinja ``sort()`` and ``dictsort()`` filters are not localized. For instance, in French, those words are sorted as: ``Âne, Antilope, Éléphant, Vache, Zèbre``. Jinja, however, put the diacritics at the end of the list. Indeed, the following script:

~~~python
import jinja2

LIST=["Antilope", "Âne", "Zèbre", "Éléphant", "Vache"]
DICT={
            "Antilope": 1,
            "Âne": 3,
            "Zèbre": 2,
            "Éléphant": 4,
            "Vache": 0,
        }

print(jinja2.Template("{{ l|sort }}").render(l=LIST))
print(jinja2.Template("{{ d|dictsort}}").render(d=DICT))
~~~

gives:

~~~sh
$ python sort.py
['Antilope', 'Vache', 'Zèbre', 'Âne', 'Éléphant']
[('Antilope', 1), ('Vache', 0), ('Zèbre', 2), ('Âne', 3), ('Éléphant', 4)]
~~~

One could sort the list (or dict, as a list of pairs) before submitting it to jinja, but it would be nice to have jinja do it. For instance, ``sort`` and ``dictsort`` could have a ``locale: bool = False``  attribute (or ``localized``, or ``i10n``, or whatever), which, given that ``locale.setlocale()`` has been called earlier, would use [``locale.strxfrm()``](https://docs.python.org/3/library/locale.html#locale.strxfrm) to sort strings. Or create new filters ``localized_sort`` and ``localized_dictsort`` (or ``sort_i10n`` or ``dictsort_i10n`` or whatever), which would take the very same arguments as ``sort()`` and ``dictsort()``, but would use ``locale.strxfrm()`` to compare strings.

If you think this is worth doing, I can implement it.

Thanks for your work,
-- Louis

**Comment by davidism** [comment]
Detecting if locale is being used and using a special comparison in that case sounds reasonable, I can review a PR. Do any other libraries do this for sorting?

**Comment by ThiefMaster** [comment]
Setting a `sort_locale` via env/policy (and a new kwarg on the sort filters to override it) could be an interesting option as well. I think in most cases you don't deal with different locales, nor would you want to specify it every single time you sort something.

**Comment by bcoca** [comment]
By default you want to sort in the 'current locale', but allow an override. 

Using C/POSIX locale for sorting is very fast  and helpful for cases in which you want matching  of sorted items, but don't really care to present the sorted results to a user. So letting the user override the default is a must IMHO.

I recommend adding a `locale=None` to the filters and use 'current' when none is specified and attempt to use the one passed in when it exists. Then you have the question to either error out or default to current if  the provided locale is invalid or unavailable.

**Comment by bcoca** [comment]
not working code, but something like this?
```python
diff --git a/src/jinja2/filters.py b/src/jinja2/filters.py
index 7a554a0..22c7b1d 100644
--- a/src/jinja2/filters.py
+++ b/src/jinja2/filters.py
@@ -1,4 +1,5 @@
 """Built-in template filters used with the ``|`` operator."""
+import locale
 import math
 import random
 import re
@@ -22,6 +23,23 @@ _word_re = re.compile(r"\w+")
 _word_beginning_split_re = re.compile(r"([-\s({\[<]+)")


+class Localize():
+    """Context manager to allow using a specific locale with in it"""
+
+    def __init__(self, user_locale):
+        self.current_locale = local.get_locale()
+        self.context_locale = user_locale
+
+    def __enter__(self):
+        try:
+            locale.setlocale(locale.LC_ALL, self.context_locale)
+        except locale.Error as e:
+            raise FilterArgumentError('Unusable locale supplied')
+
+    def __exit__(self, exc_type, exc_value, exc_traceback):
+        locale.setlocale(locale.LC_ALL, self.current_locale)
+
+
 def contextfilter(f):
     """Decorator for marking context dependent filters. The current
     :class:`Context` will be passed as first argument.
@@ -254,7 +272,7 @@ def do_title(s):
     )


-def do_dictsort(value, case_sensitive=False, by="key", reverse=False):
+def do_dictsort(value, case_sensitive=False, by="key", reverse=False, use_locale=None):
     """Sort a dict and yield (key, value) pairs. Because python dicts are
     unsorted you may want to use this function to order them by either
     key or value:
@@ -280,19 +298,21 @@ def do_dictsort(value, case_sensitive=False, by="key", reverse=False):
     else:
         raise FilterArgumentError('You can only sort by either "key" or "value"')

-    def sort_func(item):
-        value = item[pos]
+    with Localize(use_locale) as l:

-        if not case_sensitive:
-            value = ignore_case(value)
+        def sort_func(item):
+            value = item[pos]

-        return value
+            if not case_sensitive:
+                value = ignore_case(value)

-    return sorted(value.items(), key=sort_func, reverse=reverse)
+            return locale.strxfrm(value)
+
+        return sorted(value.items(), key=sort_func, reverse=reverse)


 @environmentfilter
-def do_sort(environment, value, reverse=False, case_sensitive=False, attribute=None):
+def do_sort(environment, value, reverse=False, case_sensitive=False, attribute=None, use_locale=None):
     """Sort an iterable using Python's :func:`sorted`.

     .. sourcecode:: jinja
@@ -335,10 +355,14 @@ def do_sort(environment, value, reverse=False, case_sensitive=False, attribute=N
     .. versionchanged:: 2.6
        The ``attribute`` parameter was added.
     """
-    key_func = make_multi_attrgetter(
-        environment, attribute, postprocess=ignore_case if not case_sensitive else None
-    )
-    return sorted(value, key=key_func, reverse=reverse)
+
+    with Localize(use_locale) as l:
+
+        key_func = locale.strxfrm(make_multi_attrgetter(
+            environment, attribute, postprocess=ignore_case if not case_sensitive else None
+        ))
+
+        return sorted(value, key=key_func, reverse=reverse)
```

**Comment by paternal** [comment]
I don't know anything about locales, but the [python documentation](https://docs.python.org/3/library/locale.html#background-details-hints-tips-and-caveats) reads:

> It is generally a bad idea to call [setlocale()](https://docs.python.org/3/library/locale.html#locale.setlocale) in some library routine, since as a side effect it affects the entire program. Saving and restoring it is almost as bad: it is expensive and affects other threads that happen to run before the settings have been restored.

What I had in mind was, in an application:

1. Set the locale at the initialization of the application
2. Do some stuff…
3. Render your jinja template, which uses the default locale.

However, I would like to have this for a [lektor](https://github.com/lektor/lektor) website, which [support the same page in different languages](https://www.getlektor.com/docs/content/alts/). So I do not see any other solution but yours: define locale as an argument to ``sort()``, and set and restore locale as you did.

Is jinja thread-safe? If so, if this solution is implemented, it is no longer thread-safe (as [setlocale() is not thread-safe](https://docs.python.org/3/library/locale.html#locale.setlocale)).

**Comment by bcoca** [comment]
yeah, that is the drawback of having locale control, sadly its a python interpreter global

**Comment by paternal** [comment]
> yeah, that is the drawback of having locale control, sadly its a python interpreter global

We can also put ``locale.setlocale()`` into a global [context lock](https://docs.python.org/3/library/threading.html#with-locks): `Localize.__enter__()` should call `some_lock.__enter__()`; same with `Localize.__exit__()`.

@bcoca Should I take over, or are you continuing your draft?

**Comment by bcoca** [comment]
@paternal  feel free to run with it, just note that the lock will prevent other threads from changing the locale, but not from being affected by the change. It should take care of most cases in which they need specific locale as they'll be forced to wait, but there will always be 'that' corner case.

**Comment by paternal** [comment]
I added this to my TODO list.

**Comment by davidism** [comment]
I'm fine with adding a toggle to do locale sorting, but I don't want to add anything that is not thread (or asyncio) safe or is only safe using a global lock. It's up to the user to set up their locale appropriately first, or to sort the values ahead of time if they need to mess with the locale.

**Comment by paternal** [comment]
This excludes [@bcoca's proposal](https://github.com/pallets/jinja/issues/1583#issuecomment-1042237214). I do not see any solution using [stdlib locale](https://docs.python.org/3/library/locale.html#locale.strxfrm) package.

It would be nice if Babel provided such a tool. There is [an issue about it](https://github.com/python-babel/babel/issues/154) but it was closed without explanation.

One solution that remains is sorting the data before it being processed by jinja, but I need this with Lektor, and I don't see how I can do it here. I am opening an issue there.

**Comment by davidism** [comment]
I don't understand, you can still use `locale.strxfrm` without the context manager. It's the `setlocale` part that's not thread safe.

**Comment by paternal** [comment]
> I don't understand, you can still use `locale.strxfrm` without the context manager. It's the `setlocale` part that's not thread safe.

Yes, but it no longer solves my issue: I want to use this in a Lektor template (see https://github.com/lektor/lektor/issues/1005), so I would like to do everything in the template only.

I could write a quick and dirty lektor package that calls `setlocale` at the start of compilation, but in that case, I might as well write a quick and dirty `locale_sort()` and `locale_isort()` filters in that same package: it would be nice to be able to set everything in the template.

I think it seems off to require an external function call (to `setlocale`) with a side effect, to sort a list in a template.

**Comment by davidism** [comment]
OK, I'm going to close this then.

**Comment by paternal** [comment]
In lektor/lektor#1005, @dairiki suggested using ``unidecode()`` as a "poor man's solution" to sort without switching locale. I could write a PR that adds a `unidecode: bool` parameter to `sort()` and `dictsort()`, unless this is too much of a hack?
