### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by diolk49** [pallets/jinja#1601]
Error when trying to install jinja : 
`   File "/usr/local/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
     from markupsafe import soft_unicode
 ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.9/site-packages/markupsafe/__init__.py)`

With new version of markup safe (2.1.0), `soft_unicode` has been removed (it was previously deprecated). We need to "Use `soft_str` instead" : https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

Environment:

- Python version: 3.9
- Jinja version: ^2.11.3

**Comment by ThiefMaster** [comment]
https://github.com/pallets/jinja/issues/1585
