### ISSUE TITLE
The behavior of (overriding) blocks within includes still isn't clear from the documentation

### ISSUE THREAD

**Issue by ernstki** [pallets/jinja#1604]
Hi everyone, hope you're doing well.

I'm opening this issue in the context of:

* #84
* #169; (presumably) closed as duplicate of #84
* #243
* #1083, which addresses _part_ of #423, but not the part about overriding `block`s within `include`s.

I get that overriding `block`s within `include`d templates caused some unwanted behavior when #84 was merged, and so it was reverted, and that feature may never be implemented.

It would _still_ be nice to see a very definitive statement about this not being supported in the documentation. Or a runtime error, similar to an `include` when the file doesn't exist.

## Minimal test case

```console
$ python app.py
Template "base"

Content in block "bb" from "b" template
```

<details>
<summary>Source files to produce the above</summary>
<h4><code>app.py</code></h4>
<pre><code>
from jinja2 import Environment, FileSystemLoader

env = Environment(loader=FileSystemLoader('.'))
t = env.get_template('a')
print(t.render())
</code></pre>

<h4><code>base</code></h4>
<pre><code>
Template "base"
{% include 'b' %}
</code></pre>

<h4><code>a</code></h4>
<pre><code>
{% extends 'base' %}
{% block bb %}
Block "bb" overridden within template "a"
{% endblock %}
</code></pre>

<h4><code>b</code></h4>
<pre><code>
{% block bb %}
Content in block "bb" from "b" template
{% endblock %}
</code></pre>
</details>  

## Expected behavior

Either:

* block `bb` can be overridden from template `a`, which inherits from `base`
    ```console
    $ python app.py
    Template "base"
    
    Block "bb" overridden within template "a"
    ```
* —or— a runtime error along the lines of
    ```
    RuntimeError: Blocks within included templates cannot be overridden. See issue #XXX.
    ```
* —or— the documentation states very plainly, in the section on template inheritance, that blocks from included templates cannot be overridden (feature will never be supported)

## Environment

- Python 3.7.12 from MacPorts
- Jinja 3.1.0.dev0 from a fresh GitHub clone

### Thanks!

**Comment by davidism** [comment]
Happy to review a docs PR.

**Comment by ernstki** [comment]
@davidism Super, I will look at where best to fit this in, and have a go at it. On a timescale of next week-ish, though.

**Comment by davidism** [comment]
Added the following:

> The included template can `extend` another template and override blocks in that template. However, the current template cannot override any blocks that the included template outputs.

**Comment by ernstki** [comment]
@davidism Short, sweet, and to the point! Thanks.

Stated in words, "the current template overrid[ing] blocks [in] the included template" _does_ sound like an awkward operation. It seems like a natural thing to want to do when you're _in_ the template, writing it, top-to-bottom, but I bet the code to implement that behavior is gnarly.

Appreciate all your hard work. Take care.
