### ISSUE TITLE
You should be able to pass a list to loop.cycle

### ISSUE THREAD

**Issue by ChrisSchmittAtNetapp** [pallets/jinja#1615]
Currently when you pass a list to loop.cycle, it will just set the item to the entire list. It would be great if there was a way to be able to use loop.cycle to cycle through a list instead of just being given the entire list.

**Comment by davidism** [comment]
`loop.cycle(*values)`

**Comment by ChrisSchmittAtNetapp** [comment]
I swear I tried to figure out how to do this for hours. Thanks for the solution. Just one of those days.
