### ISSUE TITLE
option to cast input of filter to string

### ISSUE THREAD

**Issue by rene-dev** [pallets/jinja#1618]
If the input to a filter is a function, even when using @property string filters like lower or upper just return "bound method"
you need to call it like this: object.function()|lower with braces to call the function.
django templates include an option to set the input of a filter to be always a string.
It will cast the input to string before calling the filter. This way when writing templates you dont need to know
if you are calling a method or using a variable.
https://docs.djangoproject.com/en/4.0/howto/custom-template-tags/#template-filters-that-expect-strings
I could not find a similar feature in jinja.

**Comment by davidism** [comment]
> If the input to a filter is a function, even when using https://github.com/Property string filters like lower or upper just return "bound method".

I can't reproduce this, a property is not rendered as "bound method".

> This way when writing templates you dont need to know if you are calling a method or using a variable.

This is a deliberate design choice in Jinja. Just like Python, attribute access is valid and distinct from calling that attribute.

**Comment by rene-dev** [comment]
you are right, using @property does work. there was another function with the same name name in my model. Thanks!
