### ISSUE TITLE
Flake8 failed to load plugin "html" due to cannot import name 'Markup' from 'jinja2'

### ISSUE THREAD

**Issue by jontwo** [pallets/jinja#1628]
The latest version of Jinja2 (3.1.0) does not work with the flake8-html plugin.

```
$ pip install -U flake8-html Jinja2
$ flake8
```

This gives the error `flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "html" due to cannot import name 'Markup' from 'jinja2' `

Environment:

- Python version: 3.8.8
- Jinja version: 3.1.0

**Comment by davidism** [comment]
That library will need to update to use `from markupsafe import Markup`. Importing it directly from Jinja has been issuing a DeprecationWarning and is called out as deprecated and then removed in the changelog.
