### ISSUE TITLE
3.1.0 update breaks Sphinx 3.5

### ISSUE THREAD

**Issue by ahwagner** [pallets/jinja#1630]
Jinja2 3.1.0 release breaks Sphinx 3.5.

This bug is replicated whenever loading `rst.py` from sphinx version 3.5. [Here](https://readthedocs.org/projects/vr-spec/builds/16457265/) is a build failure caused by the Jinja2 update.

Sphinx 3.5 expects Jinja2 3.x to have the `environmentfilter` available for import, but it is not able to be imported beginning with the 3.1.0 update.

Environment:

- Python version: 3.8
- Jinja version: 3.1.0

**Comment by davidism** [comment]
Yes, you'll need to either upgrade Sphinx, or use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates.

**Comment by ahwagner** [comment]
No worries, it was a quick fix, I had already pinned the Jinja2 dependency after this error came up. 

But I think you'll find introducing a breaking change in a minor version release is going to net you a hundred (well-intentioned) issues like this one to swat. Good luck!

**Comment by davidism** [comment]
See https://hynek.me/articles/semver-will-not-save-you/, https://snarky.ca/why-i-dont-like-semver/, and https://bernat.tech/posts/version-numbers/, which go in depth on why pinning is the only valid solution to these types of issues, regardless of if a project follows semver.
