### ISSUE TITLE
{% set %} doesn't assign var to global context

### ISSUE THREAD

**Issue by DriverX** [pallets/jinja#164]
template:

```
{% set foo = "bar" %}
foo - {{ foo }}

{% for i in range(2) %}
     for:foo - {{ foo }}
     {% set foo = i %}
     for:foo - {{ foo }}
{% endfor %}

{{ foo }}

{% block test %}
    block:foo - {{ foo }}
    {% set foo = "baz" %}
    block:foo - {{ foo }}
{% endblock %}

foo - {{ foo }}
```

result:

```
foo - bar
    for:foo - bar
    for:foo - 0
    for:foo - 0
    for:foo - 1
foo - bar
    block:foo - bar
    block:foo - baz
foo - bar
```

wtf?

Please make a method of assigning a global variable.

**Comment by i5513** [comment]
http://stackoverflow.com/questions/4870346/can-a-jinja-variables-scope-extend-beyond-in-an-inner-block and http://stackoverflow.com/questions/9486393/jinja2-change-the-value-of-a-variable-inside-a-loop

I really don't understand why those hacks are neccesary, should be "local var" syntax or similar 

Regards
