### ISSUE TITLE
Cannot use filter 'bool' in version 3.1.1

### ISSUE THREAD

**Issue by egkelly** [pallets/jinja#1642]
# Issue
Since upgrading to version 3.1.1 as of March 25th, we have been unable to use the 'bool' filter in our Ansible templates. We are able to workaround by downgrading to version 3.1.0

# How to Reproduce
Install venv with Jinja2==3.1.1, python==3.8, and ansible==2.9 and create a template utilizing 'bool' filter

Example:

> {% if enable_logs | bool %}
	"logs": {
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "/var/log/syslog",
						"log_group_name": "/aws/ec2/instance/{{ cloudwatch_ec2_instance_tags.tags.Name }}/syslog",
						"log_stream_name": "{{ ansible_hostname }}"
					},
					{
						"file_path": "/var/log/auth.log",
						"log_group_name": "/aws/ec2/instance/{{ cloudwatch_ec2_instance_tags.tags.Name }}/auth",
						"log_stream_name": "{{ ansible_hostname }}"
					},
					{
						"file_path": "/var/log/audit/audit.log",
						"log_group_name": "/aws/ec2/instance/{{ cloudwatch_ec2_instance_tags.tags.Name }}/syslog",
						"log_stream_name": "{{ ansible_hostname }}"
...
...
...

> },

# Expected Behavior
Ansible should run without any issues.

Environment:

- Python version: 3.8
- Jinja version: 3.1.1

**Comment by davidism** [comment]
Jinja does not provide a `|bool` filter. Please report this to Ansible.
