### ISSUE TITLE
Typing: Missing attribute for i18n

### ISSUE THREAD

**Issue by Dreamsorcerer** [pallets/jinja#1652]
In mypy, I get:
`error: "Environment" has no attribute "install_null_translations"  [attr-defined]`

Would be nice to have this work correctly, though it might be a little tricky to figure out the right way to do this.

**Comment by davidism** [comment]
From what I understand of typing, this is not possible with the way extensions were designed. Happy to review a PR if you figure something out though.

**Comment by Dreamsorcerer** [comment]
I had a couple of thoughts, but they might be awkward. e.g. `Environment` could be generic, with the type inferred from the arguments passed in to `__init__`. So, only the `Environment[i18n]` version would have those methods.

Though might be easier to rethink the plugin approach to better suit static typing.

**Comment by davidism** [comment]
Typing is always less of a priority. I don't have time to completely redesign and transition an extension system on top of everything else.
