### ISSUE TITLE
Jinja version: 2.11.3 ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by ShangSky** [pallets/jinja#1658]
jinja2/filters.py line 13
```python
from markupsafe import soft_unicode
```
will raise ImportError: cannot import name 'soft_unicode' from 'markupsafe'

requires "MarkupSafe<2.1" can resolve this probrem

- Python version: python3.8
- Jinja version: 2.11.3

**Comment by greyli** [comment]
Duplicate of #1585
