### ISSUE TITLE
Jinja2 incompatible with utf-8 with bom

### ISSUE THREAD

**Issue by kid143** [pallets/jinja#167]
When  using utf-8 with bom as template file encoding, jinja seems to treat bom characters like normal characters. This is quiet annoying when using include command to reference another template store in utf-8 with bom encoding. 

Browsers will also treat the invisible bom character as normal character, though they are invisible, this often breaks the style of  web pages.

**Comment by MiCHiLU** [comment]
I think should correspond by jinja2.

I am using jinja2 with compass about building AMP-HTML.
The AMP-HTML must include a style section without another CSS files.

My case is written style by SASS then compiling by compass.
The CSS file has BOM that is the specification of the compass.
https://github.com/sass/sass/blob/d26e6fa17f55d64278c9f09b5ace5e256e363e3f/lib/sass/util.rb#L833-L838
