### ISSUE TITLE
The get_template() example doesn't seem to match the API

### ISSUE THREAD

**Issue by slott56** [pallets/jinja#1680]
See https://jinja.palletsprojects.com/en/3.1.x/templates/#template-objects This example doesn't seem to align with https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment.get_template.

I think the example needs to be fixed to properly reflect the API.

Environment:

- Python version: 3.10.4
- Jinja version: 3.1.2

**Comment by davidism** [comment]
Ah, I wrote `get_template` instead of `render_template` on the last line.
