### ISSUE TITLE
Consider updating cache algorithm from sha1 to sha256

### ISSUE THREAD

**Issue by scovetta** [pallets/jinja#1690]
There are a few places in [src/jinja2/bccache.py](https://github.com/pallets/jinja/blob/52843b5cbf635b37a82ac0b6c901921a8ee076ff/src/jinja2/bccache.py) and [src/jinja2/loaders.py](https://github.com/pallets/jinja/blob/94fd2d9241410e6f7467ea02cf60e11f26133e31/src/jinja2/loaders.py) that use SHA-1 to calculate the hash of a template name or content.

SHA-1 is known to have collision attacks, and while still impractical, especially where the attacker has little or no control over the template itself, a collision would cause the wrong template to be recalled from cache.

I was wondering if you'd consider taking a pull request that changed the SHA-1 calls to SHA-2. The upside is that SHA-2 is widely supported on Python. The downside is that after updating, any cached templates wouldn't be recognized and would have to be re-generated. There's also a risk that an app would rely on the current algorithm (i.e. generating the hash independently and looking for the file), so this might need to be part of a major version bump.

**Comment by davidism** [comment]
This has no attack surface. It's not worth the change right now
