### ISSUE TITLE
Add the ability to specify a time limit for `render()`

### ISSUE THREAD

**Issue by cmason3** [pallets/jinja#1691]
I am currently using Jinja2 to render user provided templates via a web frontend. While we have the ability to use a Sandboxed environment to limit the range of for loops, etc, there is nothing stopping a user from doing the following:

```jinja2
{% for x in range(100000) %}
  {% for y in range(100000) %}
    {% for z in range(100000) %}
      ...
    {% endfor %}
  {% endfor %}
{% endfor %}
```

The above template sends the CPU to 100% for a very long time and causes a DoS situation. When I am rendering multiple outputs I am able to check how long it has taken between renders and raise an `Exception` if the time limit has been exceeded, but I have no way to check during a single render activity.  I have added a time limit check in some custom filters I have written, but it doesn't address the above scenario. I am unable to use signals to limit the `render` function as the rendering occurs within a thread.

The feature request is to be able to pass a time limit to the `render` function and for Jinja2 to check at various stages within the rendering to see if that time limit has been exceeded and raise an Exception. I don't know the inner workings of Jinja2, but I assume when you pass a token or iterate through a loop there could be an opportunity to check the current render time against a passed time limit?

**Comment by davidism** [comment]
This seems like something that could be done quite easily outside of Jinja. There's nothing Jinja-specific about only running something for a certain amount of time.

**Comment by ThiefMaster** [comment]
I think overriding the `LoopContext` to add this code would be the easiest option. There's no nice way besides monkeypatching to do that though, but maybe that's good enough as a workaround...

**Comment by davidism** [comment]
I don't see what that custom code would be. The only way I could think to solve this are a thread or signals like you mention, and I don't want to start messing with either of those in the runtime.

**Comment by davidism** [comment]
Checking the loop index is meaningless, as you could just do something a bit more complex during each loop to slow it down instead of looping quite as many times. I want to solve the halting problem here.

**Comment by davidism** [comment]
Find some timeout library, and do the equivalent of

```python
with timeout() as to:
    to.run(tmpl.render, context)
```

**Comment by cmason3** [comment]
ok thanks.. I do see the point about someone just adding a custom filter which blocks for ages that would bypass any time limit checks we did within loops, etc. I will go down the route of wrapping the `render` function in some sort of time limit function.
