### ISSUE TITLE
namespace is preserved between invocations

### ISSUE THREAD

**Issue by mortoray** [pallets/jinja#1692]
The object created by `namespace(...)` appears to be preserved between invocations of jinja, that is, it appears to become a global Python variable. I'm seeing this via `render_template` from flask routes.

For example, given a file `index.html`:

```
{% set gs = namespace(count = 0) %}
{% set gs.count = gs.count + 1 %}
{{ gs.count }}
```

The first call to `render_template('index.html')` produces `1` as expected.

The second call produces `2` which is unexpected. I was expecting a `1` to be produced again. This happens even if the next render is in a following HTTP request to a new route. This happens across sessions as well.

This has these implications:
- security: `namespace` is unsafe as it allows values from one template evaluation to leak into other template evaluations
- one bad evaluation of a template could break further invocations.
- individual runs are not independent of each other, making templates non-deterministic

Environment:

- Python version: 3.10
- Jinja version: 3.1.2
- Flask 2.1.2

----

This behaviour is not exhibited by the direct use of Jinja. For example:

```
from jinja2 import Environment, FileSystemLoader, select_autoescape
env = Environment(loader=FileSystemLoader("."))

template = env.get_template("index.html")
print(template.render())
print(template.render())
```

This writes "1" both times.

**Comment by ThiefMaster** [comment]
```
In [1]: from flask import render_template_string

In [2]: render_template_string('''{% set gs = namespace(count = 0) %}
   ...: {% set gs.count = gs.count + 1 %}
   ...: {{ gs.count }}''')
Out[2]: '\n\n1'

In [3]: render_template_string('''{% set gs = namespace(count = 0) %}
   ...: {% set gs.count = gs.count + 1 %}
   ...: {{ gs.count }}''')
Out[3]: '\n\n1'

In [4]: render_template_string('''{% set gs = namespace(count = 0) %}
   ...: {% set gs.count = gs.count + 1 %}
   ...: {{ gs.count }}''')
Out[4]: '\n\n1'
```

can't reproduce it in a flask shell. would you mind providing a minimal example that reproduces it? single-file preferred (ie render_template_string instead of a separate template file unless it doesn't happen there)

**Comment by mortoray** [comment]
A minimal Flask app does not reproduce this. I'm trying to narrow down what part of the configuration might be the issue (I'm not aware that I modify any variables affecting the Jinja environment):

```
from flask import Flask, render_template
app = Flask(__name__)

@app.route('/')
def hello_world():
    return render_template('index.html')
```

**Comment by davidism** [comment]
I can't reproduce this in Flask or Jinja. Here's a minimal Jinja example with external template.

```python
from jinja2 import Environment, FileSystemLoader

e = Environment(loader=FileSystemLoader("."))
t = e.get_template("example.txt")
print(t.render())
print(t.render())
```

```jinja
{% set gs = namespace(count=0) -%}
{% set gs.count = gs.count + 1 -%}
count = {{ gs.count }}
```

```
count = 1
count = 1
```

**Comment by ThiefMaster** [comment]
are you passing something custom as `namespace` to your jinja context by any chance?

because the default Namespace (`namespace` simply points to that class) is this, and i don't see how it would remember things between instances...

https://github.com/pallets/jinja/blob/main/src/jinja2/utils.py#L734
