### ISSUE TITLE
urlencode filter missing ?

### ISSUE THREAD

**Issue by harobed** [pallets/jinja#17]
Hi,

in List of Builtin Filters (http://jinja.pocoo.org/docs/templates/#list-of-builtin-filters) I don't found "urlencode" filter. It's a missing ?

I don't understand, in jinja1 this filter exists : http://wsgiarea.pocoo.org/jinja/docs/filters.html

Do you have some comment about that ?

Regards,
Stéphane

**Comment by jace** [comment]
For anyone who stumbles on this looking for a `urlencode` filter, it was added back in 2012 in 06a8b1c02b2091b31ef4f39ddde3184f25f58260 and 5145401fe5f9995a32757f34359623b87048ab8b. Discussion in #85.

It's called `urlencode` and not `urlquote`, `urlquoteplus`, `urlquote_plus` or `urlescape` (adding these for anyone else landing via search).
