### ISSUE TITLE
Support template tags in a separate column

### ISSUE THREAD

**Issue by mnieber** [pallets/jinja#1703]
I've developed a type of syntactic sugar that results in cleaner looking templates. On the "Nutshell" example it looks like this:

```
{% extends "base.html" %}
{% block title %}Members{% endblock %}
{% block content %}
  <ul>
    <li><a href="{{ user.url }}">{{ user.username }}</a></li>            {% for user in users %}{% endfor %}
  </ul>
{% endblock %}
```

The {% for %} and {% endfor %} could be called "right-side template tags". These template tags are processed as follows:

1. A right-side template tag that starts with "end" such as "endfor" is placed after the line on the left side
2. All other right-side template tags are placed before the line on the left side.
3. After removing the right-side tag, the remaining line is rtrim()-ed to remove right-side white-space.

By applying these three rules, the original "Nutshell" example is restored. 

In my experience, the cleanup achieved by this syntax can be massive. By moving all {% for %} and {% if %} statements to a separate column, the remaining text on the left side looks more like a normal document and less like a piece of source-code. I can show you some examples if you are interested, just let me know.

Of course, for backward compatibility this syntactic sugar would have to be put behind a feature flag.

**Comment by ThiefMaster** [comment]
Not a fan of this at all tbh... it feels really weird to me.

**Comment by mnieber** [comment]
I agree that it's weird. I just happens to work really well (in my opinion). Most radical ideas look weird at first :-).
