### ISSUE TITLE
lex does strip trailing newlines, making impossible to restore original text

### ISSUE THREAD

**Issue by ssbarnea** [pallets/jinja#1711]
I am writing a jinja whitespace reformatter for adding it to ansible-lint, one that aims to match black formatting rules by making use of the great `lex()` method.

Still, while working with it I found what appears to be a bug: any trailing newlines at the end of the template are trimmed, basically trying to lex `foo\n` and `foo` does produce the same set of tokens, so I cannot reconstruct the original argument.

I did check and newlines at any other places inside the templates are treated as expected, only the trailing ones being removed.

Is that intended? Would it be possible to address it?

I am currently adding wrapper to compensate for this behavior but it would be awesome not to have to do that. Maybe in the future, if you are interested, I could even contribute the reformatter to jinja itself, as I am sure others might find it useful too.

**Comment by davidism** [comment]
Yes, it's an intended behavior. I don't plan to add a formatter to Jinja at this time, it is complex enough to maintain as is already. I do have vague future plans to rewrite the parser, at which point it may become more possible, but there is absolutely no timeline for that. Happy to review a PR, but I'm not going to keep this issue open.

**Comment by ssbarnea** [comment]
Thanks, makes sense! I already have a [change](https://github.com/ansible/ansible-lint/pull/2306/files) that seems to perform formatting well with several tests but I am aware that it might take some time until I get more confidence in it. I bet users will find corner cases that I missed.
