### ISSUE TITLE
Can I enforce a Jinja (builtin) filter to sync even if environment is set to async? (how to use sync filters with Quart?)

### ISSUE THREAD

**Issue by jeanmonet** [pallets/jinja#1714]
When using Quart, the Jinja environment is set to async by default.
Apparently this produces the following behavior: builtin Jinja filters become async coroutines.

As a consequence, I can no longer do this (for example):
```python
list(request.args.values() | reject())
```
because the `reject` filter becomes an async coroutine, which results in `TypeError: 'async_generator' object is not iterable`.

How to enforce sync functions for built-in filters? (on a case-by-case basis if needed?)
Thanks

**Comment by davidism** [comment]
Use the list filter.

**Comment by jeanmonet** [comment]
The `list` was just an example. I'm actually using `dict(request.args... | reject('custom_test'))`. IMO there's no dict filter for this specific case.
Also does not answer actual question, there are other examples as well where sync is required. Question is thus: can a sync version of those filters be used (on case-by-case if needed)?

**Comment by davidism** [comment]
Add or override your own filters/functions as needed for your specific use case.

**Comment by jeanmonet** [comment]
Was slightly afraid of that. Oh well, hope this works:
```python
app.jinja_env.filters['reject_sync'] = jinja2.filters.sync_do_reject
```

https://github.com/pallets/jinja/blob/15e4959a2e0fa8744c7275c4e0a6542640900998/src/jinja2/filters.py#L1548-L1551

**Comment by pgjones** [comment]
I think this is an additional argument for #1191
