### ISSUE TITLE
A filter that supports more than one undefined element

### ISSUE THREAD

**Issue by mdione-cloudian** [pallets/jinja#1719]
`{{ a.b.c.d is defined }}` only works on  `d`, but if any of `a`, `b` or `c` are undefined, it explodes. 

Our templates are expanding a big tree of configuration items (~1k), and many are optional, meaning they don't have to be defined. This means that in some cases, whole branches might not exist. Using the example above, `c` and possibly `b` might not be defined, so we have to resort to constructions like `{{ a.get('b', {}).get('c', {}).d is defined }}` a lot.

I checked the code, and it seems impossible to do it as an extension, since the expression is traversed and only the last element is tested. maybe he `*Undefined` classes should return empty objects of the same class from `__getattr__()` et al.

What do you think?

**Comment by ThiefMaster** [comment]
You can always provide a custom `Undefined` subclass that implement this behavior.

**Comment by mkrizek** [comment]
I think you are describing [ChainableUndefined](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.ChainableUndefined) (https://github.com/pallets/jinja/issues/977).

**Comment by ThiefMaster** [comment]
Indeed, I was just about to comment hat as well after looking at the code ;)
