### ISSUE TITLE
[Feat] type checked templates

### ISSUE THREAD

**Issue by hiaselhans** [pallets/jinja#1734]
Most problems i encounter with templates are when the template-context has changed but templates aren't following due to the lack of IDE-support (and me...).

I wonder if it would be possible to define a (pydantic/dataclass) schema for the template context and have the Jinja environment emit a "pseudo-template": translated control flow and variable access in pure python code. This could then be type-checked with tools like mypy.

I am thinking about a workflow like this:

- define a context-schema per template
- load the template
- provide a template.emit_pseudo_code(schema, env) function which emits python code including the context-schema, filters and globals or respectively their imports
- run a static type-checker on the emitted python code.

**Comment by davidism** [comment]
Jinja is a separate language from Python. When it compiles to Python, the code it produces is not amenable to type checking. It doesn't necessarily match what is written, or look like normal Python code that could contain meaningful types.

Issue #1194 is about the fact that we don't have a formal grammar describing the language. Adding an entire new grammar on top of  for type checking, as well as writing a type checking tool to use it, is well outside both the priorities and scope of the Jinja project itself.

You're welcome to write an extension that does this, but I don't plan to work on it myself or add it directly to Jinja.

**Comment by hiaselhans** [comment]
looking at the code output it doesn't seem too far away:

``` python
>>> import jinja2
>>> env=jinja2.Environment()
>>> def get_code(template):
...     parsed = env.parse(template)
...     compiled = env._generate(parsed, "", "")
...     return compiled
... 
>>> print(get_code("""
...     <html>
...     {% for elem in test %}
...     <div>{{ elem.upper(loop.index) }}</div>
...     {% endfor %}
...     {% if 1 < test2 %}
...     test2 is big
...     {% endif %}
... </html>"""))
... 
from jinja2.runtime import LoopContext, Macro, Markup, Namespace, TemplateNotFound, TemplateReference, TemplateRuntimeError, Undefined, escape, identity, internalcode, markup_join, missing, str_join
name = ''

def root(context, missing=missing, environment=environment):
    resolve = context.resolve_or_missing
    undefined = environment.undefined
    concat = environment.concat
    cond_expr_undefined = Undefined
    if 0: yield None
    l_0_test = resolve('test')
    l_0_test2 = resolve('test2')
    pass
    yield '\n    <html>\n    '
    l_1_loop = missing
    for l_1_elem, l_1_loop in LoopContext((undefined(name='test') if l_0_test is missing else l_0_test), undefined):
        _loop_vars = {}
        pass
        yield '\n    <div>'
        yield str(context.call(environment.getattr(l_1_elem, 'upper'), environment.getattr(l_1_loop, 'index'), _loop_vars=_loop_vars))
        yield '</div>\n    '
    l_1_loop = l_1_elem = missing
    yield '\n    '
    if (1 < (undefined(name='test2') if l_0_test2 is missing else l_0_test2)):
        pass
        yield '\n    test2 is big\n    '
    yield '\n</html>'

blocks = {}
debug_info = '3=15&4=19&6=23'

```

so, thanks for your answer. I will look into how Jinja addons are built and where to find them :)
