### ISSUE TITLE
Make it possible to set Environment settings from within a template file (i.e. not via command line or programmatically)

### ISSUE THREAD

**Issue by lfvjimisola** [pallets/jinja#1739]
We have a template collection where we want some of the templates to have _trim_blocks_ and _lstrip_blocks_ set for the entire template.

We do not want to set it from command line or programmatically in Python, but rather something like:

<template_file.jinja2>
```
{#jinja2: lstrip_blocks:True, trim_blocks:True #}

<div>
    {% if true %}
        yay
    {% endif %}
</div> 
```

**Comment by davidism** [comment]
This would require a significant restructuring of the code. I don't plan to add this. You could probably use different environments to render different templates.
