### ISSUE TITLE
My temp's file path is divided by '\\\', but the following if - statement need '/' is in the file path, causes the error template not  found. In fact, the file exists.

### ISSUE THREAD

**Issue by Guangyu-Y** [pallets/jinja#1740]
Environment:

- Python version: 3.6.5
- Jinja version:3.0.3
- OS: Windows11

My temp's file path is divided by '\\\', but the following if - statement need '/' is in the file path, causes the error template not  found. In fact, the file exists.

![image](https://user-images.githubusercontent.com/23715415/197528620-75f048d1-3867-4af5-9f98-67baeb0660b3.png)

**Comment by ThiefMaster** [comment]
Jinja uses forward slashes, regardless of the underlying OS. You cannot use backslashes unless you implement your own template loader (don't dot hat).
