### ISSUE TITLE
Support pathlib.Path instances in Environment.get_template

### ISSUE THREAD

**Issue by invisibleroads** [pallets/jinja#1754]
Users might define custom loaders that override `BaseLoader.get_source` to accept a `pathlib.Path` instance.

```
from pathlib import Path
env.get_template(Path('t.html'))
```

Doing so will result in the following exception:

```
name 'PosixPath' is not defined
```

The request is to let `Environment.get_template` take `pathlib.Path` instances.

**Comment by davidism** [comment]
Templates paths are not file system paths. The `FileSystemLoader` supports pathlib already because it _does_ deal with file system paths.
