### ISSUE TITLE
PytestRemovedIn8Warning with pytest 7.2.0

### ISSUE THREAD

**Issue by frenzymadness** [pallets/jinja#1758]
When running tests with pytest 7.2.0, I'm getting:
```
E               pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
E               tests/test_loader.py::TestModuleLoader::test_supports_pathlib_in_list_of_paths is using nose-specific method: `teardown(self)`
E               To remove this warning, rename it to `teardown_method(self)`
E               See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
```
Which is probably caused by:

https://github.com/pallets/jinja/blob/6f79daafe868b8ef20baecdcb45d12299529ed2e/tests/test_loader.py#L199

According to the message, renaming the teardown methods to `teardown_method` should be enough to suppress the warning.

**Comment by heirecka** [comment]
Looks like that was done with 3fadee01b712580d811bdd2cb06cd8a1b5ee0821
