### ISSUE TITLE
The latest / 3.1.x API Reference is not rendered properly

### ISSUE THREAD

**Issue by xzmeng** [pallets/jinja#1783]
The latest / 3.1.x API Reference is not rendered properly.

https://jinja.palletsprojects.com/en/latest/api/

After upgrading to sphinx 5, autoclasses are included in ToC by default, causing the ToC to overlap with the document body.

Environment: macOS

- Python version: 3.11.1
- Jinja version: main branch ([ae53ea5350c5dd622c7e4b85f8aca5dedc5af7a7](https://github.com/pallets/jinja/commit/ae53ea5350c5dd622c7e4b85f8aca5dedc5af7a7))

**Comment by davidism** [comment]
Duplicate, search closed issues
