### ISSUE TITLE
Typo in documentation (template whitespace)

### ISSUE THREAD

**Issue by maldata** [pallets/jinja#1791]
There is a small (but confusing) typo in [this section of the template documentation](https://github.com/pallets/jinja/blob/main/docs/templates.rst#whitespace-control):

```
With both trim_blocks and lstrip_blocks enabled...
...
But with both trim_blocks and lstrip_blocks enabled...
```
It seems likely that the first line (before the example) should read "With both trim_blocks and lstrip_blocks **_disabled_**."

**Comment by davidism** [comment]
Please just fix typos, no need to open an issue first.

**Comment by davidism** [comment]
It appears to be correct as written. It's talking about enabling those, shows what happens by default, then shows what happens when they're enabled.
