### ISSUE TITLE
Docs API menu covers page text

### ISSUE THREAD

**Issue by hugovk** [pallets/jinja#1795]
Environment:

- Python version: n/a
- Jinja version: 3.1.x
- Chrome version: 108
- macOS Ventura 13.1
- Screen resolution: 1512x982

To reproduce:

1. Open https://jinja.palletsprojects.com/en/3.1.x/api/
2. Look at the left hand menu

Actual result:

The menu items cover the main page content

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1324225/213917481-b604b163-bd9a-472c-9ebc-3824a83a9983.png">

Expected result:

Some sort of wrapping or truncating so menu items don't obscure the page text

**Comment by davidism** [comment]
Duplicate

**Comment by hugovk** [comment]
Sorry for the noise. I didn't find the duplicate beforehand, but for future reference:

Duplicate of https://github.com/pallets/jinja/issues/1751 and https://github.com/pallets/pallets-sphinx-themes/issues/64, with a PR at https://github.com/pallets/pallets-sphinx-themes/pull/65.
