### ISSUE TITLE
Jinja docs 3.1 render the side bar overlapping with page content

### ISSUE THREAD

**Issue by BenAuerLeukeleu** [pallets/jinja#1802]
On https://jinja.palletsprojects.com/en/3.1.x when clicking on one of the links in "Contents" the side bar is overlapping with the page content

MacBook Pro M1
MacOS: Ventura 13.2
Chrome: Version 110.0.5481.77 (Official Build) (arm64)

<img width="1907" alt="Screenshot 2023-02-13 at 15 19 46" src="https://user-images.githubusercontent.com/112627346/218487550-0ac6f276-2cdc-450c-beb5-e72583e70da3.png">

**Comment by davidism** [comment]
Duplicate
