### ISSUE TITLE
Missing test coverage from pull request #1511?

### ISSUE THREAD

**Issue by jayaddison** [pallets/jinja#1806]
As part of pull request #1511, the changes may have fixed a bug related to native type rendering for iterator; it could be worth adding test coverage related to that.

Before #1511, the code was calling `itertools.islice(values, 2)` to retrieve the head elements from a `values` collection (potentially of an iterator type) and then using `itertools.chain(head, values)` to subsequently produce output.

In the case where `values` _is_ an iterator, I think that works correctly.  But in cases where `values` is _not_ an iterator, it can result in output duplication (something that I think #1511 indirectly resolves with [this check](https://github.com/pallets/jinja/pull/1511/commits/2903565262e6c8971e612a2717feb430e284e4ac#diff-25a3ba2093b8517416a58a44407a2580496610a92a90b6d6550da54ce4f3220cR35-R37)).

For example:

```pycon
>>> from itertools import islice
>>> values = [1,2,3,4]
>>> head = islice(values, 2)
>>> from itertools import chain
>>> list(chain(head, values))
[1, 2, 1, 2, 3, 4]
```

**Comment by jayaddison** [comment]
(note: opened this as a separate issue thread since the existing thread(s) have been locked)

**Comment by davidism** [comment]
Happy to consider a PR that fixes this or adds tests.

**Comment by jayaddison** [comment]
Work-in-progress at https://github.com/openculinary/jinja/tree/issue-1806/pr-1511-additional-test-coverage:

- [x] Test coverage to demonstrate that a problem could have occurred during `async` rendering of templates containing native types
- [ ] Enable `async` support for `pytest` and `tox`

**Comment by jayaddison** [comment]
Does the test coverage offered in #1807 seem reasonable for this?  (that's one of my pull requests, and I'm trying to close/refresh a few that have been open for a while)

**Comment by davidism** [comment]
Seems fine, just haven't had time to get to merges here.
