### ISSUE TITLE
Make class Namespace iterable

### ISSUE THREAD

**Issue by joeUser555** [pallets/jinja#1809]
The namespace feature is very handy to define local objects similar to a dictionary.
Unfortunatly they are not iterable, thus making them unusable in for-loops like " {% for k,v in namespaceObject %}..."

I tryed to implement the __iter__ method in the class Namspace in jinja2/utils.py.
But I did not understand the implementation concept of that class so I faild.

Perhaps someone from the team can do that.
It should not be so complicated from the view that a namspace object is acting like a dictionary object.

The iterator should yield only the items that are directly defined in it.
It should not yield items from posible parent namespaces.

**Comment by davidism** [comment]
This is not an intended use case for `namespace`. It is intended only for tracking and accessing data between loop iterations.

**Comment by joeUser555** [comment]
That sounds plausible.
