### ISSUE TITLE
Explicit macro call does not accept more than the defined arguments

### ISSUE THREAD

**Issue by joeUser555** [pallets/jinja#1810]
I defined two macros calling each other.

```
{% macro a(parm) -%}
    <foo>
       {{ parm }}
       {{ varargs }}
    </foo>
{%- endmacro %}

{% macro b(parm) -%}
    <bar>
       {{ a(param, *vargargs)}}
    </bar>
{%- endmacro %}
```
### What I expect to happen:

I expected the output:

```
<bar>
    <foo>
        bla
        blub
    </foo>
</bar>
```

A call to macro b with additional arguments 

`{{ b('bla', 'blub') }}
`
causes an exception:

`TypeError: macro 'b' takes not more than 1 argument(s)`

- Python version: 3.10
- Jinja2 version: 3.1.2
[varargstest.jinja.txt](https://github.com/pallets/jinja/files/10813516/varargstest.jinja.txt)

**Comment by joeUser555** [comment]
The documentation says in the Marcos section:

```
Inside macros, you have access to three special variables:

varargs
If more positional arguments are passed to the macro than accepted by the macro, they end up in the special varargs variable as a list of values.

kwargs
Like varargs but for keyword arguments. All unconsumed keyword arguments are stored in this special variable.
```

**Comment by joeUser555** [comment]
The documentationi could(should) be updated with some examples of how to use this special variables.

**Comment by davidism** [comment]
After fixing the typos in your example, it works fine. You wrote `vargargs` instead of `varargs`, and `parm` instead of `param`.

**Comment by joeUser555** [comment]
Thank you,

Four eyes see more than two.
Or
With glasses this could not have happened.
