### ISSUE TITLE
UnknownTokenException: Unknown token found: value_json.power_on_behavior

### ISSUE THREAD

**Issue by gargamelonly** [pallets/jinja#1811]
using zigbee2mqtt with HA auto-discovery.
I am getting lots of error log entries with the following message:
`Executing the JINJA-transformation failed: An error occurred while transformation. UnknownTokenException: Unknown token found: value_json.power_on_behavior
`
Environment:
OpenHAB 3.4.2 
JINJA transformation service with Zigbee2MQTT Home-assistant Auto-Discovery option.

```
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x60a423fffed2e99f"
    ],
    "manufacturer": "TuYa",
    "model": "Socket module (TS011F_socket_module)",
    "name": "wallplug16A"
  },
  "enabled_by_default": false,
  "entity_category": "config",
  "icon": "mdi:power-settings",
  "json_attributes_topic": "zigbee2mqtt/wallplug16A",
  "name": "wallplug16A power on behavior",
  "state_topic": "zigbee2mqtt/wallplug16A",
  "unique_id": "0x60a423fffed2e99f_power_on_behavior_zigbee2mqtt",
  "value_template": "{{ value_json.power_on_behavior }}"
}
```

**Comment by davidism** [comment]
This appears to be an issue with something using jinja, not with jinja itself.
