### ISSUE TITLE
Flake error B031 caused by new release flake8-bugbear

### ISSUE THREAD

**Issue by szabgab** [pallets/jinja#1823]
Using `flake8-bugbear-23.1.20` the pre-commit hook passed. Once `flake8-bugbear-23.2.13` was released the flake8 step of the pre-commit hook started to fail with

```
scripts/generate_identifier_pattern.py:33:18: B031 Using the generator returned from `itertools.groupby()` more than once will do nothing on the second usage. Save the result to a list, if the result is needed multiple times.
```

**Comment by davidism** [comment]
Fixed in the 3.1.x branch, I just need to merge it forward. https://github.com/pallets/jinja/commit/be0bcb61f9e2918c85cbe0ccb04e1d7b36c68a70
