### ISSUE TITLE
Documentation sidebar overflows onto the body

### ISSUE THREAD

**Issue by LFA-V10** [pallets/jinja#1826]
Documentation sidebar overflows onto the body making it difficult to read. The issue is happening with the 3.1.x version documentation and not with the older versions' documentation.

Example link to view the issue - [https://jinja.palletsprojects.com/en/3.1.x/api/#](https://jinja.palletsprojects.com/en/3.1.x/api/#)

![screenshot - jinja](https://user-images.githubusercontent.com/129112835/228050786-79ec2c90-c3c7-4723-83d0-f77d00524722.png)

**Comment by davidism** [comment]
Duplicate, see theme repo.
