### ISSUE TITLE
Update the https://jinja.palletsprojects.com/en/3.1.x/api/ website with the HTML fix from https://github.com/pallets/pallets-sphinx-themes/pull/65

### ISSUE THREAD

**Issue by goxberry** [pallets/jinja#1837]
This is **not** a duplicate of the previous bugs -- rather, a project maintainer needs to rebuild a copy of the Jinja 3.1.x HTML docs with the fix in https://github.com/pallets/pallets-sphinx-themes/pull/65 and push the fixed HTML to https://jinja.palletsprojects.com/en/3.1.x/api/ so users stop reporting the menu bar overlap problem.

Here's how you reproduce:

- Open a browser and visit https://jinja.palletsprojects.com/en/3.1.x/api/ -- **not** a locally-built copy of the documentation -- and you will see something like the following below

![image](https://user-images.githubusercontent.com/321479/230684900-ca78ec37-9dc5-4aba-aabd-30be557c6c86.png)

Again, note that this image is **not** a locally built copy of the documentation, because if it were, the fix in https://github.com/pallets/pallets-sphinx-themes/pull/65 would be pulled in, and users wouldn't see that menu bar overlap in the HTML.

If one of the project maintainers rebuilds the docs to HTML and pushes the rebuilt docs up to https://jinja.palletsprojects.com/en/3.1.x/api/, I suspect people would stop reporting this bug.

Also note that this issue occurs with other Pallets project websites, like the posted Click API docs, e.g., in https://click.palletsprojects.com/en/8.1.x/api/#utilities, and the same type of fix is needed: a project maintainer needs to rebuild the HTML docs for that project with the fix in https://github.com/pallets/pallets-sphinx-themes/pull/65 and push the fixed HTML up to the project's documentation website.

![image](https://user-images.githubusercontent.com/321479/230687492-f5022f93-ad3a-4cfa-b64a-ba32fc2d6ca2.png)

Users keep reporting this problem not because it hasn't been fixed in source code -- as noted elsewhere, the source code has already been fixed -- but because the public-facing documentation website hasn't been regenerated and updated with the fixed HTML.

**Comment by goxberry** [comment]
For reference, this bug is not a duplicate of https://github.com/pallets/jinja/issues/1826, https://github.com/pallets/jinja/issues/1802, https://github.com/pallets/jinja/issues/1783, or https://github.com/pallets/jinja/issues/1768.

**Comment by goxberry** [comment]
@davidism I still see the links in the left menu bar overflowing their bounds and tracked the behavior to the project requirements: the `Pallets-Sphinx-Theme==2.0.2` requirement in `requirements/docs.txt` does not contain the changes mentioned in https://github.com/pallets/pallets-sphinx-themes/pull/65. #1841 is a notional change to this project's requirements to fix that behavior.

**Comment by davidism** [comment]
I'm really trying to be polite, but this is getting silly. I know the theme needs a new release, and that each project's docs need to be rebuilt. Please stop hounding me about it, I've already indicated that I know about it and that more issues don't need to exist for it.
