### ISSUE TITLE
https://jinja.palletsprojects.com/en/3.1.x/api : page format -- table of contents overlaps content on page

### ISSUE THREAD

**Issue by zipperer** [pallets/jinja#1842]
This issue is neither urgent nor important.

Issue: On this webpage (https://jinja.palletsprojects.com/en/3.1.x/api), the table of contents overlaps the content on the page. Please see screenshot: 
![20230417-jinja-website-api-brave-browser-on-ubuntu-table-of-contents-overlaps-content](https://user-images.githubusercontent.com/47086307/232563235-fba07b39-c65f-4962-95dc-21d792b55920.png)

Environment: 
Brave Browser (https://brave.com/): Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)
Please see screenshot:
![20230417-brave-browser-version](https://user-images.githubusercontent.com/47086307/232563665-614149f9-b666-4431-8270-ed5433b32e58.png)

Steps to reproduce issue: 
 - open web browser Brave
 - visit url https://jinja.palletsprojects.com/en/3.1.x/api

When I visited the page, I edited the local HTML file to add padding-left to section with id='api'. Please see screenshot
![20230417-jinja-website-api-brave-browser-on-ubuntu-after-padding-table-of-contents-does-not-overlap-content](https://user-images.githubusercontent.com/47086307/232567048-5b6bf243-68ee-455a-9b86-a4b33881bfb3.png)

With the padding, the left panel table of contents does not overlap the main panel contents. I do not hereby suggest that section gets padding-left; for, I am not an experienced user of CSS, so I don't know which changes are best.

If this is not the correct project to which to add this issue report, I apologize. I used this project because I found the 'Issue Tracker' link on page https://jinja.palletsprojects.com/en/3.1.x/.

**Comment by davidism** [comment]
Duplicate, please search first
