### ISSUE TITLE
Add ljust, rjust, and center "fill" filters...

### ISSUE THREAD

**Issue by rkad41** [pallets/jinja#1846]
Jinja is awesome.  Appreciate what you do.  Here's one thing I think would make it even better...

Add filter `ljust`, `rjust` and `center` (like the Python `str` methods) that pad the interpolated variable to the length of the replacement string.  For example:

```
+--------------------------+---------------------+
| City                     |               Value |
+--------------------------+---------------------+
{% for row in table -%}
| {{ row.name|ljust     }} | {{ row.val|rjust }} |
{% endrow -%}
+--------------------------+---------------------+
```

This would render as:

```
+--------------------------+---------------------+
| City                     |               Value |
+--------------------------+---------------------+
| New York City, NY        |           8,622,357 |
| Los Angeles, CA          |           4,085,014 |
| Houston, TX              |           2,378,146 |
+--------------------------+---------------------+
```

The only way to accomplish this function now is to create custom filters.  But this technique is limited.  For example, I created a custom `ljust` filter that implements the Python `ljust` string method:

```
{{ data.op|ljust(44)                      }}
```

Here you have to specify the length of the replacement string.  It would be a significant enhancement if this filter could use the length of the replacement string syntax as the default.  In other words, this would work as well:

```
{{ data.op|ljust                          }}
```

This feature would be very beneficial if you are trying to create fixed width data tables as illustrated above.

**Comment by davidism** [comment]
`data.op.ljust`, `.rjust`, and `.center()` string methods already exist, call them directly.

> this filter could use the length of the replacement string syntax

I _think_ you're implying that the Jinja parser could somehow pass the number of spaces inside the braces to the filter. This is not possible, and if it were it would require special casing these three filters which is also not possible.

It sounds like you're trying to do too much in the template. Preprocess your data in Python to determine column widths, or even use a library (I'm aware of [tabulate](https://pypi.org/project/tabulate/) but I'm pretty sure there are others) to format the table for you.
