### ISSUE TITLE
Configurable Parser

### ISSUE THREAD

**Issue by hasier** [pallets/jinja#1850]
It's not a common use case, but I would find it very useful to be able to tweak how the `Parser` works. For my use case, I'd like to tweak the keywords the `Parser` recognises (`for`, `if`, `block`...) in order to restrict them as necessary (but not extend them, as that would involve changing the actual behaviour of the `Parser`, which I'm not aiming to tackle here).

Currently the `Parser` recognises the keywords from a module-level constant, which is not easily editable just for 1 `Parser` class.
https://github.com/pallets/jinja/blob/953acd65b2be5428482dcb60f5b8481b66252ac9/src/jinja2/parser.py#L18-L33
Besides, even if it were possible to specifically change a `Parser`, say by subclassing it and dynamically overwriting some of the methods, we would need to further subclass an `Environment` and override some of its methods, as the `Parser` is hardcoded in them.
https://github.com/pallets/jinja/blob/953acd65b2be5428482dcb60f5b8481b66252ac9/src/jinja2/environment.py#L615-L619

I would find much easier to implement this behaviour if the `Parser` had a class-level variable that could be swapped in an inheriting class, and the same with a class-level variable for the `Parser` in the `Environment` class. This is a pattern that's already followed for other internals, such as the `CodeGenerator` class via the `code_generator_class` class-variable.
https://github.com/pallets/jinja/blob/953acd65b2be5428482dcb60f5b8481b66252ac9/src/jinja2/environment.py#L284

**Comment by davidism** [comment]
See #1194. I plan to rewrite the parser and make it more extensible, so adding this right now only for the entire API to change doesn't seem ideal.

**Comment by davidism** [comment]
In your case, you can probably use an extension: https://jinja.palletsprojects.com/en/3.1.x/extensions/#writing-extensions

**Comment by davidism** [comment]
Or overriding `Environment.parse` is fine, it's the only part of the parser API that's publicly documented.

**Comment by davidism** [comment]
> it just felt cleaner to have the class variable to configure it

Subclassing and overriding methods is an accepted and standard way to extend things in both Python and Jinja.
