### ISSUE TITLE
Docs: Table of contents spills into main content

### ISSUE THREAD

**Issue by robertgodfrey** [pallets/jinja#1853]
![example](https://i.imgur.com/z6ejGZs.jpg)

Screenshot taken from [this page](https://jinja.palletsprojects.com/en/3.1.x/api/#basics).

This makes the docs difficult to read. Same behavior in Chrome, Firefox, and Safari.

**Comment by davidism** [comment]
Thanks, this has already been reported and fixed in the then repository.

**Comment by davidism** [comment]
Thanks, this has already been reported and fixed in the then repository and many times here.
