### ISSUE TITLE
`select_autoescape` default value for `default_for_string` should be `False`

### ISSUE THREAD

**Issue by clavedeluna** [pallets/jinja#1890]
According to jinja's select_autoescape [documentation](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.select_autoescape)

> The select_autoescape() function returns a function that works roughly like this:

> def autoescape(template_name):
          if template_name is None:
                return False

Furthermore, the docs makes it clear that jinja's default autoescape is still `False`. So, If I setup autoescape like this:

```
from jinja2 import Environment, select_autoescape
env = Environment(autoescape=select_autoescape())
```
I would expect autoescape to end up as `False`

However,  in the code [here](https://github.com/pallets/jinja/blob/d594969d722ceb4e8f3da8861befc9c0ac87ae1b/src/jinja2/utils.py#L617C8-L617C8) when template_name is None, it returns the default value of `default_for_string`, which at this time is `True`.

Should `default_for_string` not be `False`, just like `default`?

Environment:

- Python version:
- Jinja version: 3.0.x

**Comment by davidism** [comment]
I don't plan to change the param defaults at this time. Both are configurable, to whatever behavior the application needs.
