### ISSUE TITLE
Doesn't parse HTML multi escape sequence codes

### ISSUE THREAD

**Issue by t3lmoazevedo** [pallets/jinja#1897]
The template parser doesn't recognize anymore the more-than-one escape sequence HTML codes.
Examples:
🔋  \uD83D\uDD0B
🐌 \uD83D\uDC0C
🌡️   \uD83C\uDF21\uFE0F

![image](https://github.com/pallets/jinja/assets/41584793/cadb7e76-14b3-4986-b883-7c0c61249216)

Environment:

- Python version: 3.11
- Jinja version: 3.0
- Home Assistant 2023.10.1
  - Supervisor: 2023.10.0
  - Operating: System 10.5
  - Frontend: 20231005.0

**Comment by davidism** [comment]
Jinja doesn't deal with HTML at all. It renders text, how that text is interpreted is up to the client viewing it, such as a browser for HTML.

**Comment by t3lmoazevedo** [comment]
Thank you @davidism for the explanation. I will report to HomeAssistant team.
