### ISSUE TITLE
Otera, a Better name than jinja..

### ISSUE THREAD

**Issue by HuangChiEn** [pallets/jinja#1905]
Um... It's barely to talk about the misunderstanding of 神社 ( じんじゃ, jinja ) while jinja already become a popular package.
However, otera (お寺, おてら) may be the proper name according to the FAQ (https://jinja.palletsprojects.com/en/3.0.x/faq/#why-is-it-called-jinja)...

ref: https://www.blogblog.life/entry/differencebetweenshrineandtemple30

**Comment by ThiefMaster** [comment]
we're not going to rename jinja... so I'm not sure what the point of even opening this issue is.
