### ISSUE TITLE
Change github link to ssh in "contributing" docs

### ISSUE THREAD

**Issue by ratchek** [pallets/jinja#1916]
Github no longer allows for pushing through https. "Contributing" documentation should reflect that.

Right now, the documentation reads:
`$ git remote add fork https://github.com/{username}/jinja`
Instead should be
`$ git remote add fork git@github.com:{username}/jinja.git`

Environment:

- Python version:
- Jinja version:

**Comment by davidism** [comment]
I don't see any reference to this change. Where is this documented?

**Comment by ratchek** [comment]
I guess I meant the change to token authentication.
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

I feel like most new users will be authenticating with ssh.

**Comment by ThiefMaster** [comment]
While I personally think SSH is far superior for Git operations than HTTPS, I think this blog post has nothing to do with what you suggest... it's more about them ditching legacy username/password authentication for performing git operations over HTTPS, which makes perfect sense considering there's 2FA.

I'm not sure what the default on GitHub is, but it might very well be HTTPS (with a token).
