### ISSUE TITLE
How to sum the values of a dict

### ISSUE THREAD

**Issue by charlax** [pallets/jinja#192]
Shouldn't `sum` be a function and not only a filter? How would you sum the values of a dict (e.g. a `Counter` instance)?

Those two (logically) do not work:

```
{{ number_of_stuff|sum(number_of_stuff.values()) }}
{{ number_of_stuff|sum(attribute=values) }}
```

Thanks!

**Comment by gad2103** [comment]
is there any way to handle None type objects gracefully in sum?

**Comment by untitaker** [comment]
Please ask on StackOverflow

On 21 May 2016 00:57:11 CEST, gabriel duncan <notifications@github.com> wrote:
>is there any way to handle None type objects gracefully in sum?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/jinja/issues/192#issuecomment-220737518

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
