### ISSUE TITLE
`tojson` always do autoescape

### ISSUE THREAD

**Issue by boy2000-007man** [pallets/jinja#1934]
`tojson` always escape `'` to `\u0027` even if `autoescape=False`, actually it also happens to `<`, `>`, `&`

```python
>>> import jinja2
>>> env = jinja2.Environment(autoescape=False)
>>> t = env.from_string("{{ x|tojson }}")
>>> print(t.render(x="'"))
"\u0027"
```

I think the expected output should be `"'"`

Environment:

- Python version: 3.11.4
- Jinja version: 3.1.2

**Comment by boy2000-007man** [comment]
Sorry, but what does `not planned` mean here?
Is it a feature or due to inappropriate setting? Or it's duplicated? Or won't fix?

**Comment by CheeseCake87** [comment]
Can you explain your use case a little more?

If you are storing html in a value, this is working for me even with the escapes:

```python
@app.route("/")
def index():
    value = {"html": "<p class=\"this\"> foo and 'bar' </p>"}
    return render_template("template.html", value=value)
```

```javascript
<script>
    const str_json = JSON.stringify({{ value|tojson }})
    console.log(str_json)
    fetch('/json', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: str_json
    })
</script>
```

This gives a `console.log` result of `{"html":"<p class=\"this\"> foo and 'bar' </p>"}` which is what I'm assuming you're doing?

**Comment by ThiefMaster** [comment]
`tojson` is meant to be used inside script tags, and there autoescape would break things. But nobody disables autoescape for those.

Is the current behavior less safe than requiring everyone to use `...|tojson|safe` while inside script tags? Yes.

Would it be extremely annoyed by having to (manually) update a huge amount of templates in my own applications if this change went live? Absolutely yes. And I think almost everyone else would have a similar reaction...

Just FWIW, the current behavior is well-documented:

> The returned string is safe to render in HTML documents and `<script>` tags. The exception is in HTML attributes that are double quoted; either use single quotes or the `|forceescape` filter.

**Comment by ThiefMaster** [comment]
Ah, or maybe I misunderstood this after looking at the PR. It seems to not change the behavior at all in the typical HTML context, it just avoids wrapping the result in a `Markup` object when autoescaping is disabled.

**Comment by CheeseCake87** [comment]
Yeah, I'm also trying to work out if there might be a use case outside of a web environment...

It might be better to change `utils.htmlsafe_json_dumps` in some way to achieve this? - That already imports json

**Comment by CheeseCake87** [comment]
This change would change default behaviour as `jinja2.Environment.autoescape` defaults to `False`. It also looks like `autoescape` is focused specifically towards XML/HTML and not JSON. 

I don't think this change makes sense to go ahead with.

**Comment by CheeseCake87** [comment]
This will provide what you need with less potential disruption to core jinja functionality.

```python
from jinja2 import Environment

import json

env = Environment()
env.filters["rawjson"] = json.dumps

t = env.from_string("{{ x|rawjson }} <p></p>")

print(t.render(x={"html": "<p class=\"this\"> foo and 'bar' </p>"}))
```

Outputs:
`{"html": "<p class=\"this\"> foo and 'bar' </p>"} <p></p>`

**Comment by boy2000-007man** [comment]
I know, but the default behavior cannot be disabled is somehow weird.

**Comment by CheeseCake87** [comment]
The `tojson` is specifically focused towards outputting safe JSON in `<script>` tags, which the docs describe. `autoescape` is mentioned in the docs to only touch XML/HTML. Playing around with the meaning of these is a lot harder to reason over than creating a new filter, or overwriting one like you've mentioned.

I wouldn't recommend overwriting incase a user of your API decides to read the jinja docs, then again, I'm not sure of you use case so that might be fine.

Thank you for your efforts here, we do appreciate all interest and effort in improving the library.

**Comment by boy2000-007man** [comment]
I think the arguable thing might be Jinja enforces a html script tag specific behavior while not claim itself is html specific templating engine.
> Jinja is a fast, expressive, extensible templating engine. Special placeholders in the template allow writing code similar to Python syntax. Then the template is passed data to render the final document.

**Comment by davidism** [comment]
You can replace the `tojson` filter (`env.filters["tojson"] = other_tojson`) if you have specific needs. Note that the escapes aren't HTML character references, they're JSON Unicode escapes, so while the characters being escaped are HTML-related, the resulting value is still valid JSON in any context, without any change in meaning. When the JSON is decoded, the escapes become the actual characters in any context.
