### ISSUE TITLE
Native types in macros works for list but does not work for int

### ISSUE THREAD

**Issue by AndreKR** [pallets/jinja#1936]
#1511 by @mkrizek added a test that looks like this (formatting mine):

```jinja2
{%- macro x() -%}
  {{- [1,2] -}}
{%- endmacro -%}
{{- x()[1] -}}
```

This shows that rendering `[1,2]` in the macro returns an actual `list` from the macro, not a string.

According to the first example on https://jinja.palletsprojects.com/en/3.1.x/nativetypes/ I would expect this to work as well:

```jinja2
{%- macro x(a,b) -%}
  {{- a + b -}}
{%- endmacro -%}
{{- x(1,2) > 3 -}}
```
I would expect the macro to return an `int`, but apparently it returns a string.

Environment:

- Python version: 3.11.6
- Jinja version: 3.1.3

**Comment by mkrizek** [comment]
> but apparently it returns a string.

The expression `x(1,2) > 3` is a boolean expression and as such should return a boolean which indeed it does:
```python
>>> from jinja2.nativetypes import NativeEnvironment
>>> r = NativeEnvironment().from_string("{%- macro x(a,b) -%}{{- a + b -}}{%- endmacro -%}{{- x(1,2) > 3 -}}").render()
>>> r, type(r)
(False, <class 'bool'>)
```

If the macro returned a string there would be an error like `TypeError: '>' not supported between instances of 'str' and 'int'`. Can you clarify why you think the macro returns a string?

Or maybe https://github.com/pallets/jinja/issues/1701 is related to your issue?

**Comment by AndreKR** [comment]
Hm, indeed, that code works when I try it in another Jinja2 playground. I was using it in the Template editor in Home Assistant, where it does in fact give the error you mention:

![image](https://github.com/pallets/jinja/assets/1188538/b824abc3-278f-4f8c-bce4-3a7a7f7d4034)

So there must be something special about the environment there.
