### ISSUE TITLE
Standardize contribution doc for all Pallets projects

### ISSUE THREAD

**Issue by j7an** [pallets/jinja#1987]
It would be great if we could standardize the contribution doc for all Pallets projects. Currently each project has its own `CONTRIBUTING.rst` file which requires each file to be updated separately taking up valuable time for contributors. Would it be possible to have one `CONTRIBUTING.rst` in the website repo and have the other project's `CONTRIBUTING.rst` reference it instead? Or just have one contribution guide on the website?

e.g. each Pallets' `CONTRIBUTING.rst` has the following `git clone` instruction. But as a new contributor using the following git clone will cause problems later on when the contributor realizes Github does not allow password auth for http cloned repos when pushing commits. The new contributor will either have to edit their git remote to ssh or reconfigure git using a Personal Access Token. Neither is mentioned in the docs.

So in this situation if we're to update the docs, we'll need to update the contribution instructions on each Pallets project.

```bash
$ git clone https://github.com/your-username/flask
$ cd flask
```

**Comment by davidism** [comment]
> Or just have one contribution guide on the website?

This is something I'm actively working on, including improving the instructions in general. Once that's completed I'll ask the community to review it.
