### ISSUE TITLE
float comparison with x.10 fails

### ISSUE THREAD

**Issue by brianjmurrell** [pallets/jinja#1989]
```
$ cat template
# VERSION: {{ VERSION }}
# {{ (VERSION|float < 8.9) }}
# {{ (VERSION|float < 8.10) }}
$ jinja2 -D VERSION=8.8 --format=json template
# VERSION: 8.8
# True
# False
```

That `False` should be `True` given that `8.8` is `< 8.10`.

Environment:

- Python version: 3.12.3
- Jinja version: 3.1.3

**Comment by davidism** [comment]
The float `8.10` is equivalent to `8.1`, trailing zeros don't matter. I'm fairly sure that's universally true in programming languages. You're looking for version parsing and comparison, which is completely different. Try https://packaging.pypa.io/en/stable/version.html
