### ISSUE TITLE
TemplateNotFound on Window OS

### ISSUE THREAD

**Issue by jgauby** [pallets/jinja#2009]
On Window, this line fails :
https://github.com/pallets/jinja/blob/main/src/jinja2/loaders.py#L30

The path separator on Window is `\`

Jinja version 3.1.4

**Comment by ThiefMaster** [comment]
Forward slashes are perfectly fine and valid on Windows.

And template paths are not filesystem paths even though they may map to such paths. They **always** use forward slashes.
