### ISSUE TITLE
DebugUndefined for blocks to allow iterative rendering

### ISSUE THREAD

**Issue by sdementen** [pallets/jinja#2014]
I would like to be able to render a template progressively, interpreting only the variables/blocks which are defined and leaving untouched the one undefined. This can be done for variables {{ ... }} with the DebugUndefined but not for blocks {% ... %}.

For example, 
```python
from jinja2 import DebugUndefined, Template

tpl_base = "{% if option_enabled %}You choose the option for {{ year }}{% else %}You did not choose the option.{% endif %}"
print(tpl_base)

tpl_rendered_first = Template(tpl_base, undefined=DebugUndefined).render({"option_enabled": True})
print(tpl_rendered_first)

tpl_rendered_second = Template(tpl_rendered_first, undefined=DebugUndefined).render({"year": 2024})
print(tpl_rendered_second)
```
prints
```
{% if option_enabled %}You choose the option for {{ year }}{% else %}You did not choose the option.{% endif %}
You choose the option for {{ year }}
You choose the option for 2024
```
The template is rendered first by interpreting the block depending on `option_enabled` and leaving untouched the variable `year` that is undefined. And in a second pass, the variable `{{ year }}` is replace as it is defined.

However, I would be able to delay the rendering of the blocks when undefined:
```python
from jinja2 import DebugUndefined, Template

tpl_base = "{% if option_enabled %}You choose the option for {{ year }}{% else %}You did not choose the option.{% endif %}"
print(tpl_base)

tpl_rendered_first = Template(tpl_base, undefined=DebugUndefined).render({"option_enabled": True})
print(tpl_rendered_first)

tpl_rendered_second = Template(tpl_rendered_first, undefined=DebugUndefined).render({"year": 2024})
print(tpl_rendered_second)
```
to get
```
{% if option_enabled %}You choose the option for {{ year }}{% else %}You did not choose the option.{% endif %}
{% if option_enabled %}You choose the option for 2024{% else %}You did not choose the option.{% endif %}
You choose the option for 2024
```
but instead I get the following as DebugUndefined does not apply to blocks
```
{% if option_enabled %}You choose the option for {{ year }}{% else %}You did not choose the option.{% endif %}
You did not choose the option.
You did not choose the option.
```

**Comment by davidism** [comment]
This is not an intended use of the `DebugUndefined`, and is only working the way you want by accident here. `DebugUndefined` is outputting a message, and when there's no information beyond "name of top level", then that's what's output. But this won't work for attributes, indexing, filters, or tests.

This is not generally possible in Jinja. A template is compiled to Python code, it's no longer the template by the time you render it. `{% if x %}...{% endif %}` turns into something like `if x: ...`, `{{ x.y }}` turns into something like `yield find("y", find("x", ctx))`.

It may be possible to do this by using [`find_undeclared_variables`](https://jinja.palletsprojects.com/page/api/#jinja2.meta.find_undeclared_variables) and then maybe some clever string replacement, or maybe something similar with an [extension](https://jinja.palletsprojects.com/en/3.1.x/extensions/). However, this progressive rendering is not something we can add to Jinja itself.
