### ISSUE TITLE
Incorrect list comprehension

### ISSUE THREAD

**Issue by lindhe** [pallets/jinja#2015]
This list comprehension is incorrect:

![image](https://github.com/user-attachments/assets/d1d07840-bad8-43da-aab2-c1f65a975b4f)

https://jinja.palletsprojects.com/en/latest/templates/#jinja-filters.selectattr

It says `u for user in users` when it should be `user for user in users` (I'm pretty sure). Tried to find it here in this repo, but was unable to. Didn't find a link to GitHub on the docs page, so hope this is the right place to post.

Cheers!

**Comment by ThiefMaster** [comment]
https://github.com/pallets/jinja/blob/3.1.x/src/jinja2/filters.py#L1632-L1633

PR welcome :) (against the 3.1.x branch)
Note that the `rejectattr` docstring has the same issue.

**Comment by lindhe** [comment]
Ah, there it is! Thank you. PR coming soon!
