### ISSUE TITLE
`StrictUndefined` and `{% if foo is defined %}` disagree about whether a parameter set to `None` is defined

### ISSUE THREAD

**Issue by decathorpe** [pallets/jinja#2045]
I have something like this in my Jinja2 templates:

```
{% if something %}
{{ something }}
{% endif %}
```

When I define `something` to `None` when rendering the template, this works as expected. However, I would like to use `StrictUndefined` in my project to eliminate issues with potentially undefined parameters, and then this breaks, as using `StrictUndefined` seems to cause parameters that are defined to  `None` to be treated the same as if they were *not* defined at all.

When I change my template to this:

```
{% if something is defined %}
{{ something }}
{% endif %}
```

Then it will get rendered as:

```
None
```

So it looks like the using `StrictUndefined`  in the environment and checking whether a parameter is defined within the template disagree on whether `None` means the parameter is defined or not.

Environment:

- Python version: 3.13.0, 3.12.7, 3.11.10
- Jinja version: 3.1.4

**Comment by decathorpe** [comment]
As a workaround, I found that this works in combination with `StrictUndefined`:

```
{% if something is defined and something is not none %}
{{ something }}
{% endif %}
```

But as expected, this does not:

```
{% if something is not none %}
{{ something }}
{% endif %}
```

→ `jinja2.exceptions.UndefinedError: 'something is undefined`

**Comment by davidism** [comment]
Undefined means not passed at all. None is a value.

**Comment by decathorpe** [comment]
Yes, that's my point? `StrictUndefined` seems to interpret `dict(something=None)` the same as `dict()` when checking whether `something` is defined.

**Comment by ThiefMaster** [comment]
You can do `{% if something|default %}` to check for both defined and not falsy (or add `is not none` if you want a stricter check)

**Comment by davidism** [comment]
I think you're saying the opposite of what you're observing. Your workaround is nota workaround, it's exactly what needs to happen. Undefined is only for undefined variables, not for variables defined as none. If you don't define the variable and try to check if it's none, it's undefined. If you define it as none, it's not undefined.

**Comment by decathorpe** [comment]
> In your case, you want to check both.

Ok - but that's what I thought I was doing by using `Environment(undefined=StrictUndefined)` *and* checking the value for "truthiness" in the template? Why would I need to duplicate the `is defined` check if that's supposed to get checked by `StrictUndefined`?

And it still doesn't explain why using `Environment(undefined=StrictUndefined)` causes a different behaviour for checking whether something is defined than using `{% if something is defined %}` 😞

**Comment by decathorpe** [comment]
> No behavior is changing, defining a value as `None` means it's defined.

Yes, that is what I expect, and I understand that - but what I'm saying is that this is ***not*** what happens with `Environment(undefined=StrictUndefined)` - it causes values that are defined to `None` to be detected as undefined.

- pass `dict(something=None)`
- get `jinja2.exceptions.UndefinedError: 'something' is undefined`

**Comment by decathorpe** [comment]
*sigh* I changed something in my code that *should* be unrelated, and now the behaviour of `StrictUndefined` is suddenly as I expect it to be ... so, thank you for helping me with this, and sorry for the noise! 🙈
