### ISSUE TITLE
line_statement_prefix doesn't allow empty lines

### ISSUE THREAD

**Issue by aspiers** [pallets/jinja#205]
If I set

```
line_statement_prefix="%%"
```

in my environment, and then include in my template

```
%%
```

I get a `tag name expected` error.  As per #52, it would be much more useful behaviour to ignore the line entirely, since this would allow increasing legibility of multiple consecutive line statements by separating them with a "%%" line.

See also #204.

**Comment by davidism** [comment]
This is solved by line comments.
