### ISSUE TITLE
{% with %} syntax - u'with' expected at least one variable assignment

### ISSUE THREAD

**Issue by foxx** [pallets/jinja#208]
In the docs it states to use:

```
{% with foo = 42 %}
lol
{% endwith %}
```

However this does not work and results in the following exception;

```
TemplateSyntaxError: u'with' expected at least one variable assignment
```

To fix this, you need to remove the space between each side of the = sign, for example;

```
{% with foo=42 %}
lol
{% endwith %}
```

Requires a docs fix

**Comment by aldo123** [comment]
Nice Fix, worked for me!
