### ISSUE TITLE
PrefixLoader does not pass globals to load (with fix)

### ISSUE THREAD

**Issue by duxiaoyao** [pallets/jinja#225]
After upgraded to 2.7, my app got an error: 
UndefinedError: 'static_url' is undefined
where 'static_url' is a global function. And this worked before the upgrade.

It works after changing line 352 in loaders.py as below:
return loader.load(environment, local_name)
=>
return loader.load(environment, local_name, globals)

**Comment by davidism** [comment]
Fixed in 2.7.2, 701e9ada2b6968cf2bc41a3c1d4235922ce164f5
