### ISSUE TITLE
Include Null Master Fallback recursion exceeded

### ISSUE THREAD

**Issue by teddybear** [pallets/jinja#237]
There is might be regression in migrate from 2.6→2.7:

Let's assume we have two templates that both have 
`{% extends  'layout' %}` , `{% block head %}` and `{% block content %}`.
One of them have the [Null Master Fallback](http://jinja.pocoo.org/docs/tricks/#null-master-fallback) like this:

``` jinja2
{% if request.path == url_for(view') %}{% extends "main/layout.html" %}{% endif -%}
```

And in another one we include this template like this:

```
{% block content %}
//...
{% include 'view.html' %}
{% endblock content %}
```

In 2.6 this works great, but in jinja 2.7 there is error:

```
RuntimeError
RuntimeError: maximum recursion depth exceeded in __instancecheck__
```

Is this a bug, or i'm must rewrite the code? And if the answer is "rewrite it", how to do this?

**Comment by mitsuhiko** [comment]
Not actually sure if this is correct.

**Comment by davidism** [comment]
I can't reproduce this issue as described, although it was difficult to understand your template layout based on the brief snippets provided. If you believe this is still an issue, please provide a minimal reproducible example.

I created the following templates:

`layout.txt`

```
head
{% block content %}{% endblock %}
foot
```

`view-fallback.txt`

```
{% if path == "view" %}{% extends "layout.txt" %}{% endif %}
{% block content %}
fallback
{% endblock %}
```

`view.txt`

```
{% extends "layout.txt" %}
{% block content %}
{% include "view-fallback.txt" %}
{% endblock %}
```

Rendering `view.txt` or `view-fallback.txt`, with or without passing `path="view"`, all succeeded.
