### ISSUE TITLE
Loop properties revindex and revindex0 not behaving correctly in Jinja2 2.7

### ISSUE THREAD

**Issue by yawor** [pallets/jinja#244]
In Jinja2 2.7 both `loop.revindex` and `loop.revindex0` give incorrect values.

`loop.revindex` should be 1-based, but instead is 0-based.
`loop.revindex0` should be 0-based, but instead is -1-based (it has value -1 in last loop iteration).

**Comment by unusual-thoughts** [comment]
This appears to be still wrong when length of the iterator/sequence is 1:
```python
 >>> jinja2.Template("{% for i in lst|reverse %}{{ loop.revindex }}:{{ i }}, {% endfor %}").render(lst=[10,11])
'2:11, 1:10, '

>>> jinja2.Template("{% for i in lst|reverse %}{{ loop.revindex }}:{{ i }}, {% endfor %}").render(lst=[10])
'2:10, '
```
(Should be `1:10, `)

**Comment by davidism** [comment]
Please open a new issue to track this.
