### ISSUE TITLE
Filter implementation is limited (only values are passed to filters)

### ISSUE THREAD

**Issue by dagwieers** [pallets/jinja#245]
For the Ansible project we would like to have a filter to indicate whether a variable should be _mandatory_. This means that if a variable used in a template is not defined, it should bail out.

An implementation of such a _mandatory_ filter is in ansible/ansible#3375 but the problem here is that the filter only gets the value passed, not anything else from the context of where the filter has run.

What would be useful in this case would be at least the variable name that was passed (if any), but also the file and/or line number of where the filter is called. So an extension to the filter plugin API would be very useful for other types of filters.

**Comment by davidism** [comment]
Closing due to age and lack of movement. I'm not clear what could be done at this point to accomplish what's being asked, but as Armin points out you can check the `Undefined` object as well as scan the AST before compiling.
