### ISSUE TITLE
Allow to groupby without loosing sort order

### ISSUE THREAD

**Issue by palmkevin** [pallets/jinja#250]
Currently, you cannot group sorted lists using `groupby` without loosing the sort order of the list.
This is because jinja's `groupby` method uses the method `sorted`.

Here an example template:

    {% set l = [{'c': 3, 'result': 1.0},
                {'c': 3, 'result': 2.0},
                {'c': 9, 'result': 3.0},
                {'c': 1, 'result': 4.0}] %}
    {% for d in l|groupby('c') %}
        {{d}}
    {% endfor %}

Unfortunately, this templates outputs:

    (1, [{'c': 1, 'result': 4.0}])
    (3, [{'c': 3, 'result': 1.0}, {'c': 3, 'result': 2.0}])
    (9, [{'c': 9, 'result': 3.0}])

But what I was expecting is:

    (3, [{'c': 3, 'result': 1.0}, {'c': 3, 'result': 2.0}])
    (9, [{'c': 9, 'result': 3.0}])
    (1, [{'c': 1, 'result': 4.0}])

It would be smart if the `groupby`-filter would have an optional attribute `sortKeys=True` that could be used to switch automatic re-ordering off.

**Comment by yawor** [comment]
I would also like to see a `groupby` filter do only what it should do because now it does to much. The collection can already be sorted by the key but in some specific order (for example the can may not be in alphabetical order) and current functionality breaks that order.

`groupby` should only be a simple wrapper over `itertools.groupby` and current functionality can be achieved by stacking `sort` and `groupby` filters:

```
{% for grouper, items in collection|sort(attribute='foo.bar')|groupby('foo.bar') %}
{% endfor %}
```

**Comment by jeffwidman** [comment]
I'm a fan of cleaning this up. Since it's a backwards incompatible change, it'll have to wait until the next major version.

**Comment by untitaker** [comment]
@jeffwidman The current behavior is *not* consistent with `itertools`.

**Comment by untitaker** [comment]
OTOH this does make sense: https://github.com/pallets/jinja/pull/430#issuecomment-127755500

**Comment by jeffwidman** [comment]
I'm not at all opposed to switching to an unsorted `groupby`, as long as it behaved more like SQL's `GROUP BY` rather than `itertools.groupby`. I think that's the most intuitive solution to someone using Jinja without a Python background.
