### ISSUE TITLE
Template imported twice when using only one loader

### ISSUE THREAD

**Issue by jchoude** [pallets/jinja#255]
Currently starting out with Jinja2, and testing with a simple setup. I would expect a template found in my `templates` directory to be loaded only once, but it gets loaded twice. A simple test case follows.

 Let's say the application is called `report_generator`, with the following directory structure:

<pre>
report_generator/
  report_generator.py
  templates/
    base.html
</pre>

`base.html` is a very simple HTML template, without any tag. The code included in `report_generator.py` is as follows:

```
from jinja2 import Environment, PackageLoader
env = Environment(loader=PackageLoader('report_generator', 'templates'))
print env.list_templates()
```

When I run `report_generator.py`, I get the following output:

<pre>
['base.html']
['base.html']
</pre>

which seems to indicate that the template was found 2 times, even though it only is present once.

Is this a bug or an oversight on my part?

**Comment by chapsticks** [comment]
twice too

**Comment by chapsticks** [comment]
me too
