### ISSUE TITLE
Command line client?

### ISSUE THREAD

**Issue by tebeka** [pallets/jinja#258]
I wrote a little utility to expand Jinja templates from the command line - https://bitbucket.org/tebeka/pythonwise/src/tip/jj2.py?at=default.

Maybe we can incorporate it to Jinja? Either as a tool or as `__main__.py` module?

**Comment by cp10000** [comment]
I agree that there should be a command-line interface to use Jinja2.   The command-line should be done in a way that exposes all the features (no loss of features).   Today (2015), there are more reasons than ever to have a command-line interface.

**Comment by luzpaz** [comment]
:+1: for CLI

**Comment by jeffwidman** [comment]
I'm not sure I see enough value here to add this to the main repo versus just letting you maintain it in your own repo. It feels like a helper script that won't get used a lot, and those who really want it are somewhat likely to google and stumble across your repo.

> Flask has several options to load data into a config file (from_envvar, from_object, ...). I think it's a good idea to move these functions to a new package and use them in a CLI tool to load template variables.

Maybe I'm misunderstanding, but didn't we reject a similar idea over on Flask? https://github.com/pallets/flask/issues/1706

**Comment by kblomqvist** [comment]
I have made this kind of CLI tool, https://github.com/kblomqvist/yasha. I know there are others as well, but not as complete I think.

**Comment by davidism** [comment]
#129 is closed as well.  I'd rather go the route that @mitsuhiko suggests and @kblomqvist took: build the tool you need separately.  There's so much in Jinja that any official cli would either be massive or would be underpowered.  Instead, focus on the exact use case you need and build it with Jinja and Click.
