### ISSUE TITLE
template.module fails with StrictUndefined

### ISSUE THREAD

**Issue by gbach** [pallets/jinja#260]
This fails:

```
from jinja2 import Environment, FileSystemLoader, StrictUndefined, Undefined
from jinja2.environment import TemplateModule
from jinja2.exceptions import UndefinedError

env = Environment(loader=FileSystemLoader(".", "utf-8"),
              undefined=StrictUndefined)

tpl = env.get_template("test.html")

print dir(tpl.module)
```

... when using the following test.html:

``` html

{{ yay }}

{% macro yo() %}
    YO!
{% endmacro %}
```

This is because making the "module" involves rendering the complete template in the background. Since "StrictUndefined" is used and "yay" can not be passed to this process it fails.
The following patch solves this problem:

Add this to "environment.py":

```
class _NeverFailValue(object):
    def __call__(self, *args, **kwargs): return self
    def __str__(self): return ""
    def __repr__(self): return ""
    def __getitem__(self, key): return self
    def __getattr__(self, key): return self
    def __cmp__(self, other): return 0
    def __len__(self): return 0
    def __iter__(self): return self
    def next(self): raise StopIteration

class _NeverFailData(object):
    def __getitem__(self, key):
        return _NeverFailValue()
    def __contains__(self, key):
        return True
```

and modify the "make_module" method:

```
def make_module(self):
    vars = _NeverFailData()
    shared = True # so we get vars passed to the Context
    locals = None
    return TemplateModule(self, self.new_context(vars, shared, locals))
```

**Comment by mitsuhiko** [comment]
Not sure if this would come up in practice. Closing this down unless reopened with some reasons about why this comes up.

**Comment by ThiefMaster** [comment]
I usually use a separate `_foo.html` file that contains only macros to avoid executing "out-of-macro" code when building a template module to call a macro from Python code.

However, it would be nice if `tpl.module` simply ignored anything outside macros. Doing so would also avoid any issues with whatever Undefined implementation is used (unless the macro itself is trying to use something undefined, which usually shouldn't be the case).

**Comment by mitsuhiko** [comment]
@ThiefMaster however why is there stuff in the first place. I mean undefines are clearly not the only issue there :)

**Comment by ThiefMaster** [comment]
With the separate html file there isn't - but for the simplest (and probably most common) case for `.module` where you just want to re-render something via AJAX it would often be nicer to have it in the same template, e.g. something like this:

```
{% macro row(item) %}
    <tr>...</tr>
{% endmacro %}

<table id=items>
    {% for x in items %}{{ row(x) }}{% endfor %}
</table>
```

**Comment by mitsuhiko** [comment]
That's intentionally not supported though. You cannot import from files that also have other shit going on.

**Comment by mitsuhiko** [comment]
I mean, if we want to support that we need a complete new compiler mode that also has some other potential disadvantages: eg: conditional macro defines.
