### ISSUE TITLE
How to pass varargs and kwargs to a block?

### ISSUE THREAD

**Issue by iurisilvio** [pallets/jinja#270]
I want to wrap flask-assets filter and it uses varargs.
```
{% macro my_macro(output) -%}
    {% assets output=output, 'base_css', *varargs -%}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
    {%- endassets %}
{%- endmacro %}
```

The `*varargs` doesn't work. How should I do this?

**Comment by jeffwidman** [comment]
This sounds like a question rather than a bug report. Please ask questions like this on StackOverflow. If you think you're hitting a bug, then feel free to open an issue here.
