### ISSUE TITLE
Documentation: Make it clear string methods are available

### ISSUE THREAD

**Issue by pas256** [pallets/jinja#273]
Based on:

https://github.com/mitsuhiko/jinja2/pull/247

Plain string methods are available on string variables. Please make this abundantly clear in the documentation:

http://jinja.pocoo.org/docs/templates/

**Comment by jeffwidman** [comment]
@pas256 Mind submitting a PR with your suggested improvements?

**Comment by kojiromike** [comment]
It's hard to say what would be a good writeup of the issue. The documentation says things like

> …don’t use builtin Python constructs such as str.format or the string modulo operator (%).

That clearly imply it's _possible_ to use builtin Python constructs (such as the ever popular `str.split`), but afaict it's never explicitly said anywhere that such Python constructs are allowed.

**Comment by edgan** [comment]
I was already using python methods in my jinja from having run across examples, but I just realized that it wasn't just the few I was already using. This is huge, and opens doors I didn't know existed. There should be a dedicated section with examples.
