### ISSUE TITLE
Wrong line number for UndefinedError exceptions

### ISSUE THREAD

**Issue by terminalmage** [pallets/jinja#276]
When using `jinja2.StrictUndefined` and rendering a template, the line numbers seem to be off when an `UndefinedError` exception is triggered:

``` python
Python 2.7.5 (default, Sep  6 2013, 09:55:21)
[GCC 4.8.1 20130725 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> template = '''Hello world!
... {{ missing }}
... {{ exists }}
... '''
>>> jinja_env = jinja2.Environment(undefined=jinja2.StrictUndefined)
>>> print jinja_env.from_string(template).render(exists='foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
jinja2.exceptions.UndefinedError: 'missing' is undefined
```

The `missing` variable is on line 2, not line 3. However, when the variables are properly defined, the value for the `missing` variable is on line 2 like you would expect.

``` python
>>> print jinja_env.from_string(template).render(exists='foo', missing='bar')
Hello world!
bar
foo
>>>
```

The same line number mismatch is seen when loading the template from a file, as well:

``` python
Python 2.7.5 (default, Sep  6 2013, 09:55:21)
[GCC 4.8.1 20130725 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> jinja_env = jinja2.Environment(loader=jinja2.FileSystemLoader('/home/erik'), undefined=jinja2.StrictUndefined)
>>> print jinja_env.get_template('template.txt').render(exists='foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/erik/template.txt", line 3, in top-level template code
    {{ exists }}
jinja2.exceptions.UndefinedError: 'missing' is undefined
```

So, `missing` is undefined, yet the traceback shows the `exists` line.

The above testing was done using version 2.7.1.

**Comment by warvariuc** [comment]
+1

**Comment by rbjorklin** [comment]
@terminalmage I'm not sure I understand this issue and actually stumbled over here from [this saltstack issue](https://github.com/saltstack/salt/issues/29028) where I seem to get the line number as can be seen [in my comment](https://github.com/saltstack/salt/issues/29028#issuecomment-227386511). Is this what you were looking for?

**Comment by terminalmage** [comment]
@rbjorklin I think you misread this issue. The problem isn't that jinja doesn't give a line number (a perusal of my original post will show you that it does), the problem is that it gives the *wrong* line number, for reasons upon which others have elaborated.

**Comment by cachedout** [comment]
+1

**Comment by quantus** [comment]
I think I hit this same issue with Raven where the stack information collection fails if the call stack contains jinja templates. The wrong line numbers cause `inspect` module functions raise unexpected exceptions. I reported the issue there: https://github.com/getsentry/raven-python/issues/1133

**Comment by kinow** [comment]
Proposed fix in the PR linked above :point_up:. Hoping to pass the builds on Azure now :crossed_fingers:

**Comment by terminalmage** [comment]
@davidism Thanks!
