### ISSUE TITLE
i18n + utf-8 encoded PO

### ISSUE THREAD

**Issue by smari** [pallets/jinja#277]
Hi! I'm using UTF-8 encoded PO/MO files with Gettext, and in a template saying:

`{{gettext("message")}}`

This yields 

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)`

when using languages where "message"'s translation contains non-ascii characters. 

Setting Jinja2/i18n up with:
```
    env = Environment(loader=FileSystemLoader('%s' % theme_path),
                      extensions=['jinja2.ext.i18n', 'jinja2.ext.with_',
                                  'mailpile.jinjaextensions.MailpileCommand'])
    env.install_gettext_translations(config.get_i18n_translation(), newstyle=True)
```
and config.get_i18n_translation essentially returns: `gettext.translation("mailpile", "locale", [language])`

Not sure how to fix this, but it appears to be a Jinja-side bug, since I'm not having problems when I use gettext() directly elsewhere (outside of the templating)..

**Comment by jeffwidman** [comment]
This issue is old enough that I'm not sure it's still valid, and since it only shows up when the PO file is misconfigured, I think it can safely be closed. If someone runs across it in the future, feel free to comment and we can re-open and take a closer look.
