### ISSUE TITLE
map() filter returns string "<generator object do_map at 0x10bd730>"

### ISSUE THREAD

**Issue by l1k** [pallets/jinja#288]
Let zonelist be a data structure like this:

```
[{'zones': ['pe.com', 'ps.de', 'p-s.de'], 'file': 'gm'},
 {'zones': ['p-e.net', 'ps.net', 'p-s.net'], 'file': 'grpc'}]
```

When using zonelist|map(attribute='file'), a string like this is returned:

```
<generator object do_map at 0x10bd730>
```

Expected behaviour would be to return a list containing the 'file' attributes of zonelist.

As it turns out there's a workaround: Using e.g. zonelist|map(attribute='file')<b>|list</b> or zonelist|map(attribute='file')<b>|sort</b> will result in the expected list:

```
[gm, grpc]
```

I'm using Jinja 2.7.1 with Ansible 1.4.3.

**Comment by jaytaylor** [comment]
I didn't know about the `{{ ... | list }}` solution for the ansbile `<generator object do_map at 0x1079f56e0>` issue.

Thanks for filing this!
