### ISSUE TITLE
wordwrap filter does not use Environment.newline_sequence

### ISSUE THREAD

**Issue by sevas** [pallets/jinja#29]
When setting the `newline_sequence` environment parameter to, say `\r\n`, and if the `wordwrap` filter is used,  the resulting file contains a mix of `\n` and `\r\n`, which, imo, isn't an acceptable behavior.

I'm not sure if this is a design decision and if there is a rationale behind it. In any case, a patch (sevas/jinja2@218cb643136134da17526e01a42c30a4c71f27ba) is available in the branch 'wordwrap-newline' of my fork.

A pull request has been initiated.

**Comment by tbnorth** [comment]
This is definitely fixed now (2019-05-06):
```python
import jinja2
plates = {'plate': "{{ data | wordwrap }}"}
data = " ".join(["Here's some text."]*40)
length = []
for eol in ('\n', '\r', '\r\n'):
    env = jinja2.Environment(
        loader=jinja2.DictLoader(plates),
        newline_sequence=eol,
    )
    template = env.get_template('plate')
    context = dict(data=data)
    length.append(len(template.render(context)))
print(length)
# [719, 719, 728]
```
