### ISSUE TITLE
Problem with the sort filter in Python 3.x

### ISSUE THREAD

**Issue by jpoppe** [pallets/jinja#355]
To reproduce:
```python
from jinja2 import Template
items = [{'a': 'bla', 'b': 'baa'}, {'c': 'cla', 'd': 'daa'}]
t = Template("Hello {{ bug|sort }}!")
t.render(bug=items)
```
In python 3.x this will throw: TypeError: unorderable types: dict() < dict()

For more information and an explanation see:
http://stackoverflow.com/questions/22333388/dicts-are-not-orderable-in-python-3

Line where it goes wrong:
https://github.com/mitsuhiko/jinja2/blob/master/jinja2/filters.py#L264

**Comment by ThiefMaster** [comment]
Makes sense in my opinion. Trying to sort a dict, which gives you just its keys when iterating it, doesn't make lots of sense. Why not get its `.items()` or use `|dictsort` instead?

**Comment by jpoppe** [comment]
I have used a different approach, but I filed the ticket because this raises an exception on Python 3, and not on Python 2. I don't think that is the desired result.

**Comment by jeffwidman** [comment]
I agree @ThiefMaster, doesn't make sense to be able to compare two dicts. If anything, the desired result is raising an exception on Py2 as well. But I'm not really a fan of that either, I'd rather just let Py2 do it's thing.
