### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'gettext' is undefined

### ISSUE THREAD

**Issue by njouanin** [pallets/jinja#363]
I'm using Jinja2 2.7.3 inderectly through pelican and I get this error with templates using {% trans% } directive.
So be sure it's not related to pelican, i've created this small test file (https://gist.github.com/njouanin/36292368ad15f9b87ba0). When I run it with python interpreter (3.4.1) I get the following exception : 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nico/Brassage/Beerfactory/env-site/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/nico/Brassage/Beerfactory/env-site/lib/python3.4/site-packages/jinja2/environment.py",     line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nico/Brassage/Beerfactory/env-site/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "theme/templates/base.html", line 50, in <module>
    {% block header_left_section %}
  File "theme/templates/base.html", line 60, in <module>
    <h2 id="site-description">{{ gettext('Brasser libre !') }}</h2><!-- #site-description -->
jinja2.exceptions.UndefinedError: 'gettext' is undefined
```

I've googled this issue which appear to be related to gettext library which is missing. Here importing gettext module in python works fine, so I guess it is installed.
Here is my environnement : 
MacOs 10.9
Python 3.4.1
Jinja2 : 2.7.3

**Comment by thijstriemstra** [comment]
Also running into this using Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) on OSX 10.7.5.

**Comment by fabiankreutz** [comment]
The i18n extension of Jinja adds a function `install_gettext_translations` into the environment: http://jinja.pocoo.org/docs/dev/extensions/#i18n-extension
That must be called with the i18n backend that you want to use (python gettext, google app's webapp2_extras.i18n or babel):
```python
from jinja2 import Environment
import gettext

env = Environment(extensions=['jinja2.ext.i18n'])
env.install_gettext_translations(gettext.GNUTranslations)
print(env.from_string(...))
```

**Comment by SkyzohKey** [comment]
As anyone found an idea for this on Pelican ?

**Comment by mixmastamyk** [comment]
Getting this on Linux with pelican-bootstrap3 theme.  What is the workaround?

**Comment by smartass101** [comment]
Not sure if this is related, but maybe `jinja2.Environment.install_gettext_callables` is required in addition to `install_gettext_translations`?

**Comment by greyli** [comment]
I got the same issue when using Jinja2 2.10 with Python 2.7 on Windows7.

**Comment by mitsuhiko** [comment]
I'm going to close this issue. This happens if the i18n extension is installed but no gettext function is provided. This is a configuration problem of whatever integrated Jinja into a project.

**Comment by davidism** [comment]
You (or the library that's configuring Jinja for you) need to install the gettext functions after enabling the i18n extension. This is shown in the docs https://jinja.palletsprojects.com/en/3.0.x/extensions/#i18n-extension

```python
translations = get_gettext_translations()
env = Environment(extensions=["jinja2.ext.i18n"])
env.install_gettext_translations(translations, newstyle=True)
```
