### ISSUE TITLE
Truncate filter returns longer string than specified

### ISSUE THREAD

**Issue by jkhradil** [pallets/jinja#369]
Calling do_truncate function like this:

``` python
jinja2.filters.do_truncate("1234567890asd", 10)
```

returns 11 characters

```
'1234567 ...'
```

I suggest not adding adding a space between truncated string and an ellipsis as there is not much of a reason to do so.

Possible implementation follows:

``` python
def do_truncate(s, length=255, killwords=False, end='...'):

...

    if len(s) <= length:
        return s
    elif killwords:
        return s[:length - len(end)] + end

    result = s[:length - len(end)]
    # Make sure we don't overtruncate the string
    if s[length - len(end)] != ' ':
        result = result.rsplit(' ', 1)[0]
    return result + end
```

**Comment by jab** [comment]
> Calling do_truncate function like this:
> jinja2.filters.do_truncate("1234567890asd", 10)
> returns 11 characters
> '1234567 ...'

Looks like this has been fixed:

> In [6]: filters.do_truncate('1234567890asd', 10, True)
> Out[6]: '1234567...'

**Comment by ricky-undeadcoders** [comment]
The space following the ellipsis has been removed as of 2.10. This can be closed.
