### ISSUE TITLE
Cannot mark input values into trans block as safe in auto escaped environment

### ISSUE THREAD

**Issue by dwt** [pallets/jinja#373]
Hi there,

I just noticed that I wasn't able to mark a value in a trans block as safe in an auto escaped environment.

For example: `{% trans foo='<foo>'|safe %}bar{{foo}}bar{% endtrans %}` results in `bar&lt;foo&gt;bar` instead of in `bar<foo>bar` as I would have expected.

wrapping the whole block in an `{% autoescape false %}` block allowed me to work around this issue for now, but it seems wrong, as the whole block is not something I want to remove from auto escaping, for example because it could contain other variables which should be escaped.

So, is this a bug in jinja2 or am I somehow using it wrong?

**Comment by davidism** [comment]
I can't reproduce this issue. Marking a variable as safe in the tag seems to work for both standard and new-style gettext.
