### ISSUE TITLE
problems with inspect.stack

### ISSUE THREAD

**Issue by apollo13** [pallets/jinja#38]
If someone traverses the stack with _inspect.stack_ one can get ugly errors like this one: http://paste.pocoo.org/show/398237/ This is caused by _inspect.stack_ which tries to match the current linenumber of the code object to a line in the file that's attached to the code object. Now if Jinja is in the stack the code objects will have the html file as filename, which are usually way smaller than the generated pythoncode which was used to compile this code object -- which causes and IndexError. Not sure if you consider that as _inspect.stack_ bug, but it would be great if jinja could somehow work around this…

http://apolloner.eu/~apollo13/testing.tar is a small django/jinja/django-debug-toolbar project which shows the problem…

**Comment by mitsuhiko** [comment]
This is unlikely to change.
