### ISSUE TITLE
State of block sets

### ISSUE THREAD

**Issue by Garito** [pallets/jinja#382]
Hi!
According with this: http://jinja.pocoo.org/docs/dev/templates/#block-assignments it is possible to asign blocks to variables but I could check that it doesn't work @ Jinja2==2.8-devdev-20141113

It doesn't crash but the variable seems empty

am i correct?
Did you know any news about this stuff?

Thanks

**Comment by ThiefMaster** [comment]
```
>>> env = Environment()
>>> env.from_string('{% set foo %}bar{% endset -%} foo={{ foo }}').render()
'foo=bar'
```

Works fine for me with the current Git version; there's even [a testcase](https://github.com/mitsuhiko/jinja2/blob/master/jinja2/testsuite/core_tags.py#L310) for it.

Do you have any code reproducing the issue?

**Comment by Garito** [comment]
Sorry, has been kind of 3 month since I publish this issue
As you can expect I solve my needs in other ways so I don't have the code

**Comment by clj** [comment]
I have just seen what is perhaps the same oddness that @Garito initially reported.

Assignments within a single template works as I would expect and as @ThiefMaster showed, however when using template inheritance the block assignments no longer work consistently as they do when not using template inheritance. Testing done using version Jinja2 2.8 from PyPi.

### Single template

This all works:
```python
from jinja2 import Environment

env = Environment()

# Assignment and block assignment without blocks work as I would expect
print(env.from_string(
    '''1: {% set assignment="ASSIGN" %}{% set block_assignment %}BLOCK{% endset -%}
       block_assignment={{ block_assignment }},assignment={{ assignment }}
    ''').render())

# Assignment outisde a block and use inside a block work as I would expect
print(env.from_string(
    '''2: {% set assignment="ASSIGN" %}{% set block_assignment %}BLOCK{% endset -%}
       {% block a %}block_assignment={{ block_assignment }},assignment={{ assignment }}{% endblock %}
    ''').render())

# Assingment inside a block and use inside another block, assignments have gone
# out of scope which makes sense
print(env.from_string(
    '''3: {% block a %}{% set assignment="ASSIGN" %}{% set block_assignment %}BLOCK{% endset %}{% endblock -%}
       {% block b %}block_assignment={{ block_assignment }},assignment={{ assignment }}{% endblock %}
    ''').render())
```

and outputs the following:
```
1: block_assignment=BLOCK,assignment=ASSIGN

2: block_assignment=BLOCK,assignment=ASSIGN

3: block_assignment=,assignment=
```

### Template inheritance

When using template inheritance however, things change:

```python
from jinja2 import Environment
from jinja2 import DictLoader
loader = DictLoader({
    'base': '{% block content %}{% endblock %}',
    'main': '''{% extends "base" -%}
               {% set assignment="ASSIGN" %}{% set block_assignment %}BLOCK{% endset -%}
               {% block content %}block_assignment={{ block_assignment }},assignment={{ assignment }}{% endblock %}'})
            '''})
env = Environment(loader=loader)
print(env.get_template('main').render())
```

which produces:
```
block_assignment=,assignment=ASSIGN
```

which I would expect to produce the same output as case 2 above.

**Comment by eshlox** [comment]
It works when block assignment is set before extends tag.

```
from jinja2 import Environment
from jinja2 import DictLoader

loader = DictLoader({
    'base': '{% block content %}{% endblock %}',
    'main': '''
        {% set assignment="ASSIGN" %}{% set block_assignment %}BLOCK{% endset -%}
        {% extends "base" -%}
        {% block content %}block_assignment={{ block_assignment }},assignment={{ assignment }}{% endblock %}'})
    '''
})
env = Environment(loader=loader)
print(env.get_template('main').render())
```

Output:

```
block_assignment=BLOCK,assignment=ASSIGN
```

Of course it's not a solution for that issue. The extends tag should be the first tag in the template so this is only an example or quick workaround if someone needs that.

**Comment by davidism** [comment]
#596
