### ISSUE TITLE
Tests fail under pypy/pypy3 due to reliance on garbage collection policies.

### ISSUE THREAD

**Issue by amcgregor** [pallets/jinja#384]
https://github.com/mitsuhiko/jinja2/blob/master/jinja2/testsuite/utils.py#L59-L70 duplicates the test from markupsafe pretty much exactly; like markupsafe#39 this is corrected by the conditional execution of `gc.collect()` prior to the addition of the count.

Same argument that this is testing runtime garbage collection policy is is a bit of a non-portable test.

Downstream bug: https://bugs.gentoo.org/show_bug.cgi?id=529934

**Comment by davidism** [comment]
Markup tests seem to have been removed some time ago.
