### ISSUE TITLE
how to print bellow json data using loop in template html

### ISSUE THREAD

**Issue by satyanani40** [pallets/jinja#390]
{
  "Website": {
    "color": "#16a085",
    "type": "module",
    "icon": "icon-globe"
  },
  "Core": {
    "color": "#589494",
    "type": "module",
    "system_manager": 1,
    "icon": "icon-cog"
  },
  "To Do": {
    "color": "#f1c40f",
    "doctype": "ToDo",
    "label": "To Do",
    "link": "List\/ToDo",
    "type": "list",
    "icon": "icon-check"
  },
  "Setup": {
    "color": "#bdc3c7",
    "type": "module",
    "icon": "icon-wrench"
  },
  "Messages": {
    "color": "#9b59b6",
    "type": "page",
    "label": "Messages",
    "link": "messages",
    "icon": "icon-comments"
  },
  "Installer": {
    "color": "#888",
    "type": "page",
    "label": "Installer",
    "link": "applications",
    "icon": "icon-download"
  },
  "Calendar": {
    "color": "#2980b9",
    "type": "view",
    "label": "Calendar",
    "link": "Calendar\/Event",
    "icon": "icon-calendar"
  }
}

**Comment by skatkar** [comment]
I have a JSON data like this:
{
	'messages': 
	[
		{'text': 'hello', 'author_id': 1, 'pub_date': 1518506778, 'message_id': 1}, 
		{'text': 'hell', 'author_id': 2, 'pub_date': 1518420378, 'message_id': 2}, 
	]
}

How can I display it in Jinja template? I tried above mentioned method but its not working.
