### ISSUE TITLE
Documentation has 'not' jokes.

### ISSUE THREAD

**Issue by pudo** [pallets/jinja#393]
![screen shot 2014-12-22 at 12 17 36](https://cloud.githubusercontent.com/assets/41628/5524387/9e3a133e-89d4-11e4-86b2-db1559c58d6a.png)

[source](http://jinja.pocoo.org/docs/dev/templates/#import-context-behavior).
:smile:

**Comment by ksaylor11** [comment]
ditto.

**Comment by davidism** [comment]
This was fixed in #389
