### ISSUE TITLE
base.html examples in docs appears to contain broken HTML

### ISSUE THREAD

**Issue by faassen** [pallets/jinja#394]
The base.html example here:

http://jinja.pocoo.org/docs/dev/templates/#base-template

appears to contain some broken HTML in the form of a duplicated html tag:

```
<html lang="en">
<html xmlns="http://www.w3.org/1999/xhtml">
```

and no closing `</html>` tag either.

**Comment by esonderegger** [comment]
I just created a pull request (https://github.com/mitsuhiko/jinja2/pull/395) that should fix this.

This is my first time submitting a pull request to a major project. Please let me know if I did everything right.
