### ISSUE TITLE
It seems that a macro files must be end with ".html"

### ISSUE THREAD

**Issue by xiechao06** [pallets/jinja#409]
for example, if I put this macro

``` html
{% macro foo() -%}
    <div>foo</div>
{% endmacro %}
```

in a file named "macros.jinja2", and the template file is like: 

``` html
{% from "macros.jinja2" import foo %}
<body>
{{ foo() }}
</body>
```

 then the macro will be expanded as a string. the produced html is like:

``` html
<body>
"
    <div>foo</div>
"
</body>
```

I known it may sound silly to name a macro file as "xxx.jinja2", please update the document at least.

**Comment by mitsuhiko** [comment]
This has nothing to do with Jinja but the configuration of the autoescape settings you have configured (or the framework where JInja is included).
