### ISSUE TITLE
jinja2.loaders: split_template_path doesn't respect absolute Windows paths

### ISSUE THREAD

**Issue by eddieparker** [pallets/jinja#412]
In split_template_path, if the path you're passing in has a hardcoded path like "C:\\Foo\\Bar\\Baz", you get back pieces that look like "C:", "Foo", "Bar", "Baz".

It's then passed back into FileSystemLoader.get_source's "path.join" call, which will give you a string that looks like:

"C:Foo\\Bar\\Baz".

The fix would involve seeing if the passed in path is a full path (path.isabs) and then prepending "\\" to the first piece (if the path doesn't start with a letter, i.e., "\\Foo\\Bar\\Baz" yields ["\\Foo", "Bar", "Baz"]), or the second piece (if the path starts with a letter and a colon, i.e., "C:\\foo\\bar\\baz" yields ["C:", "\\foo", "bar", "baz"])

**Comment by longfin** [comment]
IMHO, using `\` in template path is not intended.

https://github.com/mitsuhiko/jinja2/pull/99

> You should always be using / in templates no matter what OS.

**Comment by jeffwidman** [comment]
As well as https://github.com/pallets/jinja/pull/303#issuecomment-45543460
