### ISSUE TITLE
Rename killwords argument of truncate filter to something more definitive

### ISSUE THREAD

**Issue by Suor** [pallets/jinja#415]
kill = remove, so if `killwords=True` then partial words should be removed, yet they are cut. Even your docs examples confuse that - https://github.com/mitsuhiko/jinja2/pull/388. Plural also adds to confusion cause each time we deal with at most single border word.

I propose using `cutword` instead with a same meaning, can be done in backwards compatible way, just make `killwords` obsolete and make it as last argument and set `cutword` in its place.

**Comment by mitsuhiko** [comment]
It has been like this for years now, it's kinda late to rename it ;(
