### ISSUE TITLE
Python 3 compatibility of examples

### ISSUE THREAD

**Issue by untitaker** [pallets/jinja#416]
The documentation examples should work under both versions if feasible (and equally performant).

**Comment by techtonik** [comment]
http://jinja.pocoo.org/docs/dev/templates/#for

**Comment by kooky** [comment]
https://github.com/kooky/jinja2/commit/8033d4f59e1bae614556b52a63f6ee9ca8529fc8  is one fix.

**Comment by Cabalist** [comment]
I think this should be reevaluated as Python3 has a much higher acceptance rate these days.  Especially for beginners.  The pull request makes sense.

**Comment by davidism** [comment]
I would happily accept PRs that make examples work in 2 and 3. It doesn't have to be everything in one go.

**Comment by techtonik** [comment]
One of the ways to fix this is to make examples run as a part of test suite.

**Comment by hugovk** [comment]
https://github.com/pallets/jinja/pull/1010 ("Python3-ize the examples") has been merged. Can this be closed?

**Comment by jab** [comment]
Looks like it, thanks for checking, @hugovk!
