### ISSUE TITLE
Is it possible to enforce all the variables in a template with a specific filter?

### ISSUE THREAD

**Issue by godsarmy** [pallets/jinja#422]
Hi

I am about to implement an application with jinja2. We developed a universal filter that should be applied to all the values in the template. So as a result, we have to write each of the variables in the template with a filter name like `{{my_variable|my_filter}}`. 

I wonder whether there is a way to enforce a filter to all the variables in the template. I looked into code, it seems extension can not fulfill my requirement. The only possible way is to monkeypatch `jinja2.parser.Parser.subparse`, then to change the line of `add_data`.

Do you think it is possible to have a new feature in jinja to make this scenario simpler? 

```
    elif token.type == 'variable_begin':
        next(self.stream)
        add_data(self.parse_tuple(with_condexpr=True))
        self.stream.expect('variable_end')
```

**Comment by davidism** [comment]
This seems like it should be handled by processing all variables before calling `render`. Or now that `finalize` only applies to the output of expressions, that might be another option depending on what you're trying to do.
