### ISSUE TITLE
Blocks inside If/Else and includes

### ISSUE THREAD

**Issue by DaNNaD** [pallets/jinja#423]
As I had to find out through <a href="https://stackoverflow.com/questions/22655031/jinja2-how-to-put-a-block-in-an-if-statemen">stackexchange</a> blocks ({% block %}) can not be inside a else/if block. This is really confusing -- never did I see anything that is not obeying an if statement -- especially since the documentation does not mention this. 

Another problem that I encountered which is (not clearly enough?) documented: if a block is embedded in a file, which is included, for example into base.html, which than is extended by index.html, the index.html can not modify the content of the mentioned block.

**Comment by RevengeComing** [comment]
i noticed i cant use blocks in a file included and expand it in extended file right now ... is it possible to be fixed ?

**Comment by ThiefMaster** [comment]
Please rewrite your issue using the provided template. It's there for a 
reason...

**Comment by RevengeComing** [comment]
Its the same issue as DaNNaD's issue ...
