### ISSUE TITLE
docs:  "Comparisons" section should be merged/added to "Builtin Tests"

### ISSUE THREAD

**Issue by alvaroaleman** [pallets/jinja#435]
Every item described inside [Comparisons](http://jinja.pocoo.org/docs/dev/templates/#comparisons) is a test. However, those items are not included in the [test section](http://jinja.pocoo.org/docs/dev/templates/#list-of-builtin-tests). 

This is quite counterintuitive and should be changed.

**Comment by untitaker** [comment]
That is not true. ["Test" has a special meaning in Jinja](http://jinja.pocoo.org/docs/dev/templates/#tests).

**Comment by alvaroaleman** [comment]
I do not agree here. Tests and comparisons may differ in how they are declared, but they have the exact same purpose: Be a test in a conditional statement.

If someone reads the docs and finds one of either tests or comparisons, he or she will be led to believe there are no other conditional statemens available.

**Comment by davidism** [comment]
I think this was addressed by #665, which added the missing comparison operators as tests.
