### ISSUE TITLE
Add pgettext function to i18n extension

### ISSUE THREAD

**Issue by razmig** [pallets/jinja#441]
I was wondering if there is any plan to add the pgettext extention

**Comment by schmilblick** [comment]
I was also looking in to this, I saw that it was mentioned in issue #328 that got closed.

**Comment by untitaker** [comment]
I think what Armin wanted to say in this issue is that patches are welcome.

**Comment by imomaliev** [comment]
I've finished PR for this feature, need someone to look at it and help me finalize things so that could be merged

**Comment by tvb** [comment]
@imomaliev any update?

**Comment by tvb** [comment]
@imomaliev Any update?

**Comment by tvb** [comment]
@imomaliev Any update on this?

**Comment by davidism** [comment]
@tvb please don't post "when will this come out" comments, they generate noise without contributing to the discussion.
