### ISSUE TITLE
StrictUndefined does not trigger exception for membership test in empty list

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [pallets/jinja#462]
``` python
import jinja2

jinja_env = jinja2.Environment()
jinja_env.undefined = jinja2.StrictUndefined

jinja_env.from_string('{{ zzz in [] }}').render()
# Somewhat surprisingly, it does not fail.

jinja_env.from_string('{{ zzz in [42] }}').render()
# As expected:
#   jinja2.exceptions.UndefinedError: 'zzz' is undefined
```

This happens because membership test for sequences is implemented as iteration over elements and comparison, so if the sequence is empty, comparison is never performed.

I suppose it can't be fixed with the current approach to StrictUndefined, just want to document this quirk for posterity.

**Comment by davidism** [comment]
Huh?  A list, empty or not, is defined.  `zzz in []` is a perfectly valid expression evaluating to `False`.

**Comment by mitsuhiko** [comment]
Yeah, we can't change that sadly. Closing here.
