### ISSUE TITLE
Missing documentation on "configuration"

### ISSUE THREAD

**Issue by lusitania** [pallets/jinja#463]
Hi

In the [Template Designer Documentation](http://jinja.pocoo.org/docs/dev/templates/#whitespace-control) it is said that

> If an application configures Jinja to trim_blocks...

However, I can't find any hint _how_ I can configure Jinja - neither on jinja.pocoo.org, nor on flask.pocoo.org nor via Google.

So my question is: How do I configure Jinja2 to accept trim_blocks/lstrip_blocks?

Best

Edit: Reading the code I've discovered this work around. Is this the way to go?

```
# in bootstrap
wsgi = Flask(__name__.split('.')[0])

wsgi.jinja_env.lstrip_blocks = True
wsgi.jinja_env.trim_blocks = True
```

**Comment by hackebrot** [comment]
From what I know you pass these settings to the ``Environment`` initialization.

See https://github.com/mitsuhiko/jinja2/blob/9b4b20aa56fde3a5cd5ac49d4feacd96eacb832d/jinja2/environment.py#L143

And https://github.com/mitsuhiko/jinja2/blob/master/tests/test_lexnparse.py#L444
