### ISSUE TITLE
Regression: int filter always returns 0 in 2.8, returned result of __int__() in 2.7.3

### ISSUE THREAD

**Issue by gsmethells** [pallets/jinja#466]
I am seeing a regression in my test suite since Jinja2 2.8 came out. I have in my template:

id="scope-stream-{{stream|int}}"

the stream instance has a ```__int__()``` dunder method. 

In Jinja 2.7.3 my template renders with:

id="scope-stream-2"

In Jinja 2.8 my template renders with:

id="scope-stream-0"

**Comment by snoack** [comment]
Reproduced ..and fixed. That was because `int()` always fails with a `TypeError` when an explicit base is specified, but the value isn't a string. Hence this regression where introduced by adding the optional `base` argument to the `int` filter.
