### ISSUE TITLE
Cycler object has no attribute 'next' in Python 3.4.3

### ISSUE THREAD

**Issue by tark-hidden** [pallets/jinja#474]
Python 3.4.3, Pyramid 1.5.7, Jinja 2.8 (2.7.3 produce the same error)

I got a weird exception

```
jinja2.exceptions.UndefinedError: 'jinja2.utils.Cycler object' has no attribute 'next'
```

in string

```
<li class='struct-item{{ row.next() }}' data-id="{{ category._id }}" 
data-owner="{{ category.owner }}">
```

template:

```
<ul>
{% set row = cycler('', ' back') %}
{% for category in categories[0] recursive %}
    <li class='struct-item{{ row.next() }}' data-id="{{ category._id }}" 
    data-owner="{{ category.owner }}">
        <div class="title">{{ category.caption }}</div>
        <div class="action">
            {% if not loop.depth0 %}
            <a href='#' class="category-add">
                <img src='/static/admin/img/action-add.png'>
             </a>
             {% endif %}
            <a href='#' class="category-edit">
                <img src='/static/admin/img/action-edit.png'>
            </a>
            <a href='#' class="category-delete">
                <img src='/static/admin/img/action-delete.png'>
            </a>
        </div>
    </li>
    {% if category._id in categories %}
        <ul class="children">{{ loop(categories[category._id]) }}</ul>
    {% endif %}
{% endfor %}
</ul>
```

When I make a call print(dir(self)) in a constructor Cycler, echo was

```
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', 
 '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', 
 '__module__', '__ne__', '__new__', '__next__', '__reduce__', '__reduce_ex__', 
 '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 
 'current', 'items', 'pos', 'reset']
```

that means Cycler object really has no `next` method. Temporary fix is `jinja2.utils.Cycler.next = jinja2.utils.Cycler.__next__` in a Pyramid`main` method, but...

**Comment by cmacmackin** [comment]
I can confirm this bug.

**Comment by tark-hidden** [comment]
Hey guys. This issue has been opened more than month ago.

This can be fixed by adding exactly the same function ``implements_iterator`` in code block ``if not PY2`` in ``_compat.py``. And... is there any reason for deleting ``cls.__next__`` in this code?

        def implements_iterator(cls):
            cls.next = cls.__next__
            del cls.__next__
            return cls

**Comment by ThiefMaster** [comment]
Could you create a PR (including a testcase that fails in Python 3 without the fix)? Seems to be pretty straightforward.

**Comment by tark-hidden** [comment]
Sorry... Seems like I cannot understand what are you talking about. Should I write the test which will fail without this fix? Or should I write some simple use case which raise a error?

In a current github release tests_api.py contains the code for testing Cycler a "right" iteration way.

    def test_cycler(self, env):
        items = 1, 2, 3
        c = Cycler(*items)
        for item in items + items:
            assert c.current == item
            assert next(c) == item
        next(c)
        assert c.current == 2
        c.reset()
        assert c.current == 1

You see? Here is next(c), not c.next() in http://jinja.pocoo.org/docs/dev/templates/#cycler . This test is passed in both cases.

**Comment by ThiefMaster** [comment]
I'm suggesting you to create a pull request to fix the bug - and such a PR should go along with a testcase so if the bug is ever re-introduced for some reason the test would fail.

**Comment by ThiefMaster** [comment]
Actually... maybe renaming `__next__` to `next` would be more appropriate? I don't think `cycler` objects are ever meant to be used as an actual iterator or with `next(cycler)`.

**Comment by tark-hidden** [comment]
I think, adding ``next = __next__`` is the best choice! :)

**Comment by tark-hidden** [comment]
And I'm very sorry, I was wrong. In Python 2.7.3 current release works fine, as expected.
