### ISSUE TITLE
Multiple caller-style arguments to macros

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/jinja#482]
E.g. like this:

```
{% macro form(footer) %}
    <form>
        {{ caller() }}
        <div class=footer>
            {{ footer }}
        </div>
    </form>
{% endmacro %}

{% call form(...) %}
    ...body...
{% arg 'footer' %}
   ...footer...
{% endcall %}
```

Especially for widget-like macros it would be very useful to be able to specify more than one block of HTML that's not as limited as a simply string argument. Of course one could use the new `{% set %}` block but that's a bit ugly if you use it multiple times

I'm not sure about the best syntax on how to do this, so if the idea itself is accepted (ping @mitsuhiko) and someone has a good suggestion syntax-wise I wouldn't mind having a look at implementing this and sending a PR

**Comment by donkopotamus** [comment]
I'd be very interested in seeing this implemented ... this is one of the [features][1] in mako that I very much miss in jinja2.

If we were to translate the equivalent mako implementation to jinja it would appear something like:

```
{% macro form(footer) %}
    <form>
        {{ caller() }}
        <div class=footer>
            {{ caller.footer() }}
        </div>
    </form>
{% endmacro %}

{% call form(...) %}
    ...body...
    {% macro footer() %}
       ...footer...
    {% endmacro %}
{% endcall %}
```

In mako, it seems that a macro within a call block (a `def` in mako parlance) gets lifted to become an attribute on the call block.  If my understanding is correct, this would not be appropriate in jinja, which treats the call block effectively as a macro, meaning the embedded macro is part of the local closure. 

What if there was some kind of tag, eg `submacro` or `attribute` that could be placed within a `call` (or `macro`!), and lifted its definition up to become an attribute on its container?

[1]: http://docs.makotemplates.org/en/latest/defs.html#calling-a-def-with-embedded-content-and-or-other-defs

**Comment by ThiefMaster** [comment]
That macro solution looks really strange. IMHO my `arg` idea is prettier. ;)

**Comment by donkopotamus** [comment]
I think I'm arguing for almost exactly your syntax, just with an end tag included :-), oh and I guess that it becomes an attribute on `caller`, rather than another named argument in the macro.  Making it an attribute on `caller` would help prevent clobbering the local namespace.

**Comment by ThiefMaster** [comment]
`caller.something()` sounds good; it makes a clearer difference between normal arguments and "block-like" arguments. Not a big fan of a `macro`-ish name though. Seems confusing to me.

**Comment by donkopotamus** [comment]
It feels like we are trying to meet an expected interface from the macro we are calling ... so what about something like `implement`, or `using`?

eg

```
{% call form(...) %}
    ...body...
    {% using footer() %}
       ...footer...
    {% endusing %}
{% endcall %}
```

**Comment by ThiefMaster** [comment]
```
{% call form(...) %}
    normal caller() stuff
    {% as footer %}
        caller.footer() stuff
    {% endas %}
{% endcall %}
```

That wouldn't look too bad IMO - you are already inside the caller, so you'd use the new block *as* the contents for caller.footer

**Comment by donkopotamus** [comment]
Good argument, I like `as`
