### ISSUE TITLE
Block Assignment Filters

### ISSUE THREAD

**Issue by eli-collins** [pallets/jinja#486]
2.8's block assignments have been incredibly useful, but I've found myself doing the following a lot...

``` jinja
{% set title %}
    <h1>{{ value }}</h1>
{% endset %}
{% set title = title | safe %}
```

Would it be possible to allow moving the filter call into the block assignment call, such as with the following syntax?

``` jinja
{% set title | safe %}
    <h1>{{ value }}</h1>
{% endset %}
```

(There might be a better / more generally flexible syntax, that's just the one that first occurred to me to try).

**Comment by ThiefMaster** [comment]
:+1:

**Comment by ThiefMaster** [comment]
Actually, the fact that you need to filter your set block as `safe` feels more like a bug to me since it results in double-escaped data *very* easily (which is something Jinja is usually pretty good at avoiding!).

Opened another issue about this: #490

**Comment by eli-collins** [comment]
#490 alone would definitely solve all my use-cases; if that was pushed through, I'd be happy whichever way you end up deciding this issue.  Without the frequent need to use a 'safe' filter, the block filter syntax is probably more than sufficient for the remaining edge cases that I can think of.
