### ISSUE TITLE
Bug: floats are arbitrarily rounded (no filters used)

### ISSUE THREAD

**Issue by aartur** [pallets/jinja#487]
Test case is just rendering a float:

```
$ python -c 'from jinja2 import Template; print Template("{{num}}").render(num=1441712583.216615)'
1441712583.22
```

4 last digits are not present and the last digits indicates rounding.

If I delete 3 last integer digits I get 5 rounded fraction digits (instead of full 6):

```
python -c 'from jinja2 import Template; print Template("{{num}}").render(num=1441712.216615)' 
1441712.21662
```

Unless I'm overlooking something stupid, it's a critical bug. I tested it on Jinja2 2.7.3 and 2.8.0 and CPython 2.7.6 and PyPy 2.6.1.

**Comment by aartur** [comment]
One possibility is that the floats are too big to be accurately represented but Python's __repr__ has no problems with them:

```
$ python -c 'print repr(1441712583.216615)'
1441712583.216615
```

**Comment by aartur** [comment]
Ok I found the reason: Jinja uses `str(float_val)` which does the rounding, while `repr(float_val)` has higher precision by a few digits. And since interactive Python shell uses `repr` to print values I expected Jinja to have the same precision.

So it probably isn't Jinja's bug, but weird Python's discrepancy. Maybe Jinja should use `repr`, but I see an explicit check for float:
```
def visit_Const(self, node, frame):
    val = node.value
    if isinstance(val, float):
        self.write(str(val))
    else:
        self.write(repr(val))
```

**Comment by darkryder** [comment]
Ping.
Could someone please tell why float values are being rendered using `str` and not `repr`?

**Comment by davidism** [comment]
@darkryder because Jinja uses `str` to render all values.  It doesn't (and shouldn't) have a special case for `float`.  If you need specific precision, use a `Decimal` instead.

**Comment by Skuzzzy** [comment]
@darkryder `str` is more appropriate to use in this case. Typically `str` is used for customer facing representations of objects while `repr` is typically used for dev/debugging. `str` is meant to be human readable, while `repr` is meant to be unambiguous as possible.

Maybe this is something that a setting could be set for, but I think that using `str` is appropriate default behavior.

**Comment by aartur** [comment]
Jinja isn't only used to directly produce "customer facing representations". Even when it's used to produce HTML, there are major usages (data-* attributes, <input> elements, Javascript fragments) for which you want a higher precision for floats. it's also advertised as working good not only for HTML, and indeed it's widely used for things like source code or configs (Salt and Ansible).

For me the behavior of `str(float_val)` (using up to exactly 17 digits of representation) is weird and I don't see reasons, other than being easy to implement in CPython, that it was chosen.

**Comment by mitsuhiko** [comment]
This won't change because it would require special casing floats. I'm happy to accept filters to improve float rendering in general for specific cases.
