### ISSUE TITLE
collapse whitespace in trans blocks

### ISSUE THREAD

**Issue by willkg** [pallets/jinja#504]
One of the things I have difficulties with is the fact that the `trans` block has no way to collapse whitespace in the text. It strips leading and trailing whitespace and that's great, but if you do paragraphs of text in an HTML template, then you end up with something like this:

```
...
        <div>
          {% trans url='someurl' %}
            This is some text in a paragraph.
            Yay.
          {% endtrans %}
        </div>
...
```

It's nice to indent the various levels of HTML because it makes it more readable. However, the msgid for that string ends up with spaces and newlines in it that have no substantive meaning to the string. This creates a couple of problems:
1. Translators get confused about the whitespace--is it significant? do they need to maintain it? what happens to line length? etc.
2. If we ever change the structure of the HTML, that might change the indentation and then we have a new msgid and that breaks translations.

Django added a "trimmed' flag to their blocktrans tag in Django 1.7 for similar reasons:

https://code.djangoproject.com/ticket/5849

Right now, we have code that extends InternationalizationExtension and overrides `_parse_block` to always collapse whitespace in the text. That sort of works, but it's got some issues and I'd rather it were implemented in Jinja2 proper.

Is there any interest in a "trimmed" flag or something similar? Does it already exist in Jinja and I just haven't seen it, yet?

**Comment by ThiefMaster** [comment]
:+1: would be very useful. Possibly a good opportunity to also add context support

The syntax could be this for example:

    {% trans [trimmed] [with context 'something'] [variables...] %}

e.g.

```
{% trans foo=bar, some=variable %}
{% trans trimmed foo=bar, some=variable %}
{% trans with context 'something' foo=bar, some=variable %}
{% trans trimmed with context 'something' foo=bar, some=variable %}
```

**Comment by willkg** [comment]
What would the behavior of "with context 'something'" do here? I don't see any issues in the tracker for that (maybe I searched for the wrong things?) so I'm not sure what it would do or what the use cases for it are.

**Comment by willkg** [comment]
@ThiefMaster ^^^ What would the behavior of "with context 'something'" do here?

**Comment by ThiefMaster** [comment]
https://www.gnu.org/software/gettext/manual/html_node/Contexts.html

**Comment by willkg** [comment]
Ahh... ok.

I haven't experienced a case where I've needed to provide context for a block of text. It's usually only a problem with very short strings. Is there a compelling use case for this?

**Comment by ThiefMaster** [comment]
it'd not specific to this.. but trans is also used for short strings..

**Comment by thor** [comment]
Seeing as this has been a dormant issue for quite some time I'm wondering whether there's anything in particular that makes this a tricky issue, say, if I wanted to give it a go?

I'm fairly sure willkg's own code he's referring to is puente, which is useful and neat, but hasn't been updated in a while. At the same time there's `django_jinja` trying to bridge the gap for Django and Jinja2 users, and both do their own monkey-patching to enhance the extraction of messages, both with their own limitations.

Either way, what I'm trying to get at is: are there elements holding this back as a possibility? Similarly to Django, would a `trimmed` option be feasible? Are there principles against this?

**Comment by ThiefMaster** [comment]
I think the context stuff I initially suggested should be ignored for now, it's unrelated to this PR.

Having trimming would be *very* useful. I'd even go as far and make this configurable through a policy so it can be enabled by default! I think there are fewer cases where one does not want trimming than vice versa, but the default should remain without trimming for backwards compatibility.
