### ISSUE TITLE
gettext fails when source text has a "%" sign in it

### ISSUE THREAD

**Issue by eastside** [pallets/jinja#516]
Take this example--

```
{{_('Get 50% off your first purchase')}}
```

Raises the following error--

```
  File "/home/vagrant/perkville/businesses/templates/business_profile.jinja2", line 194, in template
    <p>{{_('Get 50% off your first purchase')}}</p>
  File "/home/vagrant/perkville.com/local/lib/python2.7/site-packages/jinja2/ext.py", line 132, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/home/vagrant/perkville.com/local/lib/python2.7/site-packages/jinja2/ext.py", line 141, in gettext
    return rv % variables
  File "/home/vagrant/perkville.com/local/lib/python2.7/site-packages/markupsafe/__init__.py", line 101, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
TypeError: %o format: a number is required, not _MarkupEscapeHelper
```

The problem seems to be here--

```
def _make_new_ngettext(func):
    @contextfunction
    def ngettext(__context, __singular, __plural, __num, **variables):
        variables.setdefault('num', __num)
        rv = __context.call(func, __singular, __plural, __num)
        if __context.eval_ctx.autoescape:
            rv = Markup(rv)
        return rv % variables
    return ngettext
```

For some reason, it always calls modulo with `variables`, even if there are no variables. This doesn't seem to be correct.

**Comment by fergyfresh** [comment]
`{{_('Get 50% off your first purchase')}}`

might need raw tags, I'm not home so I can't check it. It seems like it doesn't like that you're stomping on the jinja2 template percent sign %!!!!

try 

`{{_('{{% raw %} Get 50% off your first purchase {% raw %}')}}`

It is somehow related to you not escaping that percent sign though.

**Comment by ThiefMaster** [comment]
Why not use `{% trans %}Get 50% off your first purchase{% endtrans %}`?

**Comment by ThiefMaster** [comment]
This has nothing to do with `{% raw %}` tags.

**Comment by fergyfresh** [comment]
Sorry @ThiefMaster  I will delete my post.

**Comment by ThiefMaster** [comment]
ok, deleted my comment too

**Comment by eastside** [comment]
My understanding was that {% trans %} was a wrapper for gettext. And indeed, the same error results when using {% trans %} tags.

**Comment by ThiefMaster** [comment]
I guess that shouldn't happen..

**Comment by razor-1** [comment]
+1 that this should be fixed. If a translator enters an unexpected % you don't want everything failing completely. Pull request created #541

**Comment by davidism** [comment]
Treating all strings as format strings seems intentional based on the docs:

>  with newstyle gettext, string formatting is also used if no placeholders are used which makes all strings behave exactly the same.

I added something to the docs about this.
