### ISSUE TITLE
Inject additional nodes in an extension

### ISSUE THREAD

**Issue by stevelacey** [pallets/jinja#517]
I am attempting to adapt the [WithExtension](https://github.com/mitsuhiko/jinja2/blob/2.8/jinja2/ext.py#L413-L431) to produce a generic extension for wrapping a block (followed by some more complex ones).

My objective is to support the following in templates:

```
{% wrap template='wrapper.html.j2' ... %}
    <img src="{{ url('image:thumbnail' ... }}">
{% endwrap %}
```

And for wrapper.html.j2 to look like something like:

```
<div>
    some ifs and stuff
    {{ content }}
    more ifs and stuff
</div>
```

I believe my example is most of the way there, WithExtension appears to parse the block and then append the AST representation of some `{% assign .. %}` nodes into the context of the nodes it is parsing.

So I figured I want the same thing, those assignments, followed by an include block, which I'd expect to be able to access those variables when the AST is parsed, and to pass through the block that was wrapped as a variable `content`.

I have the following thus far:

```py
class WrapExtension(Extension):
    tags = set(['wrap'])

    def parse(self, parser):
        node = nodes.Scope(lineno=next(parser.stream).lineno)
        assignments = []
        while parser.stream.current.type != 'block_end':
            lineno = parser.stream.current.lineno
            if assignments:
                parser.stream.expect('comma')
            target = parser.parse_assign_target()
            parser.stream.expect('assign')
            expr = parser.parse_expression()
            assignments.append(nodes.Assign(target, expr, lineno=lineno))
        content = parser.parse_statements(('name:endwrap',), drop_needle=True)
        assignments.append(nodes.Name('content', content))
        assignments.append(nodes.Include(nodes.Template('wrapper.html.j2'), True, False))
        node.body = assignments
        return node
```

However, it falls over at my `nodes.Include` line, I simply get `assert frame is None, 'no root frame allowed'`. I believe I need to pass AST to `nodes.Template` rather than a template name, but I don't really know how to parse in additional nodes for the objective of getting AST rather than string output (i.e. renderings) – nor whether this is the right approach. Am I on the right lines, any ideas on how I should go about this?

--

**Edit**: Since the above I've been playing with the parser to see if that's the way to go, the following seems closer but still isn't quite right:

```py
template = self.environment.loader.load(self.environment, 'wrapper.html.j2')
assignments.append(nodes.Include(template, True, False))
```

I figure based on what I'm seeing that maybe I don't want to parse this as a template as a template is a top-level/root thing rather than something that's included.

--

https://stackoverflow.com/questions/34021437/how-do-you-parse-and-inject-additional-nodes-in-a-jinja-extension

**Comment by stevelacey** [comment]
More specifically, maybe I am asking, how do I use `nodes.Include` when I don't have the template or its nodes, it accepts `template` as its first argument but doesn't seem to want a `nodes.Template` (or at least the kind I am building).

**Comment by stevelacey** [comment]
@mitsuhiko any thoughts? Thanks in advance!

**Comment by damz** [comment]
@stevelacey Take a look at the [example extension](http://jinja.pocoo.org/docs/dev/extensions/#module-jinja2.ext) in the documentation. I think it will take you 90% of the way there.

A nice trick of the jinja2 extension API is that `nodes.Callblock(self.call_method(...))` which allows the generated code to call back to your extension.

In your case you should be able to do just do something like this in your called function:

```
return self.environment.get_template(template_name).render(content=caller())
```

In any case, when confused, don't hesitate to look at what Jinja2 is seeing:

 * Print the AST of the generated template with `print env.parse(template_data, name, template_filename)`;
 * Print the generate Python code: `print env.compile(template_data, name, template_filename)`

(Where `name` and `template_filename` can be arbitrary strings.)

**Comment by stevelacey** [comment]
http://stackoverflow.com/a/34181507/160821

**Comment by AlJohri** [comment]
I'm running into almost exactly the same issue as @stevelacey. In Steve's case, he's trying to return a nodes.Import which can be mocked by returning `self.environment.get_template(**).render(**)` instead. What I'm trying to do is essentially wrap the `import xx as yy` and `from xx import zz` tags into extensions. I would like to change `xx` in the previous examples based on the context. In other words, I would like to change the name of the template being imported based on the context.

It seems like there is no way to modify the AST once it is parsed. What I want to do is when `visit_CallBlock` is run, modify the AST to return a proper `nodes.ImportNode` and have the compiler handle it.

Is there anyway to inject additional nodes into the AST at compile time? cc @mitsuhiko 

Thanks!

**Comment by mitsuhiko** [comment]
Not sure what exactly you mean with "additional nodes into the AST at compile time". Obviously you can return as many nodes as you want for as long as the nodes are statically determined.

In particular "I would like to change xx in the previous examples based on the context" does not work as the context is not available at compile time.

**Comment by AlJohri** [comment]
Ah, okay - that makes sense.

I'm mocking the functionality of the `nodes.IncludeNode` via `self.environment.get_template(**).render(**)` to change functionality at runtime.

Can you think of a simple way to mock the functionality of the `nodes.ImportNode` and `nodes. FromImport` at runtime via a dynamic import?

I think it would be somehow replicating the logic of the the `visit_ImportNode` method in the compiler but there's a lot going on so I'm not sure how it would be done. https://github.com/pallets/jinja/blob/fc5be479ddb3ffd2687607aada5a53bd5304f060/jinja2/compiler.py#L944-L963

I think it would be something like running `_get_default_module` but I'm not entirely sure.
