### ISSUE TITLE
Shouldn't `For.iter` be evaluated in the parent frame?

### ISSUE THREAD

**Issue by damz** [pallets/jinja#518]
Context: I'm trying to write an introspection that finds all the chains of `Getitem` or `Getattr` that start with an undefined `Name`. Like `jinja2.find_undeclared_variables` but that goes deeper into attribute chains when it's easy to do.

Now, I'm seeing that `For.iter` is visited within `loop_frame`, which doesn't make sense to me, as the `loop_frame` is defined as the frame of everything _except_ `iter`:

```
children = node.iter_child_nodes(exclude=('iter',))
if node.recursive:
    loop_frame = self.function_scoping(node, frame, children,
                                       find_special=False)
else:
    loop_frame = frame.inner()
    loop_frame.inspect(children)
```

Can you confirm this is a bug that can be fixed?

**Comment by mitsuhiko** [comment]
I think this should no longer happen with the cleaned up identifier tracking.
