### ISSUE TITLE
`Frame.outer_undeclared` is probably bogus

### ISSUE THREAD

**Issue by damz** [pallets/jinja#519]
In `Frame.__init__`, you can see:

```
self.identifiers.outer_undeclared.update(
    parent.identifiers.undeclared -
    self.identifiers.declared
)
```

Unfortunately, the frame has not been inspected yet, so `self.identifiers` is just a new object, and `self.identifier.declared` will always be empty.

**Comment by mitsuhiko** [comment]
This is no longer used now.
