### ISSUE TITLE
Line statements eat newlines

### ISSUE THREAD

**Issue by gavento** [pallets/jinja#52]
Line statements eat not only the spaces until the beginning of the line as documented at  http://jinja.pocoo.org/docs/templates/#whitespace-control , but also all the previous newlines.

As of  2.7-dev, the following code generates no empty lines:

```
%% for i in range(3)
{{i}}, next line should be empty

%% endfor
```

This is an issue in languages where newlines matter (generated LaTeX).

**Comment by lajarre** [comment]
Newlines **after** a end control bloc (`endif`, `endfor`) are still eaten up:

```
%% for i in range(2)
hello
%% endfor

I want to be alone
```

renders as =>

```
hello
hello
I want to be alone
```

Is this expected behavior? This doesn't make sense to me regarding the documentation.

**Comment by MatanRubin** [comment]
This has been resolved a long time ago, but I'm not sure why. I still see my newlines eaten up with line statements on version 2.10.3...

Any way of getting this to work?
