### ISSUE TITLE
urlize filter ignores ftp:// URLs

### ISSUE THREAD

**Issue by Self-Perfection** [pallets/jinja#522]
Documentation [states](http://jinja.pocoo.org/docs/dev/templates/#urlize):

```
 urlize(value, trim_url_limit=None, nofollow=False, target=None)

    Converts URLs in plain text into clickable links.
```

Therefore I expect that anything that [looks like URL](https://en.wikipedia.org/wiki/Uniform_Resource_Locator#Syntax) gets converted to `<a href=...>` tag. Unfortunately now `urlize` picks only http and https URLs.

Something has to be changed. Either `urlize` behaviour or documentation to cleary describe `urlize` limitations.

**Comment by Skuzzzy** [comment]
https://github.com/mitsuhiko/jinja2/blob/b78f2617b04cc549ed5fea4eca944c4d8054d187/jinja2/utils.py#L187

Comment: The documentation in the code seems to differ from the documentation on the website.

Would changing the `urlize` behavior to accept valid urls be something people are interested in?
