### ISSUE TITLE
Make jinja2 create new style python-brace-format translations for {% trans %} block

### ISSUE THREAD

**Issue by sassanh** [pallets/jinja#533]
I'm using babel to generate po files out of my project, I have some Jinja2 files, when I use:

```
{% trans a=x.y %}print {{ a }}{% endtrans %}
```

and do the extraction with babel it writes this line in po file:

```
#, python-format
msgid "print %(a)s"
msgstr ""
```

how can I make it write this instead:

```
#, python-format
msgid "print {a}"
msgstr ""
```

---

What I've done so far:
I changed this line in _parse_block method in ext.py in jinja:

```
buf.append('%%(%s)s' % name)
```

to

```
buf.append('{{{}}}'.format(name))
```

it makes jinja create the desired msgid in po file, but then it fails to translate it because the compile.py file in jinja package generates this:

```
yield escape(((context.eval_ctx.autoescape and Markup or identity)(context.call(l_gettext, 'print {a}')) % {'a': environment.getattr(x, 'y')}))
```

look at this part:

```
 % {'a': environment.getattr(x, 'y')}
```

it's because there's visit_Mod (binary % operator) at this part of the buffer sent to compile.py. So I concluded that I can't make a PR for jinja that generates new style python-brace-format translations and maybe someone in jinja team can help me on this.

**Comment by mitsuhiko** [comment]
Going to close this.  This will not happen in core Jinja2.
