### ISSUE TITLE
trim_blocks behaves differently on {% raw %} blocks

### ISSUE THREAD

**Issue by voetsjoeba** [pallets/jinja#538]
Was taken by surprise by trim_blocks appearing to behave differently on {% raw %} blocks than on others. This is with Jinja 2.8, latest available at the time of writing.

Consider this example:

```
from jinja2 import *

if __name__ == "__main__":
    env = Environment(trim_blocks=True, lstrip_blocks=True)
    template_str = """an awesome template
{% if myvar %}
   3 spaces
{% endif %}
end of template"""
    print env.from_string(template_str).render(myvar=True)
```

As documented, this results in:

```
an awesome template
   3 spaces
end of template
```

```
00000000: 616e 2061 7765 736f 6d65 2074 656d 706c  an awesome templ
00000010: 6174 650a 2020 2033 2073 7061 6365 730a  ate.   3 spaces.
00000020: 656e 6420 6f66 2074 656d 706c 6174 650a  end of template.
```

The behaviour is identical for e.g. a {% filter %} block instead of an {% if %} block, so that's all good.
But for {% raw %} blocks, things are different:

```
from jinja2 import *

if __name__ == "__main__":
    env = Environment(trim_blocks=True, lstrip_blocks=True)
    template_str = """an awesome template
{% raw %}
   3 spaces
{% endraw %}
end of template"""
    print env.from_string(template_str).render(myvar=True)
```

Results in:

```
an awesome template

   3 spaces
end of template
```

```
00000000: 616e 2061 7765 736f 6d65 2074 656d 706c  an awesome templ
00000010: 6174 650a 0a20 2020 3320 7370 6163 6573  ate..   3 spaces
00000020: 0a65 6e64 206f 6620 7465 6d70 6c61 7465  .end of template
00000030: 0a
```

Am I missing something? If this is as designed, could the documentation be updated to reflect that the behaviour is different for {% raw %} tags?

**Comment by ngr** [comment]
I believe the behavior is valid.
`{% raw %}` opens the block ignored by Jinja and you have a newline char exactly after the `{% raw %}`.
In case you do not need it, try: 
```
template_str = """an awesome template
{% raw %}   3 spaces
{% endraw %}
end of template"""
```

**Comment by davidism** [comment]
I agree. `raw` means the content will be rendered as-is.
