### ISSUE TITLE
Streaming support in jinja2?

### ISSUE THREAD

**Issue by auvipy** [pallets/jinja#540]

**Comment by ThiefMaster** [comment]
Could you please describe what you are actually asking for? Just a title as vague as this one is not a proper issue.

**Comment by auvipy** [comment]
https://github.com/django/django/pull/4783 this is something what I actually meant

**Comment by ThiefMaster** [comment]
http://jinja.pocoo.org/docs/dev/api/#jinja2.Template.stream

**Comment by praiskup** [comment]
Could we consider **stream reading** of jinja templates to be a valid RFE?  So far, IIUC, jinja template is compiled into monolithic object at once;  and that object can be rendered in a stream fashion.  But reading line-by-line would be neat, too.

The use-case would be to use some "jinja-tool" in commandline pipeline, e.g. `cat template | jinja-tool | sed ...`.  Similarly we could have "interactive" jinja "shell", reading stdin from commandline line-by-line and outputting instantiated output as soon as it is possible?:
```
jinja>{%- if True %}
jinja>something
something
jinja>{%- endif %}
jinja>{%- for something in ['a', 'b', 'c'] %}
jinja>{{ something }}
jinja>{%- endfor %}
a
b
c
```

**Comment by ThiefMaster** [comment]
What would be the benefit of a Jinja REPL? I can't imagine any use case where this would be more useful than just reading a template from stdin in one go and then rendering it.

**Comment by praiskup** [comment]
The same as for `m4`, etc -> e.g. large but slow jinja2 streams, but also debugging.  E.g.
in https://github.com/devexp-db/distgen/issues/42 I'd like to experiment like:
```
$ dg --template -
{{ config.os.sth }}
... traceback for undefined item ...
{{ config.os.name }}
fedora
```
