### ISSUE TITLE
Getting Could not parse the remainder '('images/favicon.ico')' from 'static('images/favicon.ico')'

### ISSUE THREAD

**Issue by vaibhav-jain** [pallets/jinja#542]
I am using jinja2 without any problem until now but when I try to render my apps template I got this error  `Could not parse the remainder: '('images/favicon.ico')' from 'static('images/favicon.ico')'`

The django template is rendering but when I try to use jinja2 syntax in my templates I am getting this error.
Templates in `BASE_DIR('templates'),` is using jinja2 syntax and working fine but why not with 
`BASE_DIR('apps/blog/templates/zinnia')`

How do I fix this syntax error??

```
Here is settings.py
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [
            BASE_DIR('templates'),
            BASE_DIR('apps/blog/templates/zinnia')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'config.jinja2.environment',
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
                "django.core.context_processors.request"
            ],
        },
    },
]

```

**Comment by mitsuhiko** [comment]
Closing this because I am not sure what this issue is describing. Feel free to reopen with more information.

**Comment by avirepo** [comment]
I am facing the same issue. Any suggestions.

**Comment by mleger45** [comment]
Hello, I am facing the exact same issue.

**Comment by mitsuhiko** [comment]
This does not appear to be a jinja2 related issue. Neither is there enough information available, now is the error message one that comes from jinja.

**Comment by d-tto** [comment]
I got this error when jinja extends to the django template (html)
