### ISSUE TITLE
There is no 'sudo' command in the documentation

### ISSUE THREAD

**Issue by blueboar2** [pallets/jinja#543]
From Installation part of the documentation:
(If you are installing from the Windows command line OMIT THE SUDO and make sure to run the command as user with administrator rights)

But there is no sudo command, there is only
easy_install Jinja2
pip install Jinja2

Which sudo i need to omit? Can you add it to easy_install and pip?

**Comment by DavidBruchmann** [comment]
Sudo is a system command available in some Linux Operating Systems.
The impact is the same as "Run as Administrator" in Windows.

**Comment by blueboar2** [comment]
Yes, i know the purpose of the Sudo command.
But the 'omit' means that i need to _ignore_ it. Which sudo do i need to omit? Thee is no sudo command in the example earlier.
Can you, for example write

sudo easy_install Jinja2
or something like?

**Comment by DavidBruchmann** [comment]
yes,
sudo easy_install Jinja2
sudo pip install Jinja2

but it might depend on several parameters if you've to execute it as Sudo,
i.e. if python is installed by sudo too or if it shall be available for all
users.

**Comment by blueboar2** [comment]
So, why this is not in the documentation? If you say to omit something, then there must be something to omit.

**Comment by davidism** [comment]
You should *never* be installing Python packages as root.  Use a virtualenv.  The fix here is to remove the "omit sudo" comment, not to add it in the commands.

**Comment by blueboar2** [comment]
I agree. Remove omit sudo comment.
