### ISSUE TITLE
How to apply "format" on a list of strings?

### ISSUE THREAD

**Issue by htgoebel** [pallets/jinja#545]
I try to do something like in Python

```
("db.%s.dump" % n for n in names)
```

I tried 

```
{{ databases | map("format", "db.%s.dump") }}
{{ "db.%s.dump" | map("format", databases) }}
```

and a lot more. All I tried failed.

The documentation is of no help :-(

**Comment by NormanDenayer** [comment]
why not ```{% for n in names %} {{ "db.%s.dump"|format(n) }} {% endfor %}```?

**Comment by krzysztof-magosa** [comment]
@NormanDenayer it's fine unless you want to pass it to another filter in map().

**Comment by krzysztof-magosa** [comment]
Personally I ended with writing own plugin:
```
from jinja2.utils import soft_unicode

def format_string(text, fmt, *kw):
    return soft_unicode(fmt).format(text, *kw)

class FilterModule(object):
    def filters(self):
        return dict(format_string=format_string)
```

Usage:
```
list_of_names | map('format_string', 'hello {}!')
```

**Comment by davidism** [comment]
See https://github.com/pallets/jinja/pull/906#issuecomment-548393215 for why I'm declining this. It also contains a filter that could accomplish this, or you can write a more specific filter as shown above.
