### ISSUE TITLE
Update recommendation re file extensions

### ISSUE THREAD

**Issue by carljm** [pallets/jinja#547]
The template designer documentation says:

> A Jinja template is simply a text file. Jinja can generate any text-based format (HTML, XML, CSV, LaTeX, etc.). A Jinja template doesn’t need to have a specific extension: .html, .xml, or any other extension is just fine.

While this is all true, I think it implies a bad recommendation, and makes things harder for the ecosystem around Jinja2. I think Jinja2 should recommend (but not require) a single file extension for Jinja2 templates.

A Jinja2 template for an HTML file is not the same thing as an HTML file. The Jinja2 template may not even be valid HTML until rendered, and it certainly shouldn't be syntax highlighted as simply HTML, or served by a static-files web server as `text/html`. It is a distinct type of file, and deserves its own file extension to indicate that.

Personally, I use the `.j2` extension, and I often "stack" extensions to indicate what the intended type of the rendered template is; e.g. `foo.html.j2` is "a Jinja2 template that will be an HTML file when rendered." (This is inspired by existing precedent for stacked extensions, e.g. `.tar.gz` is a "a gzip file that will be a tar file when unzipped").

I would be happy to put together a small pull request for the documentation recommending this approach (while still making it clear that Jinja2 itself enforces no such convention), if the concept is accepted.

**Comment by ThiefMaster** [comment]
I think it is a good recommendation to "allow" any extensions. Frameworks like Flask determine whether to auto-escape data for HTML based on the extension for example. And at least IDEs usually let you select which template engine you use so html files will be highlighted accordingly (at least that's the case with PyCharm).

**Comment by jeffwidman** [comment]
> I would be happy to put together a small pull request for the documentation recommending this approach (while still making it clear that Jinja2 itself enforces no such convention), if the concept is accepted.

I'm okay with this, as long as it was a docs recommendation that wasn't enforced at the code level. The Ansible project already uses this convention in their docs: http://docs.ansible.com/ansible/template_module.html

Also, having a convention might make it easier for linters/syntax highlighters to auto-pickup on the file type, I'd be curious to hear from @danielchatfield if this would have made it easier to write https://github.com/danielchatfield/atom-jinja2

That said, this is just my personal opinion. Other maintainers may think differently.

**Comment by davidism** [comment]
At least with Flask, I view the fact that the templates are in a folder called "templates" to be signal enough, without requiring an extra extension.  PyCharm does understand the ".jinja2" extension, but normally you just mark a directory as containing templates.  I don't think adding a more explicit recommendation is necessary.
