### ISSUE TITLE
Document Environment.template_class

### ISSUE THREAD

**Issue by afg984** [pallets/jinja#551]
The source code says `Environment.template_class` [makes it possible to use custom templates](https://github.com/mitsuhiko/jinja2/blob/5b498453b5898257b2287f14ef6c363799f1405a/jinja2/environment.py#L1213), however, [I cannot find it in the documentation](http://jinja.pocoo.org/docs/dev/search/?q=template_class).

Please document it so it would be a part of the stable API, if appropriate, thanks!

**Comment by mitsuhiko** [comment]
This is part of the stable API but intentionally not documented.
