### ISSUE TITLE
Generating large template hogs all memory

### ISSUE THREAD

**Issue by tomchop** [pallets/jinja#556]
More than a year later, I'm running into an issue similar to #372.

Here is my code:

```
t = Template(self.template).stream(objects=MyObjects.objects(q))
t.enable_buffering(5)
t.dump(self.output_file, encoding="utf-8")
```

`MyObjects.objects(q)` is a generator, but the process dies because it hogs up all my memory. My template has a header, then a loop, and a footer:

```
<header>
{% for obj in objects %}
{{ obj.value }}
{% endfor %}
<footer>
```

Any obvious workarounds you can think of?

**Comment by mitsuhiko** [comment]
This is very hard to answer. Jinja itself should not exhaust the memory here. You would have to run some testing here to see what is actually at fault. My guess is that whatever objects is, is actually not an iterator but something that buffers internally all the objects.
