### ISSUE TITLE
Add default to map filter if attribute is not defined

### ISSUE THREAD

**Issue by Yannik** [pallets/jinja#557]
It would be great if the map filter would return an optional default value if the attribute is not defined.

Example:

```
list_of_dicts|map(attribute='version', default='5.6')
```

**Comment by pief** [comment]
+1

**Comment by esaezgil** [comment]
Can anyone review my PR please? :)

**Comment by DanyC97** [comment]
any reason why this issue and PR hasn't been progressed ?

**Comment by Yannik** [comment]
Yeah @davidism, please finally merge this.

**Comment by esaezgil** [comment]
Hi @DanyC97 and @Yannik thanks for raising this! :) it's been so long that the MR has conflicts. I will try to solve them asap

**Comment by davidism** [comment]
The following is not a statement about the issue or PR itself, and I do not want to give the impression that your comments had a positive effect on our future actions with it.

Please recognize that Jinja is one of multiple packages maintained by a few people in their spare time. We are under no timeline nor obligation to merge pull requests. While this may not have been your intention, posting comments that contain no content relevant to the issue but just prod us to take action are not welcome. Please do not do that here or elsewhere in the open source community.

**Comment by davidism** [comment]
@Yannik @DanyC97 The following is not a statement about the issue or PR itself, and I do not want to give the impression that your comments had a positive effect on our future actions with it.

Please recognize that Jinja is one of multiple packages maintained by a few people in their spare time. We are under no obligation to close issues on any specific timeline, although we do try to address things as we can. While this may not have been your intention, posting comments that contain no content relevant to the issue but just prod us to take action are not welcome. Please do not do that here or elsewhere in the open source community.

**Comment by hsychla** [comment]
Is somebody still loooking into this? I reaaaally could have used this right now...

**Comment by wedi** [comment]
Are there any news regarding this feature? Why was the pulled request closed? Should someone else take over or is this just undesired?

**Comment by esaezgil** [comment]
I closed the pull request myself as I do not have any further interest pursuing it. Please feel free to contribute with another PR.

**Comment by akamac** [comment]
I would love to see this implemented

**Comment by matthagenbuch** [comment]
+1

**Comment by shashanksingh28** [comment]
Working on this in Pycon 2019 Sprints

**Comment by kbiggers** [comment]
#1018

**Comment by flexferrum** [comment]
Is it a good idea to add 'default' param to the 'attr' filter as well?
