### ISSUE TITLE
Prefix variables

### ISSUE THREAD

**Issue by memeplex** [pallets/jinja#561]
Currently we have line blocks and line comments, both signalled by a configurable prefix. The missing part in this picture are "prefix expressions". I'm not sure how difficult it's for the parser to parse just one single expression without the help of an end delimiter, but a more modest goal will be to implement "prefix variables". Something like `$name` allowing only valid identifiers. What do you think?

**Comment by ThiefMaster** [comment]
IMHO the whole idea of line statements is questionable. But maybe I misunderstood your question and you are asking for something unrelated? Maybe make an actual example of what you're suggesting.

**Comment by memeplex** [comment]
What I'm asking: to support the syntax `<v-prefix><identifier>` to expand variables as in `$name`. Ideally, I would like the more general `<e-prefix><expression>` as a complement to `<b-prefix><block>` and `<c-prefix><comment>`, but maybe the expression parser relies on a final delimiter being there, so I simplified the proposal to simple variables.

**Comment by memeplex** [comment]
Maybe it could be extended to simple attribute and item lookup, as in `$user.name` or `$user.names[0]`, in a way similar to what other templating systems do.

**Comment by ThiefMaster** [comment]
You mean inside normal `{{ ... }}` blocks etc? I think that's an awful idea. Few template engines outside the PHP world use prefixes for variables...

**Comment by memeplex** [comment]
No, outside delimiters of any kind, just prefixed by some string. That's a pretty common syntax.

**Comment by ThiefMaster** [comment]
Ah, I see. IMHO that would just add clutter and possibly break existing templates (since there's suddenly "active" content outside `{{ ... }}` and `{% ... %}`)

**Comment by memeplex** [comment]
I don't think so because:

1. The syntax would be disabled inside blocks.
2. The prefix would be configurable and it could be disabled by default.

This is not different from the introduction of line blocks and comments AFAICS.

**Comment by memeplex** [comment]
Regarding the "no filters applied", I'm proposing this as a shortcut for very short substitutions, I see no point extending it to the general case, specially when the expression itself is already of considerable extension. For example, one can configure `${,}` as expression delimiters and `$` as expression prefix.

**Comment by memeplex** [comment]
Here is a fictional example of why I said expression/variable prefixes are a missing piece:

```
environment = jinja2.Environment(
    block_start_string='@{',
    block_end_string='}',
    line_statement_prefix='@',
    comment_start_string='#{',
    comment_end_string='}',
    line_comment_prefix='#',
    variable_start_string='${',
    variable_end_string='}',
    variable_prefix='$'    # <-- this is not currently valid.
)
```

Here is a rationale for not supporting this, though: the prefixed versions are intended to work at the line level (by default, they trim leading and trailing whitespace, reclaiming the entire line for themselves). Under that interpretation, there is no case for prefixed variables since they are intended to always be embedded in a line. Now, when you set `trim_blocks` and `lstrip_blocks` to true, this line-level vs embedded classification is weakened and the prefix vs delimited one takes relevance.

**Comment by mitsuhiko** [comment]
This is unlikely to happen. You can already use `${variable}` if you want. The problem is that variable delimiter parsing is pretty tricky because once we add `$foo` the topic will come up about `$foo[0]` at which point the can is open for `$foo[expression + here]` etc.
