### ISSUE TITLE
Remove format filter and instead point folks toward '%'

### ISSUE THREAD

**Issue by jeffwidman** [pallets/jinja#566]
Opening this for long-term discussion, as it'd be a backward-incompatible change so couldn't land until the next major version. 

As outlined by @snoack in https://github.com/pallets/jinja/issues/70#issuecomment-2545521 and https://github.com/pallets/jinja/issues/70#issuecomment-2566285, both readability and compiled performance seem to be better when using `%` rather than `format`. I'd be fine with removing the `format` filter, or at the very least have the docs recommend using `%`.

Opinions from others?

**Comment by mitsuhiko** [comment]
I would just remove it from the docs but keep it the code. People can already overwrite it if they want by that name and it's easy to support.

**Comment by bladeoflight16** [comment]
I'm not sure about the wisdom of encouraging the use of the old style `%` formatting mechanism. Python itself is moving away from it and encouraging use of the `format` method. Here's [an example](https://docs.python.org/3.5/library/string.html#format-examples) of the Python docs calling it the "old" syntax.

**Comment by davidism** [comment]
It's old in the sense that it came first, not that it's deprecated or discouraged.

**Comment by bladeoflight16** [comment]
@davidism No, it is discouraged. See the [`printf`-style String Formatting](https://docs.python.org/3//library/stdtypes.html#old-string-formatting) section of the docs:

> **Note:** The formatting operations described here exhibit a variety of quirks that lead to a number of common errors (such as failing to display tuples and dictionaries correctly). Using the newer [`str.format()`](https://docs.python.org/3//library/stdtypes.html#str.format) interface helps avoid these errors, and also provides a generally more powerful, flexible and extensible approach to formatting text.

[Python 3.1.5's docs](https://docs.python.org/release/3.1.5/library/stdtypes.html#old-string-formatting-operations) explicitly suggested it might be removed:

> **Note:** The formatting operations described here are obsolete and may go away in future versions of Python. Use the new [*String Formatting*](https://docs.python.org/release/3.1.5/library/string.html#string-formatting) in new code.

I'm not sure why the warning was toned down in newer versions.

**Comment by mitsuhiko** [comment]
As it stands if you want to support 2.x and 3.x, `%` is saner to use. `.format` introduces various problems with unicode handling in 2.x.

> Python 3.1.5's docs explicitly suggested it might be removed:

They just added `%` formatting back for bytes so I doubt this will be going anywhere. If it is, we can retrofit it.

**Comment by krzysztof-magosa** [comment]
Is there any plan to create built-in format filter which could be used in map() ?

**Comment by bladeoflight16** [comment]
@mitsuhiko What problems does `format` have with Unicode? The only thing I can find is stuff about mixing bytes and text, to which the simplest, most well known answer is, "Don't do that." And according to [this](https://anonbadger.wordpress.com/2016/01/05/python2-string-format-and-unicode/), the problems of mixing them appear to go both ways regardless of which formatting option you use.
