### ISSUE TITLE
Suggest pip instead of easy_install in Readme instructions

### ISSUE THREAD

**Issue by jeffwidman** [pallets/jinja#568]
> The Jinja2 tip is installable via easy_install with easy_install Jinja2==dev.

I vote we change this to recommending `pip` instead of `easy_install`, especially now that `pip` comes bundled with Python.

**Comment by ThiefMaster** [comment]
strong :+1:, easy_install is awful

**Comment by jeffwidman** [comment]
What do you think about also tidying up the instructions here? 
http://jinja.pocoo.org/docs/dev/intro/#as-a-python-egg-via-easy-install

I think it's waayyyy too verbose. I think we should just say `pip install jinja2` and leave it at that... No need for the instructions on installing from tarball or development version. Anyone who needs to compile from source for some reason will already know how to do it (or google "compile python package from source"). 

The one part I'm not sure of is the note about the C extensions being compiled if you install via `distribute`. I'm not familiar enough with python packaging... Do the more recent versions of Pip handle that?

**Comment by ThiefMaster** [comment]
I'm pretty sure `pip install` compiles extensions. But it should be pretty easy to test it yorself ;)
