### ISSUE TITLE
Seems to be broken on py3.5

### ISSUE THREAD

**Issue by magniff** [pallets/jinja#572]
```bash
> py.test tests/
============================================================================ test session starts ============================================================================
platform linux -- Python 3.5.0, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/magniff/workspace/jinja, inifile: setup.cfg
collected 323 items 

tests/test_api.py ................Aborted (core dumped)
```

Python --version == Python 3.5.0, ubuntu 15 (python from repo)

**Comment by ThiefMaster** [comment]
Python 3.5.1 is the latest version; does it also coredump with that?

Anyway, if python crashes it's more likely a broken installation or a bug in Python than a Flask issue.

**Comment by magniff** [comment]
Hmm, in Python 3.6.0a0 from semiofficial mirror on github it seems to be working.
