### ISSUE TITLE
Dynamic capitalization of variables

### ISSUE THREAD

**Issue by ffunenga** [pallets/jinja#574]
Hi,

(This is just an idea, probably difficult to implement.)

is there a way to make Jinja behave in the following manner?

```python
    template = Template('They are {{ nationality }} and they live in {{ Country }}')
    stream = template.render(nationality='portuguese', country='portugal')
    assert stream == 'They are portuguese and they live in Portugal'
```

Notice the use of a capitalized reference `{{ Country }}` to the `country` variable. Other possibilities:

```python
    # if the variable reference matches, then present the value therein
    assert Template('var').render(var='YeLLoW') == 'YeLLoW'

    # if any of the variable reference's chars misses the capitalization, then
    assert Template('VAR').render(var='YeLLoW') == 'YELLOW'
    assert Template('VaR').render(var='YeLLoW') == 'YelloW'
    assert Template('vAr').render(var='YeLLoW') == 'yELLOw'
    assert Template('Var').render(var='yellow hats') == 'Yellow Hats'
```

The high level idea here is: when variable names and their respective references fail to match due to capitalization issues, is there a way to extract command information from that and implement a filter?

**Comment by jeffwidman** [comment]
Do you have a concrete example where this would be especially convenient? Generally the `title` filter works fine for country names.

Personally, this feels like too much magic, I'd rather have casing changes handled through explicit filters, rather than leave room for ambiguity.
