### ISSUE TITLE
"map(filter)" returns confusing error message

### ISSUE THREAD

**Issue by alexjurkiewicz** [pallets/jinja#575]
If someone accidentally types:

```
{{ my_list|map(myfilter) }}
```

Instead of:

```
{{ my_list|map('myfilter') }}
```

The error message is:

``` python
  File "template.html", line 93, in block "content"
    {{ my_list|map(myfilter) }}
  File "venv/lib/python3.5/site-packages/jinja2/filters.py", line 750, in do_list
    return list(value)
  File "venv/lib/python3.5/site-packages/jinja2/filters.py", line 850, in do_map
    yield func(item)
  File "venv/lib/python3.5/site-packages/jinja2/filters.py", line 846, in <lambda>
    name, item, args, kwargs, context=context)
  File "venv/lib/python3.5/site-packages/jinja2/environment.py", line 424, in call_filter
    raise TemplateRuntimeError('no filter named %r' % name)
jinja2.exceptions.TemplateRuntimeError: no filter named Undefined
```

It would be good if this error message were clearer.

**Comment by alexjurkiewicz** [comment]
My suggestion would be to check the type of the argument in do_map and raise an exception if it is not a sensible type (eg `if not isinstance(name, BaseString)`). Would a patch along these lines be accepted?

**Comment by jeffwidman** [comment]
Agreed that the error should be more clear. 

Your suggested solution sounds good to me. Are there any other functions beyond `do_map` where it would also make sense to check for this?

This isn't a promise to merge it as I'm not very familiar with that section of code, so would prefer that another maintainer was able to review as well.

**Comment by alexjurkiewicz** [comment]
This is the only filter that takes a string argument representing another filter. Lots of filters take an 'attribute' string, but that seems like a different thing.

**Comment by alexjurkiewicz** [comment]
Nice, thanks 🙌
