### ISSUE TITLE
Should Template.render() return a safe string?

### ISSUE THREAD

**Issue by aaugustin** [pallets/jinja#576]
I just stumbled upon an interesting difference between Jinja2 and the Django template language.

`Template.render()` returns a safe string in Django. It's likely an accident of the implementation more than a design choice. It happens because `NodeList.render()` calls `mark_safe()` on its output, even at the top level.

I believe that `Template.render()` doesn't return a safe string in Jinja2. To achieve this effect, one would have to wrap the return value [here](https://github.com/pallets/jinja/blob/ec8452f6db4bd474858758e9eca123222bd7dc3f/jinja2/environment.py#L986) in `Markup()`.

It's unclear to me that one behavior has significant advantages over the other. I thought I'd bring it up here in case someone has an opinion.

It would be nice to resolve this inconsistency because it can cause non-trivial bugs such as https://github.com/torchbox/wagtail/issues/2541.

**Comment by davidism** [comment]
Rendering a template could produce an unsafe string, we don't know how it's going to be used after rendering.  Seems better to be explicit about it.

**Comment by aaugustin** [comment]
Indeed it could produce an unsafe string, all the more since Jinja2 disables autoescaping by default.

I reversed this default in Django's Jinja2 backend; this could be an argument for making the change only in Django's Jinja2 backend and not in Jinja2 itself.

**Comment by aaugustin** [comment]
I also brought up the question on the django-developers mailing-list: https://groups.google.com/forum/#!topic/django-developers/UVCc9CyGZaA

**Comment by mitsuhiko** [comment]
It's tricky to change this now, so I will close this.
