### ISSUE TITLE
Extensionless extends, includes and imports

### ISSUE THREAD

**Issue by ArmorDarks** [pallets/jinja#580]
Hello

I'm quite new to this community, thus first of all I want to thank all maintainers and contributors for such great templating language.

My proposal is to make file extensions optional in extends, includes and imports.

For example, Instead of

``` twig
{% extends "layout.nj" %}
```

use

``` twig
{% extends "layout" %}
```

All extensions should be preconfigurated during Environment configuration, or in Loader. If omitted in configuration, it will fall back to default (current, extension-required) behavior.

This will make importing much more intelligent and predictable, while in same time expressive and less verbose. And less typing as bonus.

For example, let's assume we set our `ext` during configuration to `['.j2', '.html']`

``` jinja
{% include 'base' %}
```

Will look in following order for:

1. `base`
2. `base.j2`
4. `base.html`

``` jinja
{% include 'base.j2' %}
```

Will look in following order for:

1. `base.j2`
2. `base.j2.j2`
4. `base.j2.html`

``` jinja
{% include 'base/' %}
```

Will look in following order for:

1. `base/index`
2. `base/index.j2`
4. `base/index.html`

**Comment by ThiefMaster** [comment]
I dislike this idea a lot. "Explicit is better than implicit" and considering that the file extension can control features like autoescape this is even worse.

**Comment by ArmorDarks** [comment]
@ThiefMaster Thanks for reply

My general idea was to follow pattern, which already occurs in Python import statements:

``` python
from Jinja2 import Something
```

We do not specify here any extension, since we know, that this import is executed in Python environment and by default it will look for Python files.

Same is for Jinja2. When we call extend, import or include, it's executed in Jinja2 environment, and it's logical for it to look for default or preconfigurated for that environment extension.

So, basically, there is no "implicity" issue here.

Please, correct me, if I'm wrong. Maybe I'm really missing something obvious.

> considering that the file extension can control features like autoescape this is even worse.

Hm, that is some good thought. But so far I don't see where exactly it is an issue. You are configuring autoescaping for each extension independently. If you don't want Jinja2 to match some extension by default — just don't put them in configuration. In fact, that addition doesn't make any difference in terms of controlled by extensions autoescaping.

Once again, I assume I'm missing something here.

**Comment by ThiefMaster** [comment]
In python that only works because `jinja2/__init__.py` imports `Something` and unliky Jinja Python files have only on extension.

You are right about the autoescape part, but it's still confusing as soon as you end up with more than one candidate in the same folder.

**Comment by ArmorDarks** [comment]
> In python that only works because jinja2/__init__.py imports Something

If it won't import something via `__init__.py` we still will be able to use

``` python
import jinja2
```

to get everything.

Thus for me it still feels somehow alike.

> and unliky Jinja Python files have only on extension.

That is way I proposed to allow specify array of extensions.

In case if you importing something non-standard, you always can use explicit extension, same as in Python import:

``` jinja2
{% include 'symbol.svg' %}
```

But in all other cases you know that you already told to system your default extension, so you don't need to repeat it everytime in every include, import and extend.

> You are right about the autoescape part, but it's still confusing as soon as you end up with more than one candidate in the same folder.

I think this should be up to developer. If he puts files with same names and different extensions in same directory for purpose, he might opt not to use system.

However, so far I didn't encounter repositories, which will uphold templates with same names, but different extensions, in same directory. Probably because it would seem like an architectural issue.

**Comment by ThiefMaster** [comment]
`import jinja` will just let you access things defined in its `__init__.py` and possibly modules inside the package (but I'd have to test that to be 100% sure).

No, you cannot `import` non-`.py` files in Python since the dot is already the package/module separate so you cannot put file extensions there.

**Comment by jeffwidman** [comment]
I agree with @ThiefMaster, this is less explicit and opens a can of worms around potential edge cases.
