### ISSUE TITLE
Comment in list results in error

### ISSUE THREAD

**Issue by jakirkham** [pallets/jinja#589]
Suppose I have the following text provided to `jinja2.Template`.

``` jinja
{% set a_list = [
    "a",
    # "b",
    "c",
] %}
{{ a_list[-1] }}
```

It will complain that the `#` is improper syntax with this exception.

```
TemplateSyntaxError: unexpected char u'#' at 32
```

As soon as the commented line is remove the problem goes away.

```
<Template memory:...>
```

Here is the question. Is this acceptable jinja syntax or is this a bug?

**Comment by jakirkham** [comment]
cc @pelson

**Comment by ThiefMaster** [comment]
I don't think Jinja supports comments within statements.

**Comment by jakirkham** [comment]
So, let me explain the use case here. We added a list and we would like to add one element to that list in the future, but we realize it does not work now. How can we leave it in the list, but not include it until we can support it.

**Comment by mitsuhiko** [comment]
This is the intended behavior. Jinja has no inline comments.
