### ISSUE TITLE
Translation Comments

### ISSUE THREAD

**Issue by xethorn** [pallets/jinja#591]
Hello,

In one of the project I am working on, we need to make the distinction between two exact same strings based on the context. For instance: “To:” (can mean “Destination”, but it can also mean “To” as an end date). In Babel, there's support of [it](https://github.com/pallets/jinja/blob/5b498453b5898257b2287f14ef6c363799f1405a/jinja2/ext.py#L553), same as the [extractor in Jinja2](https://github.com/pallets/jinja/blob/d760b78a2f74156f6db85f5f50304b906f3f5d6b/tests/test_ext.py#L298). 

Yet, I'm unable (reading the documentation and code) to figure out how to configure the the `babel.cfg` so the right value is provided for `comment_tags` (see [`babel_extract`](https://github.com/pallets/jinja/blob/5b498453b5898257b2287f14ef6c363799f1405a/jinja2/ext.py#L553)), and when it's properly extracted, how to tell Jinja2 to consider those comments. Probably just a piece missing from the documentation. 

Many thanks.

**Comment by xethorn** [comment]
Found the solution for the extraction: for `pybabel extract`, add: `--add-comments="tag"`.  So if "tag" is: "i18n:", jinja2 code will look like:

```jinja
{# i18n: your message #}
{{ _("Text to translate") }}
```

**Comment by jeffwidman** [comment]
So do you think something should be added to the Jinja docs or are we good here?
