### ISSUE TITLE
Documentation on macros doesn't explain what the dashes in {%- macro -%} does

### ISSUE THREAD

**Issue by robvdl** [pallets/jinja#598]
The documentation for macros appears to be using an extra dash in template tags, though it appears to work either with or without the dashes.

e.g.

{%- macro textarea(name, value='', rows=10, cols=40) -%}

vs

{% macro textarea(name, value='', rows=10, cols=40) %}

The problem is I cannot find anything anywhere in the documentation what this dash actually does or means, or if it is even significant.

**Comment by davidism** [comment]
http://jinja.pocoo.org/docs/dev/templates/#whitespace-control
