### ISSUE TITLE
Variables set with `{% set %}` not available in templates included within blocks

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/jinja#603]
``` python
from jinja2 import DictLoader, Environment
loader = DictLoader({
    'a.html': '''
        {%- set foo = 'bar' -%}
        without block: {% include 'x.html' -%}
    ''',
    'b.html': '''
        {%- set foo = 'bar' -%}
        with block: {% block test %}{% include 'x.html' %}{% endblock -%}
        ''',
    'c.html': '''
        {%- set foo = 'bar' -%}
        with set inside block: {% block test %}{% set foo = foo %}{% include 'x.html' %}{% endblock -%}
    ''',
    'x.html': '''{{ foo -}} | {{- test }}'''
})

env = Environment(loader=loader)
print env.get_template('a.html').render(test='x')
print env.get_template('b.html').render(test='x')
print env.get_template('c.html').render(test='x')
```

Output:

```
without block: bar|x
with block: |x
with set inside block: bar|x
```

While it's easy to work around I'm not sure if this behavior is intended. Getting `bar|x` in all three cases would be more straightforward for sure.

**Comment by jackwilsdon** [comment]
Sounds like this is related to #352? It's kind of a big problem and it would be nice to get it fixed.

**Comment by jackwilsdon** [comment]
Oops, I guess that'll teach me to force push!

**Comment by mitsuhiko** [comment]
It's definitely intentional but I'm not sure what happens now if we change it. Will investigate as part of #637

**Comment by mitsuhiko** [comment]
I'm super undecided on what to do with this. If we want to change this then I'm all for deriving a context for blocks the same way as we do for includes and imports.

**Comment by mitsuhiko** [comment]
Related issue is #546 where variables do not propagate to include because derived contexts are based on the parent and not local scope.

**Comment by roba91** [comment]
Does this also fix the strange behavior when overwriting a block that the parent template included?

Minimal example:
```
templates/
 |--base.html
 |--nav.html
 +--page.html
```
***base.html***
```
<html>
<head>
  <title>Title</title>
</head>
<body>
  {% include 'nav.html' %}
  {% block content %}{% endblock %}
</body>
</html>
```
***nav.html***
```
<h1>Header 1</h1>
{% block more_headers %}{% endblock %}
```
***page.html***
```
{% extends 'base.html' %}
{% block more_headers %}<h2>Second header!</h2>{% endblock %}
{% block content %}
  Content!
{% endblock %}
```

This will not output the `h2`.

**Comment by davidism** [comment]
@roba91 you can test that against the latest code to find out if it's fixed. Either way, that seems like a different issue. Please make a different post if there isn't one already.

**Comment by anjanx44** [comment]
I am facing problem to assign variable in if condition
-------------------------------------------------------------------
`{% set check_file1 = 'kkkkkkkkkk' %}
{% for line in result_dir1.stdout_lines -%} 
	{% if line | regex_search(file1) == "CM_dump_NM-LEM01_201802160200.csv" -%}
		{% if line | regex_search('17:32') == "17:32" -%} 
			{{'time match'}}
			{% set check_file1 = 'aaaaaaaaaaaaaaaaa' %}
		{%- endif %} 
	{%- endif %} 
{%- endfor %} 
{{check_file1}}`

output
`ok: [VM08] => {
    "msg": "time match\n\t\t\t \nkkkkkkkkkk\n"
}`
