### ISSUE TITLE
Exceptions thrown inside properties cause confusing errors

### ISSUE THREAD

**Issue by stevelittlefish** [pallets/jinja#604]
This is something I've experienced many times, and it still always throws me.

First of all I use strict undefined for error reporting:

```
app.jinja_env.undefined = jinja2.StrictUndefined
```

I have a class with a property that throws an exception due to trying to read an undefined variable:

```
class MyClass(object):
    @property
    def my_prop(self):
        return self.doesnt_exist
```

Then I try to access that property inside a template:

```
<p>{{ my_object.my_prop }}</p>
```

I get the following exception:

```
  File "/home/steve/git/project/project/templates/main/index.html", line 7, in block "outer_content"
    <p>{{ my_object.my_prop }}</p>
jinja2.exceptions.UndefinedError: 'main.MyClass object' has no attribute 'my_prop'
```

This is obviously a contrived example, and I understand why it happens, but would this be possible to fix so that it's obvious that the exception was caused by `my_object.doesnt_exist` being undefined instead of `my_object.my_prop`?

**Comment by mitsuhiko** [comment]
There is sadly not really anything we can do about this.

**Comment by wjdp** [comment]
@mitsuhiko I've seen this quite a few times and it's perplexed a number of developers. This bug covers any exception that happens inside a property:

```python
class MyClass(object):
    @property
    def my_prop(self):
        raise Exception("Any error")
```

will yield `jinja2.exceptions.UndefinedError: 'main.MyClass object' has no attribute 'my_prop'` when used in a template.

When developers see this they are initially confused by the error. Once they've remembered this behaviour they have to implement a call on the python side to call this property to get the actual exception.

What makes this hard to fix?

**Comment by ThiefMaster** [comment]
The only way to (possibly) fix this would be by inspecting the traceback of the `AttributeError`... (I don't think it's supposed to convert any other kinds of exceptions to `Undefined`)
