### ISSUE TITLE
recursion and relative paths

### ISSUE THREAD

**Issue by onkelheidi** [pallets/jinja#605]
i encountered the following problem:
using

``` html
{% if toc %}
    <ul>
        {% for element in toc %}
            <li>{{ element.0 }}
                {% include "./toc.html" with toc=element.1 %}
            </li>
        {% endfor %}
    </ul>
{% endif %}
```

i receive an error `The relative path '"./toc.html"' was translated to template name 'markovium/snippets/toc.html', the same template in which the tag appears.`

> The code presented echos a simple table of contents. each element consists of [ "Title", [ ["List", [] ], ["with", [] ], [ "sub-elements" [] ]  ] ]
> so element.0 gives you the title (e.g. "Title" or "List") and element.1 returns the list of the subelements ( so [ ["List", [] ], ["with", [] ], [ "sub-elements" [] ]  ] for "Title" or [] for "List" )

using essentially the same code but changing the **relative path** to an **absolute path** i get no error message and the code is executed properly:

``` html
{% if toc %}
    <ul>
        {% for element in toc %}
            <li>{{ element.0 }}
                {% include "markovium/snippets/toc.html" with toc=element.1 %}
            </li>
        {% endfor %}
    </ul>
{% endif %}
```

**Comment by mitsuhiko** [comment]
Relative paths are not supported by Jinja2 out of the box so that's expected.
