### ISSUE TITLE
Maybe a problem，about windows path

### ISSUE THREAD

**Issue by berlinsaint** [pallets/jinja#607]
i wrote a custom filter wiht jinja2： 

the content of demo.py:

```
import jinja2
from jinja2 import  Environment

scriptLoader = jinja2.FileSystemLoader(searchpath='.')#
env = Environment(loader=scriptLoader)
def extract(_factory_args, *_factory_kwargs):
    def _extract(path, _request_args, *_request_kwargs):
        print request_args[0]
        return 0
    return _extract

env.filters['extract'] = extract()
tpl = env.get_template("demo.tpl")
print tpl.render()
```

and the demo.tpl is:
`{{"error"|extract("E:\project_test\Edu_Root3.0\OnlineService\data\320068142153001.txt")}}`

after rendered,  the jinja2 render '\320' to be \xd, and result like this,
E:\project_test\Edu_Root3.0\OnlineService\dataÐ068142153001.txt

this is wrong result. i want it to be E:\project_test\Edu_Root3.0\OnlineService\data\320068142153001.txt

i know one solution is  change the path in tpl, but is there any other method that deal it well in jinja2 filter's funtion?

**Comment by ThiefMaster** [comment]
Simply escape the backslashes..

**Comment by berlinsaint** [comment]
Because  user can copy from windows‘s explorer, and  not want modify it self. 
Now i use re library to replace them , but i still confused about  how jinja2  deal with it, and what does it do in dealing  wih the  ‘\’ character

**Comment by davidism** [comment]
That's just not how strings work in Python. Escape characters are going to escape things.
