### ISSUE TITLE
found UndefinedError: 'dict object' has no attribute 'iteritem' error with Python 2.x

### ISSUE THREAD

**Issue by GitProBo** [pallets/jinja#611]
{% for key, value in row.items() %}
UndefinedError: 'dict object' has no attribute 'iteritem'

Python 2.7.12 (default, Sep  9 2016, 11:24:49) 
#pip list jinja2
Jinja2 (2.8)

**Comment by NormanDenayer** [comment]
I suspect the problem is not in jinja itself because the following code works well:

``` bash
$ python
Python 2.7.12 (default, Oct 11 2016, 09:23:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jinja2 import Environment
>>> rows = {'foo': 'bar', 'foo2': 'bar2'}
>>> my_str = Environment().from_string('{% for i, e in rows.items() %}{{i}}={{e}}\n{%endfor%}').render(rows=rows)
>>> print(my_str)
foo=bar
foo2=bar2

>>> import jinja2
>>> jinja2.__version__
'2.8'
```

my guess is you should look at `row`base class implementation.
(indeed dict objects have iteritem**s** and no iteritem)

**Comment by davidism** [comment]
@NormanDenayer thanks for checking this. @GitProBo if you're still having this issue, please post a minimal example that reproduces it.
