### ISSUE TITLE
jinja template conflict with front-end template

### ISSUE THREAD

**Issue by htlhenry** [pallets/jinja#615]
hello, i use flask with jinja2 template engine to render html, but i also use front-end template.js.
I got this error message :  
```
    <%for(var system in data){%>
   TemplateSyntaxError: tag name expected
```
This is my code in template file, the code in html file don't use jinja2 engine render is ok.
```
<script type="text/html" id="test-js">
    <%for(var system in data){%>
        <ul>system: <%=system%></ul>
    <%}%>
</script>
```
I search on google and StackOverflow don't get similar problem, so i'm create this issue， thank you very much.

**Comment by zoidbergwill** [comment]
It's probably because `{%` is ambiguous and could be the beginning of a Jinja2 tag.

You probably wanna try look at the [Escaping](http://jinja.pocoo.org/docs/dev/templates/#escaping) docs.

You probably want something like:

```
    <%for(var system in data){{ '{%' }}>
        <ul>system: <%=system%></ul>
    <{{ '%}' }}%>
```
 
Because then Jinja2 will output the HTML you expect for template.js.

**Comment by davidism** [comment]
http://stackoverflow.com/questions/30362950/is-it-possible-to-use-angular-with-the-jinja2-template-engine

**Comment by htlhenry** [comment]
thanks @zoidbergwill
I know the reason ,```{```and```%```  can't together, they must middle left space, right code:
```
<script type="text/html" id="test-js">
    <%  for(var system in data){  %>
        <ul>system: <%=system%></ul>
    <%  }  %>
</script>
```
