### ISSUE TITLE
environments render failing to decode dictionary

### ISSUE THREAD

**Issue by andreanidouglas** [pallets/jinja#621]
see errorlog

Python 3.5 changelog inside flask
https://gist.github.com/anonymous/faeb2e6d75f571406fbfdcd5cc3356dd

```
return render_template('echo.html', text='ola')
```
```
<h1>

    You Said: {{ text }}

</h1>
```

**Comment by davidism** [comment]
I can't reproduce your issue.  Please include a test that demonstrates the issue.

**Comment by andreanidouglas** [comment]
https://github.com/andreanidouglas/python-blog it works on python 3.4 but not on python 3.5, you can just try to render the echo.html template passing a value from the view module

**Comment by ThiefMaster** [comment]
Does it happen with a minimal test case like this one?

```python
import flask
app = flask.Flask(__name__)
with app.app_context():
    print(flask.render_template_string('text: {{ text }}', text='hi'))
```

Because for me that one works.

```
[adrian@blackhole:/tmp/test]> python --version
Python 3.5.2
[adrian@blackhole:/tmp/test]> python test.py
text: hi
```

**Comment by andreanidouglas** [comment]
it works, i will close the issue and look further to see if there is any bug in the code.

thanks

**Comment by ThiefMaster** [comment]
I didn't spot one. If you have the flask debugger enabled check what `args` and `kwargs` contains in the last stack frame (`vars = dict(*args, **kwargs)`)
