### ISSUE TITLE
Output finalize function issue

### ISSUE THREAD

**Issue by tzzt** [pallets/jinja#63]
The finalize function seems to be executed on the whole template, not only on variables.

E.g. a function like 
def fin(s): print s; return s 
dumps the whole template file.

**Comment by godsarmy** [comment]
is this fixed? i still see it in the latest version (2.8).

```
rom jinja2 import Environment, Template

context = {'k': 'v'}

template = """
abc
{{ k }}
def
"""

def fin(data):
    return 'replaced'

env = Environment(finalize=fin)

tpl = env.from_string(template, template_class=Template)

print tpl.render(**context)
```

It displayed 'replacedreplacedreplaced', we want this to be fixed as we need this feature very explicitly
