### ISSUE TITLE
Add `rel="noopener"` option to `urlize` built-in filter for better security

### ISSUE THREAD

**Issue by nirfse** [pallets/jinja#633]
Please consider adding  `rel=noopener` option to the `urlize` built-in filter. Probably you might consider adding it automatically, if `target="_blank"` is set, however I'm not sure it won't break anything. Security concerns [are clearly outlined](https://mathiasbynens.github.io/rel-noopener/) by @mathiasbynens.

According to the [documentation](http://jinja.pocoo.org/docs/dev/templates/#urlize),`urlize(value, trim_url_limit=None, nofollow=False, target=None)` currently utilizes only `rel=nofollow`.

**Comment by mitsuhiko** [comment]
I'm unhappy with the entire urlize filter. I rather have it follow some security policy that you configure with the environment.

**Comment by mitsuhiko** [comment]
With 2.9 this can be configured with policies now.
