### ISSUE TITLE
Issue with jinja2.9 and flask-assets

### ISSUE THREAD

**Issue by mohamed-aziz** [pallets/jinja#644]
There seems to be an issue while using flask-assets with jinja 2.9 and 2.9.1 in the template there isn't the asset_url.

[This test](https://github.com/miracle2k/flask-assets/blob/master/tests/test_env.py) fails with jinja2.9 and 2.9.1 but works with 2.8.1.

**Comment by ThiefMaster** [comment]
It would be helpful if you included information on how exactly that test fails.

**Comment by mohamed-aziz** [comment]
assert t.render() == '/static/file1;/static/file2;'

the t.render() returns ';;'

**Comment by davidism** [comment]
Please include a self-contained example that reproduces the issue.

**Comment by ThiefMaster** [comment]
I wonder if https://github.com/miracle2k/webassets/blob/master/src/webassets/ext/jinja2.py#L87 is using any undocumented APIs and/or relying on Jinja internals that changed with @mitsuhiko's recent scoping changes...

**Comment by mitsuhiko** [comment]
I don't even know what this is supposed to do. It sets the arguments to the call block to context `store` as name context. That seems wrong.

**Comment by mohamed-aziz** [comment]
@davidism sur

app.py

    from flask import Flask, render_template
    from flask_assets import Environment, Bundle


    app = Flask(__name__)
    assets = Environment(app)
    js = Bundle(
            'js/app.js',
            output='gen/app.js'
            )
    assets.register(
            'js_all',
            js
            )

    @app.route('/')
    def index():
        return render_template('index.html')

    if __name__ == '__main__':
        app.run()

index.html

	<html>
		{% assets "js_all" %}
		<script src="{{ ASSET_URL }}"></script>
		{% endassets %}
	</html>

with jinja2>2.9

	λ ~/ http :5000   
	HTTP/1.0 200 OK
	Content-Length: 49
	Content-Type: text/html; charset=utf-8
	Date: Sat, 07 Jan 2017 22:58:47 GMT
	Server: Werkzeug/0.11.15 Python/3.6.0

		<html>

			<script src=""></script>

		</html>


with jinja2<2.9

	λ ~/ http :5000   
	HTTP/1.0 200 OK
	Content-Length: 76
	Content-Type: text/html; charset=utf-8
	Date: Sat, 07 Jan 2017 23:00:29 GMT
	Server: Werkzeug/0.11.15 Python/3.6.0

		<html>

			<script src="/static/gen/app.js?491dc8f8"></script>

		</html>

**Comment by mitsuhiko** [comment]
From what I can tell this is an issue in webassets. I left a comment here: https://github.com/miracle2k/webassets/issues/477

Closing there here until someone proves this wrong :)
