### ISSUE TITLE
Jinja2-2.9 and Python3 generate <generator> tag

### ISSUE THREAD

**Issue by tk0miya** [pallets/jinja#645]
With 2.9, 2.9.1 and 2.9.2, Jinja2 generates `<generator>` tag for macro having blocks.

Example code:
```
import sys
import jinja2
from jinja2 import Template

template = """
{%- macro hello() %}
  Hello, {% block name %}jinja2{% endblock %}!
{%- endmacro %}
{{ hello() }}
"""
```

Result:
```
Python vesion: 3.5.2 (default, Oct 11 2016, 17:23:55)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Jinja2 vesion: 2.9.2

<generator object macro at 0x10ffe2468>
```

But this works fine on python2.7.
```
Python vesion: 2.7.13 (default, Dec 20 2016, 13:27:09)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Jinja2 vesion: 2.9.2


  Hello, jinja2!
```

Note: result of 2.8 and py27, py35.
```
Python vesion: 2.7.13 (default, Dec 20 2016, 13:27:09)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Jinja2 vesion: 2.8.1


  Hello, jinja2!
```
```
Python vesion: 3.5.2 (default, Oct 11 2016, 17:23:55)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Jinja2 vesion: 2.8.1


  Hello, jinja2!
```

**Comment by mitsuhiko** [comment]
What does it even mean to have a `{% block %}` inside a macro O_O.

**Comment by mitsuhiko** [comment]
It does the same now it did in earlier versions however I'm surprised this does something useful.

**Comment by cdeil** [comment]
@mitsuhiko - Thanks for fixing it. Could you please make a patch release soon?

This issue is affecting other Sphinx projects, e.g. the sidebar from the Astropy docs disappeared recently and it took me some time to find this issue:
https://github.com/astropy/astropy/issues/5679#issuecomment-271175414
It's particularly nasty since there's no warning or error from Sphinx, but the generated HTML is corrupted.

**Comment by mitsuhiko** [comment]
Yes, there will be another one tonight. I just want to see if there is not anything else creeping up.

**Comment by mitsuhiko** [comment]
Release is out now.

**Comment by tk0miya** [comment]
I confirmed it works fine :-)
Thank you for quick fix!
