### ISSUE TITLE
Bytecode cache does not invalidate old items, leading to spurious errors after 2.8->2.9 upgrade

### ISSUE THREAD

**Issue by rbu** [pallets/jinja#650]
I've performed a 2.8.1->2.9.3 upgrade and experienced inexplicable macro errors*. When debugging these, the errors went away, and it turned out they were caused by the bytecode cache. Entries generated with Jinja 2.8 stayed in the cache and were found by 2.9.

The documentation or changelog makes no mention of a necessity for cleaning the bytecode during a version upgrade, so I would consider it a bug Jinja does not invalidate entries made using a previous version automatically. Thoughts?

* For example, the macro argument count would be identified incorrectly, leading to runtime errors such as this:
```
    {{ abc.ABC(request, "one", "two") }}
TypeError: macro() takes exactly 3 arguments (4 given)
```

even when the macro is defined as
```
{% macro ABC(request, class_one="", class_two="") %}
```

**Comment by mitsuhiko** [comment]
That's indeed an oversight.

**Comment by rbu** [comment]
Thanks for the quick fix!
