### ISSUE TITLE
v2.9 resets variable values on each pass of a for-loop

### ISSUE THREAD

**Issue by MinchinWeb** [pallets/jinja#656]
In the past, I've set a variable during a for-loop, and then referenced it on subsequent passes through the loop. This worked in version 2.8.1. On upgrading, this behavior changes, and now the variable value at the beginning of the for-loop is the same as it was for the first pass through the loop.

## Expected Behavior (works in v2.8.1)
False True / True True / True True / True True / True True /

## Actual Behavior (as reported by v2.9.0 and 2.9.4)
False True / False True / False True / False True / False True /

## Template Code
```jinja
{% set k = False %}
{% for _ in range(5) %}
    {{ k }}
    {% set k = True %}
    {{ k }}
    /
{% endfor %}
```

## Full Traceback
[no exception thrown]

## Your Environment
* Python version: 3.6.0 (64 bit)
* Jinja version: 2.9.4
* OS: Windows 10 x64
* template code is being run through Pelican 3.6.3

**Comment by mitsuhiko** [comment]
This was never intended to work and if variables reset or not depended on various factors and it always reset at the end of the loop. This is considered a bug and it's unlikely the bug will be reintroduced.

See #641 for an ongoing conversation about it.
