### ISSUE TITLE
2.9.3 `with` code generation bug

### ISSUE THREAD

**Issue by brookskindle** [pallets/jinja#657]
Looking at the [changelog](https://github.com/pallets/jinja/blob/4e7fd1a521223c6627cfcd02db48a8e1765079ca/CHANGES#L41), 2.9.3 rewrote the code generation for the `with` statement.

This prevents variables defined in an opening `with` block 
```jinja2
{%- with -%}  {# <-- this line right here #}
...
{%- endwith -%}
```
from being accessed in the same opening `with` block.

## Expected Behavior
If two variables are defined in an opening `with` block (a and b) then you should be able to set the default value of the second variable to be equal to the first. (a=1, b=a)

## Actual Behavior
This presumably sets the default value of the second variable to None, or whatever jinja2's equivalent is.

## Template Code
```jinja2
{%- with a=1, b=a -%}
  {{ a }} | {{ b }}
{%- endwith -%}
```
This would just result in `1|`

## Alternate Template Code
```jinja2
{%- with a={}, b=a.update({1:2}) -%}
  {{ a }}     
{%- endwith -%}
```

If, for example, you use a dictionary as a default value, [like flask_bootstrap does](https://github.com/mbr/flask-bootstrap/blob/c5df414cfcfe94b6a706de65de338dce9d18dc70/flask_bootstrap/templates/bootstrap/pagination.html#L20), then you won't be able to access one of its methods (like `update`) without getting the following traceback.

## Full Traceback
```pytb
self = <jinja2.environment.Environment object at 0x7f11a163fbe0>, obj = Undefined
attribute = 'update'

    def getattr(self, obj, attribute):
        """Get an item or attribute of an object but prefer the attribute.
            Unlike :meth:`getitem` the attribute *must* be a bytestring.
            """
        try:
>           return getattr(obj, attribute)
E           jinja2.exceptions.UndefinedError: 'a' is undefined

```

## Your Environment
* Python version: 3.5.2
* Jinja version: 2.9.3

To be honest, I'm not sure if I want to call this a "bug", but it was a thing that existed prior to 2.9.3. I'm bringing this to light because [flask_bootstrap](https://github.com/mbr/flask-bootstrap) uses it, so there might be other projects out there that relied on this functionality.

**Comment by mitsuhiko** [comment]
Annoyingly this is actually the root of a pretty severe scoping bug which is why I had to change it. IF you did for instance `{% with a=b, b=42 %}` unclear things would happen under the new scoping rules. This definitely was not intended behavior.

I'm willing to just define the new behavior the intended one going forward with 2.9.

**Comment by jeffwidman** [comment]
If this does end up being "worksasdesigned", then @brookskindle do you mind filing a bug against `flask_bootstrap`?

I use `flask_bootstrap` myself on a few projects, so trying to avoid the inevitability that I will forget about this issue when upgrading dependencies.

**Comment by brookskindle** [comment]
Yeah if it broke when moving from 2.8.x to 2.9.x I probably wouldn't have investigated too deeply, but I tried this out on 2.9.2 and it worked, hence why I put `bug` in the title.

@mitsuhiko do you think this is worth documenting / putting a notice somewhere in the documentation that "the following code does not work" (or something like that)?

@jeffwidman Already ahead of you :) See https://github.com/mbr/flask-bootstrap/pull/149, author notes that 3.3.7.1 has the fix. None of the other libraries/projects that I use have run into this problem, but that doesn't mean they don't exist.
