### ISSUE TITLE
Conditionally install async{support,filter}.py

### ISSUE THREAD

**Issue by thmo** [pallets/jinja#662]
Would it be possible to skip installing asyncsupport.py and asyncfilter.py in case the python version in use doesn't have async support?

Background: When creating RPM packages for Fedora, all Python files get bytecompiled in advance. This fails for the two files mentioned for system Python versions < 3.6, failing the package build process. A workaround would be to try to skip bytecompiling these two files, or simply have them removed by the spec file after the install step.

**Comment by ThiefMaster** [comment]
Related: #643, #655, #653

**Comment by ThiefMaster** [comment]
https://github.com/pallets/jinja/issues/653#issuecomment-271647267 should avoid failing

**Comment by davidism** [comment]
What do you mean by "skip installing"? All the source goes in the sdist (the .tar.gz file), there aren't multiple sdists.

**Comment by thmo** [comment]
I meant `setup.py install`, not `sdist`.

**Comment by mitsuhiko** [comment]
@thmo you will need to file this against your build tool. This was fixed in pip.

**Comment by thmo** [comment]
Not sure I understand. I'm simply calling `setup.py install` and that installs `.py` files into standard Python locations, which are *not valid* Python files, at least for Python < 3.6. That's got nothing to do with RPM. 

Adding workarounds to hide the fact that theses files cannot be byte-compiled is imho sweeping the original problem under the carpet. (How does pip differentiate between "valid" byte-compilation errors, and real ones?)

**Comment by mitsuhiko** [comment]
@thmo these files are not imported so that is not an issue. Bytecompilation is supposed to skip over files it cannot byte compile as a result of this. pip does this correctly.

**Comment by ricard33** [comment]
Some packaging tools like PyInstaller need to load every modules to try to find dependencies. This is not a solution for them to ignore loading/parsing error because these errors have to be reported to the user. 
Currently, I haven't any solution to exclude these incompatible files from PyInstaller analysis. And I think it would be a lot cleaner to not install modules that can't be load by current python interpreter.
