### ISSUE TITLE
Assignment to variable in loop failing in Jinja 2.9

### ISSUE THREAD

**Issue by aabdnn** [pallets/jinja#663]
## Expected Behavior

If I use {% set %} to set a variable in a template, I should be able to change the value of that variable later in the template, inside loops. This works in Jinja 2.8, but appears to be broken in Jinja 2.9.

## Actual Behavior
The variable's value appears to get lost on every iteration of a loop.

## Template Code
```jinja
{% set count = 0 %}
{% for x in range(10) %}
{% if count < 3 %}
{{ count }}
{% set count = count+1 %}
{% endif %}
{% endfor %}
```

## Full Traceback
No traceback

## Your Environment
* Python version: 2.7.13
* Jinja version: 2.9.4

**Comment by kblomqvist** [comment]
Duplicate with #641.
