### ISSUE TITLE
Jinja doesn't deal well with generators

### ISSUE THREAD

**Issue by nowox** [pallets/jinja#680]
Consider this simple code: 

```
In [0]: from jinja2 import Template
    ...: def gen10():
    ...:     for i in range(10):
    ...:         yield i
    ...:
    ...: Template("{% for i in data %} {{i}}{% endfor %}\n" * 2).render(data = gen10())
    ...:
Out[0]: u' 0 1 2 3 4 5 6 7 8 9\n'
```

I was expecting my template to return `0123456789 0123456789`. The explanation is not difficult, but I think Jinja could detect generators and consume them recursively when the context is built. 

This has to be done recursively because I could imagine something like: 

```
def gen():
    for i in range(10):
        yield gen()
```

**Comment by ThiefMaster** [comment]
I don't think the would be a good idea. If I iterate over something in Jinja I don't expect any automated recursion in case one of the items is also a generator / iterable / list / ...

**Comment by nowox** [comment]
So could I do something like this instead: 

```
Template("{% for i in data() %} {{i}}{% endfor %}\n" * 2).render(data = gen10)
```

**Comment by ThiefMaster** [comment]
Have you tried it? That should work.

**Comment by nowox** [comment]
Yeah it works :) So it could be the answer to my question actually...
