### ISSUE TITLE
Truncate breaks xml escaped characters if no whitespace is in the string

### ISSUE THREAD

**Issue by DennyWeinberg** [pallets/jinja#689]
jinja may be xml independent, but I think that it should be handled, no? Since this library is also widely used for html generation.

## Expected Behavior
Characters like &amp; should not be truncated if there are no spaces in the string
--> `Gemeinschaftspraxis&#xA;C.Detemple/Dr.K.Konkol ...`

## Actual Behavior
&amp; is transformed into &
--> `Gemeinschaftspraxis&#xA;C.Detemple/Dr.K.Konkol& ...`

## Template Code
```jinja
{{ 'Gemeinschaftspraxis&#xA;C.Detemple/Dr.K.Konkol&#xA;Ärztinnen f. Gynäkologie'|truncate(50) }}
```

## Your Environment
* Python version: 3.6.0
* Jinja version: All

## Code suggestion
```
if '&' in result[-3:]:
    result = result.rsplit('&', 1)[0]
```

Please reject this issue if you are not agreed.

**Comment by ThiefMaster** [comment]
There is absolutely no way for Jinja to know whether it is dealing with HTML or not.

Is there any reasaon you have HTML entities in your text? In the era of Unicode there's rarely a good reason for this. Assuming you have proper (ie unescaped) data in your DB you should truncate it while it's still unescaped unicode and only then perform HTML escaping and similar processing.

**Comment by DennyWeinberg** [comment]
OK. Thank you. So you can close this issue.

**Comment by davidism** [comment]
You can always write your own truncate and replace the filter.
