### ISSUE TITLE
Unable to convert int to binary string

### ISSUE THREAD

**Issue by Alko89** [pallets/jinja#694]
I want to format an integer to binary string. I have tried different formats and nothing seems to work.
If I try:

`{{ '%b'|format(12) }}`

`Error in your values input filed: unsupported format character 'b' (0x62) at index 1`

Or:

`{{ '{:b}'|format(12) }}`

`Error in your values input filed: not all arguments converted during string formatting`

Doing the same thing in python (`"{:b}".format(12)`) returns:
`1100`

**Comment by ThiefMaster** [comment]
Jinja uses the normal `%` formatting of Python in the format filter.

However, you can use `'{:b}'.format(12)` (not sure where you got the idea that `%b` is a thing ;))
