### ISSUE TITLE
nodes.Const class AttributeError

### ISSUE THREAD

**Issue by jjkalucki** [pallets/jinja#698]
## Expected Behavior
No exception rising.

## Actual Behavior
I encountered problem with current jinja2 library while using it in few of my projects.
In version 2.9.5 of jinja2.nodes.Const.as_const() method, exception is rising:
AttributeError: 'NoneType' object has no attribute 'policies' in line 484.
Patch in attachment.

[nodes.txt](https://github.com/pallets/jinja/files/886752/nodes.txt)

**Comment by davidism** [comment]
Closing as there's not enough information to reproduce the issue. Either this was fixed at some point, or you're doing something custom, but currently all nodes have `environment` set by the time they get compiled. If this is still an issue for you, please provide a minimal example or a PR with tests.
