### ISSUE TITLE
please add a "pyformat" filter

### ISSUE THREAD

**Issue by mfrasca** [pallets/jinja#70]
the current implementation of filters allows us to pipe one value through filters and combine the effect of each step.

I see the "format" filter as an exception.

it filters a format according to values, instead of filtering a value according to a format.

I think the following filter would be more useful:

    def do_pyformat(value, format):
        """return float according to format
        """

        return soft_unicode("%" + format) % value

you would use it like this:

    ...] {{ length | float | pyformat("0.1f") }} m [...

this follows the documentation of the old `format` filter, as I found it on http://wsgiarea.pocoo.org/jinja/docs/filters.html#format

**Comment by chris-hailstorm** [comment]
Here's a simple approach with a user-defined filter.  If the overall filter behavior of this appeals to you, one of us could easily add to Jinja standard filters and make a pull request.  Your thoughts this on this?

(1) example of a message to be interpolated -- a custom flask-security error message:

    SECURITY_MSG_CONFIRMATION_REQUIRED = ('This email address has not been confirmed. '\
        'Please click on the link in the email we sent you. To receive the confirmation '\
        'email again, <a href="{0.url_root}confirm">click here</a>.', 'error')

(2) custom filter defined in a flask app, for example:

    def _jinja_interp(text, obj):
        return text.format(obj)
    
    app.jinja_env.filters['interp'] = _jinja_interp

(3) filter as used used in a Jinja template:

    {% for error in field.errors %}
        ... other stuff ....
        {{ error | interp(request) | safe }}
    {% endfor %}

This allows simple string interpolation via a filter, given a dictionary to interpolate from -- exact analog of `'string {placeholder}'.format(**some_dict)` in typical Python.  Can be filter-piped on to subsequent filters.

**Comment by jeffwidman** [comment]
I think the `pyformat` filter is unlikely to get implemented/merged.
