### ISSUE TITLE
list filter that can cast string to list with one element

### ISSUE THREAD

**Issue by mattymo** [pallets/jinja#705]
## Expected Behavior
Tell us what should happen
"myval" | list would be useful if it returned ['myval']

It would be convenient to be able to take a var that might be a string or a list and then treat it as either a single element list OR a list with multiple values.

## Actual Behavior
Tell us what happens instead
['m','y','v','a','l']
## Template Code
```jinja
Paste the template code (ideally a minimal example) that causes the issue

```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception

```

## Your Environment
* Python version: 2.7
* Jinja version: 2.8

**Comment by ThiefMaster** [comment]
This would be quite different from what `list()` in python does so I think it would be rather misleading. If you want to convert a string to a list simply use `[....]`

**Comment by magnetik** [comment]
I agree with the confuseness caused by the use of `list` for this, but this filter would be usefull to have a **short way** to cast a single item into a list of one item or doing nothing if variable is already a list.

**Comment by reyjrar** [comment]
FWIW, not having an "Up Convert to a List" is a huge oversight.  Let's say I'm dealing with data from ElasticSearch.  Any key could be a string *or* a list of strings.  Without the capacity to treat each key as a potential list I have to write ugly go-betweens like:
```
{% set an_actual_list = document.key|string()|ternary([document.key],document.key) %}
```

The use case for a templating language and a programming language are dramatically different.
