### ISSUE TITLE
High compute-time penalty for Unicode identifiers

### ISSUE THREAD

**Issue by mcondarelli** [pallets/jinja#707]
Hi, I'm using Jinja2 in a rather underpowered embedded (MIPS24KEc/580 MHz) and I found out startup time ("import jinja2") is unacceptably slow (>12sec).

I traced the bulk of delay to _stringdefs.py / lexer.py specifically to compilation of "name_re" regular expression (>10 sec!).
Reverting to this to the "ASCII only" regex drops time to an acceptable level.

IF I understand correctly this regex is used to parse identifiers; as such using full Unicode seems overzealous (especially so since it has this large impact).

Would it be possible to make it a configuration option?
Perhaps making current behavior "default" would minimize impact on current users; it would even be possible to think about a "the-state" setting with the "plain ASCII" as fallback and a "compromise" with a few accented letters, but without full blown Unicode (does it even make sense? for identifiers?)

I also suspect (but I didn't measure) the full blown Unicode regex carries a sizeable runtime penalty with little usability gain.

I saw #666 and I fully agree with @ThiefMaster that "IMO using non-ascii chars in identifiers is an awful idea"; I also understand it's perhaps too late to revert default behavior, but having some config option would be helpful (to avoid directly editing the code).

In general this makes me wonder if there are other such "smart" trade-offs in the code... did I miss something?

## Your Environment
* Python version: 3.6.1
* Jinja version: 2.9.5

**Comment by ThiefMaster** [comment]
Since this is import-time behavior a setting would be hard to implement. However, you could probably add a custom `sys.modules['jinja2._stringdefs']` before importing jinja...

**Comment by mcondarelli** [comment]
Thanks for the prompt answer.

Personally I edited lexer.py not to include jinja2._stringdefs at all (in a rather brutal way; see patch below), but I still think it would be a nice feature to have in the mainstream version.

It seems there's little attention for performance issues (central in the embedded world, but admittedly secondary on a Web Server).
BTW: I already had to completely ditch Flask/connext because it had a (on another embedded) a startup time >5min.

As I'm active in the embedded/Buildroot area I was directed to ask to Jinja2 developers what they think about the issue before considering such a "solution" for the issue...
So, here I am ;)
Any comment is very welcome.
Thanks.

 
===============================================
diff -ru a/jinja2/lexer.py b/jinja2/lexer.py
--- a/jinja2/lexer.py<->2017-04-27 11:45:04.459555267 +0200
+++ b/jinja2/lexer.py<->2017-04-27 11:46:47.988306713 +0200
@@ -34,28 +34,29 @@
                        r'|"([^"\\]*(?:\\.[^"\\]*)*)")', re.S)
 integer_re = re.compile(r'\d+')

-def _make_name_re():
-    try:
-        compile('föö', '<unknown>', 'eval')
-    except SyntaxError:
-        return re.compile(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b')
-
-    import jinja2
-    from jinja2 import _stringdefs
-    name_re = re.compile(r'[%s][%s]*' % (_stringdefs.xid_start,
-                                         _stringdefs.xid_continue))
-
-    # Save some memory here
-    sys.modules.pop('jinja2._stringdefs')
-    del _stringdefs
-    del jinja2._stringdefs
-
-    return name_re
-
-# we use the unicode identifier rule if this python version is able
-# to handle unicode identifiers, otherwise the standard ASCII one.
-name_re = _make_name_re()
-del _make_name_re
+name_re = re.compile(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b')
.
 float_re = re.compile(r'(?<!\.)\d+\.\d+')
 newline_re = re.compile(r'(\r\n|\r|\n)')

**Comment by davidism** [comment]
You're describing a pretty specialized case, I'd just do what Thief suggested or what you're doing.

We could move the import and regex generation into the Lexer, then allow overriding the regex with an Environment attr used in `get_lexer`, but I'm not really sure it's worth the effort and added complexity.

**Comment by mcondarelli** [comment]
Thanks.
I will see what we can do on our side.
I would suggest a warning about this in the docs so whoever will need speed could use the same technique, hopefully having less pain to find the "culprit".
Thanks and Regards.

**Comment by davidism** [comment]
Should be solved by #731.
