### ISSUE TITLE
Newline issue when trim_blocks and lstrip_blocks are set

### ISSUE THREAD

**Issue by FabriceSalvaire** [pallets/jinja#713]
When trim_blocks and lstrip_blocks are set, we had to add a space character to keep the newline in this template:

```jinja
{% for n in (1, 2, 3) %}
    {{n}}{% if not loop.last %},{% endif %}<space>
{% endfor %}
```

However this one works as expected

```jinja
{% for n in (1, 2, 3) %}
    {{n}}
{% endfor %}
```

and return

```
  1
  2
  3
```

## Your Environment
* Python version: 3.5
* Jinja version: 2.9.6

**Comment by jrschneider** [comment]
+1
Jinja: 2.10
Python: 3.5.2 (Ubuntu 16.04.5 LTS)

**Comment by kevin-brown** [comment]
This lines up with the documented behaviour of `trim_blocks`.

> If this is set to True the first newline after a block is removed (block, not variable tag!). Defaults to False.

Since the `{% endif %}` is a block, the newline that immediately follows it is stripped. You don't see this with the working version because it doesn't have a block inside the `{% for %}` loop.
