### ISSUE TITLE
unable to parse custom extension template tag nodes in parallel?

### ISSUE THREAD

**Issue by AlJohri** [pallets/jinja#715]
Hi, I have a custom extension that takes a JSON and returns text by hitting an external API. It works fine at the moment, but I want to batch the calls to this external API. If I use my extension in a dozen places throughout a template, ideally it still only makes one API call.

I tried to have the extension return a `nodes.Dict` instead, but this creates a weird situation where I have a document that is half text and half json. This issue is related to #714. In that issue, I take the approach of turning the entire document into a json and hitting the API with that big json.

In my current approach, I'm trying to essentially get something along the lines of a **compiled AST**. A tree of nodes that are already compiled and rendered and I can walk through the tree and find all nodes of a particular type to run some batch post processing on them.

The extension is pretty simple:

```python
class SimpleNLGExtension(Extension):
    tags = set(['simplenlg'])

    def parse(self, parser):
        lineno = next(parser.stream).lineno
        ctx_ref = nodes.ContextReference()
        body = parser.parse_statements(['name:endsimplenlg'], drop_needle=True)
        node = self.call_method('_render_simplenlg', [ctx_ref], lineno=lineno)
        return nodes.CallBlock(node, [], [], body).set_lineno(lineno)

    def _render_simplenlg(self, context, caller):
        # return nodes.Dict(json.loads(caller()))
        response = requests.post(SIMPLENLG_API, json=json.loads(caller()))
        return response.json()['text']
```

Any help would be appreciated. Thanks!

**Comment by davidism** [comment]
Closing as there's been no development and this seems more like an implementation question rather than a bug. I don't know what the right answer for your use case is, but it seems like you're trying to do too much work in the template. If you need to introspect the AST, it might be time for a custom `CodeGenerator` instead.
