### ISSUE TITLE
[feature request] context aware template loader?

### ISSUE THREAD

**Issue by AlJohri** [pallets/jinja#716]
http://jinja.pocoo.org/docs/2.9/api/#loaders

It would be helpful to have a context aware template loader. I want to change which template is loaded based on an attribute in the context. The use case here is overriding a template.

**Comment by davidism** [comment]
The loader API doesn't take a context, that's part of the render process after you already have a template.

You can already pass a template object or path to extends with a variable.

    {% extends other_template %}

**Comment by AlJohri** [comment]
@davidism, my current issue is naming conflicts between context variable names and template names which is why I like using strings instead. I am considering implementing an alternative template tag, let's call it `include2` for the time being, used as `{% include2 'asdf' %}`, that could serve as a context aware template loader. does this seem like a reasonable approach?

thanks!

**Comment by davidism** [comment]
I don't understand what you mean. You can name variables whatever you want, independent of the strings they hold or other values in the template. Import can take variables just like extends.

**Comment by AlJohri** [comment]
@davidism just to clarify, while I can name variables whatever I want, I'm working in a system where both the `context` and the `template` themselves are out of my control. I've run into situations in the past where someone creates a variable named `state` and adds it to the context and also creates a template named `state` and intends to include that into their template.

For now, I'm namespacing the templates under a variable `t` to prevent these collisions. So someone can write a template like:

```
This is a state: {{ state }}

This is the state template:
{% include t.state %}
```

If the `include` (or another template tag `include2`) was context aware and took a string instead, this conflict would not occur.

**Comment by ThiefMaster** [comment]
But the include tag DOES take a string:

`{% include 'state' %}` includes the template with the name `state`, without looking at any variables.

**Comment by AlJohri** [comment]
Yup! I understand that.

However, it will use the template loader which isn't content aware. I need to load a different template based on some information in the context (i.e. some sort of override id).

The error occurs when I do something like:

```
context_from_user = {'state': 'NJ', story_id: 1}
additional_referenced_templates = {'state': sometemp} # queries from a database based on the Include nodes in the template and the story_id from the context
context = {**context_from_user, **additional_referenced_templates}
template.render(context)
```

Basically, it would clean up the logic a lot if I could use a **context aware** template loader that encapsulated this logic instead of sticking the templates into the context.

This might be too much of an edge case, but I've run into this more than a few times.

**Comment by AlJohri** [comment]
Is there any way to load templates relative to the caller? I currently namespace each of my templates and I want to be able to load templates relative to the current namespace. So if I'm loading a template with the namespace "my.current.namespace" and I try to load template "lede", I want it to first search "my.current.namespace" for that template.

So is there anyway to pass information to the template loader regarding the current namespace / the caller template? If not, I need to resolve the relative template name into an absolute template path and I'm not sure where that code would go either.
