### ISSUE TITLE
AST to jinja templates

### ISSUE THREAD

**Issue by dek-odoo** [pallets/jinja#719]
Is there any way to convert the AST (Abstract Syntax Tree) back into the jinja template ?

What I want to do is update the jinja2 templates, and only good way seems to be through AST.
So If I update AST, can I then get back the jinja2 template ?

I checked other issues and sources, but could not find anything relevant.
Thank you.

**Comment by ThiefMaster** [comment]
no. i believe it's impossible to get back the exact template since whitespace stripping happens in the lexer. comments are probably discarded at this point too.

**Comment by dek-odoo** [comment]
Its no problem if comments are discarded, but not even any bad solution ?
And what if I make changes in AST ?

Thanks for the quick reply.

**Comment by dek-odoo** [comment]
@davidism @mitsuhiko

**Comment by ThiefMaster** [comment]
You'd probably still need to write a custom code generation that builds jinja code from the AST.

**Comment by dek-odoo** [comment]
any clues or hints on how I can do that, please ?
Or don't you think this is a needed feature ?

If I need to change templates, regex does not look a robust option, AST manipulation looks only way.
