### ISSUE TITLE
Vim syntax file and jinja parser handle nested comments differently

### ISSUE THREAD

**Issue by jpassaro** [pallets/jinja#720]
## Expected Behavior
Jinja parser and the shipped Vim plugin have the same interpretation of comment blocks.

## Actual Behavior
They interpret them differently!
The jinja parser does not support nested comments. The vim syntax file apparently thinks it does.

## Template Code
```jinja
{# stuff.txt #}
1. This is a jinja document!
{#
2. This section was commented out recently.
{# 3. This section was commented out a long time ago.
4. This is the end of the newly-commented-out section.
#}
5. This section is supposed to appear, but Vim thinks it is a comment.
{# vim: ft=jinja
#}
```
Attempting to render:
```pycon
>>> import jinja2, sys
>>> with open('stuff.txt') as f: print jinja2.Template(f.read()).render()
...

1. This is a jinja document!

5. This section is supposed to appear, but Vim thinks it is a comment.

>>> print sys.version
2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
>>> print jinja2.__version__
2.9.5
```
Vim screenshot:
![screen shot 2017-06-01 at 1 04 52 pm](https://cloud.githubusercontent.com/assets/6754005/26691397/f3b1552e-46ca-11e7-8d50-a0e7770e9159.png)

**Comment by davidism** [comment]
I don't use vim. If you want this fixed, you're going to need to contribute a patch.

**Comment by jpassaro** [comment]
Sure, I only raised the issue to document the problem while I was working on it.

However as I was working on one I found that [a different one is available](/mitsuhiko/vim-jinja) that doesn't have this issue.

Maybe worthwhile to at least mention this defect and/or @mitsuhiko's alternative in the provided syntax file? Or just replacing the broken syntax file with a copy from that repo? I'm happy to create a patch based on your preferences. Otherwise please feel free to close.
