### ISSUE TITLE
No variable templating when using map()

### ISSUE THREAD

**Issue by Jackyjjc** [pallets/jinja#723]
## Expected Behavior
I expect this template to generate the following list: 
```
[u'testbc', u'detestf']
```

## Actual Behavior
```
[u'{{ some_var }}bc', u'de{{ some_var }}f']
```

## Template Code
```python
from jinja2 import Template

templateString = "{{ some_list | map('replace', 'a', '{{ some_var }}') | list }}"

template = Template(templateString)
values = {'some_list': ['abc', 'deaf'], 'some_var': 'test'}
print "{}".format(template.render(values))

```

## Your Environment
* Python version: Python 2.7.13
* Jinja version: Jinja2 (2.9.6)

**Comment by davidism** [comment]
`map('replace', 'a', some_var)`, you don't use Jinja expression syntax when you're already in an expression.
