### ISSUE TITLE
documentation question about nested block

### ISSUE THREAD

**Issue by calmzhu** [pallets/jinja#724]
I tried the [doc about nested block](http://jinja.pocoo.org/docs/dev/templates/#block-nesting-and-scope)

file "base":
```
===
{% block a %}{% endblock %}
===
```

file "child"
```
{% if not Standalone %} {% extends "base" %}{% endif %}
{% for item in ("a","b","c") %}
  {% set int = loop.index %}
  {% block a scoped %}
  {{ int }} : {{ item }}
  {% endblock %}  
{% endfor %}         
                     
{% block another %}
   another  block only in child
{% endblock %}       
                     
{% for item in (1,) %}                                                                                                                                                          
   {% block other %}
      other block only in child          
   {% endblock %}  
{% endfor %} 
{% for item in (1,) %}
   something in child out of block 
{% endfor %}
```
out put:
```

  1 : a

  2 : b

  3 : c

      other block only in child
   ===

   :

===

```
Maybe this is a bad practice.
Is this output normal ?I am confused about this behavior  :

1.  {% block another %} and {% block other %} are both only in child but not defined in parent .But only one nested in for loop was rendered to finally output .
4.  {% block a %} was in a for loop .But where did the ":" in the last 3 line  come from ?
4. So How would jinja deal block and text defined only in child but not in parent while template inheritances used.
4. when re-defined same named block in neither child nor base. It will throw error exception while rendering. So what's the difference when put it in a for loop.It appeared 4 times?
4. by the way. with scoped enabled. block  can access  outer var now.but loop.index seemed not accessible directly

**Comment by davidism** [comment]
There's just a bunch of weird template nesting here along with a lot of questions. And it's not super clear to me what's going on or what's being asked. This does not seem like a standard use of templates. Closing due to age. If someone runs across this and thinks they have a better example of the specific behavior, please open a new issue.
