### ISSUE TITLE
Round filter behavior inconsistent between python2 and python3

### ISSUE THREAD

**Issue by shawnsi** [pallets/jinja#725]
## Expected Behavior
Return values from the `round` filter are identical between python2/3.

## Actual Behavior
Using this test script:

```python
import jinja2

template = jinja2.Template('{{ 0.5 | round }}')
print(template.render())
```

I see this behavior:

```bash
$ python2 /tmp/jinja-test.py          
1.0
$ python3 /tmp/jinja-test.py          
0.0
```

## Template Code
```jinja
{{ 0.5 | round }}
```

## Your Environment
* Python2 version: 2.7.13
* Python3 version: 3.6.1
* Jinja version: 2.9.6

**Comment by davidism** [comment]
Yes, the rounding behavior was changed. https://stackoverflow.com/questions/10825926/python-3-x-rounding-behavior

**Comment by shawnsi** [comment]
Thanks @davidism.  The jinja2 documentation doesn't reflect this though and I'm consuming that filter rather than the python method.  Shouldn't the project address this more clearly?

**Comment by davidism** [comment]
The filter just passes to the Python function.

**Comment by shawnsi** [comment]
You know that buy your users may not.  Just trying to help other people save time debugging this and avoid a similar issue being reported in the future.
