### ISSUE TITLE
Scope of outermost part of child template

### ISSUE THREAD

**Issue by ant5** [pallets/jinja#726]
There are some problem with scope in outermost (out of any block) part of child template.
Parents outermost variables is not availble from outermost part of child template but normally visible inside a block. 

---
## Template Code
base.html:
```
{% set basestr = 'John' -%}

{% block X %}
{% endblock X %}
```

child.html:
```
{% extends 'base.html' %}

{% set childstr = 'Mary' %}
{% set child_hello = 'Hello,'~ childstr %}
{% set base_hello = 'Hello,'~ basestr %}

{%- block X %}
 basestr: {{basestr}}
 childstr: {{childstr}}
 base_hello: {{base_hello}}
 child_hello: {{child_hello}}
{% endblock %}
```
## Expected Behavior
basestr: John
childstr: Mary
base_hello: Hello,John
child_hello: Hello,Mary 

## Actual Behavior
basestr: John
childstr: Mary
base_hello: Hello,
child_hello: Hello,Mary 

## Your Environment
* Python version: 2.7.13
* Jinja version: 2.9.6

**Comment by kevin-brown** [comment]
This is actually documented at https://jinja.palletsprojects.com/en/2.10.x/templates/#block-nesting-and-scope

The solution is to specify `scoped` on the `{% block X %}` and it will include the `basestr` variable in the child template
