### ISSUE TITLE
_make_name_re causes very slow jinja2 imports due to abuse of regexes

### ISSUE THREAD

**Issue by lf-** [pallets/jinja#729]
## Expected Behavior
Jinja2 should import near-instantly

## Actual Behavior
It imports in almost 250 milliseconds

## Repro Code
```python
import time
start = time.time()
import jinja2
end = time.time()
print('Jinja2 took ', end-start, 's to import')
```

Output: `Jinja2 took  0.2398972511291504 s to import`

The profiler shows that (in the profiled run), 289 ms was spent in _make_name_re in lexer.py.

Upon further inspection, I found that this line:

```python
name_re = re.compile(r'[%s][%s]*' % (_stringdefs.xid_start,
                                     _stringdefs.xid_continue))
```

is the culprit, taking around 159 ms to run. It's incredibly slow because of the sheer length of the regex.

## Your Environment
* Python version: 3.6.1
* Jinja version: 2.9.6 (found similarly slow results on a git checkout seconds before submitting this)

**Comment by davidism** [comment]
This had come up a few times. I wonder if there's a better way to validate names?

**Comment by lf-** [comment]
Probably. It looks like the regex is basically just testing if a character is in a certain range (which someone wrote a script to automatically generate that range). There already is a script that generates this range which needs reading.

I think we can actually reduce the time this takes considerably at runtime as well since it can most likely be reduced to character code (read: integer) comparisons.

**Comment by lf-** [comment]
I'm poking around in the source for that particular module. It's evident that the author was likely going to do something sensible, but then realized that there were combining characters.

It seems that the code actually has a bug in it: Take for example `\u0327`. That's a combining cedilla, which puts a cedilla on a character before it. That means that `c\u0327` will look like `ç`. On normalization, it is turned into `ç`. The current code normalizes just the characters in the list it pulls from unicodedata. That means that `\u0327` normalizes to `\u0327` and thus names with combining characters may behave weirdly.

What I'm planning to do and submit as a patch, is to move all this into runtime since it takes microseconds to find unicode character categories, which should be a hell of a lot faster than regexes.

**Comment by davidism** [comment]
ping @mitsuhiko

**Comment by lf-** [comment]
Hm. I can check if a string is a valid name, but I don't know how to integrate it into the parser. Can you (or anyone else) provide some assistance on that front?

**Comment by davidism** [comment]
I'm not very familiar with this code, I'd need to review when I have more time. I'm not sure exactly where this is used, but if it's really just for validating names, maybe something in the built-in libraries can validate names. Assuming we follow the same naming rules in Jinja. For example:

```python
try:
    compile(
        source='{name} = 1'.format(name=name),
        filename='<input>',
        mode='single'
    )
except SyntaxError:
    # not a valid name
```

**Comment by lf-** [comment]
Well, in writing property-based tests for my checking code, I broke the old one several times:

```
𐲟Υ𝑼Ỻ𝖥ЮЯӸꝢᏗ
𒑧𐅈𒑌𐅯𒑀𒐤𒐥𐏓𒐁ⅼ
𐅧𐅧Ⅼ𒐆𒐝𒐞𐅉𐅖𒐈𐅆
```

According to the categories, these should be legit names. They're not according to the old name checker.

**Comment by mitsuhiko** [comment]
If someone sends a PR with a better solution I'm happy to merge. But it needs to still match the Python 3 identifiers.

**Comment by lf-** [comment]
Please clarify what you mean by "match the python 3 identifiers". Do you mean the solution *needs* to use compile? Or that it still falls back to ASCII?

**Comment by mitsuhiko** [comment]
It means the lexer must still support Unicode identifiers on Python 3. I don't really care about how :)

**Comment by lf-** [comment]
@mitsuhiko my PR should definitely do that.
