### ISSUE TITLE
Optimizer seems too restricted

### ISSUE THREAD

**Issue by davidism** [pallets/jinja#733]
While looking at #476, I noticed that `Optimizer` only folds certain nodes. For example, `Concat` nodes are not optimized, but should be. Since all it's doing is trying to call `node.as_const`, and all `Expr` nodes define `as_const` and raise `Impossible` appropriately, can we safely make `fold` apply to all nodes that define `as_const`? Something like:

```python
def generic_visit(self, node):
    if hasattr(node, 'as_const'):
        try:
            return self.fold(node)
        except Impossible:
            pass

    return super().generic_visit(node)
```

@mitsuhiko

**Comment by mitsuhiko** [comment]
It looks sane but I'm not quite sure if there are some unintended consequences to this. As far as I know it should not break anything or it was not sound before either.

**Comment by davidism** [comment]
@mitsuhiko thanks, just wanted to check that there weren't any obvious problems or design reasons before going forward.
