### ISSUE TITLE
Order of filter arguments 'attribute' and 'case_sensitive'

### ISSUE THREAD

**Issue by davidism** [pallets/jinja#736]
`sort` initially didn't take an `attribute` argument, so when it was added, `case_sensitive` came first. Therefore, you have to do `sort(attribute='name')` to specify the attribute only. Now we've added `unique`, `min`, and `max`, all of which take both arguments. I think it makes more sense for `attribute` to come first, but for consistency should we keep it second even for new filters?

~Aside: I also think `case_sensitive` should default to true, not false, especially since `str.lower` is not very robust for Unicode.~

**Comment by ThiefMaster** [comment]
> Aside: I also think case_sensitive should default to true

Not for sorting for sure. In templates you almost never want a case-sensitive sort, it's not very human-friendly and that's what sorting in templates is usually used for.

**Comment by davidism** [comment]
#737 makes the order `attribute, case_sensitive` for `unique`, `min`, and `max`, but we can change it back if we decide that's what we want.

**Comment by ThiefMaster** [comment]
While I think people should be using a kwarg for `case_sensitive` since `|sort(true)` is not very clear, we can't expect everyone to have done that. So I'd prefer to not break people's templates...

**Comment by davidism** [comment]
Not going to change `sort` or `dictsort`, just talking about new filters. Mostly concerned with consistency: if `sort` is one way and `unique` is the other, people may be confused.

**Comment by ThiefMaster** [comment]
I'd rather keep the same order in the new filters to avoid this kind of confusion. I think using kwargs for any of these arguments is clearer anyway

**Comment by davidism** [comment]
Yeah, being consistent is probably a better idea here. I'll change the examples to use kwargs consistently too.
