### ISSUE TITLE
2.9 template optimizer seems to apply filters too early.

### ISSUE THREAD

**Issue by mjpieters** [pallets/jinja#739]
A `{{ [1, 2, 3] | random }}` interpolation results in **one** value being picked and re-used, no matter how often that interpolation is run inside a loop:

```sh
$ cat test.py
from jinja2 import Template
template = Template('''
{%- for i in range(10) -%}
{{ ['foo', 'bar', 'baz', 'eggs', 'ham', 'spam'] | random }}{{ ' ' }}
{%- endfor %}
''')
print(template.render())
$ python3 test.py
baz baz baz baz baz baz baz baz baz baz
```

This started with 2.9 and is present in 2.9.6 still. 2.8.1 doesn't show this behaviour (downgrading with pip install -U Jinja2==2.8.1 results in a proper random series of choices).

When you make the list a variable, things work as expected as well, so `{% set seq = [...] %}` then `{{ seq | random }}` works fine, as well as passing in the sequence as a template variable on rendering.

**Comment by davidism** [comment]
Fixed by #734
