### ISSUE TITLE
Provide an easy way to disable Jinja template caching

### ISSUE THREAD

**Issue by radiantone** [pallets/jinja#744]
I use jinja as part of my Flask application. I don't create the jinja Environment, it is done for me.
I need a way to control caching that Jinja does. This behavior recently changed and Jinja's caching is either not doing what is expected or conflicting with Flask or other caching systems.

Changes to templates and/or imported files (not templates) are being masked due to Jinja caching only the template and not considering other files that have changed. This behavior is undesirable, especially when developing.

---

## Expected Behavior
Whenever I change a template, or any file imported by a template, the change should be visible in my browser when Flask user_reloader or debug mode is on. I should be able to disable Jinja caching after the environment is created because in many situations I do not control the creation of the environment. Nor want to.

## Actual Behavior
Regardless if I edit a template or change a javascript file imported by it, the change is not reflected when I refresh my page. This forces me to restart my app to see the changes, a lengthy nuisance.

I set 
application.config['TEMPLATES_AUTO_RELOAD'] = True
and the page still does not refresh properly.

```

## Your Environment
* Python version: 2.7.12
* Jinja version: 2.9.6

**Comment by davidism** [comment]
`env = Environment(cache_size=0)` or `env.cache = None`
