### ISSUE TITLE
Feature request: StrictSandboxedEnvironment

### ISSUE THREAD

**Issue by estianross** [pallets/jinja#756]
Our team is in need of a very strict sandboxed environment which uses a whitelisting approach to security. All methods on dev defined objects should automatically be seen as unsafe unless marked with @safe contrary to the current approach of making everything fair game and forcing devs to annotate every method on every model including the standard types python provides.

**Comment by davidism** [comment]
Is there something stopping you from implementing such an environment with the existing classes and methods?

**Comment by estianross** [comment]
Experience

**Comment by ThiefMaster** [comment]
Which you will quickly gain by trying to implement it yourself by subclassing the existing SandboxedEnvironment ;)

**Comment by estianross** [comment]
I will be attempting this in my spare time not on company time. Care to share a few pointers on where to even start? The sphinx generated documentation is.. quite unfriendly

**Comment by ThiefMaster** [comment]
Look at the docs and the code of the sandboxed environment. That's pretty helpful. And you can always ask on IRC if needed.

BTW, while I'm not your boss, you should be allowed to to this on company time if you need this functionality for a work project. This is basically using a - very flexible - feature of Jinja to make it work the way you need it. But of course you'd then need to check with your superiors about contributing it back upstream if you want to do that...
