### ISSUE TITLE
String comparison result changed in 2.9

### ISSUE THREAD

**Issue by jpek-m** [pallets/jinja#761]
This script tries to find list of different initials from a name list. It gives wrong result with Jinja2==2.9.6 but runs ok with Jinja2=2.8. Is the problem in` for loop`, `string` comparison or in my code?

## Expected Behavior
Script output with Jinja2 2.8: repeating identical values are recognized:

     "" | "" != ""
     "" | "" != ""
     "Arctopolitanus" | "A" != "" - a new initial
     "Bergenheim" | "B" != "A" - a new initial
     "Borg" | "B" != "B"
     "Chydenius" | "C" != "B" - a new initial
     "Haartman" | "H" != "C" - a new initial
     "Heikkinen" | "H" != "H"

## Actual Behavior
Script output with current Jinja2 2.9.6: repeating same initial not recocnized:

    "" | "" != ""
    "" | "" != ""
    "Arctopolitanus" | "A" != "" - a new initial
    "Bergenheim" | "B" != "" - a new initial
    "Borg" | "B" != "" - a new initial
    "Chydenius" | "C" != "" - a new initial
    "Haartman" | "H" != "" - a new initial
    "Heikkinen" | "H" != "" - a new initial 

## Template Code (python3)
```
    from flask import Flask, render_template 
    import jinja2, sys

    app = Flask(__name__)
    t = jinja2.Template(
    """
    {% for p in persons %}
        {% set ini = p|list|first %}
        <p> "{{p}}" | "{{ini}}" != "{{alpha}}" 
        {% if alpha != ini %}
           {% set alpha = ini %} - a new initial 
        {% endif %} </p> 
    {% endfor %}
    """)

    @app.route('/')
    def index():
        n = ("", "", "Arctopolitanus", "Bergenheim", "Borg", "Chydenius", "Haartman", "Heikkinen")
        return render_template(t, persons=n)
    print(jinja2.__version__)
    print(sys.version)

    if __name__ == '__main__':
       app.run(debug='DEBUG')
```

## Your Environment
* Python version: 3.5.2
* Jinja version: 2.9.6 and 2.8

**Comment by ThiefMaster** [comment]
Sounds like an (overly complicated ;)) case of #641.

There are a bunch of workarounds in that issue's thread and the next Jinja version will also contain some sugar to make it even easier to handle the case of "did something change since the last loop".
