### ISSUE TITLE
Variables from included templates are not visible in parent template

### ISSUE THREAD

**Issue by vlad0337187** [pallets/jinja#770]
Hello.

## Short info
From [documentation](http://jinja.pocoo.org/docs/2.9/templates/) I didn't understood, must or not must be so, that variables from included template doesn't appear in parent template.
If to look on other programming languages (like C, Nim), keyword "include" includes all content (including variables) of target file to current.
I read, that it must return rendered context into current namespace, but does it must include defined variables, or no ? (sorry, maybe because of my bad English I didn't understood this)
Also I tried "with context" "without context" with "include" keyword - nothing worked. With "import" all worked well.

## Expected Behavior
I want to figure this out. If it's not a bug, than sorry for disturbing.

## Actual Behavior
Variables from included template doesn't appear in parent template.

## Template Code
```jinja
#! /usr/bin/python3


from jinja2 import DictLoader, Environment




loader = DictLoader({

    'base.html': '''
    
{% include 'links.html' %}

<html>
	<head>
		<title>
			Website for testing bugs.
		</title>
	</head>
	<body>
		{{ link_1 }}
		{{ link_2 }}
	</body>
</html>

    ''',
    
    
    'links.html': '''
    
{% set link_1 %}
	string inside link_1
{% endset %}

{% set link_2 = 'string inside link_2' %}

        ''',
})

env = Environment(loader=loader)
base_template = env.get_template('base.html')

print (base_template.render())

```

## Full Traceback
Absent.

## Your Environment
* Python version: 3.5, 3.6
* Jinja version: 2.9.6

Best regards,
Vladislav

**Comment by kevin-brown** [comment]
I think this is behaving as documented?

> The include statement is useful to include a template and return the rendered contents of that file into the current namespace

So it's rendering `links.html` (which has nothing to render except whitespace) and including that into `base.html`. When you `{% include %}` a template it includes the _rendered results_, which means that it behaves similar to if you called `get_template('links.html')` and then passed the results into the template as context.
