### ISSUE TITLE
Context is not passed to included template, if that context was imported

### ISSUE THREAD

**Issue by vlad0337187** [pallets/jinja#771]
## Expected Behavior
According to [documentation](http://jinja.pocoo.org/docs/2.9/templates/#import-context-behavior), `included templates are passed the current context`.
This means, that variables from parent templates may be passed to included ones.
Also, `You can import a complete template into a variable` by `{% import 'forms.html' as forms %}`.

So when we, in parent template, import complete template into a variable, than include child template, all variables from parent template may be passed to included one.

## Actual Behavior
When we, in parent template, import complete template into a variable, than include child template, only that variables, which were defined in parent template, are passed to included one.
That variable, which contains complete template and which was created when we imported whole template, is not passed to included template.

## Template Code

```python
from jinja2 import DictLoader, Environment

loader = DictLoader({
    'base.html': '''{% import 'links.html' as links %}
{% set link_3 = "link_3 text. Included, because it's defined in parent template" %}
{% include 'body.html' %}''',
    'body.html': '''{{ link_1 }}
{{ link_2 }}
{{ link_3 }}''',
    'links.html': '''{% set link_1 %}
link_1 text. Must be included
{% endset %}
{% set link_2 = 'link_2 text. Must be included' %}''',
})

env = Environment(loader=loader)
base_template = env.get_template('base.html')
print (base_template.render())
```

Only link_3 text is output.

```
link_3 text. Included, because it's defined in parent template
```

## Your Environment
* Python version: 3.5
* Jinja version: 2.9.6

**Comment by davidism** [comment]
You imported `links`, so you need to render `{{ links.link_1 }}` and `{{ links.link_2 }}`. Alternatively, `{% from 'links.html' import link_1, link_2 %}` to import the names directly.
