### ISSUE TITLE
A rendered template should not remove the last '\n' character

### ISSUE THREAD

**Issue by tntmatthews** [pallets/jinja#777]
## Expected Behavior
A jinja2 rendered template should not remove the last '\n' character.  

## MCVE
import jinja2

orig_str = \
'''This is my jinja template.

'''

env = jinja2.Environment()
templ = env.get_template(jinja2.Template(orig_str))
rendered_str = templ.render()

print('orig_str: %s' % orig_str)
print('orig_str line count: %s' % orig_str.count('\n'))
print('---')
print('rendered_str: %s' % rendered_str)
print('rendered_str line count: %s' % rendered_str.count('\n'))

**Comment by davidism** [comment]
There's already an option on the environment for this.
