### ISSUE TITLE
Docs inconsistent with current version

### ISSUE THREAD

**Issue by wjdp** [pallets/jinja#781]
## Expected Behavior
The for loop loop.previtem property should be avaliable in 2.9.6 as it is shown on the docs site with the title of *Jinja2 2.9.6 documentation*

See http://jinja2.readthedocs.io/en/latest/templates.html#for

## Actual Behavior
`'jinja2.runtime.LoopContext object' has no attribute 'previtem'` as 2.9.6 does not contain the previtem property.

## Template Code
```jinja
{% for x in y %}
  {{ loop.previtem }}
{% endfor %}
```

## Full Traceback
```pytb
'jinja2.runtime.LoopContext object' has no attribute 'previtem'
```

## Your Environment
* Python version: 3.5.2
* Jinja version: 2.9.6

**Comment by ThiefMaster** [comment]
The docs for the latest release are here: http://jinja2.readthedocs.io/en/stable/templates.html#for
The `latest` docs are based on git master.

Anyway, I think we should release a 2.10 soon. ping @mitsuhiko

**Comment by wjdp** [comment]
Ah, couldn't find the docs for stable, the domain redirects to /latest by default. Perhaps /stable should be the default?
