### ISSUE TITLE
Loop properties revindex and revindex0 still wrong in Jinja2 2.10

### ISSUE THREAD

**Issue by unusual-thoughts** [pallets/jinja#794]
## Expected Behavior
`loop.revindex` should be 1 when using a reversed iterator of length 1
```python
jinja2.Template("{% for i in lst|reverse %}{{ loop.revindex }}:{{ i }}, {% endfor %}")
      .render(lst=[10])
```
should print out: `'1:10, '`

## Actual Behavior
The index of the only iteration is set to 2
```python
jinja2.Template("{% for i in lst|reverse %}{{ loop.revindex }}:{{ i }}, {% endfor %}")
      .render(lst=[10])
```
prints out: `'2:10, '`

**However**:
```python
jinja2.Template("{% for i in lst|reverse %}{{ loop.revindex }}:{{ i }}, {% endfor %}")
      .render(lst=[10, 11])
```
correctly prints out: `'2:11, 1:10, '`

## Template Code
```jinja
{% for i in lst|reverse %}{{ loop.revindex }}:{{ i }}, {% endfor %}
```

## Your Environment
* Python version: 3.6.4
* Jinja version: 2.10

**Comment by unusual-thoughts** [comment]
Related to https://github.com/pallets/jinja/issues/244#issuecomment-356029542

**Comment by FreddieChopin** [comment]
Also related to #751

**Comment by asenov** [comment]
Fix is so easy

**Comment by davidism** [comment]
@asenov if this is easy for you, it would be helpful if you submitted a patch. We welcome constructive contributions.

**Comment by asenov** [comment]
And my question here is what about the following code and output: 
``
jinja2.Template("{% for i in lst|reverse %}{{ loop.index }}:{{ i }}, {% endfor %}")
      .render(lst=[10, 11])
``
As following: 
``
jinja2.Template("{% for i in lst|reverse %}{{ loop.revindex }}:{{ i }}, {% endfor %}")
      .render(lst=[10, 11])
``
?

**Comment by wuwentao2000** [comment]
got the same length 2 error.
Any updates or workaround about this issue?

**Comment by aayushuppal** [comment]
working on this as part of pycon pallets sprint.

**Comment by markroth8** [comment]
Also seems related to #459

**Comment by aayushuppal** [comment]
Should be fixed in https://github.com/pallets/jinja/pull/993
