### ISSUE TITLE
docs/templates#if-expression code isn't formatted well

### ISSUE THREAD

**Issue by mvolfik** [pallets/jinja#800]
As you can see on website docs (http://jinja.pocoo.org/docs/dev/templates/#if-expression), code there isn't well formatted. Simple to fix I think, but I'm very new here so just reporting. I think it's related to https://github.com/pallets/jinja/commit/5ffbf8e5715bb4512b14427ba237b61f484a39c4#diff-0f54a58b39617a700a0b750e7a8bf07e

Sorry for bad English and issue formatting...

**Comment by davidism** [comment]
Good catch, thanks.
