### ISSUE TITLE
Any way to get variables keys from jinja2 template string?

### ISSUE THREAD

**Issue by jkryanchou** [pallets/jinja#808]
Here is the code snippet I have initialized jinja2 template

```
from jinja2 import Template

templ = Template("{{foo}} to {{bar}}")
```

And I am willing to extract the template string variable keys from the template obj as below.

templ.keys() == ["foo", "bar"]

Is there any API to make it work? I have searched for a long while but got nothing work.

**Comment by mcouthon** [comment]
+1!

**Comment by davidism** [comment]
http://jinja.pocoo.org/docs/dev/api/#jinja2.meta.find_undeclared_variables

**Comment by thoth291** [comment]
@davidism, Thank you for your reply above - it makes perfect sense for `simple` variables.
But what should I do with `nested variables` like `foo.bar`?
Is thee any way to get those too?

Using the method above I can get `foo`, but I'm not getting `foo.bar`.
