### ISSUE TITLE
embedded javascript comments cannot contain bad  Jinja2

### ISSUE THREAD

**Issue by MrBillium** [pallets/jinja#810]
I found out the hard way that commented out javascript is still parsed for Jinja2 and so can generate errors .

```
// this is a comment line in a  javascript block that works
// this a comment line in   javascript that does not work {{ bogusVar | tojson }}
```
---

## Expected Behavior
commented out javascript should not be parsed for Jinja2 

## Actual Behavior
commented out javascript is parsed for Jinja2 so if the Jinja2 is bad then the browser throws an error

## Template Code
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <script type="text/javascript">

     // this is a comment line in a  javascript block that works
     // this a comment line in   javascript that does not work {{ bogusVar | tojson }}
    // this a comment line in   javascript that DOES work - missing double bracket before bogus { bogusVar | tojson }}
    

        var a = 3;
        var b = 4;
        var ret = a + b;

 </script>
</body>
</html>
```
``
## errors
TypeError: Object of type 'Undefined' is not JSON serializable

File "C:\Users\Bill\Documents\Projects\PenguinProject\code_checkout\coldsureweb\ColdSureWeb\templates\foo.html", line 12, in top-level template code
// this a comment line in   javascript that does not work {{ bogusVar | tojson }}

```

## Your Environment
* Python 3.6
* Jinja version: 2.10

**Comment by ThiefMaster** [comment]
Of course. Jinja doesn't care about anything but the Jinja syntax. Wrap the JS blocks in `{% raw %}...{% endraw %}` or even better, don't inline JS in your templates...
