### ISSUE TITLE
FileSystemLoader.get_source expecting a variable which is unused

### ISSUE THREAD

**Issue by brunoripa** [pallets/jinja#816]
## Expected Behavior

Was trying to understand the Jinja2 loader and its logic to retrieve file system templates.

## Actual Behavior
No misbehaviour, but spotted a method signature, for `FileSystemLoader.get_source` which is expecting an unused `environment` variable.

here: https://github.com/pallets/jinja/blob/master/jinja2/loaders.py#L167

Code is:

```
    def get_source(self, environment, template):
        pieces = split_template_path(template)
        for searchpath in self.searchpath:
            filename = path.join(searchpath, *pieces)
            f = open_if_exists(filename)
            if f is None:
                continue
            try:
                contents = f.read().decode(self.encoding)
            finally:
                f.close()

            mtime = path.getmtime(filename)

            def uptodate():
                try:
                    return path.getmtime(filename) == mtime
                except OSError:
                    return False
            return contents, filename, uptodate
        raise TemplateNotFound(template)
```

## Template Code
None available

## Full Traceback
None available

## Your Environment
* Python version: irrelevant
* Jinja version: 2.10

**Comment by jackwilsdon** [comment]
It looks like this is because it overrides the `get_source` method of `BaseLoader` (which it inherits from), and therefore needs the same signature.
