### ISSUE TITLE
Custom templatetag implementation

### ISSUE THREAD

**Issue by Darkskope** [pallets/jinja#817]
I am switching an existing Django project's templates to jinja2. I use crispy forms (https://github.com/django-crispy-forms/django-crispy-forms/)  to render all forms in the project but jinja2 does not understand the {% crispy form %} tag. I need help with an extension that registers the crispy form tags in jinja2

Environment
* Python version: 3.6
* Jinja version: 2.10

**Comment by ThiefMaster** [comment]
You cannot use a tag written for Django templates in Jinja - look at its code what it does, maybe you can re-implement it as a Jinja extension.
