### ISSUE TITLE
Documentation: some intersphinx entries are wrong

### ISSUE THREAD

**Issue by Kapeli** [pallets/jinja#830]
The intersphinx entry for "With Statement" is wrong, as it points to http://jinja.pocoo.org/docs/2.10/extensions/#with-extension instead of http://jinja.pocoo.org/docs/2.10/templates/#with-statement

Steps to reproduce:
1. Run `python -msphinx.ext.intersphinx http://jinja.pocoo.org/docs/2.10/objects.inv`
2. Search for "With Statement"
3. Notice that the path is set to `extensions/#with-extension`, instead of `templates/#with-statement`

"Loop Controls" and "Autoescape Extension" are also affected by this.

**Comment by davidism** [comment]
That's the entry for the `with-expression` reference, there is no reference for the `with-statement` header on the templates page.
