### ISSUE TITLE
ext/jinja.el is GPL, not BSD

### ISSUE THREAD

**Issue by televi** [pallets/jinja#833]
## Expected Behavior
Files should not be GPLv2 (or v3) licensed as (I think) that implies all of Jinja2 is GPL.

## Actual Behavior
The file ext/jinja.el is GPL v2 licensed.  It says you can use later versions but still of GPL.  As such, Jinja2 is expected to include a copy of the GPL along with the other software/licenses.

## Template Code
```jinja
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation; either version 2, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 51 Franklin Street, Fifth
;; Floor, Boston, MA 02110-1301, USA.
```

## Full Traceback
```pytb
N/A
```

## Your Environment
* Python version: 3
* Jinja version: 2.10 (but that file hasn't been touched in 7 years so likely everything for the last 7 years?)

**Comment by mihaolteanu** [comment]
For some reason the latest released source code still contains this file.

The release seems to contain this commit: https://github.com/pallets/jinja/compare/2.10.1...master but the source code still contains the file: https://github.com/pallets/jinja/archive/2.10.1.zip

Could you please clarify? Would it be possible to remove this file after dynamically linking the jinja2 library?

Thank you!

**Comment by mitsuhiko** [comment]
Not sure I understand the question but this file is unnecessary. It has been removed from the repository since.

**Comment by mihaolteanu** [comment]
I noticed there was a build failure. Maybe this prevented the commit to be included in the release?

https://travis-ci.org/pallets/jinja/jobs/359579479

**Comment by ThiefMaster** [comment]
that's not how CI-based deployments/releases work ;) (not sure if we even use CI to build releases)

**Comment by mihaolteanu** [comment]
Ok. could you please advise :) ? We are using the jinja2 library and we are having a licensing issue due to this particular file.
Thank you!

**Comment by ThiefMaster** [comment]
just FYI, if you install the wheel that file is not included.

also, the file never gets loaded and I don't think (but: IANAL!) that having a GPL file merely *exist* will affect any other code unless it's actually used/executed/...

**Comment by mihaolteanu** [comment]
ok, thanks a lot for the helpful information provided! I'm also looking forward for the next release which will not contain at all this file :)

**Comment by iomintz** [comment]
> also, the file never gets loaded and I don't think (but: IANAL!) that having a GPL file merely exist will affect any other code unless it's actually used/executed/...

this is true, so i'm not sure why the file was dropped…

**Comment by davidism** [comment]
Commit message seems clear:

> This is unmaintained anyways and we do not want to ship non BSD code.

**Comment by iomintz** [comment]
ah, missed that, thanks

**Comment by mistercrunch** [comment]
What's the first version without that file? It would be great to have this here for reference.

For context: FOSSA caught this and I want to bump the version range on my `setup.py`...

**Comment by davidism** [comment]
There was no release that installed or used that file.
