### ISSUE TITLE
String interpolation filter

### ISSUE THREAD

**Issue by valtido** [pallets/jinja#836]
Would you consider adding the following filter feature on the jinja?

https://github.com/mozilla/nunjucks/issues/899

thank you.

**Comment by ThiefMaster** [comment]
IMO such a feature is pretty nasty. "How to get you data leaked"-nasty. I can already see something calling this on a user-provided string with all the implications that come with it...

**Comment by valtido** [comment]
(on the risk of sounding totally mad) IMO if you are already exposing that data to the template it does not really matter what's leaked, From nunjucks perspective (not familiar with jinja) the data is contained by the context anyways any sensitive data does not even get to pass through the template.

**Comment by ThiefMaster** [comment]
Exposing e.g. a `User` model instance to a template that shows user information is perfectly normal. But you wouldn't want to expose e.g. `user.password` (even if that's just a hash) or `user.is_hiv_positive` ;)

Also, Jinja code can call methods on the objects in the context, so unless you use the sandboxed environment, your templates must be about as trustworthy as your Python code.

FYI: You could always add a function that renders a string as a template as a filter from your application code. No need to have something like this in the Jinja core.
