### ISSUE TITLE
Can't increment variables

### ISSUE THREAD

**Issue by patrickelectric** [pallets/jinja#837]
{% set counter = 0 %}
{% for f in somearray %}
{% set counter = counter + 1 %}
{% print(counter) %}
{% endfor %}

The result is always zero.

Python 3.6, jinja2

**Comment by davidism** [comment]
See Jinja's documentation on for loops for an explanation and what to do instead.

**Comment by patrickelectric** [comment]
Ty @davidism, After reading about 2.10 I got the correct solution for my problem.
I added [here](https://stackoverflow.com/a/49699589/7988054) if someone want to follow.
