### ISSUE TITLE
Documentation: substring missing

### ISSUE THREAD

**Issue by thany** [pallets/jinja#862]
In the documentation explanation of substring is missing. So for example, one can do something like this:
```
{{ foo[:3] }}
```
To get the first three characters from `foo`. But the documentation says absolutely nothing about what's possible with this kind of syntax, and how to work it. I will now basically have to go trial&error until I get a part of the string that I need.

Can this please be added?

**Comment by davidism** [comment]
It's just Python, there no special documentation regarding it.

**Comment by thany** [comment]
For those who aren't familiar with python?
I for one, just have to use this template syntax to build up websites. I don't write the python code behind it. I have no way of knowing what I can do if it isn't documented.
