### ISSUE TITLE
UnicodeDecodeError in environment.py

### ISSUE THREAD

**Issue by myst404** [pallets/jinja#865]
Hello,

I got an error while creating a Jinja template due to the fact that my path have accents.

---

## Expected Behavior
Jinja should work even if there are unicode characters in the path.

## Actual Behavior
An exception was raised.

## Template Code
The python script where Jinja is called is: https://github.com/WJDigby/apd_launchpad/blob/master/apd_launchpad.py

## Full Traceback
```
/tmp/Téléchargements# python2 apd_launchpad.py -t TEST -s TEST -i TEST -cn "TEST"
Traceback (most recent call last):
  File "apd_launchpad.py", line 244, in <module>
    main()
  File "apd_launchpad.py", line 195, in main
    wpa_version=args.wpa_version
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 24, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
```

## Your Environment
* Python version: Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
* Jinja version: 2.10

**Comment by davidism** [comment]
Please include a minimal example in the issue itself. Also, please try to include more of a description, as I'm having a hard time figuring out what the issue is.

**Comment by myst404** [comment]
Hey,

Sorry, I think it actually falls into the following case in you documentation:

"Another important thing is how Jinja2 is handling string literals in templates. A naive implementation would be using Unicode strings for all string literals but it turned out in the past that this is problematic as some libraries are typechecking against str explicitly. For example datetime.strftime does not accept Unicode arguments. To not break it completely Jinja2 is returning str for strings that fit into ASCII and for everything else unicode:"


Regards.

**Comment by davidism** [comment]
I would highly recommend upgrading to Python 3.
