### ISSUE TITLE
Trailing comma in if statement results in True

### ISSUE THREAD

**Issue by Kellel** [pallets/jinja#875]
I made a simple test case to reproduce an issue that caused a semi major outage for our team today.

## Expected Behavior
An error (TemplateException) should be thrown

## Actual Behavior
Statement evaluates to True
```
foo:
    bar
bar:
    bar
```

## Template Code
```jinja
foo:
    bar

{%- if False or False , %}
bar:
    bar
{%- endif %}
```

## Your Environment
* Python version: 2.7.15
* Jinja version: 2.10

**Comment by davidism** [comment]
Most likely `False,` is being interpreted as a 1-tuple. This doesn't look like a syntax error, just a logic error.

**Comment by Kellel** [comment]
I noticed the same thing, but I do think that this is a parsing error.
For instance in just vanilla python

```
if False or False , :
    print("fail")
```

Will result in a syntax error

**Comment by davidism** [comment]
Jinja syntax is close to, but not exactly, Python. There are no colons in block statements in Jinja, so this seems acceptable.

**Comment by Kellel** [comment]
Ok. I see what you are saying. I guess that makes sense. I think our team is going to try and make a linting script to try and catch this kind of bug in our production code.

Thanks for the fast response!

**Comment by davidism** [comment]
It would be cool to see a linter/formatter for Jinja, I'm not aware of any so far.
