### ISSUE TITLE
Windows path delimiter

### ISSUE THREAD

**Issue by eran-pinhas** [pallets/jinja#880]
https://github.com/pallets/jinja/blob/bbe0a4174c2846487bef4328b309fddd8638da39/jinja2/loaders.py#L27

Hey, there an unclear code at referred lines. why is the `/` delimiter is hard-coded, and why should we check if the delimiter is in the pieces. 

It causes 2 issues: When using in windows environment still requires to use the `/` and when file referencing to other template - its path will be `".\second.xml"` which raises the TemplateNotFound error automaticly

Instead of:  
```python
    for piece in template.split('/'):
        if path.sep in piece \
           or (path.altsep and path.altsep in piece) or \
           piece == path.pardir:
            raise TemplateNotFound(template)
        elif piece and piece != '.':
            pieces.append(piece)
```
I would expect:
```python
    for piece in template.split(path.sep):
        if (path.altsep and path.altsep in piece) or \
           piece == path.pardir:
            raise TemplateNotFound(template)
        elif piece and piece != '.':
            pieces.append(piece)
```

Best Regards

**Comment by ThiefMaster** [comment]
Jinja template paths/names are not file system paths; they only map to a file system path when a FileSystemLoader is being used. They always use forward slashes.

FWIW, even when dealing with the actual filesystem in Python you can safely use forward slashes on Windows, since all the internal Windows APIs support them just fine, and so does Python.

**Comment by eran-pinhas** [comment]
OK, thanks

But that resolves the only first issue, it will still raise an error when including another inner template even though the reference path is plain (`innerTemplate.xml`) or forward slashed (`./innerTemplate.xml`) because the template variable will be `.\innerTemplate.xml` or `.\./innerTemplate.xml` respectively.

**Comment by ThiefMaster** [comment]
Can you provide a minimal runnable example that triggers the other issue?

**Comment by eran-pinhas** [comment]
You were right, the backslash problem came from library that was not using jinja2 properly.

BR

**Comment by AmnonSagiv** [comment]
@ThiefMaster -  relevant not only for file referencing.
when passing a directory that contains template files to render_skeleton,
jinja2.exceptions.TemplateNotFound: is raised.
cause win paths include '\' (and not '/') switching to template.split(os.path.sep) solves it
