### ISSUE TITLE
vim syntax file: set comments and commentstring

### ISSUE THREAD

**Issue by minusf** [pallets/jinja#884]
This is not a bug in jinja2 per se, but a minor usability issue with the included vim syntax file.

While the syntax file highlights comments correctly, it does not set the variables for `commentstring` and `comments`.  These help with folding and editing in general. A very simple fix is just to include these 2 lines in the vim syntax file:

```
setlocal commentstring={#%s#}
setlocal comments=s:{#,e:#}
```

**Comment by ThiefMaster** [comment]
Sounds like a good candidate for a pull request!

**Comment by tbnorth** [comment]
PR submitted.

**Comment by davidism** [comment]
closed by #990
