### ISSUE TITLE
Are there any list of unacceptable character in Jinja2 template

### ISSUE THREAD

**Issue by keydaimon** [pallets/jinja#885]
I would like to know if there are any list of unacceptable charaters in Jinja2 template.
The other day, I have encountered that I cannot use hyphen character '-' in Jinja2 template in any form.
To be precise, I tried to use a string '{{ foo['bar-baz'] }}' which is defined out of the template file, but I got an error and it didn't seem to work. It seemed to work when I eliminate the character hyphen '-' of the variable key-name (foo['barbaz']).

I guess that the meta character of Jinja2 template, such as '%', '{', '}' are also unacceptable as variable name in Jinja2 template engine.

So, I searched the web to find the official document about this issue, but I couldn't find any infomation.
I would be happy if anyone let me know why this happened.

Thank you.

---

## Expected Behavior
Smoothly printed out the value of the variable 'foo['bar-baz']'.

## Actual Behavior
I got an error.

## Template Code
```jinja
{{ foo['bar-baz'] }}
```

## Your Environment
* Python version: 2.7
* Jinja version: 2.10

**Comment by asenov** [comment]
Hi, can you confirm that you have got an issue with that code: 

``
from jinja2 import Template

tpl = Template('''{{data['foo-bar']}}''')
data = {'foo-bar': 'Foo Bar'}

assert tpl.render(data=data) == data['foo-bar']
``

**Comment by keydaimon** [comment]
Sorry for the late reply.
I confirmed the code you provided and there are no errors.
The bottom line is that the code "data['foo-bar']" works fine in Jinja template.

I am still wondering there must be the unacceptable characters in Jinja2 specification, but I don't have the reproducible code so far.
So please let me close the issue this time.

Thank you so much for your response, asenov.
