### ISSUE TITLE
Python 3 Support still "Experimental"

### ISSUE THREAD

**Issue by guettli** [pallets/jinja#890]
According to this page, Python 3 support is still experimental.

http://jinja.pocoo.org/docs/2.10/intro/#experimental-python-3-support

Is this still true today?

**Comment by Lucid-Network** [comment]
would also like to know, how about future plans?

**Comment by davidism** [comment]
Python 3 is fully supported and has been for years, along with the rest of the Pallets projects. The docs are out of date because I forget that these sections exist. Submit a PR that removes all mentions of Python 3 support being experimental / causing problems and I'd be happy to review.

**Comment by guettli** [comment]
I think docs are even more important than code. That's why the real experts (not me) should do it.

**Comment by Gamrix** [comment]
This was done in #868 , can we close this (and maybe update the version of the docs that are online)?

**Comment by davidism** [comment]
Not easily, but I guess this will resolve itself once I get Jinja on RTD (just did Click recently). Thanks for finding the duplicate.
