### ISSUE TITLE
Native pluralize template filter in Jinja2

### ISSUE THREAD

**Issue by dspruell** [pallets/jinja#893]
Pluralization of strings appears to be a use case solved by rolling one's own filter and registering it, or using the i18n extension. Neither is particularly convenient (and the former is error-prone).

I wanted to ask if it would be possible to implement a useful and standard pluralize template filter in Jinja2 that could be used out of the box. This is generally a helpful feature from other template engines.

**Comment by davidism** [comment]
Pluralization is a hard, locale-dependent problem. There are existing libraries for it, pick one that works for you and add it as a filter. Creating another implementation that we have to maintain would be redundant.
