### ISSUE TITLE
|safe doesn't effect i18n _ arguments

### ISSUE THREAD

**Issue by dspeyer** [pallets/jinja#896]
When I use _'s argument interpolation inside a jinja template's {{}} clause with the |safe tag, the format string is treated as safe but the interpolated arguments aren't.

I can work around this with {% autoescape False %} but it's ugly, and this is what |safe is for.

## Expected Behavior
```html
    <p>Cost is &yen;10,000 per <b>month</b></p>
```

## Actual Behavior
```html
    <p>Cost is &amp;yen;10,000 per <b>month</b></p>
```

## Template Code
```jinja
    <p>{{ _("Cost is %(price) per <b>month</b>", price=get_price()) |safe }}</p>
```

Where get_price returns `'&yen;10,000'`

## Your Environment
* Python version: 2.7.15
* Jinja version: 2.8

**Comment by dspeyer** [comment]
{% trans %} doesn't interpolate named arguments

**Comment by ThiefMaster** [comment]
{% trans price=get_price()|safe %}Cost is {{ price }} per <b>month</b>{% endtrans %}

**Comment by davidism** [comment]
New-style gettext marks the translation as safe, then performs formatting. Mark the variable as safe, like `price=get_price()|safe`.

I added something to the docs about this.
