### ISSUE TITLE
 Possible inconsistency between `first` and `last` filters

### ISSUE THREAD

**Issue by tterranigma** [pallets/jinja#897]
[Here](https://github.com/ansible/ansible/issues/45840) is the original bug report. I was told to post it here.

## Template Code
```jinja
{%- set qqq=[111,222,333] -%}
{{ qqq | selectattr('name', 'equalto', 222) | first }}
{{ qqq | selectattr('name', 'equalto', 222) | last }}
```

## Full Traceback
Error via ansible:

```pytb
Unexpected templating type error occurred on ({{ qqq | selectattr('name', 'equalto', 222) | last }}): 'generator' object is not reversible"
```

## Your Environment
* Python version: 3.7.0
* Jinja version: 2.10

**Comment by davidism** [comment]
Fairly sure this is intentional. `last` would have to convert generators to a list first, which may be dangerous (infinite stream, user intentionally doesn't want to hold everything in memory, etc.).

**Comment by davidism** [comment]
This could be mentioned in the docs, something like:

> If the iterable is a generator, it must be explicitly converted to a list to get the last element. For example, when using `selectattr`:
>
>     data | selectattr('name', '==', 'Jinja') | list | last`
>
> Otherwise you'll get the error "generator object is not reversible".

Marking this as beginner friendly if you'd like to make PR.

**Comment by flexferrum** [comment]
> Fairly sure this is intentional. last would have to convert generators to a list first, which may be dangerous (infinite stream, user intentionally doesn't want to hold everything in memory, etc.).

Actually, the same issue could be addressed to the `loop.length` (and all related) loop property. Currently, it silently converts any arbitrary sequence to the list and then returns the length.
