### ISSUE TITLE
Strip redundant spaces in context keys

### ISSUE THREAD

**Issue by liwt31** [pallets/jinja#905]
Recently I made a really stupid mistake which wastes me lots of time and I hope jinja2 can help prevent people from making similar mistakes. Code:
```
template = jinja2.Template('Hello {{ username }}!')
print(template.render(**{'username ': 'liwt31'}))
```
What I expect is:
```
Hello liwt31!
```
What I get is :
```
Hello !
```
The mistake I made is simple. I accidentally add a space to the key of the context so the `username` is not in the context. But the origin is quite difficult to find out (perhaps piece of case for a C/C++ programmer).
Of course it's all my fault, but I hope maybe jinja2 can help careless people like me. As far as I know, there's no need for any spaces in jinja2 context, so I think if it's possible for jinja2 to strip spaces, if any, for users, or give some kind of warning or error if there are inappropriate spaces?

**Comment by ThiefMaster** [comment]
I don't see any real advantage from this. Usually people pass kwargs as actual kawrgs and don't unpack a dict there.

**Comment by liwt31** [comment]
Just for your information, the situation I posted here is a simplified version, what I really do is that I'm using context processor in Flask in which I have to return a dict.
