### ISSUE TITLE
Feature Request: New filter to provide alternate values based on bool() as an alternative to inline {% if %} blocks.

### ISSUE THREAD

**Issue by jrschneider** [pallets/jinja#907]
## Feature Request 
Provide a built-in filter that outputs a given string or variable value based on a bool() of the original _value_.

## Use Case
I use Jinja2 to build configurations for network equipment from multiple vendors. The context variables I'm looking at have attributes that can be checked via bool(). Currently, in the templates for the various vendor configurations, I use an inline {% if %} like this in numerous locations:

`spantree vlan {{ vlan }} admin-state {% if vlan_entry.stp_disable %}disable{% else %}enable{% endif %}`

While this works, the inline {% if %} statement is super hard to read and makes the line length considerably longer. I would propose something like this:

`spantree vlan {{ vlan }} admin-state {{ vlan_entry.stp_disable|bool_values('disable','enable') }}`

The signature could be _bool_values(value, true_value='True', false_value='False')_. 

An undefined context variable would use the false_value. 

I don't think the filter would be hard to write, but I didn't see anything built-in that would accomplish this task. I'm totally open to naming the filter to something more pragmatic if need be.

I don't know if there would be a need to allow for callbacks in the true_value/false_value variables, but I can see references to existing values in the template context being useful.

It would also have the benefit of working around issue #713 for me in most cases since I wouldn't be ending the line with a block.  

If there is already a way to do this, I'd love to hear it. I can't imagine I'm the only one who uses inline {% if %} blocks. 

## Your Environment
* Python version: 3.5.2
* Jinja version: 2.10

**Comment by davidism** [comment]
`if else` can already be used inline like in Python: `{{ "disable" if vlan_entry.stp_disable else "enable" }}`
