### ISSUE TITLE
With async, map doesn't work with any other async filter

### ISSUE THREAD

**Issue by seaders** [pallets/jinja#915]
This is to highlight the fix I've PR'd - https://github.com/pallets/jinja/pull/913

    import logging
    from jinja2 import Environment
    
    tmpl_str = '{{ [[1,2], [3], [4,5,6]]|map("sum")|list }}'
    
    env = Environment()
    output = env.from_string(tmpl_str).render()
    
    from jinja2 import asyncsupport
    
    env_async = Environment(enable_async=True)
    output_async = env_async.from_string(tmpl_str).render()
    
    logging.warning(f'''
        {output}
        {output_async}
    ''')
    
    assert output == output_async

Both outputs should be the same, but actually, the result of ^^^ is

    <template>:13: RuntimeWarning: coroutine 'do_sum' was never awaited
    WARNING:root:
        [3, 3, 15]
        [<coroutine object do_sum at 0x1037b7678>, <coroutine object do_sum at 0x1037b76d0>, <coroutine object do_sum at 0x1037b7728>]
    
    Traceback (most recent call last):
      File "/Developer/repos/git/betapilibs/lbbsports/scrapbook/test_jinjathing.py", line 19, in <module>
        assert output == output_async
    AssertionError

You get the same for all the async_filters, https://github.com/pallets/jinja/blob/master/jinja2/asyncfilters.py, 

```
ASYNC_FILTERS = {
    'first':        do_first,
    'groupby':      do_groupby,
    'join':         do_join,
    'list':         do_list,
    'reject':       do_reject,
    'rejectattr':   do_rejectattr,
    'map':          do_map,
    'select':       do_select,
    'selectattr':   do_selectattr,
    'sum':          do_sum,
    'slice':        do_slice,
}
```

This error occurs because async's do_map, https://github.com/pallets/jinja/blob/master/jinja2/asyncfilters.py#L108 doesn't respect the warning in `Environment`'s call_filter, https://github.com/pallets/jinja/blob/master/jinja2/environment.py#L444

        Note that on Python 3 this might return a coroutine in case the
        filter is running from an environment in async mode and the filter
        supports async execution.  It's your responsibility to await this
        if needed.

**Comment by seaders** [comment]
Sorry to bump, but any chance some movement can be made on this? @mitsuhiko

**Comment by kevin-brown** [comment]
I believe this can be closed off now that https://github.com/pallets/jinja/issues/913 has been merged.
