### ISSUE TITLE
NativeEnvironment: json string is converted to dict

### ISSUE THREAD

**Issue by mkrizek** [pallets/jinja#917]
```
In [1]: from jinja2.nativetypes import NativeEnvironment

In [2]: e = NativeEnvironment()

In [3]: t = e.from_string('{"foo": "bar"}')

In [4]: t.render()
Out[4]: {'foo': 'bar'}

In [5]: type(t.render())
Out[5]: dict
```

We can workaround it with:
```
In [1]: t = e.from_string('{% raw %}{"foo": "bar"}{% endraw %}')

In [2]: t.render()
Out[2]: u'{"foo": "bar"}'

In [3]: type(t.render())
Out[3]: unicode

```

Jinja version: master `11888dc`

Related issue reported against `ansible/ansible` - https://github.com/ansible/ansible/issues/46169

cc @davidism I'd like to hear your opinion on this, if you think it's intended or not. If not, what we can do here. Thanks!

**Comment by davidism** [comment]
That's not a string, that's a dict. A string would be surrounded by quotes. Remember, the native environment is parsing what it sees as Python literals. Right now you've done the equivalent of writing `{"foo": "bar"}` in a Python file, but serialized JSON looks like:

```python
import json
data = {"foo": "bar"}
print(json.dumps(data))
'{"foo": "bar"}'
```

So you would write `e.from_string('\'{"foo": "bar"}\'')` if you wanted to output string that contained serialized JSON data.
