### ISSUE TITLE
Cannot reach multiple levels up in template hierarchy with super

### ISSUE THREAD

**Issue by eteq** [pallets/jinja#928]
I asked about this on `#pocoo` and got no answer.  I'm fairly sure it's not possible, which means this is probably a feature request?

There does not not seem to be any way to get multiple-levels up in a ``super()`` call in a template.  That is, if I have template C that extends B and B extends A, I want a super from C that skips the block in question from B and goes straight to the super from A.

(I know one answer is "don't do the super in B", but in this case it's impossible because A and B are from an external package)

### a.templ

```jinja
...
{% block body %}
  {% for complex in complicated %}
    <span>
    ... something complex using {{ complex }} that I don't want to have to reproduce...
    <span>
  {% endfor %}
{% endblock %}
...
```

### b.templ

```jinja
{% extends "a.templ" %}
{% block body %}
  <div class="something_I_dont_need">
    {{ super() }}
  </div>
{% endblock %}
```

### c.templ

```jinja
{% extends "a.templ" %}
{% block body %}
  <div class="something_I_actually_DO_need">
    {{ super(2) }}  # Or maybe {{ super("a.templ") }} ?
  </div>
{% endblock %}
```

## Actual Behavior

Impossible to do, because `c.templ` has no access to the "body" block from `a.templ` without going through `b.templ` (which has parts I don't want)

**Comment by davidism** [comment]
The `super` object has a `super` attribute which points at the next block up the context. Turns out the docs only mention that you can call `super()`, not that you can access `super.super`. Would you be willing to submit a PR to document that?

**Comment by eteq** [comment]
Oh, fantastic! Yes I'll do a PR to clarify that (may be a few weeks before I get to it though)

**Comment by kushthedude** [comment]
@eteq Can i proceed if you are busy somewhere else?

**Comment by davidism** [comment]
@kushthedude you don't need to ask to make PRs, just make them

**Comment by kushthedude** [comment]
@davidism New to this repo , Just for precaution thought to ask first , Cool will push the PR

**Comment by eteq** [comment]
Thanks @kushthedude!  Sorry I dropped the ball on this but glad that it got done.
