### ISSUE TITLE
meta.find_undeclared_variables returns "range" as undeclared variable

### ISSUE THREAD

**Issue by ppastuszkaocado** [pallets/jinja#931]
Given the following text snippet:
```SQL
SELECT date, sku, {% for lag in range(1, 5) %} a {% endfor %} FROM `{{project}}.{{dataset}}.targets`
```
I'd expect `meta.find_undeclared_variables` to return only `project` and `dataset`.
In fact, `range` is also returned as undeclared variable.

* Python version: 3.6
* Jinja version: 2.10

**Comment by bkiu** [comment]
I'll work on this for PyCon 2019 sprints.
