### ISSUE TITLE
Exception in `__html__` method causes segfault when autoescaping

### ISSUE THREAD

**Issue by leamingrad** [pallets/jinja#941]
The following code fails with a segmentation fault:

```python
from jinja2 import Template

class Test:
    def __html__(self):
        assert False
    
test = Test()
template = Template('{{ test }}', autoescape=True)
print(template.render(test=test))
```

## Expected Behavior
Running the code completes in some way (either by successfully rendering something or raising the error).

## Actual Behavior
The interpreter crashes with a segmentation fault

## More Details
This seems to be related in some way to a combination of `autoescape=True` on the template, and the error being in the `__html__` method. In particular:
* If I change to `autoescape=False` in the above example, then the repr of the `test` object is printed successfully
* If I move the error into a `__str__` method rather than a `__html__` method (with `autoescape=True`) the assertion error is propagated to the terminal

Not really sure where the bug lies here, but I am guessing it is in the compiled template code. Running with `-X faulthandler` gives:

```
Fatal Python error: Segmentation fault

Current thread 0x00007fd45c000080 (most recent call first):
  File "<template>", line 11 in root
  File "/home/james/.local/share/virtualenvs/web-findings-dozQMylR/lib/python3.6/site-packages/jinja2/environment.py", line 1005 in render
  File "/home/james/.local/share/virtualenvs/web-findings-dozQMylR/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76 in render
  File "test.py", line 10 in <module>
```

Is there a way to view the compiled template code?

## Your Environment
* Python version: 3.6.7
* Jinja version: 2.10

**Comment by ThiefMaster** [comment]
if python segfaults it might be a bug in markupsafe

**Comment by leamingrad** [comment]
Just realized I forgot to say in the above: the example is obviously stupid, but this actually occurred when trying to render a WTForms form that had a broken custom field widget in a flask app - I don't think that jinja2 should be able to handle errors in `__html__` methods but it would be helpful to get the stacktrace.

**Comment by leamingrad** [comment]
It appears that it is Markupsafe that is at fault. Just running `jinja2.runtime.escape(test)` also segfaults.

Looks like this has already been reported: https://github.com/pallets/markupsafe/issues/108 so I'll code this
