### ISSUE TITLE
urlencode doesn't escape slashes

### ISSUE THREAD

**Issue by agowa338** [pallets/jinja#944]
Just opening this issue, to ask about the status of my pull request.

As of `urlencode doesn't escape slashes` #515  the issue got closed, even though there are reports of users having that problem.

Please let me know what to do with the pull request `Implement do_urlencodecomponent` #864.
Or do you consider the regex `myvar | urlencode | regex_replace('/','%2F')` workaround as the official solution?

**Comment by davidism** [comment]
The status of your PR is that it's still open. You'll know when the status changes because you'll get a notification about it. Sorry I can't be more specific, but there's only so much time I can devote to Pallets, and I'm currently focused on Werkzeug, not Jinja.
