### ISSUE TITLE
"TypeError: 'int' object is not callable" in reraise() hiding real AttributeError

### ISSUE THREAD

**Issue by edmorley** [pallets/jinja#945]
## Expected Behavior
`AttributeError` exceptions generated in Python blocks inside Jinja templates should result in an exception message that makes it easy to debug what the exception was, and where it occurred.

For example in this case: `AttributeError: 'Counter' object has no attribute 'iteritems'`

For bonus points the Jinja generated exception message should include the snippet of Python in the template block that failed to execute (in this case, `for repository, count in repositories.iteritems()`).

## Actual Behavior
A `TypeError: 'int' object is not callable` exception is generated, that does not include either (a) the snippet of Python to which the exception refers (`for repository, count in repositories.iteritems()`), or (b) the real `AttributeError` exception.

Note if I `s/Counter/dict` in the testcase below, then a more helpful exception is generated.

Context: A codebase being upgraded from Python 2 to 3, where the existing tests were failing with the `TypeError` above, which meant I had to manually inspect/bisect the template to find the offending line.

## Template Code
```py
from collections import Counter
from jinja2 import Template

repositories = Counter({
    'foo': 0,
    'bar': 1,
})

template = Template("""
{% for repository, count in repositories.iteritems() -%}
* {{repository}}: {{count}}
{% endfor %}
""")

print(template.render(repositories=repositories))
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "testcase.py", line 15, in <module>
    print(template.render(repositories=repositories))
  File "/home/vagrant/python/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/vagrant/python/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vagrant/python/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/python/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
TypeError: 'int' object is not callable
```

## Your Environment
* Python version: 3.7.2
* Jinja version: 2.10

**Comment by kevin-brown** [comment]
I can reproduce this issue. When replacing it with a native object, it raises an `UndefinedError` which is probably the right base class to actually use.

**Comment by kevin-brown** [comment]
Just realized what the issue is, and I think it may be expected behaviour.

```python
>>> from collections import Counter
>>> c = Counter()
>>> c.iteritems()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Counter' object has no attribute 'iteritems'
>>> c['iteritems']()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
>>>
```

It's not catching the `AttributeError` because the index call (`c['iteritems']`) is returning `0` (the default value when a key wasn't previously defined) and the error is being thrown because it tries to call `0()` which raises that error.

The test cases I used when debugging this were:

```python
def test_attribute_error_caught_counter(self, env):
    from collections import Counter

    tmpl = env.from_string("""
{% for b, c in a.iteritems() -%}
* {{b}}: {{c}}
{% endfor %}
""")

    with pytest.raises(UndefinedError):
        tmpl.render(a=Counter({
            'foo': 0,
            'bar': 1,
        }))

def test_attribute_error_caught_dict(self, env):
    tmpl = env.from_string("""
{% for b, c in a.iteritems() -%}
* {{b}}: {{c}}
{% endfor %}
""")

    with pytest.raises(UndefinedError):
        tmpl.render(a={
            'foo': 0,
            'bar': 1,
        })
```

**Comment by davidism** [comment]
Yeah, since this is such a specific case with `Counter`, I'd say this isn't something we can fix. Jinja tries both attribute and index access, and `Counter` has default behavior with unknown keys.

**Comment by edmorley** [comment]
Hi! Thank you for the reply.

Would it be possible to at least do this?

> For bonus points the Jinja generated exception message should include the snippet of Python in the template block that failed to execute (in this case, `for repository, count in repositories.iteritems()`).

:-)
