### ISSUE TITLE
By default, the last new line is deleted

### ISSUE THREAD

**Issue by tomasz-c** [pallets/jinja#949]
## Expected Behavior
Formatting the template remains unchanged, including the last new line.

## Actual Behavior
The final newline is removed from the rendered output.

The error was reported earlier:
https://github.com/pallets/jinja/issues/848

The function has been added:
`keep_trailing_newline`

However, still default, jinja2 makes changes to the file in a place where it should not change anything.
Leaving a new line at the end of the file is very important in many cases. Without this, many configuration parsers can crash.
A detailed explanation is available at:
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

Suggestion:

Set `keep_trailing_newline` default to `True`

## Your Environment
* Python version: 3.7
* Jinja version: 2.10

**Comment by davidism** [comment]
Sorry, but we'll leave this as-is unless there is an extremely good reason to change the default. When writing a project with Jinja, please use settings appropriate to the output you're trying to produce.
