### ISSUE TITLE
Deprecation warning: Using or importing the ABCs from 'collections' warning still appearing

### ISSUE THREAD

**Issue by cepbrian** [pallets/jinja#953]
Filing a new ticket because https://github.com/pallets/jinja/pull/867 is already closed.

It appears that pull 867 was never released. I'm still getting the collections warning in jinja 2.10. 

## Your Environment
* Python version: 3.7
* Jinja version: 2.10

**Comment by davidism** [comment]
3.8 isn't released for another year. There will be another release before then.

**Comment by cepbrian** [comment]
But it's making all of my pytests give LOTS of warnings...

**Comment by davidism** [comment]
You can configure your test runner to ignore specific warnings that you know upstream will handle. We do it in Werkzeug, for example.

**Comment by pierrecdn** [comment]
IMO, doing a release just for the sake of handling deprecationWarnings isn't so shocking, since the last one is almost 1.5 years old.
It would be simpler for everyone and do not let people introduce tech debt by explicitely ignoring warnings.
