### ISSUE TITLE
groupby example doesn't explain grouper attribute clearly

### ISSUE THREAD

**Issue by revelt** [pallets/jinja#954]
The groupby filter, http://jinja.pocoo.org/docs/2.10/templates/#groupby contains an example where the task is to filter people into two groups by gender:

```
{% for group in persons|groupby('gender') %}
    <li>{{ group.grouper }}<ul>
```

The `grouper` comes "out of nowhere", is it meant to be `gender`:

```
{% for group in persons|groupby('gender') %}
    <li>{{ group.gender }}<ul>
```

?

If so, please consider changing it in the documentation because it's confusing. Thank you.

**Comment by ThiefMaster** [comment]
> As you can see the item we’re grouping by is stored in the grouper attribute and the list contains all the objects that have this grouper in common.

However, for the second example there I think renaming `grouper` to `gender` would make more sense:

```diff
-{% for grouper, list in persons|groupby('gender') %}
+{% for gender, list in persons|groupby('gender') %}
```

**Comment by revelt** [comment]
Aha! Thank you for quick response. Let's update it then.

**Comment by davidism** [comment]
> please consider changing it in the documentation because it's confusing

I'm happy to review a PR that makes the docs clearer for you.

**Comment by revelt** [comment]
> I'm happy to review a PR
Please do.
Thank you. +1

**Comment by davidism** [comment]
I'm sorry, I meant "I'd be happy to review a PR if someone submitted one. Since you probably have a good idea of what's confusing to you, it would be great if you submitted a rewording that is clearer to you.

**Comment by revelt** [comment]
@davidism OK, I'll have a look. I'll try to compile Adrian's suggestion for second example and expand a bit on grouper.

**Comment by kushthedude** [comment]
@davidism I would like to update the docs if the PR is inactive

**Comment by revelt** [comment]
Please do

**Comment by kushthedude** [comment]
@revelt The issue could have been closed after the PR gets merged
