### ISSUE TITLE
DebugUndefined does not show custom delimiters

### ISSUE THREAD

**Issue by ynikitenko** [pallets/jinja#958]
`Environment` and `Template` change original string when using special parameters and `DebugUndefined`.

## Expected Behavior

The original string should not be changed.

```python
jinja2.Environment(variable_start_string='\VAR{', undefined=jinja2.DebugUndefined).from_string("\VAR{ val }}").render({"other_val": "Hello"})
u'\VAR{ val }}'
```

## Actual Behavior

```python
jinja2.Environment(variable_start_string='\VAR{', undefined=jinja2.DebugUndefined).from_string("\VAR{ val }}").render({"val1": "Hello"})
u'{{ val }}'
```

## Your Environment

* Python version: 2.7.15
* Jinja version: 2.10

**Comment by PelleUllberg** [comment]
We've worked around this by defining our own class curried with variable start and end strings:

`def get_undefined_handler(variable_start_string, variable_end_string):
    class PreservedUndefined(Undefined):

        __slots__ = ()

        def __init__(self, *args, **kwargs):
            super(PreservedUndefined, self).__init__(**kwargs)

        def __str__(self):
            if self._undefined_hint is None:
                if self._undefined_obj is missing:
                    return u'%s %s %s' % (variable_start_string, self._undefined_name, variable_end_string)
                return '%s no such element: %s[%r] %s' % (
                    variable_start_string,
                    object_type_repr(self._undefined_obj),
                    self._undefined_name,
                    variable_end_string
                )
            return u'%s undefined value printed: %s %s' % (self._undefined_hint , variable_start_string , variable_end_string)
    return PreservedUndefined
`

**Comment by EtiennePelletier** [comment]
I've looked into this and it isn't feasible to modify the DebugUndefined to use attributes from the template or environment such as `variable_start_string` and `variable_end_string` because their context isn't available.
If this functionality is required for you, I suggest creating your own undefined Class like in the workaround mentioned above.
