### ISSUE TITLE
Feature request: Output file selection

### ISSUE THREAD

**Issue by hcw70** [pallets/jinja#959]
## Expected Behavior
I want to produce multiple output files from jinja templates, and i would like to have control
over what is produced within the jinja template itself, not in my python code.

So i propose to add a new keywords (pair) like
`{% output to "filename.txt" %}
...
{% end output %}`
which will switch the output to go into the specified filename within the given block.
Since the output file can be nesting (via macros / templates), it should be
implemented as a stack of output files (with the current output to string as the lowest element)
where the top most output file is the active one:

```
 ... goes to string output 
{% output to "file1txt" %}
 ... goes to file1.txt
   {% output to "file2.txt" %}
 ... goes to file2.txt
   {% end output %}
 ... goes to file1.txt
{% end output %}
 ... goes to string output 

```

With that option i can render my toplevel template:

```
                out = type_tmpl.render(type=type,
                                       name=type_name,
                                       schema=self._xsd,
                                       root_elem = self._xsd.elements[self._root_elem_name]
                                       )
                type_file.write(out)

```

and have that template create my output file set:

```

{% macro render_child(obj) %}
...
{% endmacro %}

{% for child in root_elem.elem_childs recursive %}
{% output to child | uniqe_filename("dita) %}
  {% render_child(child) %}
{% end output %}

```

## Your Environment
* Python version: python 3.5
* Jinja version: 2.10

**Comment by davidism** [comment]
It's an interesting idea, but not one that I think belongs in Jinja core. Perhaps you could do this with an extension, but I personally would do this in Python.

**Comment by davidism** [comment]
The second part of your request, outpouring blocks to variables with filters, is already handled by `set` blocks
