### ISSUE TITLE
Empty lists are not falsy with rejectattr filter

### ISSUE THREAD

**Issue by mattias-lidman** [pallets/jinja#965]
Lists passed through the `rejectattr` filter are surprisingly not falsy even if empty (initially or after filtering), leading to unexpected behavior of `if` statements.

This is because [`select_or_reject`](https://github.com/pallets/jinja/blob/master/jinja2/filters.py#L1142) returns a generator, so presumably the `reject`, `select`, and `selectattr` filters have similar issues.

## Expected Behavior

"Shouldn't render" shouldn't be rendered if `foolist` is either empty or contains only `Foo()`s with `my_attr = True`:

```
from jinja2 import Template

class Foo(object):
    my_attr = True

temp = Template("{% if foolist|rejectattr('my_attr') %}Shouldn't render{% endif %}")

temp.render(foolist=[Foo()])
temp.render(foolist=[])
```

## Actual Behavior

"Shouldn't render" is rendered in both cases:
```
>>> temp.render(foolist=[Foo()])
u"Shouldn't render"
>>> temp.render(foolist=[])
u"Shouldn't render"
```

Filtering again with `list` causes the generator to be evaluated. Workaround template with the expected behavior:
```
>>> temp = Template("{% if foolist|rejectattr('my_attr')|list %}Shouldn't render{% endif %}")
>>> temp.render(foolist=[Foo()])
''
>>> temp.render(foolist=[])
''
```

## Template Code

`Template("{% if foolist|rejectattr('my_attr') %}Shouldn't render{% endif %}")`

## Your Environment
* Python version: 2.7.12 and 3.5.2
* Jinja version: 2.10

**Comment by davidism** [comment]
Rejectattr returns a generator. Generators are truthy. That folder isn't really intended for if statements, as you'd have to evaluate the while thing again to actually render it. Pass it through the list filter if you really want that, but you probably want a for else block instead.
