### ISSUE TITLE
Confusing error

### ISSUE THREAD

**Issue by ololoe** [pallets/jinja#979]
This works fine:

    {% for ability in item.abilities %}
      {% if ability.field is defined %}{{ability.field}}{% endif %}
    {% endfor %}

This, however, not

    {% for ability in item.abilities %}
      {% if ability.field > 0 %}{{ability.field}}{% endif %}
    {% endfor %}

It outputs very confusing error message `UndefinedError: 'collections.OrderedDict object' has no attribute 'field'				`

**Comment by davidism** [comment]
What do you expect it to say?

**Comment by ololoe** [comment]
Obviously I expect it to work as described in docs.

**Comment by davidism** [comment]
Could you point to those docs?

**Comment by ololoe** [comment]
Obviously I expect second example to work. Why does it produce error in the second example but not in first?

**Comment by carc1n0gen** [comment]
@ololoe that error is very straight forward.  `ability` has no attribute called `field`.  

The first code snippet checks if `field` is defined before using it.  The second snippet attempts to compare `field` against 0 whether it exists or not.

**Comment by ololoe** [comment]
Well, I awaited that defined checks for None. Does jinja raise an Exception if dictionary key does not exist?

**Comment by carc1n0gen** [comment]
@ololoe 

> Well, I awaited that defined checks for None

I have no idea what that is meant to say

> Does jinja raise an Exception if dictionary key does not exist?

Of course

**Comment by ololoe** [comment]
> I have no idea what that is meant to say

You surely know python, right?

**Comment by carc1n0gen** [comment]
> You surely know python, right?

It wasn't about my python abilities, but that the grammar didn't make sense so I don't know what you're trying to say.

**Comment by ololoe** [comment]
Well, `{{ability.field}}` outputs empty string if key `field` does not exist, but `{% if ability.field > 0 %}` raises an exception. That's unawaited behavior.
