### ISSUE TITLE
Import with context is expensive

### ISSUE THREAD

**Issue by tdhooper** [pallets/jinja#995]
## Expected Behavior
Import `with context` works without a performance degradation

## Actual Behavior
For large templates with many imports, applying `with context` increases render time by around 50%

## Your Environment
* Python version: 3.4
* Jinja version: 2.9.6

## Background
While using Jinja we've found that we regularly need access to some global context, such as the request or user, inside deeply nested macros. Rather than passing these globals around as macro arguments, we opted to use `with context` everywhere. This works fine, however template rendering has now become one of the more expensive parts of our stack.

**Comment by davidism** [comment]
Which is why `with context` is not the default. One option is to use environment globals instead. I'm happy to review PRs that improve performance, but I can't leave an open-ended ticket like this open.

**Comment by akx** [comment]
You can use [`Environment.globals` for those](http://jinja.palletsprojects.com/en/2.10.x/api/#global-namespace).

If you don't want to (and you probably shouldn't) create an `Environment` for each request, you can store proxies to your actual `request` and `user` variables in `Environment.globals`, that'd then look up the request-specific values from [thread-local](https://docs.python.org/3.8/library/threading.html#threading.local) or [context-local](https://docs.python.org/3.8/library/contextvars.html#module-contextvars) state.

**Comment by mitsuhiko** [comment]
The reason `with context` is optional is the performance impact. I don't think there is much we can do about this. Given the lack of activity on this issue I will close it.

**Comment by tdhooper** [comment]
> The reason with context is optional is the performance impact.

Was it originally added to solve a perf problem? @davidism suggests it was a design decision _https://github.com/pallets/jinja/pull/996#issuecomment-538543576_

> I don't think there is much we can do about this.

There's my PR https://github.com/pallets/jinja/pull/996, which fixes the performance problem at the expense of removing the default _no context_ behaviour. I imagine it would be possible to rewrite that to keep the existing behaviour _and_ the performance improvement.

I appreciate that my PR is unconventional, however if performance considerations are eliminated, I do wonder how many users would find the default behaviour of withholding context desirable. Personally I found it a gotcha.

> Given the lack of activity on this issue I will close it.

Fair, there has not been a lot of community response to this issue, however making everyone's template rendering faster would be pretty sweet, even if they're unaware.
